Repository kubeflow/kubeflow, pull requests merged in 2018-10, with the labels that each got.

#1676 Fix for "/" not directing to centralUI (#1670).
  components/centraldashboard/dashboard.go
  components/centraldashboard/frontend/layout/index.html
Labels: approved, cla: yes, lgtm, size/XS

#1682 Update image tag for centralUI
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1685 Cherry-pick #1676 fix centralUI
  components/centraldashboard/dashboard.go
  components/centraldashboard/frontend/layout/index.html
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1677 cherrypick - Remove trailing slash from KUBEFLOW_REPO (#1664)
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/XS

#1686 Build TF notebook images for TF 1.9.0 and 1.10.1
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  kubeflow/core/kubeform_spawner.py
Labels: approved, cla: yes, lgtm, size/M

#1684 [0.3] Cherry-pick #1647
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  prow_config.yaml
  testing/test_tf_serving.py
  testing/workflows/components/params.libsonnet
  testing/workflows/components/tfserving.jsonnet
  testing/workflows/components/tfserving.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1688 Tag images for TF notebooks 1.9.0 and 1.10.1
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/S

#1690 upgrade argo version to v2.2.0
  kubeflow/argo/prototypes/argo.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/S

#1692 (cherry pick) upgrade argo version to v2.2.0
  kubeflow/argo/prototypes/argo.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/S

#1693 Update kubebench-job prototype default parameters
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1544 Fix cert-manager and iap config to make dashboard accessible
  kubeflow/core/iap.libsonnet
  kubeflow/core/ingress_bootstrap.sh
  kubeflow/core/tests/iap_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#1700 Add tf serving liveness probe
  kubeflow/tf-serving/tf-serving-template.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1702 Fix jsonnet formatting errors in katib
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1687 Add PVC to Katib
  kubeflow/katib/vizier.libsonnet
Labels: approved, area/0.3.1, cla: yes, lgtm, size/M

#1708 Cherrypick #1700 - TF serving liveness probe
  kubeflow/tf-serving/tf-serving-template.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1548 HubSync v1.0
  releasing/hubsync/.gitignore
  releasing/hubsync/README.md
  releasing/hubsync/hubsync.py
  releasing/hubsync/keys.yaml.sample
  releasing/hubsync/requirements.txt
Labels: cla: yes, size/L

#1640 Update link in README
  components/gcp-click-to-deploy/README.md
Labels: approved, cla: no, lgtm, size/XS

#1594 Merge config for kftcl and click-to-deploy webapp
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
  deployment/gke/deployment_manager_configs/cluster.jinja.schema
  deployment/gke/deployment_manager_configs/gcfs.yaml
  deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
  deployment/gke/deployment_manager_configs/network.jinja
  deployment/gke/deployment_manager_configs/network.yaml
  scripts/download.sh
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/L

#1723 Create an initial CHANGELOG
  CHANGELOG.md
  scripts/update-changelog.sh
Labels: approved, cla: yes, lgtm, size/XXL

#1720 Cherry-pick: Update gcp credentials filename (#1716)
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1714 TF serving template cleanup
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  testing/test_tf_serving.py
Labels: approved, cla: yes, lgtm, size/M

#1713 Add a notice explaining to users what the app is doing.
  components/gcp-click-to-deploy/src/App.tsx
Labels: approved, cla: yes, lgtm, size/S

#1734 Change the default branch in download.sh to v0.3-branch as opposed to master
  scripts/download.sh
Labels: approved, cla: yes, lgtm, size/XS

#1705 config & dockerfile update
  bootstrap/Dockerfile
  bootstrap/config/gcp_prototype.yaml
  bootstrap/image_registries.yaml
Labels: approved, cla: yes, lgtm, size/S

#1746 Pin jupyter-console to 0.6.0
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1747 Ensure namespace exists
  scripts/gke/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#1756 Cherry pick #1746 and #1747
  components/tensorflow-notebook-image/Dockerfile
  scripts/gke/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#1752 Seldon ksonnet refactor
  kubeflow/seldon/core.libsonnet
  kubeflow/seldon/json/README.md
  kubeflow/seldon/json/template_0.1.json
  kubeflow/seldon/json/template_0.2.json
  kubeflow/seldon/prototypes/abtest-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/abtest-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/core.jsonnet
  kubeflow/seldon/prototypes/mab-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/mab-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/outlier-detector-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/outlier-detector-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/serve-simple-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/serve-simple-v1alpha2.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1762 gofmt: run go fmt github.com/kubeflow/kubeflow/bootstrap/cmd/...
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/initHandler.go
  bootstrap/cmd/bootstrap/app/k8sAuth.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
Labels: approved, cla: yes, lgtm, size/L

#1765 Use new stackdriver agents in DM config
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1728 change clusterrole to role
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/tests/centraldashboard_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1772 Enable new beta Stackdriver Kubernetes Monitoring feature if using v1beta1 (#1768)
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1626 Allow folks to have the kubeflow github repo over https + improve error message
  scripts/autoformat_jsonnet.sh
Labels: approved, cla: yes, size/S

#1674 gke/deploy.sh: test uuidgen exists before using it
  scripts/gke/deploy.sh
Labels: approved, cla: yes, lgtm, size/XS

#1760 remove statsd from ambassador deployment
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/prototypes/ambassador.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/M

#1773 Cleanup the OWNERs files.
  OWNERS
  bootstrap/OWNERS
  components/centraldashboard/OWNERS
  components/gcp-click-to-deploy/OWNERS
  components/jupyterhub/OWNERS
  components/k8s-model-server/OWNERS
  components/tensorflow-notebook-image/OWNERS
  kubeflow/OWNERS
  kubeflow/core/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#1763 pin to minor GKE version in dm config
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  deployment/gke/deployment_manager_configs/cluster.jinja
  scripts/gke/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#1777 Cherry pick #1727
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/suggestion.libsonnet
  releasing/update_katib_ksonnet.sh
Labels: approved, cla: yes, lgtm, size/L

#1727 Add katib's hyperband/bayesianoptimization suggestion images (#1464)
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/suggestion.libsonnet
  releasing/update_katib_ksonnet.sh
Labels: approved, cla: yes, lgtm, size/L

#1750 [openmpi] support `volumes` and `volumeMounts`
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, area/openmpi, cla: yes, lgtm, size/XS

#1776 Presubmits should be triggered if the DM configs are modified.
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1787 Add a few basic metrics for deployment service
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/glide.lock
  bootstrap/glide.yaml
Labels: approved, cla: yes, lgtm, size/M

#1754 fixes tensorboard generated under kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet is incomplete
  kubeflow/core/tests/tensorboard_test.jsonnet
  kubeflow/examples/prototypes/tensorboard.jsonnet
  kubeflow/tensorboard/aws.libsonnet
  kubeflow/tensorboard/gcp.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1771 add jupyterhub test
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1781 Cherry pick #1779
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#1791 remove empty readme
  docs_dev/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1780 Update katib suggestion images (#1779)
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#1800 skip readarray if --all provided to jsonnet fmt script
  scripts/autoformat_jsonnet.sh
Labels: approved, cla: yes, lgtm, size/M

#1790 remove travis config
  .travis.yml
Labels: approved, cla: yes, lgtm, size/XS

#1794 cherry-pick PR #1754 onto V0.3 branch
  kubeflow/core/tests/tensorboard_test.jsonnet
  kubeflow/tensorboard/aws.libsonnet
  kubeflow/tensorboard/gcp.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1795 Tf serving with istio 1.0
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  kubeflow/tf-serving/util.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#1804 Knative build for in-cluster image builds in Kubeflow
  kubeflow/knative-build/knative-build.libsonnet
  kubeflow/knative-build/parts.yaml
  kubeflow/knative-build/prototypes/knative-build.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1799 fixes 'add parts attribute to libsonnet for ksonnet incubator/best practices'
  kubeflow/argo/argo.libsonnet
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/cloud-endpoints.libsonnet
  kubeflow/core/echo-server.libsonnet
  kubeflow/core/google-cloud-filestore-pv.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prometheus.libsonnet
  kubeflow/core/spartakus.libsonnet
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#1813 stop e2e test for deploy app till fix letsencrypt rate limit
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1797 Pin tf-serving version in tf-notebook
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1817 add ssl cert reuse logic in e2e & prober tests
  bootstrap/build_image.sh
  prow_config.yaml
  testing/test_deploy_app.py
  testing/workflows/components/click_deploy_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1821 reorganize tests to be under their respective dirs, add aws,gcp tests for tensorboard
  kubeflow/examples/tests/tensorboard_test.jsonnet
  kubeflow/tensorboard/tests/tensorboard-aws_test.jsonnet
  kubeflow/tensorboard/tests/tensorboard-gcp_test.jsonnet
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, size/L

#1815 Fix TFMA and TFDV in Jupyter Images
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/install.sh
  components/tensorflow-notebook-image/releaser/components/params.libsonnet
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/params.libsonnet
  components/tensorflow-notebook-image/start-singleuser.sh
  components/tensorflow-notebook-image/versions/1.10.1/version-config.json
  components/tensorflow-notebook-image/versions/1.10.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.4.1/version-config.json
  components/tensorflow-notebook-image/versions/1.4.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.5.1/version-config.json
  components/tensorflow-notebook-image/versions/1.5.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.6.0/version-config.json
  components/tensorflow-notebook-image/versions/1.6.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.7.0/version-config.json
  components/tensorflow-notebook-image/versions/1.7.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.8.0/version-config.json
  components/tensorflow-notebook-image/versions/1.8.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.9.0/version-config.json
  components/tensorflow-notebook-image/versions/1.9.0gpu/version-config.json
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/L

#1814 Remove root level makefile
  Makefile
Labels: approved, cla: yes, lgtm, size/S

#1820 fixes 'add the metacontroller component #1819'
  kubeflow/metacontroller/metacontroller.libsonnet
  kubeflow/metacontroller/parts.yaml
  kubeflow/metacontroller/prototypes/metacontroller.jsonnet
  kubeflow/metacontroller/tests/metacontroller_test.jsonnet
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, size/L

#1829 fixes 'ksonnet namespace should be retrieved from env not params'
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/cloud-endpoints.libsonnet
  kubeflow/core/echo-server.libsonnet
  kubeflow/core/google-cloud-filestore-pv.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prometheus.libsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/cloud-endpoints.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/spartakus.libsonnet
  kubeflow/core/tests/centraldashboard_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
  kubeflow/credentials-pod-preset/prototypes/gcp-credentials-pod-preset.jsonnet
  kubeflow/knative-build/knative-build.libsonnet
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
  kubeflow/metacontroller/metacontroller.libsonnet
  kubeflow/metacontroller/prototypes/metacontroller.jsonnet
  kubeflow/mxnet-job/mxnet-operator.libsonnet
  kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
  kubeflow/mxnet-job/prototypes/mxnet-operator.jsonnet
  kubeflow/new-package-stub/newpackage.libsonnet
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/seldon/prototypes/core.jsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, size/L

#1633 Application crd
  kubeflow/application/application.libsonnet
  kubeflow/application/parts.yaml
  kubeflow/application/prototypes/README.md
  kubeflow/application/prototypes/application.jsonnet
  kubeflow/application/tests/application_test.jsonnet
  kubeflow/argo/argo.libsonnet
  kubeflow/core/cloud-endpoints.libsonnet
  kubeflow/core/tests/util_test.jsonnet
  kubeflow/core/util.libsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
  kubeflow/registry.yaml
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/XL

#1742 Replace 'cloud' parameter with more direct names like 'params.tfDefaultImage' and 'params.platform'
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/tests/jupyterhub_test.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#1838 Remove argo & katib from default minikube
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/XS

#1832 Create a simple flask server to redirect http to https
  components/https-redirect/Dockerfile
  components/https-redirect/Makefile
  components/https-redirect/main.py
  components/https-redirect/main_test.py
  components/https-redirect/requirements.txt
Labels: approved, cla: yes, lgtm, size/L

#1835 part of fix for 'add jsonnet tests for all libsonnet files'
  kubeflow/core/prototypes/ambassador.jsonnet
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1834 fixes 'metacontroller's compositecontrollers and decoratorcontrollers need to be at Cluster scope'
  kubeflow/metacontroller/metacontroller.libsonnet
  kubeflow/metacontroller/tests/metacontroller_test.jsonnet
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/S

#1792 Make the project configurable.
  components/gcp-click-to-deploy/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1805 Add support for using host network for OpenMPI worker pods
  kubeflow/core/util.libsonnet
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/util.libsonnet
  kubeflow/openmpi/workloads.libsonnet
  kubeflow/weaveflux/util.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1836 Add some latency metrics for GKE & KF deployments
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/M

#1847 fix iap set up and prometheus config
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/prometheus.yml
Labels: approved, cla: yes, lgtm, size/S

#1846 add gauge metrics for dashboard & alerting; add metrics for invalid a…
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#1788 Fix typos in markdown
  bootstrap/README.md
  bootstrap/developer_guide.md
  docs_dev/ksonnet_packages.md
  docs_dev/kubeflow_deployment.md
  docs_dev/releasing.md
  docs_dev/tf_serving.md
  kubeflow/seldon/json/README.md
  testing/README.md
Labels: approved, cla: yes, lgtm, size/S

#1809 Add RapidsAI notebook image
  components/contrib/rapidsai-notebook-image/Dockerfile
  components/contrib/rapidsai-notebook-image/README.md
Labels: approved, cla: yes, lgtm, size/M

#1849 make alert metrics count type & add service heartbeat
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/M

#1851 Fix broken presubmit tests
  testing/deploy_kubeflow.py
  testing/deploy_utils.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#1864 Run minikube e2e test if core components change
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1852 use broadwell
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1850 use TF serving 1.11.1
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1868 remove default version
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1869 fix iap set up and prometheus config (#1847)
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/prometheus.yml
Labels: approved, cla: yes, lgtm, size/S

#1810 Don't add a GPU pool by default
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1784 components: tf-notebook-image: pin to base image
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/versions/1.10.1/version-config.json
  components/tensorflow-notebook-image/versions/1.4.1/version-config.json
  components/tensorflow-notebook-image/versions/1.5.1/version-config.json
  components/tensorflow-notebook-image/versions/1.6.0/version-config.json
  components/tensorflow-notebook-image/versions/1.7.0/version-config.json
  components/tensorflow-notebook-image/versions/1.8.0/version-config.json
  components/tensorflow-notebook-image/versions/1.9.0/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#1874 fix iap script
  kubeflow/core/configure_envoy_for_iap.sh
Labels: approved, cla: yes, lgtm, size/XS

#1880 Add a script that automatically creates cherry-picks
  hack/cherry-picks.md
  hack/cherry_pick_pull.sh
Labels: approved, cla: yes, lgtm, size/L

#1845 prober test, kubeflow testing part
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/L

#1873 Fixing the conflict with the getting started guide
  scripts/download.sh
Labels: approved, cla: yes, lgtm, size/XS

#1865 Add base href for correct link in Argo UI
  kubeflow/argo/argo.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1785 [cuda] use runtime image instead of development image
  components/k8s-model-server/images/versions/1.7gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.10.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.5.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.6.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.7.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.8.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.9.0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#1875 upgrade app version to 0.3.2
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1879 fix iap script
  kubeflow/core/configure_envoy_for_iap.sh
Labels: approved, cla: yes, lgtm, size/XS

#1893 Dm conf
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/cmd/bootstrap/app/server.go
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/L
