Repository kubeflow/kubeflow, pull requests merged in 2018-05, with the labels that each got.

#745 Add tf1.8 build to jupyter notebook images
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#741 Fix Serving metadata
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#750 Move away from mlkube-testing to kubeflow-ci
  releasing/releaser/components/params.libsonnet
  releasing/releaser/components/workflows.libsonnet
  testing/Dockerfile
  testing/Makefile
  testing/README.md
  testing/run.sh
  testing/test-data/successful_workflow.yaml
Labels: approved, lgtm, size/M

#728 Argo Ksonnet package - Add Docker image Tag
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
Labels: approved, lgtm, size/M

#688 tf-serving support model on NFS
  components/k8s-model-server/Serve a local model using Tensorflow Serving.md
  kubeflow/tf-serving/tf-serving.libsonnet
  user_guide.md
Labels: approved, lgtm, size/L

#747 Add test to check jsonnet formatting
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/images/releaser/lib/v1.7.0/k.libsonnet
  components/k8s-model-server/images/releaser/lib/v1.7.0/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/k.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/k8s.libsonnet
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/prototypes/tensorboard.jsonnet
  kubeflow/core/tensorboard.libsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  kubeflow/core/util.libsonnet
  kubeflow/new-package-stub/all.libsonnet
  kubeflow/openmpi/assets.libsonnet
  kubeflow/pachyderm/all.libsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-job.libsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  kubeflow/tf-serving/util.libsonnet
  releasing/releaser/environments/releasing/params.libsonnet
  releasing/releaser/lib/v1.7.0/k.libsonnet
  releasing/releaser/lib/v1.7.0/k8s.libsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-ci/main.jsonnet
  testing/workflows/environments/kubeflow-ci/params.libsonnet
  testing/workflows/lib/v1.7.0/k.libsonnet
  testing/workflows/lib/v1.7.0/k8s.libsonnet
  testing/workflows/vendor/kubeflow/core/README.md
  testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet
  testing/workflows/vendor/kubeflow/core/nfs.libsonnet
  testing/workflows/vendor/kubeflow/core/parts.yaml
  testing/workflows/vendor/kubeflow/core/prototypes/all.jsonnet
  testing/workflows/vendor/kubeflow/core/tf-job.libsonnet
Labels: approved, lgtm, size/XXL

#756 [openmpi] Support RBAC
  kubeflow/openmpi/service.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/M

#759 Fix bytes literals in Python3
  tf-controller-examples/tf-cnn/launcher.py
Labels: approved, lgtm, size/XS

#754 [openmpi] Add more parameters for GPU training
  kubeflow/openmpi/README.md
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/assets/mca-params.conf
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/util.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/M

#761 [openmpi] Wait for nvidia driver to be installed before running MPI job
  components/openmpi-controller/Makefile
  components/openmpi-controller/controller/controller.py
  components/openmpi-controller/controller/main.py
  components/openmpi-controller/controller/util.py
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/L

#764 [openmpi] make RBAC be optional
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/service.libsonnet
  kubeflow/openmpi/serviceaccount.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/M

#769 Python script to set parameters for ksonnet prototypes
  scripts/update_prototype.py
Labels: approved, lgtm, size/M

#776 Update seldon ksonnet image versions to 0.1.6
  kubeflow/seldon/prototypes/core.jsonnet
Labels: approved, lgtm, size/XS

#773 [openmpi]: Fix `wait_mpi_ready()` hangs when using OpenMPI 2.1.3
  kubeflow/openmpi/assets/init.sh
Labels: approved, lgtm, size/XS

#772 [openmpi] Add custom resources support
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/XS

#771 [openmpi] support `imagePullSecrets`
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/XS

#777 Argo workflow e2e test
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#765 Support building different version of TF Serving images
  components/README.md
  components/build_image.py
  components/k8s-model-server/images/Dockerfile.cpu
  components/k8s-model-server/images/Dockerfile.gpu
  components/k8s-model-server/images/versions/1.4/version-config.json
  components/k8s-model-server/images/versions/1.6/version-config.json
  components/k8s-model-server/images/versions/1.6gpu/version-config.json
  components/k8s-model-server/images/versions/1.7/version-config.json
  components/k8s-model-server/images/versions/1.7gpu/version-config.json
Labels: approved, lgtm, size/L

#790 Support TF serving 1.5 image
  components/README.md
  components/k8s-model-server/images/versions/1.5/version-config.json
Labels: approved, lgtm, size/XS

#768 Create an examples package in kubeflow
  kubeflow/examples/parts.yaml
  kubeflow/examples/prototypes/tf-job-simple.jsonnet
  kubeflow/examples/prototypes/tf-serving-simple.jsonnet
  kubeflow/examples/prototypes/tf-serving-with-istio.jsonnet
Labels: approved, lgtm, size/L

#789 Checking that Ambassador started in e2e test
  testing/test_deploy.py
Labels: approved, lgtm, size/XS

#791 Python script to build TF notebook images
  components/README.md
  components/build_image.py
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/versions/1.4.1/version-config.json
  components/tensorflow-notebook-image/versions/1.4.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.5.1/version-config.json
  components/tensorflow-notebook-image/versions/1.5.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.6.0/version-config.json
  components/tensorflow-notebook-image/versions/1.6.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.7.0/version-config.json
  components/tensorflow-notebook-image/versions/1.7.0gpu/version-config.json
Labels: approved, lgtm, size/L

#782 Create a ksonnet package for injecting credentials through pod presets
  kubeflow/credentials-pod-preset/README.md
  kubeflow/credentials-pod-preset/parts.yaml
  kubeflow/credentials-pod-preset/prototypes/gcp-credentials-pod-preset.jsonnet
Labels: approved, lgtm, size/L

#792 Refactor testing package
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  testing/deploy_kubeflow.py
  testing/deploy_utils.py
  testing/get_gke_credentials.py
  testing/test-data/successful_workflow.yaml
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL

#766 Support deploy kubeflow bootstrapper within k8s
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/bootstrapper.yaml
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/examples/kubeflow_toolbox.yaml
  bootstrap/kubeconfig_fake.yml
Labels: approved, lgtm, size/L

#785 [tf-job] support image pull secrets
  kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
  kubeflow/tf-job/prototypes/tf-job.jsonnet
  kubeflow/tf-job/tf-job.libsonnet
  kubeflow/tf-job/util.libsonnet
Labels: approved, lgtm, size/S

#779 Adds ambassador integration for Central UI
  components/centraldashboard/frontend/dashboard.go
  components/centraldashboard/frontend/index/index.html
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/tests/centraldashboard_test.jsonnet
Labels: approved, lgtm, size/L

#797 [openmpi] Download and upload data in the controller
  components/openmpi-controller/Makefile
  components/openmpi-controller/controller/controller.py
  components/openmpi-controller/controller/main.py
  components/openmpi-controller/controller/util.py
  components/openmpi-controller/requirements.txt
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/L

#787 Initial set of deployment manager configs for creating a GKE cluster to run Kubeflow
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/configs/cluster.jinja.schema
  docs/gke/configs/env-kubeflow.sh
  docs/gke/gke_setup.md
  docs/gke/testing/deploy.sh
  prow_config.yaml
  testing/workflows/app.yaml
  testing/workflows/components/gke_deploy.jsonnet
  testing/workflows/components/gke_deploy.libsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/environments/kubeflow-testing/main.jsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: approved, lgtm, size/XL

#799 seldon load model files from PVC
  kubeflow/seldon/prototypes/serve-simple.jsonnet
  kubeflow/seldon/serve-simple.libsonnet
Labels: approved, lgtm, size/M

#803 add bootstrapper to e2e test
  bootstrap/build_image.sh
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#743 Make TFJob operator a standalone prototype
  kubeflow/core/all.libsonnet
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
  testing/workflows/vendor/kubeflow/core/tf-job-operator.libsonnet
Labels: approved, lgtm, size/L

#800 add meta api for serving
  components/k8s-model-server/http-proxy/server.py
Labels: approved, lgtm, size/S

#814 deployment manager uses new stackdriver agents
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/S

#827 IAP should route to central ui instead of jupyterhub
  kubeflow/core/iap.libsonnet
Labels: approved, lgtm, size/S

#831 [openmpi] Update README about GPU and horovod training
  kubeflow/openmpi/README.md
Labels: approved, lgtm, size/S

#820 [openmpi] support non-root users run jobs (introducing `runAsUser`, `runAsGroup`, `supplementalGroups`)
  components/openmpi-controller/Dockerfile
  components/openmpi-controller/Makefile
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/assets/ssh_config
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/util.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/M

#825 cron job & workflow config for image release
  releasing/cron_job_release.yaml
  releasing/prow_config_release.yaml
Labels: approved, lgtm, size/M

#617 Update README to reflect install experience
  user_guide.md
Labels: approved, lgtm, size/XS

#839 Add kunmingg as owner
  OWNERS
Labels: approved, lgtm, size/XS

#840 Use relative directory path so that build_image.py can be called from another dir
  components/build_image.py
Labels: approved, lgtm, size/XS

#849 params update for release workflow
  components/tensorflow-notebook-image/releaser/components/params.libsonnet
  releasing/cron_job_release.yaml
Labels: approved, lgtm, size/XS

#786 Modify NB Dockerfile and start scripts to support mount of /home/jovyan
  bootstrap/cmd/bootstrap/app/server.go
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/pvc-check.sh
  components/tensorflow-notebook-image/start-singleuser.sh
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/tests/jupyterhub_test.jsonnet
  user_guide.md
Labels: approved, lgtm, size/L

#823 Start deploying the bootstrapper via deployment manager.
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/configs/env-kubeflow.sh
  docs/gke/gke_setup.md
Labels: approved, lgtm, size/L

#857 Fix push_dockerhub in k8s-model-server/images/Makefile
  components/k8s-model-server/images/Makefile
Labels: approved, lgtm, size/XS

#856 build_image.py supports pushing images
  components/build_image.py
Labels: approved, lgtm, size/S

#859 Use a config map to configure bootstrapper.
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/M

#864 build_image.py waiting for docker daemon
  components/build_image.py
Labels: approved, lgtm, size/S

#853 Use yaml config to manage k8s resources deployed by bootstrapper
  bootstrap/Dockerfile
  bootstrap/bootstrapper.yaml
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  testing/e2e_env.yaml
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#867 Update the script so that we don't assume that the remote repository is
  scripts/autoformat_jsonnet.sh
Labels: approved, lgtm, size/S

#851 ksonnet changes to support deploying the v1alpha2 TFJob operator.
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, lgtm, size/L

#866 Create a python script to deploy Kubeflow on GCP via deployment manager.
  docs/gke/configs/cluster.jinja
  testing/deploy_kubeflow.py
  testing/deploy_kubeflow_gcp.py
  testing/deploy_utils.py
  testing/teardown_kubeflow_gcp.py
  testing/workflows/components/gke_deploy.libsonnet
  testing/workflows/components/params.libsonnet
Labels: approved, lgtm, size/L

#882 Restore openssh-client to NB images
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#886 Add tf notebook image 1.8 version
  components/README.md
  components/tensorflow-notebook-image/versions/1.8.0/version-config.json
  components/tensorflow-notebook-image/versions/1.8.0gpu/version-config.json
Labels: approved, lgtm, size/S

#889 fix endpoin deploy prototype
  kubeflow/core/cloud-endpoints.libsonnet
Labels: approved, lgtm, size/XS

#872 deployment manager and prototype bug fix
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/gcp_prototype.yaml
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/env-kubeflow.sh
Labels: approved, lgtm, size/M

#893 Use deployment name as the NAME_PREFIX and CLUSTER_NAME
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/XS

#879 Add GKE Security Features to Deployment Manager config
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/L

#892 Merge PVC from spawner and provisioners
  components/tensorflow-notebook-image/pvc-check.sh
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/S

#798 Adds Makefile to build the centraldashboard image
  components/centraldashboard/config/Dockerfile
  components/centraldashboard/frontend/Dockerfile
  components/centraldashboard/frontend/Makefile
  components/centraldashboard/frontend/dashboard.go
  components/centraldashboard/frontend/index/index.html
Labels: approved, lgtm, size/M
