Repository kubeflow/kubeflow, pull requests merged in 2018-11, with the labels that each got.

#1884 Automated cherry pick of #1717 upstream v0.3 branch
  .gitignore
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1872 create a self-serve component for data-scientists
  kubeflow/metacontroller/metacontroller.libsonnet
  kubeflow/metacontroller/prototypes/metacontroller.jsonnet
  kubeflow/metacontroller/tests/metacontroller_test.jsonnet
  kubeflow/profiles/parts.yaml
  kubeflow/profiles/profiles.libsonnet
  kubeflow/profiles/prototypes/README.md
  kubeflow/profiles/prototypes/docs/iamusers.png
  kubeflow/profiles/prototypes/docs/jobsandnotebooks.png
  kubeflow/profiles/prototypes/docs/namespacegroups.png
  kubeflow/profiles/prototypes/docs/namespaces.png
  kubeflow/profiles/prototypes/docs/rolebindings.png
  kubeflow/profiles/prototypes/docs/serviceaccounts.png
  kubeflow/profiles/prototypes/docs/userflow.png
  kubeflow/profiles/prototypes/profiles.jsonnet
  kubeflow/profiles/sync-permission.jsonnet
  kubeflow/profiles/sync-profile.jsonnet
  kubeflow/profiles/tests/profiles_test.jsonnet
  kubeflow/profiles/tests/sync-permission_test.jsonnet
  kubeflow/profiles/tests/sync-profile_test.jsonnet
  kubeflow/registry.yaml
  scripts/util.sh
  testing/test_jsonnet.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#1897 Fix model rollout with Istio
  kubeflow/tf-serving/prototypes/tf-serving-service.jsonnet
  kubeflow/tf-serving/tests/tf_serving_test.jsonnet
  kubeflow/tf-serving/tf-serving-service-template.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1902 Fix skip init project; use spaces consistently for indentation
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#1906 Envoy config change for istio
  docs/gke/gateway.yaml
  kubeflow/core/iap.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1910 make links open in new tab
  components/gcp-click-to-deploy/src/App.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1888 Provide an error message in case GCP ZONE is not set and exit, also fix styles for kfctl.sh
  .gitignore
  scripts/kfctl.sh
  testing/workflows/components/kfctl_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1919 fix typo
  docs/gke/gateway.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1921 Update tf-operator component to v1beta1
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
  kubeflow/examples/prototypes/tf-job-simple-v1beta1.jsonnet
  testing/deploy_kubeflow.py
  testing/tf_job_simple_test.py
  testing/wait_for_kubeflow.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1839 Refactor JH integration and UI
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/jupyterhub_config.py
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  kubeflow/core/ui/default/config.yaml
  kubeflow/core/ui/default/script.js
  kubeflow/core/ui/default/spawner.py
  kubeflow/core/ui/default/style.css
  kubeflow/core/ui/default/template.html
Labels: approved, cla: yes, lgtm, size/XL

#1926 Consolidate the ksonnet component update scripts
  docs_dev/releasing.md
  releasing/update_components.sh
  releasing/update_images.sh
  releasing/update_katib_ksonnet.sh
  releasing/update_ksonnet.sh
Labels: approved, cla: yes, lgtm, size/L

#1917 fixes 'ksonnet package for Jupyter/JupyterHub'
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  kubeflow/application/prototypes/README.md
  kubeflow/core/README.md
  kubeflow/core/iap.libsonnet
  kubeflow/core/setup_backend.sh
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/jupyter_config.py
  kubeflow/jupyter/parts.yaml
  kubeflow/jupyter/prototypes/jupyter.jsonnet
  kubeflow/jupyter/tests/jupyter_test.jsonnet
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/jupyter/ui/default/script.js
  kubeflow/jupyter/ui/default/spawner.py
  kubeflow/jupyter/ui/default/style.css
  kubeflow/jupyter/ui/default/template.html
  kubeflow/registry.yaml
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/setup-minikube.sh
  scripts/util-minikube.sh
  scripts/util.sh
  testing/README.md
  testing/deploy_kubeflow.py
  testing/deploy_utils.py
  testing/install_minikube.sh
  testing/test_jsonnet.py
  testing/wait_for_kubeflow.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1930 Adding support for Pytorch v1beta1 operator
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1786 [tf-notebook-image] add tf 1.11 cpu and gpu images
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/versions/1.11.0/version-config.json
  components/tensorflow-notebook-image/versions/1.11.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.12.0/version-config.json
  components/tensorflow-notebook-image/versions/1.12.0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#1941 Switch spartakus volunteer image to v1.1.0
  kubeflow/core/spartakus.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1945 Redirect deployer webapp page to Kubeflow dashboard after its ready
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#1951 Add pipeline to centaldashboard
  components/centraldashboard/frontend/index/index.html
Labels: approved, cla: yes, lgtm, size/XS

#1942 Parse all command line options in one place and within function
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/L

#1956 Allow CloudShell origin pattern in Jupyter config
  components/tensorflow-notebook-image/jupyter_notebook_config.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1937 Use iam-policy value for EMAIL if case-sensitive.
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1955 update katib components
  kubeflow/katib/modeldb.libsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
  kubeflow/katib/vizier.libsonnet
  releasing/update_components.sh
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, size/L

#1957 Automated cherry pick of #1904: Fix capitalization in katib ID fields Cherry pick of #1904 on v0.3-branch. #1904: Fix capitalization in katib ID fields
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#1958 Add prometheus annotation to tf serving service
  kubeflow/tf-serving/prototypes/tf-serving-service.jsonnet
  kubeflow/tf-serving/tf-serving-service-template.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1923 miscellaneous updates and enhacements for shell scripts
  bootstrap/build_image.sh
  bootstrap/debug.sh
  bootstrap/start.sh
  bootstrap/test_delete.sh
  bootstrap/test_setup.sh
  build/check_boilerplate.sh
  components/centraldashboard/build_image.sh
  components/gcp-click-to-deploy/ks-app/create_gcp_deploy_sa.sh
  components/k8s-model-server/http-proxy/build_image.sh
  components/k8s-model-server/images/build_image.sh
  components/k8s-model-server/inception-client/run.sh
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/install.sh
  components/tensorflow-notebook-image/pvc-check.sh
  components/tensorflow-notebook-image/start-notebook.sh
  components/tensorflow-notebook-image/start-singleuser.sh
  components/tensorflow-notebook-image/start.sh
  hack/cherry_pick_pull.sh
  hack/retag_katib_images.sh
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/ingress_bootstrap.sh
  kubeflow/core/setup_backend.sh
  kubeflow/openmpi/assets/init.sh
  releasing/add_katib_image_shas.sh
  releasing/run_apply_image_tags.sh
  releasing/update_components.sh
  releasing/update_image_tags.sh
  scripts/autoformat_jsonnet.sh
  scripts/cleanup_kubeflow_ci.sh
  scripts/download.sh
  scripts/gke/delete_deployment.sh
  scripts/gke/teardown.sh
  scripts/gke/use_gcr_for_all_images.sh
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/kfctl_generate_test.sh
  scripts/run_gofmt.sh
  scripts/setup-minikube.sh
  scripts/update-changelog.sh
  scripts/util-minikube.sh
  scripts/util.sh
  testing/install_minikube.sh
  testing/run.sh
  testing/workflows/run.sh
Labels: approved, cla: yes, lgtm, size/XXL

#1962 Fix dashboard URI and increase poll interval.
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1963 Initial version of a Kubeflow Roadmap.
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/M

#1841 Separate logic for setup_backend.sh
  kubeflow/core/iap.libsonnet
  kubeflow/core/setup_backend.sh
  kubeflow/core/update_backend.sh
Labels: approved, cla: yes, lgtm, size/L

#1974 Add IronPan as Argo owner
  kubeflow/argo/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1927 make IAP optional for click-deploy app
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
  deployment/gke/cloud_shell_templates/conn.md
  deployment/gke/cloud_shell_templates/conn.sh
Labels: approved, cla: yes, lgtm, size/L

#1975 Check for python module pyyaml when using kfctl.sh on platform GCP.
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1855 fixes 'create a notebook controller that can replace jupyterhub and uses k8 native auth'
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
  kubeflow/jupyter/notebooks.libsonnet
  kubeflow/jupyter/notebooks.schema
  kubeflow/jupyter/parts.yaml
  kubeflow/jupyter/prototypes/README.md
  kubeflow/jupyter/prototypes/docs/jupyter_notebook.png
  kubeflow/jupyter/prototypes/notebooks.jsonnet
  kubeflow/jupyter/sync-notebook.jsonnet
  kubeflow/jupyter/tests/notebooks_test.jsonnet
  kubeflow/jupyter/tests/sync-notebook_test.jsonnet
  kubeflow/profiles/profiles.libsonnet
  kubeflow/profiles/sync-permission.jsonnet
  kubeflow/profiles/tests/profiles_test.jsonnet
  kubeflow/profiles/tests/sync-permission_test.jsonnet
  kubeflow/registry.yaml
  scripts/util.sh
  testing/test_jsonnet.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#1908 make prober always sleep before execute
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/S

#1973 initial change - add pipeline entry to kubeflow registry
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/mysql.libsonnet
  kubeflow/pipeline/parts.yaml
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/pipeline-persistenceagent.libsonnet
  kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
  kubeflow/pipeline/pipeline-ui.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/spartakus.libsonnet
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1980 Add IronPan to pipeline ks package owner
  kubeflow/pipeline/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1981 add pipeline as part of kf deployment
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  kubeflow/pipeline/parts.yaml
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/L

#1984 Remove IAM permission from DM service account
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#1978 Adding Pytorch v1beta1 image
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1987 Fix CRD scopes.
  kubeflow/katib/studyjobcontroller.libsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1992 Add texasmichelle to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1998 Pipelines 0.3.3 cherrypick
  .travis.yml
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  kubeflow/argo/OWNERS
  kubeflow/pipeline/OWNERS
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/mysql.libsonnet
  kubeflow/pipeline/parts.yaml
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/pipeline-persistenceagent.libsonnet
  kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
  kubeflow/pipeline/pipeline-ui.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/spartakus.libsonnet
  kubeflow/registry.yaml
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/XXL

#2004 use backoff module to handle IAM policy retry with randmize wait time
  bootstrap/cmd/bootstrap/app/gcpUtils.go
Labels: approved, cla: yes, lgtm, size/S

#2003 Fix bad merge conflict on v0.3-branch
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2002 Adding scope for tf job dashboard
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2008 Add latest stable DSL SDK to jupyter image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1986 deploy app loadtest, python part
  bootstrap/config/gcp_prototype.yaml
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/L

#2007 fixes 'trying to deploy a component using ks after initial deployment fails'
  kubeflow/application/application.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1916 fixes 'Create an openvino component'
  kubeflow/openvino/openvino.libsonnet
  kubeflow/openvino/parts.yaml
  kubeflow/openvino/prototypes/openvino.jsonnet
  kubeflow/openvino/tests/openvino_test.jsonnet
  kubeflow/registry.yaml
  scripts/util.sh
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2013 grant KF user SA CMLE admin permission
  deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2017 Activate CMLE during one-click deployment
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#2025 Grafana routing rule
  istio/grafana-virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/S
