Repository kubeflow/kubeflow, pull requests merged in 2018-04, with the labels that each got.

#543 Add tf1.7 to tensorflow-notebook images
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#544 Add the "tensorflow-model-analysis" package to the notebook images
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/S

#523 Changes to support running E2E tests on minikube.
  .style.yapf
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  prow_config.yaml
  testing/install_minikube.sh
  testing/test_deploy.py
  testing/test_deploy_test.py
  testing/workflows/app.yaml
  testing/workflows/components/params.libsonnet
  testing/workflows/components/workflows.jsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-ci/main.jsonnet
  testing/workflows/environments/kubeflow-ci/params.libsonnet
Labels: approved, lgtm, size/XL

#559 Rety upto 3 times while building tensorflow notebook images
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#524 Docs should show how to pull a particular release
  README.md
  user_guide.md
Labels: approved, lgtm, size/S

#542 add willb to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#570 Update tf jupter notebook images to include tfma (from #544)
  kubeflow/core/jupyterhub_spawner.py
Labels: approved, lgtm, size/XS

#572 Moved OAuth secret from param to named secret
  docs/gke/iap.md
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
Labels: approved, lgtm, size/M

#575 Cherrypick #570 and #572 into v0.1-branch
  docs/gke/iap.md
  kubeflow/core/iap.libsonnet
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/iap-ingress.jsonnet
Labels: approved, lgtm, size/M

#577 Disable PVC by default
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  user_guide.md
Labels: approved, lgtm, size/XS

#580 Fix the tensorflow version in prebuilt images for python 2.7.
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#556 Correct typo for param defaultHttpProxyImage
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/XS

#582 Disable PVC by default (#577)
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  user_guide.md
Labels: approved, lgtm, size/M

#565 Add pdmack to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#584 Correct typo for param defaultHttpProxyImage (#556)
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/XS

#583 Install graphviz in tensorflow notebook image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#532 Update instructions about releasing TFJob
  releasing.md
Labels: approved, lgtm, size/M

#588 README: Add link for tf-operator
  README.md
Labels: approved, lgtm, size/XS

#552 sidecar for envoy pod to keep IAP up to date
  docs/gke/iap.md
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  kubeflow/core/tests/nfs_test.jsonnet
  kubeflow/core/tests/spartakus_test.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job.libsonnet
  kubeflow/seldon/crd.libsonnet
  kubeflow/seldon/prototypes/core.jsonnet
  kubeflow/seldon/prototypes/serve-simple.jsonnet
  kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
  kubeflow/tf-job/prototypes/tf-job.jsonnet
  kubeflow/tf-job/tf-job.libsonnet
Labels: approved, lgtm, size/XXL

#589 Update tensorflow notebook version to v20180403-1f854c44
  kubeflow/core/jupyterhub_spawner.py
Labels: approved, lgtm, size/S

#590 Cherry pick : Update tensorflow notebook version to v20180403-1f854c44 (#589)
  kubeflow/core/jupyterhub_spawner.py
Labels: approved, lgtm, size/S

#585 CP: Install graphviz in tensorflow notebook image (#583)
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#601 Update the docs to point to the v0.1.0 release now that it is cut.
  README.md
  user_guide.md
Labels: approved, lgtm, size/XS

#599 Typo in UG
  user_guide.md
Labels: approved, lgtm, size/XS

#519 Branching and tagging policy for releases
  releasing.md
Labels: approved, lgtm, size/M

#600 Create a doc with information about our docker images.
  docs_dev/README.md
  docs_dev/images.md
  docs_dev/releasing.md
Labels: approved, lgtm, size/S

#609 Provide documentation about adding ksonnet packages to Kubeflow.
  developer_guide.md
  docs_dev/ksonnet_packages.md
  kubeflow/core/util.libsonnet
  kubeflow/new-package-stub/all.libsonnet
  kubeflow/new-package-stub/parts.yaml
  kubeflow/new-package-stub/prototypes/tf-prototype.jsonnet
  kubeflow/registry.yaml
Labels: approved, lgtm, size/L

#614 images: Add the link
  docs_dev/images.md
Labels: approved, lgtm, size/XS

#613 Improve documentation
  README.md
  testing/vm_util.py
  user_guide.md
Labels: approved, lgtm, size/L

#616 Update and clarify JupyterHub README
  components/jupyterhub/README.md
Labels: approved, lgtm, size/M

#610 Initial ksonnet package for Pachyderm.
  kubeflow/pachyderm/all.libsonnet
  kubeflow/pachyderm/parts.yaml
  kubeflow/pachyderm/prototypes/pachyderm.jsonnet
  kubeflow/registry.yaml
Labels: approved, lgtm, size/L

#620 Fix setup/teardown of VM for minikube.
  testing/test_deploy.py
  testing/vm_util.py
Labels: approved, lgtm, size/L

#608 Upgrade tf-serving version to 1.6.0
  components/k8s-model-server/http-proxy/requirements/production.txt
  components/k8s-model-server/images/Dockerfile.cpu
  components/k8s-model-server/images/Dockerfile.gpu
  components/k8s-model-server/inception-client/requirements.txt
Labels: approved, lgtm, size/M

#558 Enable TF serving gpu test
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  testing/test_tf_serving.py
Labels: approved, lgtm, size/S

#638 Use dashes not underscores in junit file names.
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#625 Improve user guide wrt exposing notebook in non-cloud setup
  user_guide.md
Labels: approved, lgtm, size/S

#628 Cleaned up README.md
  README.md
Labels: approved, lgtm, size/M

#604 docs(TOC): add auto-generated TOC for all docs
  CONTRIBUTING.md
  README.md
  components/jupyterhub/README.md
  components/k8s-model-server/README.md
  components/k8s-model-server/http-proxy/README.md
  components/k8s-model-server/images/README.md
  components/k8s-model-server/test-data/README.md
  docs/gke/iap.md
  docs/gke/tf_serving_iap.md
  docs_dev/images.md
  docs_dev/ksonnet_packages.md
  docs_dev/releasing.md
  kubeflow/README.md
  kubeflow/argo/README.md
  kubeflow/core/README.md
  kubeflow/tf-job/README.md
  kubeflow/tf-serving/README.md
  testing/README.md
  testing/workflows/vendor/kubeflow/core/README.md
  tf-controller-examples/tf-cnn/README.md
  user_guide.md
Labels: approved, lgtm, size/L

#627 TF Serving + Istio
  components/k8s-model-server/istio-dashboard.png
  components/k8s-model-server/istio-integration.md
  kubeflow/tf-serving/tf-serving.libsonnet
  kubeflow/tf-serving/util.libsonnet
Labels: approved, lgtm, size/L

#634 Create a kubeflow version file: version.txt and a configmap kubeflow-version
  kubeflow/core/all.libsonnet
  kubeflow/core/version-info.json
  kubeflow/core/version.libsonnet
Labels: approved, lgtm, size/S

#647 Remove the outdated YAML specs for TFCnn job.
  tf-controller-examples/tf-cnn/README.md
  tf-controller-examples/tf-cnn/tf_job_cpu.yaml
  tf-controller-examples/tf-cnn/tf_job_cpu_distributed.yaml
  tf-controller-examples/tf-cnn/tf_job_gpu.yaml
  tf-controller-examples/tf-cnn/tf_job_gpu_distributed.yaml
Labels: approved, lgtm, size/L

#648 Remove zjj2wry as a reviewer.
  OWNERS
Labels: approved, lgtm, size/XS

#624 Add openmpi package
  kubeflow/openmpi/README.md
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/assets/mca-params.conf
  kubeflow/openmpi/assets/ssh_config
  kubeflow/openmpi/assets/sshd_config
  kubeflow/openmpi/parts.yaml
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/service.libsonnet
  kubeflow/openmpi/workloads.libsonnet
  kubeflow/registry.yaml
Labels: approved, lgtm, size/L

#642 Change naming from jupyter to jupyterhub when referring to hub
  components/jupyterhub/README.md
  docs_dev/releasing.md
  kubeflow/core/all.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/tests/jupyterhub_test.jsonnet
  testing/test_deploy.py
  testing/workflows/vendor/kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/M

#656 Add willingc to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#659 Include tensor2tensor in jupyter notebook image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#646 update user_guide
  user_guide.md
Labels: approved, lgtm, size/XS

#645 Add components to work with GCP
  kubeflow/pachyderm/README.md
  kubeflow/pachyderm/all.libsonnet
Labels: approved, lgtm, size/L

#650 [Azure] Update nvidia driver volumes for AKS
  kubeflow/core/tf-job.libsonnet
Labels: approved, cloud/azure, lgtm, size/S

#605 import of cloud-endpoints component and support in iap-ingress component
  docs/gke/iap.md
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/cloud-endpoints.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/cloud-endpoints.jsonnet
Labels: approved, lgtm, size/L

#655 [Azure] Jupyter spawner: driver volumes for azure
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/L

#670 make Dockerfile & Makefile cross platform
  bootstrap/Dockerfile
  bootstrap/Makefile
Labels: approved, lgtm, size/S

#678 Add documentation for exposing grafana dashboard
  components/k8s-model-server/README.md
  components/k8s-model-server/istio-integration.md
Labels: approved, lgtm, size/M

#671 Add batch support to openmpi package
  kubeflow/openmpi/README.md
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/assets/mca-params.conf
  kubeflow/openmpi/parts.yaml
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/redis.libsonnet
  kubeflow/openmpi/service.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/L

#676 openmpi package doesn't work on kubernetes cluster having custom dns.
  kubeflow/openmpi/assets.libsonnet
Labels: approved, lgtm, size/XS

#652 add link to Intel's tutorial
  user_guide.md
Labels: approved, lgtm, size/XS

#685 [openmpi] Add GPU support
  kubeflow/openmpi/README.md
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/M

#680 create rolebinding within namespace to guarantee permission
  bootstrap/README.md
  bootstrap/cmd/bootstrap/app/server.go
Labels: approved, lgtm, size/M

#689 Refactor tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/requirements.txt
  components/tensorflow-notebook-image/start.sh
Labels: approved, lgtm, size/L

#683 openmpi: make 'schedulerName' configurable to use custom schedulers.
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/XS

#690 openmpi: fix failing installing redis-tools in init.sh
  kubeflow/openmpi/assets/init.sh
Labels: approved, lgtm, size/XS

#693 add export to ksonnet github token instructions
  README.md
Labels: approved, lgtm, size/XS

#694 Pin instructions to ks 0.9.2 (for now)
  README.md
  user_guide.md
Labels: approved, lgtm, size/XS

#695 Migrate images to kubeflow-images-public
  bootstrap/README.md
  components/k8s-model-server/images/releaser/components/params.libsonnet
  docs_dev/images.md
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet
Labels: approved, lgtm, size/M

#696 openmpi: master/workers sync mechanism is replaced with k8s api from redis
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/parts.yaml
  kubeflow/openmpi/redis.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/L

#697 Update the hub spawner dropdown for latest NB images
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/S

#699 permission bug fix and image tag update
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/README.md
  bootstrap/cmd/bootstrap/app/server.go
Labels: approved, lgtm, size/S

#703 CP to V0.1 branch: TF notebook slimming, joyvan pip installs, and new gcr.io locations
  components/k8s-model-server/images/releaser/components/params.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/params.libsonnet
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/params.libsonnet
  components/tensorflow-notebook-image/requirements.txt
  components/tensorflow-notebook-image/start.sh
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  releasing/releaser/environments/releasing/params.libsonnet
  testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet
Labels: approved, lgtm, size/L

#706 Point instructions to 0.1.2 release
  README.md
  user_guide.md
Labels: approved, lgtm, size/S

#698 openmpi: namespaced resource names should be prefixed with component name
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/service.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/S

#704 [openmpi] Introduce a sidecar container for inter-pod synchronization
  components/openmpi-controller/.gitignore
  components/openmpi-controller/Dockerfile
  components/openmpi-controller/Makefile
  components/openmpi-controller/controller/__init__.py
  components/openmpi-controller/controller/controller.py
  components/openmpi-controller/controller/main.py
  components/openmpi-controller/requirements.txt
  kubeflow/openmpi/README.md
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, lgtm, size/L

#711 [openmpi] Add OWNERS file
  components/openmpi-controller/OWNERS
  kubeflow/openmpi/OWNERS
Labels: approved, lgtm, size/XS

#715 add kunming to reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#714 controller bug fix
  docs/gke/iap.md
  kubeflow/core/cloud-endpoints.libsonnet
Labels: approved, lgtm, size/XS

#724 Add a few packages to the jupyter notebook image
  components/tensorflow-notebook-image/requirements.txt
Labels: approved, lgtm, size/XS

#725 update ksonnet version to v0.10.0-alpha.3
  bootstrap/Dockerfile
Labels: approved, lgtm, size/XS

#553 Reformats only modified files by default #395
  scripts/autoformat_jsonnet.sh
Labels: approved, lgtm, size/M

#649 Pytorch ksonnet
  docs_dev/releasing.md
  kubeflow/pytorch-job/README.md
  kubeflow/pytorch-job/parts.yaml
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-job.libsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/registry.yaml
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
  user_guide.md
Labels: approved, lgtm, size/XL

#729 Remove spurious comma
  docs/gke/iap.md
Labels: approved, lgtm, size/XS

#673 Create deploy job
  .gitignore
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/deploy.sh
  bootstrap/examples/kubeflow_toolbox.yaml
  bootstrap/kubeconfig_fake.yml
  bootstrap/start.sh
Labels: approved, lgtm, size/L
