Repository kubeflow/kubeflow, pull requests merged in 2018-03, with the labels that each got.

#311 Fix #285 and make few tweaks to notebook Dockerfile
  components/tensorflow-notebook-image/Dockerfile.cpu
  components/tensorflow-notebook-image/start.sh
Labels: size/M

#298 Start instructions for creating a release
  components/k8s-model-server/images/releaser/components/workflows.jsonnet
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/k.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/swagger.json
  components/k8s-model-server/images/releaser/environments/releasing/main.jsonnet
  components/k8s-model-server/images/releaser/environments/releasing/params.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/spec.json
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  releasing.md
Labels: size/XXL

#316 Create an initial owners file.
  OWNERS
Labels: lgtm, size/S

#314 Add support for Python 2 kernels to the tensorflow notebook images.
  components/tensorflow-notebook-image/Dockerfile.cpu
  components/tensorflow-notebook-image/Dockerfile.gpu
Labels: approved, size/S

#320 Optimize start.sh
  components/tensorflow-notebook-image/start.sh
Labels: approved, size/S

#315 Update the Dockerfiles for tensorflow notebook images
  components/tensorflow-notebook-image/Dockerfile.cpu
  components/tensorflow-notebook-image/Dockerfile.gpu
Labels: approved, size/M

#175 Use spartakus to report usage metrics
  README.md
  kubeflow/core/all.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/spartakus.libsonnet
  user_guide.md
Labels: approved, size/L

#317 Create an Argo workflow to build the Jupyter images.
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/releaser/.ksonnet/registries/incubator/ea3408d44c2d8ea4d321364e5533d5c60e74bce0.yaml
  components/tensorflow-notebook-image/releaser/.ksonnet/registries/kubeflow/5c35580d76092788b089cb447be3f3097cffe60b.yaml
  components/tensorflow-notebook-image/releaser/app.yaml
  components/tensorflow-notebook-image/releaser/components/params.libsonnet
  components/tensorflow-notebook-image/releaser/components/workflows.jsonnet
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/releaser/environments/base.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/k.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/swagger.json
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/main.jsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/params.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/spec.json
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/k.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/swagger.json
  components/tensorflow-notebook-image/releaser/environments/releasing/main.jsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/params.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/spec.json
  releasing.md
Labels: approved, lgtm, size/XXL

#328 Fix jupyterlab by upgrading Jupyterlab
  components/tensorflow-notebook-image/Dockerfile.cpu
  components/tensorflow-notebook-image/Dockerfile.gpu
Labels: approved, lgtm, size/XS

#332 Edit user guide links and wording for Jupyter and JupyterHub
  user_guide.md
Labels: approved, lgtm, size/S

#335 Improve the Python 2 kernels for both CPU and GPU instances.
  components/tensorflow-notebook-image/Dockerfile.cpu
  components/tensorflow-notebook-image/Dockerfile.gpu
Labels: approved, lgtm, size/M

#333 Clarify JupyterHub and Jupyter description in component readme
  components/jupyterhub/README.md
Labels: approved, lgtm, size/M

#330 Refine the text and links related to JupyterHub and Jupyter
  README.md
Labels: approved, lgtm, size/S

#341 Add classify support for http-proxy
  components/k8s-model-server/http-proxy/server.py
Labels: approved, lgtm, size/M

#334 Add signature support to http proxy
  components/k8s-model-server/http-proxy/server.py
  components/k8s-model-server/test-data/README.md
  components/k8s-model-server/test-data/mnist_input.json
Labels: approved, lgtm, size/L

#347 Refactor the workflow for TF Serving
  components/k8s-model-server/images/Dockerfile.cpu
  components/k8s-model-server/images/Dockerfile.gpu
  components/k8s-model-server/images/Makefile
  components/k8s-model-server/images/build_image.sh
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/images/releaser/environments/prow/params.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/L

#339 Build the TF Serving GPU image as part of a release workflow.
  releasing.md
  releasing/releaser/.ksonnet/registries/incubator/ea3408d44c2d8ea4d321364e5533d5c60e74bce0.yaml
  releasing/releaser/.ksonnet/registries/kubeflow/5c35580d76092788b089cb447be3f3097cffe60b.yaml
  releasing/releaser/app.yaml
  releasing/releaser/components/params.libsonnet
  releasing/releaser/components/workflows.jsonnet
  releasing/releaser/components/workflows.libsonnet
  releasing/releaser/environments/base.libsonnet
  releasing/releaser/environments/prow/.metadata/k.libsonnet
  releasing/releaser/environments/prow/.metadata/k8s.libsonnet
  releasing/releaser/environments/prow/.metadata/swagger.json
  releasing/releaser/environments/prow/main.jsonnet
  releasing/releaser/environments/prow/params.libsonnet
  releasing/releaser/environments/prow/spec.json
  releasing/releaser/environments/releasing/.metadata/k.libsonnet
  releasing/releaser/environments/releasing/.metadata/k8s.libsonnet
  releasing/releaser/environments/releasing/.metadata/swagger.json
  releasing/releaser/environments/releasing/main.jsonnet
  releasing/releaser/environments/releasing/params.libsonnet
  releasing/releaser/environments/releasing/spec.json
Labels: approved, lgtm, size/XXL

#362 Create a GPU model deployment to use for E2E testing of serving with GPUs
  components/k8s-model-server/images/Dockerfile.gpu
  components/k8s-model-server/images/releaser/app.yaml
  components/k8s-model-server/images/releaser/components/gpu_model.jsonnet
  components/k8s-model-server/images/releaser/components/params.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/.metadata/k.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/.metadata/swagger.json
  components/k8s-model-server/images/releaser/environments/testing/main.jsonnet
  components/k8s-model-server/images/releaser/environments/testing/params.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/spec.json
  releasing/releaser/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/XXL

#323 Adding S3 support to model serving.
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/M

#359 Allow seperate naming of model name vs deployment name for TF Serving.
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#379 change kubeflow.io to kubeflow.org
  README.md
  components/k8s-model-server/test-data/README.md
  developer_guide.md
  tf-controller-examples/tf-cnn/README.md
Labels: approved, lgtm, size/XS

#384 Add pkg install step for argo README
  kubeflow/argo/README.md
Labels: approved, lgtm, size/XS

#386 Build http proxy image in release workflow
  components/k8s-model-server/http-proxy/build_image.sh
  releasing/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#357 Remove -E from find command as it is not supported by GNU find
  components/k8s-model-server/images/releaser/components/params.libsonnet
  components/k8s-model-server/images/releaser/components/workflows.jsonnet
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/images/releaser/environments/prow/params.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/k.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/main.jsonnet
  components/k8s-model-server/images/releaser/environments/releasing/params.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/.metadata/k.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/main.jsonnet
  components/k8s-model-server/images/releaser/environments/testing/params.libsonnet
  components/tensorflow-notebook-image/releaser/components/workflows.jsonnet
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/k.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/main.jsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/params.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/k.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/main.jsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/params.libsonnet
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  releasing/releaser/environments/releasing/params.libsonnet
  scripts/autoformat_jsonnet.sh
Labels: approved, lgtm, size/XXL

#378 add commands of how to delete a training job
  user_guide.md
Labels: approved, lgtm, size/S

#392 Add info about authenticate user account
  docs/gke/tf_serving_iap.md
Labels: approved, lgtm, size/XS

#387 Refactor the TFServing component to better support GPUs and specific clouds
  components/k8s-model-server/images/releaser/components/params.libsonnet
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  testing/test_deploy.py
  user_guide.md
Labels: approved, lgtm, size/XL

#401 Use the correct jwt validation config
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/iap-envoy.jsonnet
Labels: approved, lgtm, size/S

#400 use tini to start model server
  components/k8s-model-server/images/Dockerfile.cpu
  components/k8s-model-server/images/Dockerfile.gpu
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#407 Replace two envoy containers with a single one
  kubeflow/core/iap.libsonnet
Labels: approved, lgtm, size/L

#406 JWT validation works with GCP IAP - remove outdated docs
  docs/gke/iap.md
Labels: approved, lgtm, size/M

#409 Use kubeflow-images-staging to store envoy image instead of kubeflow-dev
  kubeflow/core/prototypes/iap-envoy.jsonnet
Labels: approved, lgtm, size/XS

#402 Add HTML5 dropdown for image selector with cpu,gpu defaults
  kubeflow/core/jupyterhub_spawner.py
  testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet
  user_guide.md
Labels: approved, lgtm, size/S

#408 Replace ClusterRole/ClusterRoleBinding for ambassador with Role/RoleBinding
  kubeflow/core/ambassador.libsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#399 Fix 2 issues with s3 config from #387.
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#413 Create a seldon-serve ksonnet prototype
  kubeflow/seldon/prototypes/serve-simple.jsonnet
  kubeflow/seldon/serve-simple.libsonnet
Labels: approved, lgtm, size/M

#416 GCP credential support for TF serving
  components/k8s-model-server/README.md
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/M

#420 Fix the import name for seldon/serve-simple.libsonnet
  kubeflow/seldon/prototypes/serve-simple.jsonnet
Labels: approved, lgtm, size/XS

#411 Use kubeflow-ci as the test cluster
  components/k8s-model-server/images/releaser/components/params.libsonnet
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#434 Run ks upgrade
  components/k8s-model-server/images/releaser/app.yaml
  components/k8s-model-server/images/releaser/environments/prow/spec.json
  components/k8s-model-server/images/releaser/environments/releasing/spec.json
  components/k8s-model-server/images/releaser/environments/testing/spec.json
  components/k8s-model-server/images/releaser/lib/v1.7.0/k.libsonnet
  components/k8s-model-server/images/releaser/lib/v1.7.0/k8s.libsonnet
  components/k8s-model-server/images/releaser/lib/v1.7.0/swagger.json
  components/tensorflow-notebook-image/releaser/app.yaml
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/spec.json
  components/tensorflow-notebook-image/releaser/environments/releasing/spec.json
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/k.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/swagger.json
  releasing/releaser/app.yaml
  releasing/releaser/environments/prow/spec.json
  releasing/releaser/environments/releasing/spec.json
  releasing/releaser/lib/v1.7.0/k.libsonnet
  releasing/releaser/lib/v1.7.0/k8s.libsonnet
  releasing/releaser/lib/v1.7.0/swagger.json
  testing/workflows/app.yaml
  testing/workflows/environments/prow/spec.json
  testing/workflows/lib/v1.7.0/k.libsonnet
  testing/workflows/lib/v1.7.0/k8s.libsonnet
  testing/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#363 update http proxy readme
  components/k8s-model-server/http-proxy/README.md
Labels: approved, lgtm, size/M

#431 Libsonnet cleanup
  kubeflow/core/all.libsonnet
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/nfs.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/tests/util_test.jsonnet
  kubeflow/core/tf-job.libsonnet
  kubeflow/core/util.libsonnet
Labels: approved, lgtm, size/L

#440 Use kubeflow-ci/test-worker as worker image
  testing/workflows/components/workflows.libsonnet
  testing/workflows/debug_pod.yaml
Labels: approved, lgtm, size/S

#439 Update autoformat script to only format files in kubeflow/ directory
  kubeflow/core/all.libsonnet
  kubeflow/core/tests/util_test.jsonnet
  kubeflow/core/util.libsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  scripts/autoformat_jsonnet.sh
Labels: approved, lgtm, size/M

#443 Run jsonnet tests as part of kubeflow-e2e workflow
  testing/test_jsonnet.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#441 Use cert-manager for obtaining valid certificates
  docs/gke/iap.md
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
Labels: approved, lgtm, size/L

#444 set termination policy to worker 0 by default when no master exists
  kubeflow/tf-job/prototypes/tf-job.jsonnet
  kubeflow/tf-job/tf-job.libsonnet
Labels: approved, lgtm, size/S

#415 Replace azure env by aks || acs-engine
  README.md
  kubeflow/core/tf-job.libsonnet
  user_guide.md
Labels: approved, size/M

#445 Add jsonnet unit tests for iap
  kubeflow/core/tests/iap_test.jsonnet
Labels: approved, lgtm, size/L

#358 Add tensorflow-serving-api to jupyter image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#393 Troubleshooting section updates
  user_guide.md
Labels: approved, lgtm, size/S

#456 Add jsonnet_path_dirs flag to test_jsonnet script
  testing/test_jsonnet.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#450 Fix for #432 Provide basic tests for every ksonnet prototype. It will…
  kubeflow/core/tests/ambassador_test.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  kubeflow/core/tests/nfs_test.jsonnet
  kubeflow/core/tests/spartakus_test.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
Labels: approved, lgtm, size/XL

#446 remove the pip install tensorboard
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#426 Inherit namespace from ksonnet environment
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/iap-envoy.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/tf-job.libsonnet
  kubeflow/seldon/prototypes/core.jsonnet
  kubeflow/seldon/prototypes/serve-simple.jsonnet
  kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
  kubeflow/tf-job/prototypes/tf-job.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  kubeflow/tf-serving/tf-serving.libsonnet
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#463 Update docs so that namespace is only set at ks env level
  README.md
  components/k8s-model-server/README.md
  docs/gke/iap.md
  user_guide.md
Labels: approved, lgtm, size/M

#466 Update cert-manager component to inherit namespace
  kubeflow/core/prototypes/cert-manager.jsonnet
Labels: approved, lgtm, size/S

#471 Update tensorflow-notebook-image workflow to pin tf and cuda version
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  releasing.md
Labels: approved, lgtm, size/M

#396 Fix k8s dashboard on Azure
  kubeflow/core/ambassador.libsonnet
Labels: approved, lgtm, size/S

#476 Fix ambassador_test.jsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
Labels: approved, lgtm, size/XS

#457 Move IAP config to initContainer on the envoy pod
  docs/gke/enable_iap.sh
  docs/gke/iap.md
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/iap-envoy.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
Labels: approved, lgtm, size/L

#461 Fix the TFCnn prototype which was broken by #444.
  kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
Labels: approved, lgtm, size/XS

#475 Tag tensorflow-notebook-images with latest
  components/tensorflow-notebook-image/build_image.sh
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#474 Set a large timeout for jupyterhub spawner
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/S

#442 E2e test for TF serving with GPU
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/images/test-worker/result-gpu.txt
  testing/test_deploy.py
  testing/test_tf_serving.py
Labels: approved, lgtm, size/L

#480 Update jsonnet tests so that it tests all files under kubeflow
  testing/test_jsonnet.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#459 Create a script to deploy minikube on a VM.
  testing/install_minikube.sh
  testing/test_deploy.py
  testing/test_deploy_test.py
  testing/vm_util.py
Labels: approved, lgtm, size/L

#485 Enhance tf serving gpu test
  testing/test_deploy.py
  testing/test_tf_serving.py
Labels: approved, lgtm, size/XS

#487 Temporarily disable gpu test since it's flaky
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#492 Add google-cloud-storage package to jupyterhub notebook
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#488 Update buildTemplateImage to take workflow_name
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#486 Use a 10 minute timeout for jupyterhub backend in envoy config
  kubeflow/core/iap.libsonnet
Labels: approved, lgtm, size/M

#494 Fix instructions for tensorflow-notebook release
  releasing.md
Labels: approved, lgtm, size/XS

#482 Add Github's rate exceeded error trobuleshooting
  user_guide.md
Labels: approved, lgtm, size/XS

#381 Fix tfjob dashboard ambassador route
  kubeflow/core/tf-job.libsonnet
Labels: approved, lgtm, size/XS

#508 Update images for our 0.1 release
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  releasing.md
  user_guide.md
Labels: approved, lgtm, size/M

#509 Fix TF serving release process
  releasing.md
  releasing/releaser/components/workflows.libsonnet
  releasing/releaser/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/S

#512 Pin tf serving version to 1.4
  components/k8s-model-server/images/Dockerfile.cpu
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#515 Use ks version 0.9.2
  README.md
  components/tensorflow-notebook-image/Dockerfile
  user_guide.md
Labels: approved, lgtm, size/S

#498 Update the nodejs and ipywidgets dependencies.
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#516 Update tensorflow notebook release to v20180327-6bb4058
  kubeflow/core/jupyterhub_spawner.py
Labels: approved, lgtm, size/S

#510 update default image for TF serving
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/XS

#513 Update ambassador and statsd to 0.30.1 as part of 0.1 release
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
Labels: approved, lgtm, size/S

#517 Http proxy default image
  components/k8s-model-server/README.md
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#493 Update release instructions to ease onboarding
  releasing.md
Labels: approved, lgtm, size/M

#503 Mount pvc
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/M

#518 Install jupyter widgets in tensorflow-notebook-image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#520 Clarify authentication requirements in release process
  releasing.md
Labels: approved, lgtm, size/XS

#497 Enable tf serving gpu test
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#525 Adds Centraldashboard (in place of #146)
  components/centraldashboard/config/Dockerfile
  components/centraldashboard/frontend/dashboard.go
  components/centraldashboard/frontend/index/index.html
  components/centraldashboard/frontend/index/styles.css
  kubeflow/core/all.libsonnet
  kubeflow/core/centraldashboard.libsonnet
Labels: approved, lgtm, size/L

#526 Fix typos in tensorflow notebook images in spawner
  kubeflow/core/jupyterhub_spawner.py
Labels: approved, lgtm, size/S

#533 Update the TFJob image in preparation for a new RC.
  kubeflow/core/prototypes/all.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#540 Cherrypick #526 and #533 into v0.1-branch
  kubeflow/core/jupyterhub_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#547 disable gpu test
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#551 Delete Makefile for tensorflow-notebook-image
  components/tensorflow-notebook-image/Makefile
Labels: approved, lgtm, size/M

#548 Add TfJob dashboard to ksonnet
  kubeflow/core/tf-job.libsonnet
Labels: approved, lgtm, size/XS
