Repository kubeflow/kubeflow, pull requests merged in 2018-06, with the labels that each got.

#900 Make bootstrapper support multi ks registry, including private ones
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/build.py
  bootstrap/build_image.sh
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  testing/e2e_env.yaml
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#895 Restrict jupyterHubRole
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/M

#888 Update to Ambassador 0.34.0
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
Labels: approved, lgtm, size/XS

#898 Create wait_for_deployment.py
  testing/deploy_utils.py
  testing/wait_for_deployment.py
Labels: approved, lgtm, size/L

#908 Update default parameters for image-releaser workflows
  components/image-releaser/components/tf-notebook-workflow.libsonnet
  components/image-releaser/components/tf-serving-workflow.libsonnet
Labels: approved, lgtm, size/S

#905 Upgrade jupyterhub and kube_spawner
  components/jupyterhub/docker/Dockerfile
  components/jupyterhub/docker/Makefile
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/M

#899 Checkin the deployment manager config for running e2e-gke test
  testing/dm_configs/cluster-kubeflow.yaml
  testing/dm_configs/cluster.jinja
Labels: approved, lgtm, size/L

#911 Doc on adding new ksonnet package
  docs_dev/ksonnet_packages.md
Labels: approved, lgtm, size/S

#904 Improvements and bug fixes in DM config.
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/configs/env-kubeflow.sh
  docs/gke/create_k8s_secrets.sh
  docs/gke/gke_setup.md
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/cloud-endpoints.jsonnet
Labels: approved, lgtm, size/L

#913 copy registry into bootstrap image during e2e test
  bootstrap/build.py
  bootstrap/build_image.sh
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  testing/e2e_env.yaml
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#915 Ambassador to jupyterhub
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/M

#874 tfjob(v1alpha2): Add validation
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, lgtm, size/M

#873 Katib ksonnet package
  kubeflow/katib/modeldb.libsonnet
  kubeflow/katib/parts.yaml
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/suggestion.libsonnet
  kubeflow/katib/vizier.libsonnet
  kubeflow/registry.yaml
Labels: approved, lgtm, size/XL

#917 Activate service account before pushing images
  components/build_image.py
Labels: approved, lgtm, size/XS

#894 Use Deployment Manager to bring up clusters for running E2E tests
  prow_config.yaml
  testing/deploy_kubeflow_gcp.py
  testing/dm_configs/cluster-kubeflow.yaml
  testing/dm_configs/cluster.jinja
  testing/workflows/components/gke_deploy.jsonnet
  testing/workflows/components/gke_deploy.libsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#897 Click to deploy Kubeflow web app on GCP
  components/gcp-click-to-deploy/.gitignore
  components/gcp-click-to-deploy/README.md
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/public/favicon.ico
  components/gcp-click-to-deploy/public/index.html
  components/gcp-click-to-deploy/public/manifest.json
  components/gcp-click-to-deploy/src/App.css
  components/gcp-click-to-deploy/src/App.js
  components/gcp-click-to-deploy/src/App.test.js
  components/gcp-click-to-deploy/src/configs/cluster-kubeflow.yaml
  components/gcp-click-to-deploy/src/configs/cluster.jinja
  components/gcp-click-to-deploy/src/configs/cluster.jinja.schema
  components/gcp-click-to-deploy/src/index.css
  components/gcp-click-to-deploy/src/index.js
  components/gcp-click-to-deploy/src/kubeflow-logo.jpg
  components/gcp-click-to-deploy/src/registerServiceWorker.js
Labels: approved, lgtm, size/XXL

#907 Install py2 to global conda env
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#922 Update image-releaser README
  components/README.md
  components/image-releaser/components/util.libsonnet
Labels: approved, lgtm, size/M

#930 fix minor typos
  docs_dev/images.md
Labels: approved, lgtm, size/XS

#926 Delete test directory after test completes
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#928 DM config should allow setting users/groups to grant IAP access to.
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/gke_setup.md
Labels: approved, lgtm, size/M

#921 keep bootstrapper pod alive when error occurs
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/bootstrap/main.go
Labels: approved, lgtm, size/M

#914 support jupyterhub in alibaba cloud
  ack_guide.md
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/tests/ambassador_test.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  user_guide.md
Labels: approved, lgtm, size/L

#937 Set 15 minute timeout for workflow step
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#936 Remove service account creation in testing deployment manager
  testing/dm_configs/cluster.jinja
Labels: approved, lgtm, size/M

#931 fix vm service account config, doc update
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/env-kubeflow.sh
  docs/gke/gke_setup.md
Labels: approved, lgtm, size/S

#924 Prevent deadlocks trying to setup IAP.
  docs/gke/configs/cluster.jinja
  docs/gke/create_k8s_secrets.sh
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/iap.libsonnet
  kubeflow/core/setup_iap.sh
Labels: approved, lgtm, size/L

#944 Update instructions for recreating minkube with required resources.
  user_guide.md
Labels: approved, lgtm, size/XS

#946 Downgrade ambassador version to 0.30.1
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/XS

#947 Update the notebook images used with Jupyter.
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/S

#918 Run v1alpha1 and v1alpha2 TfJob tests in GKE workflow
  testing/deploy_kubeflow_gcp.py
  testing/dm_configs/cluster-kubeflow.yaml
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#948 ksonnet prototype for automated image release
  docs_dev/releasing.md
  kubeflow/automation/parts.yaml
  kubeflow/automation/prototypes/release.jsonnet
  kubeflow/automation/release.libsonnet
  kubeflow/registry.yaml
Labels: approved, lgtm, size/L

#956 A bunch of fixes to the DM configs for GCP to work with latest bootstrapper
  bootstrap/.gitignore
  bootstrap/Makefile
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/create_k8s_secrets.sh
  docs/gke/gke_setup.md
  docs_dev/releasing.md
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/setup_iap.sh
Labels: approved, lgtm, size/L

#952 Add aws cloud details
  user_guide.md
Labels: approved, lgtm, size/XS

#951 hide registries config in bootstrapper image to save user effort
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/build.py
  bootstrap/build_image.sh
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  bootstrap/image_registries.yaml
  testing/dm_configs/cluster-kubeflow.yaml
  testing/e2e_env.yaml
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#975 Disable the v1alpha2 test because it is failing because mnist data can't be downloaded.
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#963 Remove gke_setup.md. The instructions are now part of the website.
  docs/gke/gke_setup.md
Labels: approved, lgtm, size/L

#965 Source admin role should be granted to KF service accounts.
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/XS

#967 Delete tf-cnn-benchmarks.jsonnet; there is now an example prototype.
  kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
  user_guide.md
Labels: approved, lgtm, size/L

#976 use ks apply in bootstrapper to avoid creation ordering issue
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/gcp_prototype.yaml
Labels: approved, lgtm, size/S

#984 Remove gpu_model.jsonnet
  components/k8s-model-server/images/releaser/components/gpu_model.jsonnet
  components/k8s-model-server/images/releaser/components/params.libsonnet
Labels: approved, lgtm, size/M

#987 Retry on ssl.SSLError in vm_util - this resolves test flakiness
  testing/vm_util.py
Labels: approved, lgtm, size/S

#985 Consolidate GKE deployment script
  docs/gke/configs/deploy.sh
  docs/gke/configs/env-kubeflow.sh
  docs/gke/create_k8s_secrets.sh
Labels: approved, lgtm, size/L

#982 config update
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/S

#989 Doc for katib
  kubeflow/katib/README.md
Labels: approved, lgtm, size/M

#979 Fix vizier core
  kubeflow/katib/vizier.libsonnet
Labels: approved, lgtm, size/XS

#993 Enable iam api and set project flag explicitly
  docs/gke/configs/deploy.sh
Labels: approved, lgtm, size/XS

#972 Adding pytorch-operator to nightly builds
  releasing/prow_config_release.yaml
  releasing/pytorch-operator/.gitignore
  releasing/pytorch-operator/app.yaml
  releasing/pytorch-operator/components/params.libsonnet
  releasing/pytorch-operator/components/pytorch-operator.jsonnet
  releasing/pytorch-operator/environments/base.libsonnet
  releasing/pytorch-operator/environments/default/globals.libsonnet
  releasing/pytorch-operator/environments/default/main.jsonnet
  releasing/pytorch-operator/environments/default/params.libsonnet
Labels: approved, lgtm, size/L

#1008 update ks version; run ks apply following config order
  bootstrap/Dockerfile
  bootstrap/cmd/bootstrap/app/server.go
Labels: approved, lgtm, size/M

#940 update default image for TF serving
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/XS

#1001 fix iam role delete for deployment manager
  docs/gke/configs/cluster.jinja
Labels: approved, lgtm, size/M

#1011 Add tf serving 1.8 cpu image
  components/README.md
  components/k8s-model-server/images/versions/1.8/version-config.json
Labels: approved, lgtm, size/XS

#1010 Add test for tf-job-simple prototype
  testing/tf_job_simple_test.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#992 bootstrapper doc update
  bootstrap/README.md
  bootstrap/bootstrapper.yaml
Labels: approved, lgtm, size/M

#929 Add AVX to Troubleshooting
  user_guide.md
Labels: approved, lgtm, size/XS

#1012 Set default version of TFJob operator to be v1alpha2
  ack_guide.md
  bootstrap/bootstrapper.yaml
  docs/gke/configs/cluster-kubeflow.yaml
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  testing/deploy_kubeflow.py
Labels: approved, lgtm, size/S

#1013 Fix hard coded "name" variable in example prototypes
  kubeflow/examples/prototypes/tf-job-simple.jsonnet
  kubeflow/examples/prototypes/tf-serving-simple.jsonnet
  kubeflow/examples/prototypes/tf-serving-with-istio.jsonnet
Labels: approved, lgtm, size/XS

#1016 Add a link to JupyterHub in the CentralUI
  components/centraldashboard/frontend/index/index.html
Labels: approved, lgtm, size/XS

#978 Fix permissions for jupyter-role
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/XS

#1015 Include the TF 1.8 image in kubeform_spawner.
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/XS

#995 Fix user guide for the refactored tf-cnn example
  user_guide.md
Labels: approved, lgtm, size/XS

#1021 update bootstrapper image to use tfJobsVersion v1alpha2 as default
  bootstrap/bootstrapper.yaml
  docs/gke/configs/cluster-kubeflow.yaml
Labels: approved, lgtm, size/XS

#1019 Pin the central UI image.
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/tests/centraldashboard_test.jsonnet
Labels: approved, lgtm, size/S

#1023 Fix param name of ambassador
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/S

#1025 Merge master commits to release 0.2 branch
  bootstrap/bootstrapper.yaml
  docs/gke/configs/cluster-kubeflow.yaml
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/tests/centraldashboard_test.jsonnet
Labels: size/M

#1026 fix format error for nightly release config
  releasing/prow_config_release.yaml
Labels: approved, lgtm, size/XS

#1030 Update TF serving 1.7 gpu image to use cuda 9.0
  components/k8s-model-server/images/versions/1.7gpu/version-config.json
Labels: approved, lgtm, size/XS

#1002 Use docs/gke/configs to run e2e tests
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/configs/deploy.sh
  testing/deploy_kubeflow_gcp.py
  testing/deploy_kubeflow_gcp.sh
  testing/dm_configs/cluster-kubeflow.yaml
  testing/dm_configs/cluster.jinja
  testing/run_with_retry.py
  testing/teardown_kubeflow_gcp.py
  testing/teardown_kubeflow_gcp.sh
  testing/update_dm_config.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1034 update pytorch image
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Labels: approved, lgtm, size/XS

#1040 Changing defaults in Pytorch-job
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
Labels: approved, lgtm, size/XS

#1037 [gcp-deployer] Move to Typescript, clear dead code
  components/gcp-click-to-deploy/.gitignore
  components/gcp-click-to-deploy/module_types.d.ts
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/public/index.html
  components/gcp-click-to-deploy/src/App.css
  components/gcp-click-to-deploy/src/App.js
  components/gcp-click-to-deploy/src/App.test.js
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/NameForm.tsx
  components/gcp-click-to-deploy/src/index.js
  components/gcp-click-to-deploy/src/index.tsx
  components/gcp-click-to-deploy/src/logo.jpg
  components/gcp-click-to-deploy/src/registerServiceWorker.js
  components/gcp-click-to-deploy/tsconfig.json
  components/gcp-click-to-deploy/tsconfig.prod.json
  components/gcp-click-to-deploy/tsconfig.test.json
  components/gcp-click-to-deploy/tslint.json
Labels: approved, lgtm, size/XXL

#1038 Delete user_guide.md; it is now part of the website
  user_guide.md
Labels: approved, lgtm, size/XL

#1052 Update default notebook image for spawner
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/XS

#1058 Fix typo in NB image sha
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/XS

#1061 Some scripts to support retagging our images as part of our releases.
  releasing/apply_image_tags.py
  releasing/image_tags.yaml
Labels: approved, lgtm, size/M

#1043 add mpi operator ksonnet package
  kubeflow/mpi-job/mpi-operator.libsonnet
  kubeflow/mpi-job/parts.yaml
  kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet
  kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet
  kubeflow/mpi-job/prototypes/mpi-operator.jsonnet
  kubeflow/registry.yaml
Labels: approved, lgtm, size/L

#1065 cherry pick: update tf_operator image to point to tag v0.2.0 (#1062)
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/tf-job-operator.jsonnet
Labels: approved, lgtm, size/XS

#1066 Tooling to make it easier to tag images and update the ksonnet prototypes
  docs_dev/releasing.md
  kubeflow/core/kubeform_spawner.py
  releasing/add_image_shas.py
  releasing/add_image_tag.py
  releasing/apply_image_tags.py
  releasing/image_tags.yaml
  releasing/update_image_tags.sh
  releasing/update_ksonnet.sh
Labels: approved, lgtm, size/XL

#1079 add a readme file to the mpi-job ksonnet component
  kubeflow/mpi-job/README.md
Labels: approved, lgtm, size/L

#1077 fix #1075, user_guide link is dead
  README.md
  bootstrap/README.md
  components/jupyterhub/README.md
  components/k8s-model-server/README.md
  kubeflow/README.md
  tf-controller-examples/tf-cnn/README.md
Labels: approved, lgtm, size/S

#1086 update tf job default version
  kubeflow/tf-job/tf-job.libsonnet
Labels: approved, lgtm, size/XS

#1087 cherry-pick: update tf job default version (#1086)
  kubeflow/tf-job/tf-job.libsonnet
Labels: approved, lgtm, size/XS

#1084 fix for file_cache is unavailable when using oauth2client >= 4.0.0
  testing/test_deploy.py
Labels: approved, lgtm, size/XS

#1073 TFJobs UI doesn't work behind IAP
  bootstrap/image_registries.yaml
  kubeflow/core/iap.libsonnet
Labels: approved, lgtm, size/M

#1085 Add katib tag to images
  kubeflow/katib/modeldb.libsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/suggestion.libsonnet
  kubeflow/katib/vizier.libsonnet
Labels: approved, lgtm, size/XS

#1054 [gcp-deployer] Add Gapi manager class, more typings and fixes
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/public/index.html
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
  components/gcp-click-to-deploy/src/NameForm.tsx
  components/gcp-click-to-deploy/tslint.json
Labels: approved, lgtm, size/L

#1063 Create a script to update some of the docker images in the prototypes
  releasing/update_images.sh
Labels: approved, lgtm, size/S

#1094 Install gpu driver in deployment manager
  docs/gke/README.md
  docs/gke/configs/deploy.sh
Labels: approved, lgtm, size/XS

#1093 Improvements to deploy.sh
  docs/gke/configs/deploy.sh
Labels: approved, lgtm, size/M

#1095 add chainer-job/chainer-operator ksonnet package
  kubeflow/chainer-job/README.md
  kubeflow/chainer-job/chainer-operator.libsonnet
  kubeflow/chainer-job/parts.yaml
  kubeflow/chainer-job/prototypes/chainer-job-simple.jsonnet
  kubeflow/chainer-job/prototypes/chainer-job.jsonnet
  kubeflow/chainer-job/prototypes/chainer-operator.jsonnet
Labels: approved, lgtm, size/XL

#1103 Make Katib work with Ambassador.
  kubeflow/katib/modeldb.libsonnet
Labels: approved, lgtm, size/XS

#1098 add seldon to ks config; pre install all pkg
  bootstrap/cmd/bootstrap/app/server.go
  kubeflow/registry.yaml
Labels: approved, lgtm, size/M

#1105 [gcp-deployer] Fix hostname typo bug
  components/gcp-click-to-deploy/src/NameForm.tsx
Labels: approved, lgtm, size/XS

#1091 Delete the tf-job package.
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  docs/gke/configs/cluster-kubeflow.yaml
  kubeflow/examples/prototypes/tf-job-simple.jsonnet
  kubeflow/registry.yaml
  kubeflow/tf-job/README.md
  kubeflow/tf-job/parts.yaml
  kubeflow/tf-job/prototypes/tf-job.jsonnet
  kubeflow/tf-job/tf-job.libsonnet
  kubeflow/tf-job/util.libsonnet
Labels: approved, lgtm, size/L

#1097 Create a version of echo-server to echo headers.
  components/echo-server/Dockerfile
  components/echo-server/Makefile
  components/echo-server/main.py
  components/echo-server/main_test.py
  components/echo-server/requirements.txt
  kubeflow/core/echo-server.libsonnet
  kubeflow/core/prototypes/echo-server.jsonnet
Labels: approved, lgtm, size/L

#1104 cherry pick 3 commits
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  docs/gke/configs/cluster-kubeflow.yaml
  kubeflow/examples/prototypes/tf-job-simple.jsonnet
  kubeflow/registry.yaml
  kubeflow/tf-job/README.md
  kubeflow/tf-job/parts.yaml
  kubeflow/tf-job/prototypes/tf-job.jsonnet
  kubeflow/tf-job/tf-job.libsonnet
  kubeflow/tf-job/util.libsonnet
Labels: size/L

#1099 Tfjob create fails in tfjob UI
  bootstrap/image_registries.yaml
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, lgtm, size/S
