Repository kubeflow/kubeflow, pull requests merged in 2018-09, with the labels that each got.

#1466 Add GCS read only scope to GKE VM scopes
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1469 Update Kaggle Dockerfile to add their API package
  components/contrib/kaggle-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1468 Add storage read scope to VM scopes; v0.2-branch (#1466)
  scripts/gke/deployment_manager_configs/cluster.jinja
  testing/test_jsonnet.py
Labels: cla: yes, lgtm, size/XS

#1475 Fix bug with updating an existing deployment.
  scripts/gke/deploy.sh
Labels: approved, cla: yes, lgtm, size/XS

#1465 Adding namespace scope to pytorch operator
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1437 standardize remaining <component>.{jsonnet,libsonnet} files
  components/gcp-click-to-deploy/ks-app/create_gcp_deploy_sa.sh
  docs_dev/ksonnet_packages.md
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/cloud-endpoints.libsonnet
  kubeflow/core/echo-server.libsonnet
  kubeflow/core/google-cloud-filestore-pv.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prometheus.libsonnet
  kubeflow/core/prototypes/ambassador.jsonnet
  kubeflow/core/prototypes/centraldashboard.jsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/cloud-endpoints.jsonnet
  kubeflow/core/prototypes/echo-server.jsonnet
  kubeflow/core/prototypes/google-cloud-filestore-pv.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/core/prototypes/metric-collector.jsonnet
  kubeflow/core/prototypes/prometheus.jsonnet
  kubeflow/core/prototypes/spartakus.jsonnet
  kubeflow/core/spartakus.libsonnet
  kubeflow/core/tests/iap_test.jsonnet
  kubeflow/core/tests/util_test.jsonnet
  kubeflow/core/util.libsonnet
  kubeflow/new-package-stub/all.libsonnet
  kubeflow/new-package-stub/newpackage.libsonnet
  kubeflow/new-package-stub/prototypes/newpackage.jsonnet
  kubeflow/new-package-stub/prototypes/tf-prototype.jsonnet
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#1482 Delete deploy.sh scripts; we use kfctl.sh now.
  scripts/gke/deploy.sh
  scripts/gke/deploy_test.sh
Labels: approved, cla: yes, lgtm, size/L

#1470 Ensure jovyan has site-packages perms
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#1490 click to deploy: remove default project name
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1494 update gke to 1.10.7-gke.1
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1485 Simplify tensorboard
  kubeflow/core/prototypes/tensorboard.jsonnet
  kubeflow/core/tensorboard.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1487 fixes add ability to only generate parts of a component in the jsonnet file
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/cloud-endpoints.libsonnet
  kubeflow/core/echo-server.libsonnet
  kubeflow/core/google-cloud-filestore-pv.libsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prometheus.libsonnet
  kubeflow/core/prototypes/ambassador.jsonnet
  kubeflow/core/prototypes/centraldashboard.jsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/cloud-endpoints.jsonnet
  kubeflow/core/prototypes/echo-server.jsonnet
  kubeflow/core/prototypes/google-cloud-filestore-pv.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/core/prototypes/metric-collector.jsonnet
  kubeflow/core/prototypes/prometheus.jsonnet
  kubeflow/core/prototypes/spartakus.jsonnet
  kubeflow/core/spartakus.libsonnet
  kubeflow/new-package-stub/newpackage.libsonnet
  kubeflow/new-package-stub/prototypes/newpackage.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1498 fixes kfctl.sh unable to find component ambassador
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/L

#1499 Change webapp url
  components/gcp-click-to-deploy/manifest/ingress.yaml
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/S

#1502 separate dep and src for bootstrapper
  bootstrap/Dockerfile.Builder
Labels: approved, cla: yes, lgtm, size/XS

#1497 Update jupyterhub-kubespawner version
  components/jupyterhub/docker/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1505 Add myself as one of the approvers.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1504 Update webapp backend to respond and then finish deployment in the background
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/L

#1501 fixes update tensorboard to use the same pattern as kubeflow/core/prototypes
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#1425 Fix kfctl.sh gcpInitProject is always skipped
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/XS

#1511 Adding v1alpha2 as the default PyTorch operator version
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1512 Remove unused Azure specific config
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
  kubeflow/mxnet-job/mxnet-operator.libsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1508 update ks version to 0.12 for webapp backend
  bootstrap/Dockerfile
  bootstrap/glide.lock
  bootstrap/glide.yaml
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/L

#1515 Integrate with cloud source repos to save ks app config.
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/L

#1516 edit gke version to 1.10.6
  components/gcp-click-to-deploy/src/configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1517 update k8s version for k.libsonnet when do ks init; remove spartakus
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1521 update manifest for webapp
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1523 NVIDIA TensorRT Inference Server
  kubeflow/nvidia-inference-server/README.md
  kubeflow/nvidia-inference-server/nvidia-inference-server.libsonnet
  kubeflow/nvidia-inference-server/parts.yaml
  kubeflow/nvidia-inference-server/prototypes/inference-server-all-features.jsonnet
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/L

#1526 Replace logFatal with logError
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#1529 add chainer-job package to registry.yaml
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1527 Adds centralui to releaser.
  components/centraldashboard/build_image.sh
  releasing/centraldashboard/.gitignore
  releasing/centraldashboard/app.yaml
  releasing/centraldashboard/components/centraldashboard.jsonnet
  releasing/centraldashboard/components/params.libsonnet
  releasing/centraldashboard/environments/base.libsonnet
  releasing/centraldashboard/environments/default/globals.libsonnet
  releasing/centraldashboard/environments/default/main.jsonnet
  releasing/centraldashboard/environments/default/params.libsonnet
  releasing/centraldashboard/vendor/kubeflow/automation@54dc98525d5da7beab15cc8ed1d9ae9ffa07811f/parts.yaml
  releasing/centraldashboard/vendor/kubeflow/automation@54dc98525d5da7beab15cc8ed1d9ae9ffa07811f/prototypes/release.jsonnet
  releasing/centraldashboard/vendor/kubeflow/automation@54dc98525d5da7beab15cc8ed1d9ae9ffa07811f/release.libsonnet
  releasing/prow_config_release.yaml
Labels: approved, cla: yes, lgtm, size/L

#1533 Update the client ID for webapp
  bootstrap/.dockerignore
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  components/gcp-click-to-deploy/src/Gapi.ts
Labels: approved, cla: yes, lgtm, size/XS

#1536 edit server address for app config on each request
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#1528 Support specifying registy version in create request
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/server.go
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/L

#1532 Fix kfctl.sh remove the ksonnet environment for the deleted cluster
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/S

#1539 Restore missing tf-hub-lb service
  kubeflow/core/jupyterhub.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1545 The minikube test should not be running the jsonnet unittests.
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#1549 add chainer-operator to releaser
  releasing/chainer-operator/.gitignore
  releasing/chainer-operator/app.yaml
  releasing/chainer-operator/components/chainer-operator.jsonnet
  releasing/chainer-operator/components/params.libsonnet
  releasing/chainer-operator/environments/base.libsonnet
  releasing/chainer-operator/environments/default/globals.libsonnet
  releasing/chainer-operator/environments/default/main.jsonnet
  releasing/chainer-operator/environments/default/params.libsonnet
  releasing/prow_config_release.yaml
Labels: approved, cla: yes, lgtm, size/L

#1547 Add version config for TF 1.9,1.10
  components/tensorflow-notebook-image/versions/1.10.1/version-config.json
  components/tensorflow-notebook-image/versions/1.10.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.9.0/version-config.json
  components/tensorflow-notebook-image/versions/1.9.0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#1553 enable sourcerepo.googleapis.com api if needed
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1555 fix cert-manager: add clusterrole back
  kubeflow/core/cert-manager.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1550 Webapp: Don't use DM for IAM.
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/src/configs/cluster.jinja
  components/gcp-click-to-deploy/src/configs/iam_bindings_template.yaml
Labels: approved, cla: yes, lgtm, size/L

#1558 increase pageSize for service list to avoid truncate
  components/gcp-click-to-deploy/src/Gapi.ts
Labels: approved, cla: yes, lgtm, size/XS

#1561 Bug fix for #1559
  bootstrap/cmd/bootstrap/app/gcpUtils.go
Labels: approved, cla: yes, lgtm, size/XS

#1556 Fix for issue 1050 - camelCase for some recently fixed params.
  kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/weaveflux/README.md
  kubeflow/weaveflux/all.libsonnet
  kubeflow/weaveflux/prototypes/weaveflux.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1571 Bump GKE version because 1.10.7-gke.1 is no longer valid master version.
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1568 Fix cert-manager
  kubeflow/core/cert-manager.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1537 Prevent ambassador getaddrinfo error logs
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/prototypes/ambassador.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/S

#1580 remove prune from kubeflow core which delete required fields
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/util.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1565 Run Jupyter image and centraldashboard image release on postsubmit
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.9.7/k.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.9.7/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.9.7/swagger.json
  docs_dev/releasing.md
  kubeflow/automation/release.libsonnet
  prow_config.yaml
  releasing/centraldashboard/.gitignore
  releasing/centraldashboard/app.yaml
  releasing/centraldashboard/components/params.libsonnet
  releasing/centraldashboard/environments/base.libsonnet
  releasing/centraldashboard/environments/default/globals.libsonnet
  releasing/centraldashboard/environments/default/main.jsonnet
  releasing/centraldashboard/environments/default/params.libsonnet
  releasing/chainer-operator/.gitignore
  releasing/chainer-operator/app.yaml
  releasing/chainer-operator/components/params.libsonnet
  releasing/chainer-operator/environments/base.libsonnet
  releasing/chainer-operator/environments/default/globals.libsonnet
  releasing/chainer-operator/environments/default/main.jsonnet
  releasing/chainer-operator/environments/default/params.libsonnet
  releasing/cron_job_release.yaml
  releasing/prow_config_release.yaml
  releasing/pytorch-operator/app.yaml
  releasing/pytorch-operator/components/params.libsonnet
  releasing/pytorch-operator/environments/base.libsonnet
  releasing/pytorch-operator/environments/default/globals.libsonnet
  releasing/pytorch-operator/environments/default/main.jsonnet
  releasing/pytorch-operator/environments/default/params.libsonnet
  releasing/pytorch-operator/vendor/kubeflow/automation/parts.yaml
  releasing/pytorch-operator/vendor/kubeflow/automation/prototypes/release.jsonnet
  releasing/pytorch-operator/vendor/kubeflow/automation/release.libsonnet
  releasing/releaser/app.yaml
  releasing/releaser/components/centraldashboard.jsonnet
  releasing/releaser/components/chainer-operator.jsonnet
  releasing/releaser/components/params.libsonnet
  releasing/releaser/components/pytorch-operator.jsonnet
  releasing/releaser/lib/ksonnet-lib/v1.9.7/k.libsonnet
  releasing/releaser/lib/ksonnet-lib/v1.9.7/k8s.libsonnet
  releasing/releaser/lib/ksonnet-lib/v1.9.7/swagger.json
  releasing/releaser/lib/v1.9.7/k.libsonnet
  releasing/releaser/lib/v1.9.7/k8s.libsonnet
  releasing/releaser/lib/v1.9.7/swagger.json
  releasing/releaser/vendor/kubeflow/automation/parts.yaml
  releasing/releaser/vendor/kubeflow/automation/prototypes/release.jsonnet
  releasing/releaser/vendor/kubeflow/automation/release.libsonnet
  scripts/autoformat_jsonnet.sh
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#1581 App frontend stop polling the status after it's done
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#1582 fix iam patch logic and update image in config
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1592 Update Seldon to 0.2.3 version
  kubeflow/seldon/core.libsonnet
  kubeflow/seldon/json/template_0.2.json
  kubeflow/seldon/prototypes/core.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1593 Update instructions about releasing images using prow.
  docs_dev/releasing.md
  releasing/cron_job_release.yaml
  releasing/prow_config_release.yaml
Labels: approved, cla: yes, lgtm, size/L

#1535 fixes 'refactor tf-job-operator to match style-guide of libsonnet'
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#1609 Update title & favicon for the deploy app page.
  components/gcp-click-to-deploy/public/favicon.ico
  components/gcp-click-to-deploy/public/index.html
Labels: approved, cla: yes, lgtm, size/XS

#1611 fixes 'tensorboard prototypes should include the optionalParams available in that prototype'
  kubeflow/tensorboard/parts.yaml
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1613 Update Seldon to 0.2.3 version on 0.3 branch (#1592)
  kubeflow/seldon/core.libsonnet
  kubeflow/seldon/json/template_0.2.json
  kubeflow/seldon/prototypes/core.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1569 Typo in nvidia inference server README
  kubeflow/nvidia-inference-server/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1614 Update pytorch image on 0.3 release branch
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1619 Tag and update pytorch operator
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1605 Update Katib images on 0.3 branch
  docs_dev/releasing.md
  kubeflow/katib/prototypes/all.jsonnet
  releasing/add_katib_image_shas.sh
  releasing/katib/.gitignore
  releasing/katib/add-katib-releaser.sh
  releasing/katib/app.yaml
  releasing/katib/components/earlystopping-medianstopping.jsonnet
  releasing/katib/components/katib-frontend.jsonnet
  releasing/katib/components/params.libsonnet
  releasing/katib/components/suggestion-bayesianoptimization.jsonnet
  releasing/katib/components/suggestion-grid.jsonnet
  releasing/katib/components/suggestion-hyperband.jsonnet
  releasing/katib/components/suggestion-random.jsonnet
  releasing/katib/components/vizier-core.jsonnet
  releasing/katib/environments/base.libsonnet
  releasing/katib/environments/default/globals.libsonnet
  releasing/katib/environments/default/main.jsonnet
  releasing/katib/environments/default/params.libsonnet
  releasing/update_katib_ksonnet.sh
Labels: approved, cla: yes, lgtm, size/L

#1608 Update the TFJob image to the latest image and tag 0.3
  docs_dev/releasing.md
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/M

#1595 Force update IAM policy; print app url on web UI.
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#1622 Add richardsliu to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1597 Update release process for Katib.
  docs_dev/releasing.md
  kubeflow/katib/prototypes/all.jsonnet
  releasing/add_katib_image_shas.sh
  releasing/katib/.gitignore
  releasing/katib/add-katib-releaser.sh
  releasing/katib/app.yaml
  releasing/katib/components/earlystopping-medianstopping.jsonnet
  releasing/katib/components/katib-frontend.jsonnet
  releasing/katib/components/params.libsonnet
  releasing/katib/components/suggestion-bayesianoptimization.jsonnet
  releasing/katib/components/suggestion-grid.jsonnet
  releasing/katib/components/suggestion-hyperband.jsonnet
  releasing/katib/components/suggestion-random.jsonnet
  releasing/katib/components/vizier-core.jsonnet
  releasing/katib/environments/base.libsonnet
  releasing/katib/environments/default/globals.libsonnet
  releasing/katib/environments/default/main.jsonnet
  releasing/katib/environments/default/params.libsonnet
  releasing/update_katib_ksonnet.sh
Labels: approved, cla: yes, lgtm, size/L

#1621 make builder image version consistent with glide.lock hash
  bootstrap/Dockerfile
  bootstrap/Dockerfile.Builder
  bootstrap/Makefile
Labels: approved, cla: yes, lgtm, size/S

#1625 Update katib image URIs
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1624 Add postsubmits to push centralui and Jupyter notebook images to kubeflow-images-public
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1628 Use JupyterNotebook as default instead of JupyterLab
  kubeflow/core/prototypes/jupyterhub.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1627 Tag and update 0.3.0 release for Kubebench controller
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1629 Install tensorflow-data-validation in jupyter notebook
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1632 Update katib component to include studyjobcontroller
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1636 Cherrypick changes from 0.3-branch to master
  components/tensorflow-notebook-image/Dockerfile
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1552 Tag and update v0.3.0 release for chainer-operator
  kubeflow/chainer-job/prototypes/chainer-operator.jsonnet
  releasing/image_tags.yaml
  releasing/releaser/components/chainer-operator.jsonnet
  releasing/releaser/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1637 Tag release 0.3.0 for Jupyter notebook images
  kubeflow/core/kubeform_spawner.py
  releasing/image_tags.yaml
  releasing/update_image_tags.sh
  releasing/update_ksonnet.sh
Labels: approved, cla: yes, lgtm, size/L

#1589 New TF Serving template
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  kubeflow/tf-serving/util.libsonnet
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, size/L

#1564 Adding --skipInitProject to kfctl_test.jsonnet until CI quota is increased
  scripts/kfctl.sh
  testing/workflows/components/kfctl_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1638 Add a simple e2e-test for katib
  scripts/kfctl.sh
  scripts/util.sh
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1646 [Cherry-pick] Add a simple e2e-test for katib
  scripts/kfctl.sh
  scripts/util.sh
  testing/test_deploy.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1647 TF Serving changes: enable http server, test cleanup etc
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  prow_config.yaml
  testing/test_tf_serving.py
  testing/workflows/components/params.libsonnet
  testing/workflows/components/tfserving.jsonnet
  testing/workflows/components/tfserving.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1623 Build image for centralui part of presubmit
  components/centraldashboard/build_image.sh
  kubeflow/automation/release.libsonnet
  prow_config.yaml
  releasing/releaser/components/params.libsonnet
  releasing/releaser/vendor/kubeflow/automation/release.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1649 Enable periodic prow tests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1657 Tag and update centraldashboard image
  kubeflow/core/prototypes/centraldashboard.jsonnet
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1656 Cherry-pick #1589 to v0.3
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
  kubeflow/tf-serving/util.libsonnet
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, size/L

#1660 Cherrypick (#1657) tag image and change libsonnet for centraldashboard image
  kubeflow/core/prototypes/centraldashboard.jsonnet
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1654 Cherrypick #1650; automatically set master version to supported version.
  scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml
  scripts/gke/deployment_manager_configs/cluster.jinja
  scripts/gke/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#1661 Change kubebench 0.3 image
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1664 Remove trailing slash from KUBEFLOW_REPO
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/XS

#1665 Add swiftdiaries as reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1667 remove prune from kubeflow core which delete required fields (#1580)
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/util.libsonnet
Labels: approved, cla: yes, lgtm, size/XS
