Repository kubeflow/kubeflow, pull requests merged in 2018-08, with the labels that each got.

#1301 Fixed broken links (to user_guide)
  bootstrap/README.md
  components/jupyterhub/README.md
  components/k8s-model-server/README.md
  kubeflow/README.md
  tf-controller-examples/tf-cnn/README.md
Labels: approved, lgtm, size/S

#1271 Improve tf serving e2e test
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/test-data/mnist_result.json
  testing/test_tf_serving.py
Labels: approved, lgtm, size/M

#1304 Add reasonable default to tf-serving s3 creds
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/XS

#1307 revert to k8s 1.9
  scripts/gke/deploy.sh
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/S

#1305 wording
  kubeflow/openmpi/README.md
Labels: approved, lgtm, size/XS

#1083 Set min-cpu-platform to haswell to support avx2 in deployment manager
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/XS

#1319 points to the documentation in kubeflow.org
  components/k8s-model-server/istio-dashboard.png
  components/k8s-model-server/istio-integration.md
Labels: approved, cla: yes, lgtm, size/L

#1324 Update ambassador to 0.37.0
  kubeflow/core/prototypes/ambassador.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1308 Turn deploy.sh into kfctl.sh
  prow_config.yaml
  scripts/deploy.sh
  scripts/download.sh
  scripts/download_test.py
  scripts/gke/README.md
  scripts/gke/delete_deployment.sh
  scripts/gke/delete_role_bindings.py
  scripts/gke/deploy.sh
  scripts/gke/deploy_test.sh
  scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml
  scripts/gke/deployment_manager_configs/gcfs.yaml
  scripts/gke/deployment_manager_configs/network.jinja
  scripts/gke/deployment_manager_configs/network.yaml
  scripts/gke/teardown.sh
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/util.sh
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
  testing/workflows/run.sh
Labels: approved, cla: yes, lgtm, size/XXL

#1329 [gcp-deployer] add service account key handler and a check health handler
  bootstrap/cmd/bootstrap/app/SaKey.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/glide.lock
  bootstrap/glide.yaml
Labels: approved, cla: yes, lgtm, size/L

#1209 Seldon 0.2 update
  kubeflow/seldon/core.libsonnet
  kubeflow/seldon/crd.libsonnet
  kubeflow/seldon/json/README.md
  kubeflow/seldon/json/apife-deployment.json
  kubeflow/seldon/json/apife-service.json
  kubeflow/seldon/json/operator-deployment.json
  kubeflow/seldon/json/rbac-cluster-binding.json
  kubeflow/seldon/json/rbac-service-account.json
  kubeflow/seldon/json/redis-deployment.json
  kubeflow/seldon/json/redis-service.json
  kubeflow/seldon/json/template_0.1.json
  kubeflow/seldon/json/template_0.2.json
  kubeflow/seldon/prototypes/abtest-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/abtest-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/core.jsonnet
  kubeflow/seldon/prototypes/mab-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/mab-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/outlier-detector-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/outlier-detector-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/serve-simple-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/serve-simple-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/serve-simple.jsonnet
  kubeflow/seldon/serve-simple.libsonnet
Labels: approved, lgtm, size/XXL

#1335 add bindRoleHandler which bind roles to service accounts
  bootstrap/cmd/bootstrap/app/initHandler.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/glide.lock
  bootstrap/glide.yaml
Labels: approved, cla: yes, lgtm, size/L

#1352 Add README steps for releasing website
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/M

#1313 Build and debug improvements for bootstrapper
  bootstrap/Dockerfile
  bootstrap/Dockerfile.Builder
  bootstrap/Makefile
  bootstrap/bootstrapper.png
  bootstrap/build.py
  bootstrap/debug.sh
  bootstrap/developer_guide.md
  bootstrap/dlv.sh
Labels: approved, cla: yes, lgtm, size/L

#1345 fixes issue #1344
  kubeflow/core/jupyterhub.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1360 fix 'kfctl.sh delete platform' doesn't delete platform correctly.
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#1356 ks version update to 0.11.0, and bug fixes.
  bootstrap/Dockerfile
  bootstrap/bootstrapper.yaml
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  bootstrap/glide.lock
  bootstrap/glide.yaml
  bootstrap/image_registries.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1341 Update TFJob operator to the latest image.
  kubeflow/core/prototypes/tf-job-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1355 upgrade gke version for v0.2
  scripts/gke/deployment_manager_configs/cluster.jinja
  testing/dm_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#1357 Fix a bug in kfctl.sh when just creating a K8s app and not GCP.
  scripts/deploy_test.sh
  scripts/gke/README.md
  scripts/kfctl.sh
  scripts/kfctl_generate_test.sh
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1361 add optionsHandler for OPTIONS request from browser
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#1374 Add Jobs permission to jupyterhub-noteook role to for common use cases
  kubeflow/core/jupyterhub.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1351 Create ks prototype for tf-batch-predict
  kubeflow/examples/prototypes/tf-batch-predict.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#1375 add apply handler; fix k8s auth; reset glide hash
  bootstrap/cmd/bootstrap/app/k8sAuth.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/glide.lock
Labels: approved, cla: yes, lgtm, size/L

#1370 use tf serving image
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1378 Change the default branch used for the configs to v0.2-branch and not master
  scripts/deploy.sh
  scripts/gke/deploy.sh
Labels: approved, cla: yes, lgtm, size/XS

#1380 Fix groups for various resources
  kubeflow/core/jupyterhub.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1385 Fix typo
  kubeflow/core/tensorboard.libsonnet
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1376 Adds argo to ambassador and Central UI
  components/centraldashboard/Dockerfile
  components/centraldashboard/dashboard.go
  kubeflow/argo/argo.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1384 Fixes the install_minikube.sh script for non-Ubuntu OSes
  testing/install_minikube.sh
Labels: approved, cla: yes, lgtm, size/XS

#1391 Cherry-pick: Update TFJob operator to the latest image
  kubeflow/core/prototypes/tf-job-operator.jsonnet
Labels: approved, cla: no, lgtm, size/XS

#1388 support customized image in ACK and update the document
  ack_guide.md
  kubeflow/core/kubeform_spawner.py
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/M

#1397 Add namespaces to the tf-job-dashboard role
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1327 Fix iap-ingress certificate creation and use BackendConfig for IAP
  kubeflow/core/cert-manager.libsonnet
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/iap.libsonnet
  kubeflow/core/ingress_bootstrap.sh
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prototypes/cert-manager.jsonnet
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/setup_backend.sh
  kubeflow/core/tests/iap_test.jsonnet
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/L

#1405 Update various scripts to use lowercase clientid/secret
  components/gcp-click-to-deploy/src/configs/cluster.jinja
  kubeflow/core/prototypes/metric-collector.jsonnet
  scripts/gke/deploy.sh
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/M

#1403 Update tf-job-operator prototype to support namespace-scoped deployment
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/tests/tf-job_test.jsonnet
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1396 Updates to iap component to support private clusters
  components/ingress-setup-image/Dockerfile
  components/ingress-setup-image/README.md
  kubeflow/core/configure_envoy_for_iap.sh
  kubeflow/core/iap.libsonnet
  kubeflow/core/ingress_bootstrap.sh
  kubeflow/core/prototypes/iap-ingress.jsonnet
  kubeflow/core/setup_backend.sh
Labels: approved, cla: yes, lgtm, size/M

#1399 Fix annotations in ambassador and centraldashboard
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/prototypes/ambassador.jsonnet
  kubeflow/core/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1406 Remove deploy_gcp.sh and update workflows.libsonnet.
  testing/deploy_kubeflow.py
  testing/deploy_kubeflow_gcp.sh
  testing/teardown_kubeflow_gcp.sh
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1395 util.libsonnet has methods that allow a <component>.part to be modified
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/prototypes/jupyterhub.jsonnet
Labels: approved, cla: yes, lgtm, size/XL

#1408 Python script to declaratively manage IAM binding patches
  scripts/gke/delete_deployment.sh
  scripts/gke/delete_role_bindings.py
  scripts/gke/deployment_manager_configs/cluster.jinja
  scripts/gke/deployment_manager_configs/iam_bindings_template.yaml
  scripts/gke/iam_patch.py
  scripts/gke/iam_patch_test.py
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/XL

#1392 Add mxnet operator (https://github.com/kubeflow/community/issues/136)
  kubeflow/mxnet-job/README.md
  kubeflow/mxnet-job/mxnet-operator.libsonnet
  kubeflow/mxnet-job/parts.yaml
  kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
  kubeflow/mxnet-job/prototypes/mxnet-operator.jsonnet
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1404 Fix use_gcr_for_all_images.sh
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/XS

#1387 Added a minikube setup script.
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/prototypes/jupyterhub.jsonnet
  scripts/kfctl.sh
  scripts/setup-minikube.sh
  scripts/util-minikube.sh
Labels: approved, cla: yes, lgtm, size/L

#1424 Add texasmichelle to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1431 Add imagePullSecret to Seldon Prototypes
  kubeflow/seldon/prototypes/abtest-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/abtest-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/mab-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/mab-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/outlier-detector-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/outlier-detector-v1alpha2.jsonnet
  kubeflow/seldon/prototypes/serve-simple-v1alpha1.jsonnet
  kubeflow/seldon/prototypes/serve-simple-v1alpha2.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#1423 Use JupyterLab as default instead of Jupyter Tree interface
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/prototypes/jupyterhub.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#1427 Add logging statements to help figure out why test results aren't reported
  testing/tf_job_simple_test.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#1434 Weaveflux version 0.1.2.
  kubeflow/weaveflux/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1439 Fix KUBEFLOW_REPO dir pointer.
  scripts/setup-minikube.sh
Labels: approved, cla: yes, lgtm, size/XS

#1411 Fix minikube test and trigger on presubmit when modified.
  prow_config.yaml
  testing/deploy_kubeflow.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1443 Ensure MOUNT_LOCAL env var is forwarded to kfctl
  scripts/setup-minikube.sh
Labels: approved, cla: yes, lgtm, size/XS

#1372 [kfctl web app] frontend & backend update to agree with api changes
  bootstrap/cmd/bootstrap/app/initHandler.go
  bootstrap/cmd/bootstrap/app/k8sAuth.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/saKey.go
  components/gcp-click-to-deploy/kf_app.yaml
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/configs/cluster-kubeflow.yaml
  components/gcp-click-to-deploy/src/configs/cluster.jinja
  components/gcp-click-to-deploy/src/configs/cluster.jinja.schema
Labels: approved, cla: yes, lgtm, size/XXL

#1445 Fix readme for local run
  components/gcp-click-to-deploy/README.md
Labels: approved, cla: yes, lgtm, size/S

#1441 Enable v1alpha2 for Pytorch operator
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#1456 Fix presubmit unit test
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, size/XS

#1447 Create webapp manifest dir
  components/gcp-click-to-deploy/manifest/ingress.yaml
  components/gcp-click-to-deploy/manifest/kf_app.yaml
Labels: approved, cla: yes, lgtm, size/M

#1449 Click to deploy ui: remove ipName and make hostName optional
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#1458 make web app stateless & backend security update
  bootstrap/cmd/bootstrap/app/initHandler.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/L

#1460 implement gcpUtils which takes care of integrating deployment manager API (part of PR 1458)
  bootstrap/cmd/bootstrap/app/gcpUtils.go
Labels: approved, cla: yes, lgtm, size/M
