Repository kubeflow/kubeflow, pull requests merged in 2018-07, with the labels that each got.

#1110 Add a jupyter-notebook-role and use it for notebooks in jupyterhub
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/M

#1108 [gcp-deployer] Rudimentary progress in logs
  components/gcp-click-to-deploy/src/App.css
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
  components/gcp-click-to-deploy/src/NameForm.tsx
  components/gcp-click-to-deploy/src/Utils.ts
  components/gcp-click-to-deploy/src/index.css
Labels: approved, lgtm, size/L

#1113 Pin and fix katib images.
  hack/retag_katib_images.sh
  kubeflow/katib/modeldb.libsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/suggestion.libsonnet
  kubeflow/katib/vizier.libsonnet
Labels: approved, lgtm, size/M

#1120 Pin and fix katib images. (#1113)
  hack/retag_katib_images.sh
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, lgtm, size/M

#1119 Put the full PyTorch prototype in the jsonnet file.
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/pytorch-job.libsonnet
Labels: approved, lgtm, size/L

#1127 Fix typos
  README.md
  components/echo-server/main.py
  components/gcp-click-to-deploy/src/configs/cluster.jinja
  components/k8s-model-server/images/releaser/environments/prow/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/prow/.metadata/swagger.json
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/releasing/.metadata/swagger.json
  components/k8s-model-server/images/releaser/environments/testing/.metadata/k8s.libsonnet
  components/k8s-model-server/images/releaser/environments/testing/.metadata/swagger.json
  components/k8s-model-server/images/releaser/lib/v1.7.0/k8s.libsonnet
  components/k8s-model-server/images/releaser/lib/v1.7.0/swagger.json
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/.metadata/swagger.json
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/environments/releasing/.metadata/swagger.json
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/k8s.libsonnet
  components/tensorflow-notebook-image/releaser/lib/v1.7.0/swagger.json
  docs/gke/configs/cluster.jinja
  kubeflow/automation/prototypes/release.jsonnet
  kubeflow/core/iap.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  releasing/pytorch-operator/vendor/kubeflow/automation/prototypes/release.jsonnet
  releasing/releaser/environments/prow/.metadata/k8s.libsonnet
  releasing/releaser/environments/prow/.metadata/swagger.json
  releasing/releaser/environments/releasing/.metadata/k8s.libsonnet
  releasing/releaser/environments/releasing/.metadata/swagger.json
  releasing/releaser/lib/v1.7.0/k8s.libsonnet
  releasing/releaser/lib/v1.7.0/swagger.json
  testing/workflows/environments/prow/.metadata/k8s.libsonnet
  testing/workflows/environments/prow/.metadata/swagger.json
  testing/workflows/lib/v1.7.0/k8s.libsonnet
  testing/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/L

#1131 Fix TFMA jupyter extensions.
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, lgtm, size/XS

#1122 Add Dockerfile and Makefile to build docker images
  components/gcp-click-to-deploy/Dockerfile
  components/gcp-click-to-deploy/Makefile
Labels: approved, lgtm, size/M

#1123 add service monitor prototype for monitoring deployment status
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prototypes/metric-collector.jsonnet
  metric-collector/Dockerfile
  metric-collector/Makefile
  metric-collector/service-readiness/kubeflow-readiness.py
Labels: approved, lgtm, size/L

#1111 Create a deployment script for gke and minikube
  scripts/gke/deploy.sh
  scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml
  scripts/gke/deployment_manager_configs/cluster.jinja
  scripts/gke/deployment_manager_configs/cluster.jinja.schema
  scripts/gke/teardown.sh
  scripts/minikube/deploy.sh
  scripts/util.sh
Labels: approved, lgtm, size/XL

#1136 Set requests and limits for RAM and CPU in TF notebook image releaser.
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#1133 Make the test robust to test flakes due to problems initializing the ksonnet app
  testing/tf_job_simple_test.py
  testing/vm_util.py
Labels: approved, lgtm, size/M

#1102 add katib releaser
  releasing/katib/.gitignore
  releasing/katib/add-katib-releaser.sh
  releasing/katib/app.yaml
  releasing/katib/components/earlystopping-medianstopping.jsonnet
  releasing/katib/components/katib-frontend.jsonnet
  releasing/katib/components/params.libsonnet
  releasing/katib/components/suggestion-bayesianoptimization.jsonnet
  releasing/katib/components/suggestion-grid.jsonnet
  releasing/katib/components/suggestion-hyperband.jsonnet
  releasing/katib/components/suggestion-random.jsonnet
  releasing/katib/components/vizier-core.jsonnet
  releasing/katib/environments/base.libsonnet
  releasing/katib/environments/default/globals.libsonnet
  releasing/katib/environments/default/main.jsonnet
  releasing/katib/environments/default/params.libsonnet
Labels: approved, lgtm, size/L

#1149 Fix the makefile so that we tag the image with the comit.
  components/centraldashboard/frontend/Makefile
Labels: approved, lgtm, size/S

#1150 Make Katib work with Ambassador. (#1103)
  kubeflow/katib/modeldb.libsonnet
Labels: approved, lgtm, size/XS

#1100 Create a script to update a ksonnet app to the latest Kubeflow package
  scripts/upgrade_ks_app.py
Labels: approved, lgtm, size/L

#1164 Make GKE VM service account storage.objectViewer
  docs/gke/configs/cluster.jinja
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/S

#1162 Skip project setup during deployment.
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#1144 Tag the latest Jupyter images with v0.2.1
  docs_dev/releasing.md
  kubeflow/core/kubeform_spawner.py
  releasing/README.md
  releasing/apply_image_tags.py
  releasing/image_tags.yaml
  releasing/run_apply_image_tags.sh
  releasing/update_image_tags.sh
  releasing/update_images.sh
  releasing/update_ksonnet.sh
Labels: approved, lgtm, size/L

#1167 Delete kubeflow namespace before deleting the cluster
  testing/teardown_kubeflow_gcp.sh
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#1163 Give KF_USER_NAME service account roles/cloudbuild.builds.editor role
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/XS

#1170 Cherypick: Tag the latest Jupyter images with v0.2.1 (#1144)
  docs_dev/releasing.md
  kubeflow/core/kubeform_spawner.py
  releasing/README.md
  releasing/apply_image_tags.py
  releasing/image_tags.yaml
  releasing/run_apply_image_tags.sh
  releasing/update_image_tags.sh
  releasing/update_images.sh
  releasing/update_ksonnet.sh
Labels: size/XL

#1174 Make the deploy scripts more efficient and other fixes.
  scripts/deploy.sh
  scripts/gke/deploy.sh
Labels: approved, lgtm, size/M

#1180 Make the deploy scripts more efficient and other fixes. (#1174)
  docs/gke/README.md
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/configs/deploy.sh
  scripts/deploy.sh
  scripts/gke/deploy.sh
  scripts/gke/deployment_manager_configs/cluster.jinja
  scripts/upgrade_ks_app.py
  scripts/util.sh
Labels: approved, lgtm, size/L

#1182 Cherry pick upgrading the central UI to v0.2.1
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/XS

#1183 Fix socket.Error typo
  testing/vm_util.py
Labels: approved, lgtm, size/XS

#1181 Update Central UI image to the v0.2.1 tag.
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/XS

#1161 Make metric collector emit k8s event
  kubeflow/core/metric-collector.libsonnet
  metric-collector/Dockerfile
  metric-collector/service-readiness/kubeflow-readiness.py
Labels: approved, lgtm, size/L

#1186 Put the full PyTorch prototype in the jsonnet file. (#1119)
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/pytorch-job.libsonnet
Labels: approved, lgtm, size/L

#1188 Use PV for /home/jovyan by default
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/XS

#1185 Grant roles/viewer to kubeflow user service account
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/XS

#1191 Use PV for /home/jovyan by default
  kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/XS

#1173 GCFS support
  kubeflow/core/all.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/kubeform_spawner.py
  kubeflow/core/nfs.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/google-cloud-filestore-pv.jsonnet
  kubeflow/core/tests/jupyterhub_test.jsonnet
  kubeflow/core/tests/nfs_test.jsonnet
  scripts/gke/deploy.sh
  scripts/gke/teardown.sh
Labels: approved, lgtm, size/XL

#1194 Fix deploy.sh moving the unpacked repo.
  scripts/deploy.sh
  scripts/deploy_test.sh
  scripts/gke/deploy.sh
  scripts/gke/deploy_test.sh
Labels: approved, lgtm, size/L

#1196 Cherrypick #1194 to master - Fix deploy.sh moving the unpacked repo
  scripts/deploy.sh
  scripts/deploy_test.sh
  scripts/gke/deploy.sh
  scripts/gke/deploy_test.sh
Labels: approved, lgtm, size/L

#1192 Support private GKE clusters in gke deploy.sh script
  scripts/gke/deploy.sh
  scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/M

#1195 Delete docs/gke/configs and move tests to scripts/gke
  docs/gke/configs/cluster-kubeflow.yaml
  docs/gke/configs/cluster.jinja
  docs/gke/configs/cluster.jinja.schema
  docs/gke/configs/deploy.sh
  docs/gke/configs/env-kubeflow.sh
  docs/gke/testing/deploy.sh
  scripts/gke/deploy.sh
  scripts/gke/teardown.sh
  testing/deploy_kubeflow_gcp.sh
  testing/teardown_kubeflow_gcp.sh
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1199 Add a script to cleanup leaked kubeflow-ci ingress resources
  scripts/cleanup_kubeflow_ci.sh
Labels: approved, lgtm, size/M

#1109 Add Kaggle notebook Dockerfile
  components/contrib/kaggle-notebook-image/Dockerfile
  components/contrib/kaggle-notebook-image/README.md
Labels: approved, lgtm, size/M

#1210 fix tf-job-dashboard fails to show logs
  kubeflow/core/tf-job-operator.libsonnet
Labels: approved, lgtm, size/XS

#1212 Improve jupyterhub form interface
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/M

#1211 Speed up gke script by running DM and GCFS creation in parallel
  scripts/gke/deploy.sh
Labels: approved, lgtm, size/S

#1208 [gcp-deployer] Require user sign in, fetch email, add splash screen
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/public/index.html
  components/gcp-click-to-deploy/src/App.css
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
  components/gcp-click-to-deploy/src/Header.tsx
  components/gcp-click-to-deploy/src/Page404.tsx
  components/gcp-click-to-deploy/src/Splash.tsx
  components/gcp-click-to-deploy/src/hero.png
  components/gcp-click-to-deploy/src/index.css
  components/gcp-click-to-deploy/src/index.tsx
  components/gcp-click-to-deploy/src/kubeflow-text.svg
  components/gcp-click-to-deploy/src/logo.jpg
  components/gcp-click-to-deploy/src/logo.svg
Labels: approved, lgtm, size/XL

#1207 Split kubeflow-core into individual prototypes
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  components/jupyterhub/README.md
  docs_dev/ksonnet_packages.md
  kubeflow/core/README.md
  kubeflow/core/all.libsonnet
  kubeflow/core/ambassador.libsonnet
  kubeflow/core/centraldashboard.libsonnet
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/prototypes/all.jsonnet
  kubeflow/core/prototypes/ambassador.jsonnet
  kubeflow/core/prototypes/centraldashboard.jsonnet
  kubeflow/core/prototypes/jupyterhub.jsonnet
  kubeflow/core/prototypes/spartakus.jsonnet
  kubeflow/core/prototypes/tf-job-operator.jsonnet
  kubeflow/core/spartakus.libsonnet
  scripts/deploy.sh
  scripts/gke/deploy.sh
  testing/deploy_kubeflow.py
  testing/deploy_kubeflow_gcp.sh
  testing/update_dm_config.py
Labels: approved, lgtm, size/XXL

#1204 prometheus prototype
  kubeflow/core/jupyterhub.libsonnet
  kubeflow/core/metric-collector.libsonnet
  kubeflow/core/prometheus.libsonnet
  kubeflow/core/prometheus.yml
  kubeflow/core/prototypes/ambassador.jsonnet
  kubeflow/core/prototypes/prometheus.jsonnet
Labels: approved, lgtm, size/L

#1165 Add doc for TF Serving
  docs_dev/tf_serving.md
Labels: approved, lgtm, size/M

#1151 Turn bootstrapper into an RPC server for ksonnet.
  bootstrap/Dockerfile
  bootstrap/Dockerfile.Builder
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/bootstrap/app/server_test.go
  bootstrap/cmd/bootstrap/main.go
  bootstrap/glide.lock
  bootstrap/glide.yaml
  bootstrap/hack/send_ks_request.py
  bootstrap/start.sh
  scripts/run_gofmt.sh
Labels: approved, lgtm, size/XXL

#1235 [gcp-deployer] Enable required GCP services before deploying
  components/gcp-click-to-deploy/public/index.html
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
  components/gcp-click-to-deploy/src/Header.tsx
  components/gcp-click-to-deploy/src/Utils.ts
Labels: approved, lgtm, size/L

#1238 Update indentation issue in jupyterhub spawner ui
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/XS

#1243 Fix deploy.sh when re-trying on existing deployment name
  scripts/gke/deploy.sh
Labels: approved, lgtm, size/XS

#1244 Scope kubeflow prow jobs by job type and modified dirs
  prow_config.yaml
Labels: approved, lgtm, size/S

#1200 change {username}{servername} to {userid} to avoid volume length restrictions of 63 characters
  kubeflow/core/kubeform_spawner.py
Labels: approved, lgtm, size/M

#1256 Scripts' code style adjustment
  scripts/autoformat_jsonnet.sh
  scripts/deploy.sh
  scripts/deploy_test.sh
  scripts/run_gofmt.sh
Labels: approved, lgtm, size/S

#1247 Modified README.md to point to Kubeflow.org community page. Issue #1237
  README.md
Labels: approved, lgtm, size/M

#1236 Fix link on front page.
  components/gcp-click-to-deploy/src/App.tsx
Labels: approved, lgtm, size/XS

#1248 Deploy click to deploy app
  components/gcp-click-to-deploy/Makefile
  components/gcp-click-to-deploy/README.md
  components/gcp-click-to-deploy/ks-app/.gitignore
  components/gcp-click-to-deploy/ks-app/app.yaml
  components/gcp-click-to-deploy/ks-app/components/clusterrole-external-dns.yaml
  components/gcp-click-to-deploy/ks-app/components/clusterrolebinding-external-dns-viewer.yaml
  components/gcp-click-to-deploy/ks-app/components/deployment-external-dns.yaml
  components/gcp-click-to-deploy/ks-app/components/ingress.jsonnet
  components/gcp-click-to-deploy/ks-app/components/params.libsonnet
  components/gcp-click-to-deploy/ks-app/components/serviceaccount-external-dns.yaml
  components/gcp-click-to-deploy/ks-app/components/webapp.jsonnet
  components/gcp-click-to-deploy/ks-app/create_gcp_deploy_sa.sh
  components/gcp-click-to-deploy/ks-app/environments/base.libsonnet
  components/gcp-click-to-deploy/ks-app/environments/default/globals.libsonnet
  components/gcp-click-to-deploy/ks-app/environments/default/main.jsonnet
  components/gcp-click-to-deploy/ks-app/environments/default/params.libsonnet
Labels: approved, lgtm, size/L

#1260 [gcp-deployer] CSS fixes, Removed Placeholder, linting
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/Css.ts
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
  components/gcp-click-to-deploy/src/Header.tsx
  components/gcp-click-to-deploy/src/Page404.tsx
  components/gcp-click-to-deploy/src/Splash.tsx
  components/gcp-click-to-deploy/tslint.json
Labels: approved, lgtm, size/L

#1267 Fix tfjob test; the simple tfjob test prototype was renamed.
  testing/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#1270 Small fix to tf serving component
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, size/S

#1272 Deploy argo in deploy.sh
  scripts/deploy.sh
  scripts/gke/deploy.sh
Labels: approved, lgtm, size/XS

#1159 Create a doc to describe the deployment process.
  docs_dev/kubeflow_deployment.md
Labels: approved, lgtm, size/L

#1265 Update TFJob image to include the fixes to make the UI work with IAP.
  kubeflow/core/prototypes/tf-job-operator.jsonnet
Labels: approved, lgtm, size/XS

#1229 TF serving support request logging
  components/k8s-model-server/fluentd-logger/Dockerfile
  components/k8s-model-server/http-proxy/server.py
  components/k8s-model-server/request-logging.md
  kubeflow/tf-serving/prototypes/tf-serving-with-request-log.jsonnet
Labels: approved, lgtm, size/L

#1273 Enable GKE node-pool autoscaling options
  scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/M

#1290 Make it easier to rerun deploy.sh
  scripts/gke/deploy.sh
Labels: approved, lgtm, size/L

#1292 Pointing katib doc to kubeflow/website
  kubeflow/katib/README.md
Labels: approved, lgtm, size/M

#1252 Enable new SD agents by default
  scripts/gke/deploy.sh
  scripts/gke/deployment_manager_configs/cluster.jinja
Labels: approved, lgtm, size/S

#1287 Update README.md
  components/contrib/kaggle-notebook-image/README.md
Labels: approved, lgtm, size/XS
