Repository kubeflow/kubeflow, pull requests merged in 2018-12, with the labels that each got.

#1989 Make it easier to debug jsonnet tests
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, size/M

#2018 Activate CMLE during kfctl deployment
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/XS

#2035 Add roles/dataproc.editor for kubeflow user account
  deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2040 Update OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2038 Add fairing library to jupyter images
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2041 delete config set in gcp-click-to-deploy dir since its already merged with kfctl config
  components/gcp-click-to-deploy/src/configs/cluster-kubeflow.yaml
  components/gcp-click-to-deploy/src/configs/cluster.jinja
  components/gcp-click-to-deploy/src/configs/cluster.jinja.schema
  components/gcp-click-to-deploy/src/configs/iam_bindings_template.yaml
Labels: approved, cla: yes, lgtm, size/L

#2011 Katib 0.3 cherrypick
  kubeflow/katib/modeldb.libsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
  kubeflow/katib/vizier.libsonnet
  releasing/update_components.sh
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, size/XL

#2045 Update Pipeline version to v0.1.3
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2055 Merge Pipeline integration change to v0.3
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/tensorflow-notebook-image/Dockerfile
  kubeflow/core/prototypes/centraldashboard.jsonnet
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  scripts/gke/deployment_manager_configs/iam_bindings_template.yaml
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/S

#2048 refactor monitoring metrics
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/M

#2053 Updates for RAPIDS AI v0.4.0 image
  components/contrib/rapidsai-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2056 unify central dashboard layout
  components/centraldashboard/frontend/index/index.html
  components/centraldashboard/frontend/layout/index.html
Labels: approved, cla: yes, lgtm, size/XS

#2047 upgrade central dashboard image to v0.3.4 to include pipeline ui link
  kubeflow/core/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2026 Support running batch prediction by launching a Dataflow job on GCP
  kubeflow/examples/prototypes/tf-batch-predict.jsonnet
  kubeflow/tf-batch-predict/parts.yaml
  kubeflow/tf-batch-predict/prototypes/tf-batch-predict.jsonnet
  kubeflow/tf-batch-predict/tests/tf-batch-predict_test.jsonnet
  kubeflow/tf-batch-predict/tf-batch-predict.libsonnet
Labels: approved, cla: yes, lgtm, size/XL

#2015 Give jupyter-notebook pods/log permission for fairing
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/tests/jupyter_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2034 always convert numGpu to int
  kubeflow/tf-serving/tests/tf_serving_test.jsonnet
  kubeflow/tf-serving/tf-serving-template.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2061 Fix a version number bug and add tf-batch-prediction into kubeflow registry
  kubeflow/registry.yaml
  kubeflow/tf-batch-predict/parts.yaml
  kubeflow/tf-batch-predict/tests/tf-batch-predict_test.jsonnet
  kubeflow/tf-batch-predict/tf-batch-predict.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2063 update kf version to v0.3.4
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#2066 Temp workaround for RAPIDS shared lib issues
  components/contrib/rapidsai-notebook-image/Dockerfile
  components/contrib/rapidsai-notebook-image/README.md
Labels: approved, cla: yes, lgtm, size/M

#2043 fixes 'Move components in core into a GCP specific ksonnet package'
  kubeflow/gcp/OWNERS
  kubeflow/gcp/README.md
  kubeflow/gcp/cert-manager.libsonnet
  kubeflow/gcp/cloud-endpoints.libsonnet
  kubeflow/gcp/configure_envoy_for_iap.sh
  kubeflow/gcp/google-cloud-filestore-pv.libsonnet
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/ingress_bootstrap.sh
  kubeflow/gcp/metric-collector.libsonnet
  kubeflow/gcp/parts.yaml
  kubeflow/gcp/prometheus.libsonnet
  kubeflow/gcp/prometheus.yml
  kubeflow/gcp/prototypes/cert-manager.jsonnet
  kubeflow/gcp/prototypes/cloud-endpoints.jsonnet
  kubeflow/gcp/prototypes/google-cloud-filestore-pv.jsonnet
  kubeflow/gcp/prototypes/iap-ingress.jsonnet
  kubeflow/gcp/prototypes/metric-collector.jsonnet
  kubeflow/gcp/prototypes/prometheus.jsonnet
  kubeflow/gcp/setup_backend.sh
  kubeflow/gcp/tests/iap_test.jsonnet
  kubeflow/gcp/update_backend.sh
  scripts/gke/util.sh
  testing/deploy_utils.py
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, size/M

#2046 Update Pipeline SDK version to v0.1.3
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2064 Update katib components
  components/centraldashboard/frontend/layout/index.html
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
  kubeflow/katib/vizier.libsonnet
  releasing/update_components.sh
Labels: approved, cla: yes, lgtm, size/M

#2085 Update private IP configuration with new GKE API
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#2071 Add job to load pipeline samples
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2082 Fix variable in setup-minikube.sh
  scripts/setup-minikube.sh
Labels: approved, cla: yes, lgtm, size/XS

#2100 ks init: --skip-default-registries + append ${KS_INIT_EXTRA_ARGS}
  scripts/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2080 fixes 'upgrade cloud-endpoints-controller to use metacontroller/metacontroller:v0.3.0
  kubeflow/gcp/cloud-endpoints.libsonnet
  kubeflow/metacontroller/prototypes/metacontroller.jsonnet
  kubeflow/metacontroller/tests/metacontroller_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2097 Update aws parameters in serving and dashboard
  kubeflow/tensorboard/aws.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/tests/tensorboard-aws_test.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2104 Replace with std.asciiUpper with supported by required version of jsonnet
  kubeflow/core/tests/util_test.jsonnet
  kubeflow/core/util.libsonnet
  kubeflow/openmpi/util.libsonnet
  kubeflow/weaveflux/util.libsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2106 add r2d4 to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2067 Enforce use string type param for S3_USE_HTTPS and S3_VERIFY_SSL
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2101 Don't grant cloudservices account IAM admin priveleges.
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/XS

#2112 Update kubeflow components to v0.4.0
  kubeflow/core/prototypes/centraldashboard.jsonnet
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  releasing/image_tags.yaml
  releasing/update_components.sh
  releasing/update_image_tags.sh
Labels: approved, cla: yes, lgtm, size/L

#2050 Add modeldb as a package for kubeflow
  kubeflow/modeldb/modeldb.libsonnet
  kubeflow/modeldb/parts.yaml
  kubeflow/modeldb/prototypes/modeldb.jsonnet
  kubeflow/registry.yaml
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/L

#2117 Fix the modeldb ambassador route.
  kubeflow/modeldb/OWNERS
  kubeflow/modeldb/modeldb.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2079 JH Spawner Enhancements - Fixes #2060
  kubeflow/jupyter/jupyter_config.py
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/jupyter/ui/default/script.js
  kubeflow/jupyter/ui/default/spawner.py
  kubeflow/jupyter/ui/default/template.html
  kubeflow/jupyter/ui/rok/config.yaml
  kubeflow/jupyter/ui/rok/script.js
  kubeflow/jupyter/ui/rok/spawner.py
Labels: approved, cla: yes, lgtm, size/XL

#2115 Fix the check if directory named ${DEPLOYMENT_NAME} exists
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2108 Add yebrahim to pipeline ksonnet owner
  kubeflow/pipeline/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2123 Create cloud sql database for ml pipeline
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
  deployment/gke/deployment_manager_configs/cluster.jinja.schema
  deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/L

#2122 fixes "Cloud Endpoints Controller not working on mmaster"
  kubeflow/gcp/cloud-endpoints.libsonnet
  kubeflow/gcp/tests/cloud-endpoints_test.jsonnet
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2138 Fix one click deployer url in README
  components/gcp-click-to-deploy/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2137 Fixes initialization script does not correctly detect ks installation
  scripts/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2111 Kubebench operator ksonnet package
  kubeflow/kubebench/OWNERS
  kubeflow/kubebench/kubebench-operator.libsonnet
  kubeflow/kubebench/parts.yaml
  kubeflow/kubebench/prototypes/kubebench-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2118 Enable stackdriver agents for GKE by default.
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2135 Update ksonnet package for Katib
  kubeflow/katib/README.md
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
  kubeflow/katib/vizier.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2139 Package size fix, client id and secret textfield styling fix
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/Css.ts
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XXL

#2151 update pipeline version
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2153 cherry pick pipeline fix to v0.3 branch
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2107 rename kubeflow/core to kubeflow/common
  kubeflow/application/application.libsonnet
  kubeflow/argo/argo.libsonnet
  kubeflow/common/OWNERS
  kubeflow/common/README.md
  kubeflow/common/ambassador.libsonnet
  kubeflow/common/centraldashboard.libsonnet
  kubeflow/common/echo-server.libsonnet
  kubeflow/common/parts.yaml
  kubeflow/common/prototypes/ambassador.jsonnet
  kubeflow/common/prototypes/centraldashboard.jsonnet
  kubeflow/common/prototypes/echo-server.jsonnet
  kubeflow/common/prototypes/spartakus.jsonnet
  kubeflow/common/spartakus.libsonnet
  kubeflow/common/tests/ambassador_test.jsonnet
  kubeflow/common/tests/centraldashboard_test.jsonnet
  kubeflow/common/tests/util_test.jsonnet
  kubeflow/common/util.libsonnet
  kubeflow/common/version-info.json
  kubeflow/common/version.libsonnet
  kubeflow/gcp/iap.libsonnet
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/notebooks.libsonnet
  kubeflow/jupyter/prototypes/README.md
  kubeflow/knative-build/knative-build.libsonnet
  kubeflow/metacontroller/metacontroller.libsonnet
  kubeflow/new-package-stub/newpackage.libsonnet
  kubeflow/openvino/openvino.libsonnet
  kubeflow/profiles/profiles.libsonnet
  kubeflow/tensorboard/aws.libsonnet
  kubeflow/tensorboard/gcp.libsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
  kubeflow/tf-batch-predict/tf-batch-predict.libsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
  scripts/kfctl.sh
  scripts/util.sh
  testing/README.md
  testing/deploy_utils.py
  testing/test_deploy.py
  testing/test_jsonnet.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2150 Cut 0.4.0 release branch
  CHANGELOG.md
Labels: approved, cla: yes, lgtm, size/L

#2062 use service account token to make request, set token life time to be 15 mins.
  components/gcp-click-to-deploy/README.md
  components/gcp-click-to-deploy/app-config.yaml
  components/gcp-click-to-deploy/manifest/ingress.yaml
  components/gcp-click-to-deploy/manifest/kf_app.yaml
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
Labels: approved, cla: yes, lgtm, size/XXL

#2160 rename kubeflow/core to kubeflow/common
  kubeflow/application/application.libsonnet
  kubeflow/argo/argo.libsonnet
  kubeflow/common/OWNERS
  kubeflow/common/README.md
  kubeflow/common/ambassador.libsonnet
  kubeflow/common/centraldashboard.libsonnet
  kubeflow/common/echo-server.libsonnet
  kubeflow/common/parts.yaml
  kubeflow/common/prototypes/ambassador.jsonnet
  kubeflow/common/prototypes/centraldashboard.jsonnet
  kubeflow/common/prototypes/echo-server.jsonnet
  kubeflow/common/prototypes/spartakus.jsonnet
  kubeflow/common/spartakus.libsonnet
  kubeflow/common/tests/ambassador_test.jsonnet
  kubeflow/common/tests/centraldashboard_test.jsonnet
  kubeflow/common/tests/util_test.jsonnet
  kubeflow/common/util.libsonnet
  kubeflow/common/version-info.json
  kubeflow/common/version.libsonnet
  kubeflow/gcp/iap.libsonnet
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/notebooks.libsonnet
  kubeflow/jupyter/prototypes/README.md
  kubeflow/knative-build/knative-build.libsonnet
  kubeflow/metacontroller/metacontroller.libsonnet
  kubeflow/new-package-stub/newpackage.libsonnet
  kubeflow/openvino/openvino.libsonnet
  kubeflow/profiles/profiles.libsonnet
  kubeflow/tensorboard/aws.libsonnet
  kubeflow/tensorboard/gcp.libsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
  kubeflow/tf-batch-predict/tf-batch-predict.libsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
  scripts/kfctl.sh
  scripts/util.sh
  testing/README.md
  testing/deploy_utils.py
  testing/test_deploy.py
  testing/test_jsonnet.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2158 Style fixes
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/src/Css.ts
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XXL

#2161 update kf version to 0.3.5; add retry around IAM policy edit
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#2163 Fix check install to use param for type as well as which check
  scripts/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2090 fixes 'bootstrap golang modules'
  bootstrap/Dockerfile
  bootstrap/Dockerfile.Builder
  bootstrap/Makefile
  bootstrap/build.py
  bootstrap/build_image.sh
  bootstrap/cleanup.sh
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/debug.sh
  bootstrap/developer_guide.md
  bootstrap/dlv.sh
  bootstrap/glide.lock
  bootstrap/glide.yaml
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/start.sh
Labels: approved, cla: yes, lgtm, size/XXL

#2164 [gcp-click-to-deploy] cleanup: remove ks and kubectl from Dockerfile
  bootstrap/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2168 "argo" should be "Argo"
  testing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2091 kfctl functional description and changes required
  kfctl/OWNERS
  kfctl/README.md
Labels: approved, cla: yes, lgtm, size/L

#2181 Add the TF 1.11 & TF 1.12 Jupyter images to the spawner drop down box.
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/jupyter/ui/rok/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2188 kfctl.sh shouldn't fail if a user isn't explicitly in the IAM policy - 0.4 patch.
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2187 kfctl.sh shouldn't fail if a user isn't explicitly in the IAM policy.
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2109 parameterize mysql and minio image
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/mysql.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/M
