Repository kubeflow/kubeflow, pull requests merged in 2019-04, with the labels that each got.

#2878 Style guide added, with supporting docs
  components/centraldashboard/README.md
  components/centraldashboard/public/kubeflow-palette.css
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/M

#2887 Let jupyter service account list/get/create secret
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/tests/jupyter_test.jsonnet
Labels: approved, cla: yes, lgtm, priority/p0, size/XS

#2873 add auth cmd to logging
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#2838 delete endpoints
  bootstrap/pkg/kfapp/gcp/gcp.go
  testing/kfctl/kfctl_delete_test.py
Labels: approved, cla: yes, lgtm, size/L

#2662 A script to reset the basic auth secret.
  scripts/create_password_secret.sh
Labels: approved, cla: yes, lgtm, size/S

#2894 Create a minimal release process for kfctl.
  bootstrap/Makefile
  bootstrap/developer_guide.md
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/M

#2823 Add aws platform option
  deployment/aws/infra_configs/iam_alb_ingress_policy.json
  deployment/aws/infra_configs/iam_cloudwatch_policy.json
  kubeflow/aws/OWNERS
  kubeflow/aws/README.md
  kubeflow/aws/aws-alb-ingress-controller.libsonnet
  kubeflow/aws/aws-efs-pv.libsonnet
  kubeflow/aws/aws-fsx-csi-driver.libsonnet
  kubeflow/aws/istio-ingress.libsonnet
  kubeflow/aws/parts.yaml
  kubeflow/aws/prototypes/aws-alb-ingress-controller.jsonnet
  kubeflow/aws/prototypes/aws-efs-pv.jsonnet
  kubeflow/aws/prototypes/aws-fsx-csi-driver.jsonnet
  kubeflow/aws/prototypes/istio-ingress.jsonnet
  kubeflow/aws/tests/aws-alb-ingress-controller_test.jsonnet
  kubeflow/aws/tests/aws-efs-pv_test.jsonnet
  kubeflow/aws/tests/aws-fsx-csi-driver_test.jsonnet
  kubeflow/aws/tests/istio-ingress_test.jsonnet
  scripts/aws/delete_deployment.sh
  scripts/aws/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#2895 update notebook controller image
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, priority/p0, size/XS

#2903 fix patch string for admission webhook
  components/gcp-admission-webhook/main.go
  kubeflow/gcp/prototypes/webhook.jsonnet
Labels: approved, cla: yes, lgtm, priority/p0, size/L

#2898 Cherry-pick #2823 to v0.5 - Add aws platform option
  deployment/aws/infra_configs/iam_alb_ingress_policy.json
  deployment/aws/infra_configs/iam_cloudwatch_policy.json
  kubeflow/aws/OWNERS
  kubeflow/aws/README.md
  kubeflow/aws/aws-alb-ingress-controller.libsonnet
  kubeflow/aws/aws-efs-pv.libsonnet
  kubeflow/aws/aws-fsx-csi-driver.libsonnet
  kubeflow/aws/istio-ingress.libsonnet
  kubeflow/aws/parts.yaml
  kubeflow/aws/prototypes/aws-alb-ingress-controller.jsonnet
  kubeflow/aws/prototypes/aws-efs-pv.jsonnet
  kubeflow/aws/prototypes/aws-fsx-csi-driver.jsonnet
  kubeflow/aws/prototypes/istio-ingress.jsonnet
  kubeflow/aws/tests/aws-alb-ingress-controller_test.jsonnet
  kubeflow/aws/tests/aws-efs-pv_test.jsonnet
  kubeflow/aws/tests/aws-fsx-csi-driver_test.jsonnet
  kubeflow/aws/tests/istio-ingress_test.jsonnet
  scripts/aws/delete_deployment.sh
  scripts/aws/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#2880 sync pipeline branch to v0.5.0-rc.1
  CHANGELOG.md
  bootstrap/cmd/bootstrap/app/k8sUtil.go
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/utils/gcputils.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/iamutils_test.go
  bootstrap/pkg/utils/k8utils.go
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/README.md
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/not-found-view.js
  components/centraldashboard/public/styles.css
  components/centraldashboard/webpack.config.js
  components/gcp-admission-webhook/README.md
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  docs_dev/releasing.md
  kubeflow/application/prototypes/application.jsonnet
  kubeflow/common/prototypes/basic-auth.jsonnet
  kubeflow/credentials-admission-webhook/README.md
  kubeflow/credentials-admission-webhook/parts.yaml
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/prototypes/webhook.jsonnet
  kubeflow/gcp/webhook.libsonnet
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
  kubeflow/mpi-job/mpi-operator.libsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/registry.yaml
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  prow_config.yaml
  scripts/update-changelog.sh
  testing/kfctl/conftest.py
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_delete_test.py
  testing/kfctl/kfctl_go_test.py
  testing/wait_for_kubeflow.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/util.libsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: cla: yes, priority/p0, size/XXL

#2909 update kubeflow mxnet integration for mxnet-operator version update (#2797)
  kubeflow/mxnet-job/README.md
  kubeflow/mxnet-job/mxnet-operator.libsonnet
  kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
  kubeflow/mxnet-job/prototypes/mxnet-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2899 include spec dir to container; use remote spec when local cache doesn't exist
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#2869 Add volumn support and unit tests for mpi-job
  kubeflow/mpi-job/mpi-job.libsonnet
  kubeflow/mpi-job/mpi-operator.libsonnet
  kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet
  kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet
  kubeflow/mpi-job/prototypes/mpi-operator.jsonnet
  kubeflow/mpi-job/tests/mpi-job_test.jsonnet
  kubeflow/mpi-job/tests/mpi-operator_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#2828 add paddle-job
  kubeflow/paddle-job/README.md
  kubeflow/paddle-job/paddle-job.libsonnet
  kubeflow/paddle-job/paddle-operator.libsonnet
  kubeflow/paddle-job/parts.yaml
  kubeflow/paddle-job/prototypes/paddle-job.jsonnet
  kubeflow/paddle-job/prototypes/paddle-operator.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#2902 Jupyter docker images should be updated on the 0.5 branch
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/jupyter/ui/rok/config.yaml
Labels: approved, cla: yes, lgtm, priority/p0, size/M

#2879 update frontend config to be compatible with v0.5
  components/gcp-click-to-deploy/app-config.yaml
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, priority/p0, size/L

#2892 Set user inside Notebook to jovyan
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, priority/p0, size/XS

#2854 Use KfError interface
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/dockerfordesktop/dockerfordesktop.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/kfapp/minikube/minikube.go
  bootstrap/pkg/utils/gcputils.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/k8utils.go
Labels: approved, cla: yes, lgtm, size/XXL

#2917 Use jupyter service account for notebook CRD
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
Labels: approved, cla: yes, lgtm, priority/p0, size/XS

#2916 deploy UI update for v0.5
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/L

#2919 Add jupyter notebook svc account and roles
  kubeflow/jupyter/jupyter-web-app.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2918 Update fairing to bd8313
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2912 List endpoints when delete is failed
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/M

#2920 add retry around IAM APIs and ksonnet app init
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/M

#2922 Added usage reporting link
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/S

#2923 Update Kubebench tags
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
  kubeflow/kubebench/prototypes/kubebench-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2914 retry for long running API enabling services
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/M

#2928 fix webhook cert
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/webhook.libsonnet
Labels: approved, cla: yes, lgtm, priority/p0, size/M

#2932 Cherrypick for 0.5
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/dockerfordesktop/dockerfordesktop.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/kfapp/minikube/minikube.go
  bootstrap/pkg/utils/gcputils.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/k8utils.go
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
  components/gcp-click-to-deploy/app-config.yaml
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
  components/tensorflow-notebook-image/Dockerfile
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/webhook.libsonnet
  kubeflow/jupyter/jupyter-web-app.libsonnet
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/jupyter/ui/rok/config.yaml
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
  kubeflow/kubebench/prototypes/kubebench-operator.jsonnet
  kubeflow/mpi-job/mpi-job.libsonnet
  kubeflow/mpi-job/mpi-operator.libsonnet
  kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet
  kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet
  kubeflow/mpi-job/prototypes/mpi-operator.jsonnet
  kubeflow/mpi-job/tests/mpi-job_test.jsonnet
  kubeflow/mpi-job/tests/mpi-operator_test.jsonnet
  kubeflow/mxnet-job/README.md
  kubeflow/mxnet-job/mxnet-operator.libsonnet
  kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
  kubeflow/mxnet-job/prototypes/mxnet-operator.jsonnet
  kubeflow/paddle-job/README.md
  kubeflow/paddle-job/paddle-job.libsonnet
  kubeflow/paddle-job/paddle-operator.libsonnet
  kubeflow/paddle-job/parts.yaml
  kubeflow/paddle-job/prototypes/paddle-job.jsonnet
  kubeflow/paddle-job/prototypes/paddle-operator.jsonnet
Labels: cla: yes, size/XXL

#2930 update UI to include port-forward; update instructions
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/L

#2913 Central Dashboard - Add statefulness to generated links
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#2941 Conditionally make kubeflow the default namespace if found
  components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
Labels: approved, area/front-end, area/jupyter, cla: yes, lgtm, priority/p0, size/XS

#2939 quick fix for deploy UI with v0.5
  bootstrap/cmd/bootstrap/app/ksServer.go
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#2940 Update Pipelines to version 0.1.15
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2942 [Hotfix] Usage reporting Link
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#2944 Cherry-pick: Update Pipelines to version 0.1.15 (#2940)
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2946 set param for notebook controller
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2938 Extract exact backend service name
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/setup_backend.sh
Labels: approved, cla: yes, lgtm, size/S

#2951 Notebook ui default namespace
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#2953 add option to create permanent storage and spartakus
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#2950 Updating Fairing commit to v0.5 release of the python library
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2955 Update Pipelines to version 0.1.16
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2957 Update Pipelines to version 0.1.16 (#2955) {Cherry-pick to v0.5-branch}
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2956 Update Pipelines to version 0.1.16 (#2955) {Cherry-pick to pipelines}
  kubeflow/pipeline/pipeline.libsonnet
Labels: cla: yes, size/S

#2948 Automated cherry pick of #2946: set param for notebook controller Cherry pick of #2946 on v0.5-branch. #2946: set param for notebook controller
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
Labels: cla: yes, size/XS

#2968 set injectGcpCredentials to true by default
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2949 Automated cherry pick of #2938: lookup backend service full name Cherry pick of #2938 on v0.5-branch. #2938: lookup backend service full name
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/setup_backend.sh
Labels: approved, cla: yes, lgtm, size/S

#2966 Automated cherry pick of #2951: Notebook ui default namespace
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
Labels: approved, cla: yes, lgtm, size/XS

#2970 Automated cherry pick of #2968: set injectGcpCredentials to true by default Cherry pick of #2968 on v0.5-branch. #2968: set injectGcpCredentials to true by default
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: cla: yes, size/XS

#2934 kfctl will fail for --platform gcp if /Users/kdkasrav/.kube/config doesn't exist
  bootstrap/Makefile
  bootstrap/cmd/kfctl/cmd/apply.go
  bootstrap/cmd/kfctl/cmd/delete.go
  bootstrap/cmd/kfctl/cmd/generate.go
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/cmd/kfctl/cmd/show.go
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/developer_guide.md
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/L

#2977 update prober test for v0.5.0
  bootstrap/config/gcp_prototype.yaml
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/M

#2972 add zabbasi to approvers for notebook images
  components/tensorflow-notebook-image/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2960 enable gang scheduling flag for tf-operator
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2967 fix python env for common packages
  components/tensorflow-notebook-image/install.sh
Labels: approved, cla: yes, lgtm, size/XS

#2556 Add extra permissions to ClusterRole 'pipeline-runner'
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3001 Shows involvedObject rather than Cluster Host in Activities view
  components/centraldashboard/public/components/activities-list.js
  components/centraldashboard/public/components/activities-list_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/S

#2999 Adds favicons to Central Dashboard
  components/centraldashboard/public/assets/favicon-128x128.png
  components/centraldashboard/public/assets/favicon-152x152.png
  components/centraldashboard/public/assets/favicon-16x16.png
  components/centraldashboard/public/assets/favicon-180x180.png
  components/centraldashboard/public/assets/favicon-192x192.png
  components/centraldashboard/public/assets/favicon-32x32.png
  components/centraldashboard/public/assets/favicon-57x57.png
  components/centraldashboard/public/assets/favicon-76x76.png
  components/centraldashboard/public/assets/favicon-96x96.png
  components/centraldashboard/public/assets/favicon.ico
  components/centraldashboard/public/index.html
  components/centraldashboard/public/index.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p2, size/M

#3012 Create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2105 Update for Kaggle Dockerfile
  components/contrib/kaggle-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#3025 Use exact name when updating backend healthz path
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/update_backend.sh
Labels: approved, cla: yes, lgtm, size/S

#3013 Istio routing rule for katib
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/vizier.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#3034 reuse source repo for continuous tests
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/S

#3010 Update RAPIDS AI Dockerfile
  components/contrib/rapidsai-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#3043 release pipeline 0.1.17
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3044 fix optional deployments bug
  bootstrap/pkg/kfapp/gcp/gcp.go
  kubeflow/gcp/basic-auth-ingress.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3051 release pipeline 0.1.17 (#3043)
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3050 Automated cherry pick of #3044: fix optional deployments bug Cherry pick of #3044 on v0.5-branch. #3044: fix optional deployments bug
  bootstrap/pkg/kfapp/gcp/gcp.go
  kubeflow/gcp/basic-auth-ingress.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3028 Jupyter ISTIO routing rule - Ksonnet
  kubeflow/jupyter/jupyter-web-app.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3033 Argo ISTIO routing rule - Ksonnet
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3054 e2e test for kfctl istio
  bootstrap/pkg/kfapp/gcp/gcp.go
  prow_config.yaml
  testing/kfctl/conftest.py
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2988 Value of kfctl version is hardcoded and not representative of the actual build
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/kfctl/cmd/root.go
  bootstrap/cmd/kfctl/cmd/version.go
  bootstrap/cmd/kfctl/main.go
Labels: approved, cla: yes, lgtm, size/S

#3037 Finish all ISTIO routing rules for IAP.
  kubeflow/common/centraldashboard.libsonnet
  kubeflow/common/echo-server.libsonnet
  kubeflow/common/prototypes/centraldashboard.jsonnet
  kubeflow/common/prototypes/echo-server.jsonnet
  kubeflow/examples/prototypes/tensorboard.jsonnet
  kubeflow/kubebench/kubebench-dashboard.libsonnet
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
  kubeflow/openvino/openvino.libsonnet
  kubeflow/openvino/prototypes/openvino.jsonnet
  kubeflow/tensorboard/gcp.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
  kubeflow/tensorboard/tensorboard.libsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3036 Pipelines ISTIO routing rules - Ksonnet
  kubeflow/pipeline/istio-service.libsonnet
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3072 kfctl default use istio
  bootstrap/cmd/kfctl/cmd/init.go
  prow_config.yaml
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/XS

#3075 Add injectIstio param to kfctl configs
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/M

#3078 iap-ingress is not used in basic auth
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#3076 Default central dashboard URI matching to /
  kubeflow/common/centraldashboard.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3077 fix typo in pipeline istio rule.
  kubeflow/pipeline/istio-service.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3052 Run kfctl go unittests as part of pre/post submittests
  bootstrap/.gcloudignore
  bootstrap/Dockerfile
  bootstrap/Dockerfile.builder
  bootstrap/Makefile
  bootstrap/cloudbuild.yaml
  bootstrap/cmd/bootstrap/app/server_test.go
  bootstrap/developer_guide.md
  bootstrap/go.mod
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/v1alpha1_suite_test.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/v1alpha1_suite_test.go
  testing/workflows/components/unit_tests.jsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: approved, cla: yes, lgtm, size/XL

#3084 Update aws OWNERS file and make ingress configurable
  kubeflow/aws/OWNERS
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3059 clusterDomain params adding to katib
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/vizier.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3070 mini fix for "kfctl delete"
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/S

#3090 Added autocomple support for Deploy Form
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#3080 Scripts for replicating Docker images using GCB to support private GKE and VPC service controls.
  .gitignore
  scripts/gke/Makefile
  scripts/gke/gcb_copy_images.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/L

#3113 Fix based images of tf gpus for tf 1.13 and tf 2.0
  components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/2.0.0a0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/XS

#3110 Renames Documentation link and removes it from iframe.
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#3019 Allow multiple namespaces
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
  components/jupyter-web-app/kubeflow_jupyter/rok/templates/notebooks.html
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#3107 Python 2/3 agnostic dict iteration in update_ks_app.py
  scripts/upgrade_ks_app.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3116 CSS Added to improve #3110
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3111 Improve the scripts for mirroing images to support VPC service controls
  kubeflow/gcp/cloud-endpoints.libsonnet
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/prototypes/iap-ingress.jsonnet
  kubeflow/gcp/tests/iap_test.jsonnet
  scripts/gke/gcb_copy_images.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/M

#3062 Make kubebench reporter optional
  kubeflow/kubebench/kubebench-job.libsonnet
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3117 fixed based images of tf gpu notebooks
  components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json
  components/tensorflow-notebook-image/versions/2.0.0a0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/XS

#3115 Color Scheme Adjusted to incorporate a better set of colors
  components/centraldashboard/README.md
  components/centraldashboard/public/kubeflow-palette.css
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p2, size/S

#3124 Automated cherry pick of #3080: Scripts for replicating Docker images using GCB to #3111: Improve the scripts for mirroing images to support VPC Cherry pick of #3080 #3111 on v0.5-branch. #3080: Scripts for replicating Docker images using GCB to #3111: Improve the scripts for mirroing images to support VPC
  .gitignore
  kubeflow/gcp/cloud-endpoints.libsonnet
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/prototypes/iap-ingress.jsonnet
  kubeflow/gcp/tests/iap_test.jsonnet
  scripts/gke/Makefile
  scripts/gke/gcb_copy_images.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/L

#3038 change 'iap' case in c2d text
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#3104 ISTIO support for notebook controller
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  components/notebook-controller/pkg/util/util.go
  kubeflow/jupyter/notebook_controller.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3087 Flip injectIstio param to true
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/common/prototypes/centraldashboard.jsonnet
  kubeflow/common/prototypes/echo-server.jsonnet
  kubeflow/examples/prototypes/tensorboard.jsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
  kubeflow/openvino/prototypes/openvino.jsonnet
  kubeflow/pipeline/pipeline.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-service.jsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  scripts/util.sh
  testing/workflows/components/tfserving.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#3066 Create a script to build the jupyter-web-app image and create a PR to update it
  .gitignore
  .pylintrc
  components/jupyter-web-app/Makefile
  components/jupyter-web-app/cloudbuild.yaml
  components/jupyter-web-app/output.yaml
  py/kubeflow/__init__.py
  py/kubeflow/kubeflow/__init__.py
  py/kubeflow/kubeflow/ci/__init__.py
  py/kubeflow/kubeflow/ci/update_jupyter_web_app.py
  py/kubeflow/kubeflow/ci/update_jupyter_web_app_test.py
  releasing/auto-update/README.md
  releasing/auto-update/update_job.yaml
  scripts/update_prototype.py
Labels: approved, cla: yes, lgtm, size/XL

#3102 Adds Option to Enable SHM for notebook containers
  components/jupyter-web-app/kubeflow_jupyter/common/README.md
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/kubeflow_jupyter/default/templates/add_notebook.html
  components/jupyter-web-app/kubeflow_jupyter/rok/app.py
  components/jupyter-web-app/kubeflow_jupyter/rok/templates/add_notebook.html
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#3125 Version Related Changes
  components/centraldashboard/Dockerfile
  components/centraldashboard/Makefile
  components/centraldashboard/make-win.ps1
  components/centraldashboard/package.json
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#2807 Parameterize containerRuntimeExecutor on argo template
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/argo/tests/argo_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3153 Update jupyter-web-app image to point to latest in master
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3139 Remove ambassador from IAP default config
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  kubeflow/gcp/healthcheck_route.yaml
Labels: approved, cla: yes, lgtm, size/M
