Repository kubeflow/kubeflow, pull requests merged in 2019-08, with the labels that each got.

#3800 Add application overlay for tf-training
  bootstrap/config/kfctl_aws.yaml
  bootstrap/config/kfctl_aws_cognito.yaml
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3754 Fix build rules for new bootstraper backend
  bootstrap/Dockerfile
  bootstrap/Makefile
  components/gcp-click-to-deploy/ks-app/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3825 Fix overlay name
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3792 Updates kfctl_k8s_istio.yaml with kfctl v2 spec
  bootstrap/config/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#3801 [KUBEFLOW-3797] When copying files fails provide correct error message
  bootstrap/pkg/kfapp/aws/aws.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3758 Multi-User Isolation 2.0 - Manage Users
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_contributors.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/manage-users-view.css
  components/centraldashboard/public/components/manage-users-view.js
  components/centraldashboard/public/components/manage-users-view.pug
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/registration-page.css
  components/centraldashboard/public/components/registration-page.js
  components/centraldashboard/public/components/registration-page.pug
  components/centraldashboard/public/components/resources/md2-input/md2-input.css
  components/centraldashboard/public/components/resources/md2-input/md2-input.js
  components/centraldashboard/public/components/resources/md2-input/md2-input.pug
  components/centraldashboard/public/components/resources/paper-chip.js
  components/centraldashboard/public/components/utilities-mixin.js
Labels: approved, cla: yes, lgtm, size/XXL

#3842 [Central-Dashboard v2] MUI Basic Auth Support
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/server.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#3845 jupyter-web-app: Use PodDefault's name as backup
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
Labels: approved, cla: yes, lgtm, size/XS

#3843 [Central-Dashboard v2] MUI Style and Nomenclature
  components/centraldashboard/public/components/manage-users-view.css
  components/centraldashboard/public/components/manage-users-view.js
  components/centraldashboard/public/components/manage-users-view.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/S

#3853 Cp062
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/app/.jasmine.json
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/attach_user_middleware.ts
  components/centraldashboard/app/attach_user_middleware_test.ts
  components/centraldashboard/app/clients/profile_controller.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/.eslintrc.json
  components/centraldashboard/public/assets/icons/namespace.svg
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/manage-users-view.css
  components/centraldashboard/public/components/manage-users-view.js
  components/centraldashboard/public/components/manage-users-view.pug
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/namespace-selector_test.js
  components/centraldashboard/public/components/registration-page.css
  components/centraldashboard/public/components/registration-page.js
  components/centraldashboard/public/components/registration-page.pug
  components/centraldashboard/public/components/resources/animated-checkmark.js
  components/centraldashboard/public/components/resources/carousel-indicator.js
  components/centraldashboard/public/components/resources/md2-input/md2-input.css
  components/centraldashboard/public/components/resources/md2-input/md2-input.js
  components/centraldashboard/public/components/resources/md2-input/md2-input.pug
  components/centraldashboard/public/components/resources/paper-chip.js
  components/centraldashboard/public/components/utilities-mixin.js
  components/centraldashboard/tsconfig.json
  components/centraldashboard/tslint.json
  components/centraldashboard/types/index.d.ts
Labels: approved, cla: yes, lgtm, size/XXL

#3599 GCP Click-to-Deploy UI changes for v0.6.x
  components/gcp-click-to-deploy/Dockerfile
  components/gcp-click-to-deploy/Makefile
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/public/manifest.json
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Utils.ts
Labels: approved, cla: yes, lgtm, size/XXL

#3830 kfctlClient is a simple utility for sending requests to click to deploy
  bootstrap/Makefile
  bootstrap/cmd/kfctlClient/README.md
  bootstrap/cmd/kfctlClient/main.go
  bootstrap/go.mod
Labels: approved, cla: yes, lgtm, size/L

#3867 kfctl: pin configs to v0.6-branch
  bootstrap/config/kfctl_aws.yaml
  bootstrap/config/kfctl_aws_cognito.yaml
  bootstrap/config/kfctl_existing_arrikto.0.6.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#3760 kfctl: existing_arrikto: fix ip discovery and cert creation on AWS for existing_arrikto config
  bootstrap/pkg/kfapp/existing_arrikto/existing.go
  bootstrap/pkg/kfapp/existing_arrikto/existing_test.go
Labels: approved, cla: yes, lgtm, size/L

#3889 Revert "kfctlClient is a simple utility for sending requests to click to deploy (#3830)
  bootstrap/Makefile
  bootstrap/cmd/kfctlClient/README.md
  bootstrap/cmd/kfctlClient/main.go
  bootstrap/go.mod
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/L

#3892 update config file on v0.6 branch
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/XL

#3894 Pin kubeflow/manifests and kubeflow/kubeflow commits on the v0.6-branch
  bootstrap/config/kfctl_existing_arrikto.0.6.yaml
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
  bootstrap/pkg/kfapp/coordinator/coordinator_test.go
Labels: approved, cla: yes, lgtm, size/M

#3841 Onboard new click 2 deploy
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
  bootstrap/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3824 Update the Kubeflow ROADMAP
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/L

#3871 use managed cert by default
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
  testing/kfctl/kf_is_ready_test.py
Labels: approved, cla: yes, lgtm, size/M

#3899 [CentralDashboard v2] Registration flow for basic auth
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/registration-page.css
  components/centraldashboard/public/components/registration-page.js
  components/centraldashboard/public/components/registration-page.pug
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/M

#3912 Don't set dummy values for project, email, or hostname in kfctl_gcp iap.yaml
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/M

#3926 Fix the default poddefaults add-gcp-secret in v0.6-branch
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
Labels: approved, cla: yes, lgtm, size/M

#3906 frontend update for v0.6
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#3934 Automated cherry pick of #3926: Fix the default poddefaults add-gcp-secret in v0.6-branch Cherry pick of #3926 on master. #3926: Fix the default poddefaults add-gcp-secret in v0.6-branch
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
Labels: approved, cla: yes, lgtm, size/M

#3941 Fix the error link description when using kfctl install.
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3928 extend wait time for endpoint test from 15min to 25 min
  testing/kfctl/endpoint_ready_test.py
Labels: approved, cla: yes, lgtm, size/XS

#3942 Automated cherry pick of #3941: Fix the error link description when using kfctl install. Cherry pick of #3941 on v0.6-branch. #3941: Fix the error link description when using kfctl install.
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3946 deployment/existing: add yanniszark as approver
  deployment/existing/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3919 Create a kfctl_gcp_iap file to use as an RC for 0.6.2
  bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml
Labels: approved, cla: yes, lgtm, size/L

#3885 kfctl: existing_arrikto: direct all 5556 traffic to Dex
  deployment/existing/auth_oidc/gateway.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3933 [CentralDashboard v2] Error surfacing for profile controller errors
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/utilities-mixin.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/M

#3955 Automated cherry pick of #3885: kfctl: existing_arrikto: direct all 5556 traffic to Dex Cherry pick of #3885 on v0.6-branch. #3885: kfctl: existing_arrikto: direct all 5556 traffic to Dex
  deployment/existing/auth_oidc/gateway.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3961 Fixed indentation in kfctl_existing_arrikto.0.6.yaml in v0.6-branch
  bootstrap/config/kfctl_existing_arrikto.0.6.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3877 Disable istio authorization in kfctl_k8s_istio
  bootstrap/config/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3969 Update repo commit.
  bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3971 [Centraldashboard v2] Env vars added to dockerfile
  components/centraldashboard/Dockerfile
  components/centraldashboard/app/server.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/S

#3884 Cherry pick 3857 to v0.6-branch
  bootstrap/config/kfctl_existing_arrikto.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3980 [Centraldashboard v2] Added a /debug route to dashboard for python e2e from Kubeflow
  components/centraldashboard/app/attach_user_middleware.ts
  components/centraldashboard/app/attach_user_middleware_test.ts
  components/centraldashboard/app/server.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/M

#3982 Cherry pick "always create default profile"; update configs on v0.6
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/XL

#3978 Update cofig file versions
  bootstrap/config/kfctl_existing_arrikto.yaml
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
  bootstrap/pkg/apis/apps/group.go
  bootstrap/v2/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/M

#3987 Revert "Update cofig file versions (#3978)"
  bootstrap/config/kfctl_existing_arrikto.yaml
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#3990 Cherry pick of #3899 #3933 #3971 #3980 on v0.6-branch.
  components/centraldashboard/Dockerfile
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/attach_user_middleware.ts
  components/centraldashboard/app/attach_user_middleware_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/registration-page.css
  components/centraldashboard/public/components/registration-page.js
  components/centraldashboard/public/components/registration-page.pug
  components/centraldashboard/public/components/utilities-mixin.js
  components/centraldashboard/webpack.config.js
Labels: approved, cla: yes, lgtm, size/L

#3992 [Centraldashboard v2] Correctly update Kubeflow Dashboard version from Kubeflow Resource
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/k8s_service_test.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/S

#3991 Create 0.6.2 versions of all config files.
  bootstrap/config/kfctl_existing_arrikto.0.6.2.yaml
  bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.2.yaml
  bootstrap/config/kfctl_k8s_istio.0.6.2.yaml
Labels: approved, cla: yes, lgtm, size/XL

#3993 Automated cherry pick of #3992 on v0.6-branch.
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/k8s_service_test.ts
Labels: approved, cla: yes, lgtm, size/S

#3994 Set userid prefix and header for IAP and pull in the latest fixes to the applications repo for GCP configs
  bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.2.yaml
Labels: approved, cla: yes, lgtm, size/S

#3904 kfctl: existing_arrikto: update config and enable multi-user identity awareness
  bootstrap/config/kfctl_existing_arrikto.yaml
  deployment/existing/auth_oidc/authservice.tmpl
  deployment/existing/auth_oidc/envoy-filter.yaml
  deployment/existing/istio/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/L

#3856 Culling of Idle Jupyter Notebooks
  components/notebook-controller/.gitignore
  components/notebook-controller/go.sum
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  components/notebook-controller/pkg/culler/culler.go
  components/notebook-controller/pkg/culler/culler_test.go
  components/notebook-controller/pkg/util/util.go
Labels: approved, cla: yes, lgtm, size/L

#4031 update config on v0.6 branch
  bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
  bootstrap/config/kfctl_k8s_istio.0.6.2.yaml
Labels: approved, cla: yes, lgtm, size/S

#3947 Remove C2D Defer IAP option for v0.6.x
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#4033 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4014 Update monitoring signals; Remove unused code
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/pkg/kfapp/kustomize/kustomize.go
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/L

#3953 Adding kfserving to Kfctl config
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
  testing/kfctl/kf_is_ready_test.py
Labels: approved, cla: yes, lgtm, size/L
