Repository kubeflow/kubeflow, pull requests merged in 2019-12, with the labels that each got.

#4518 Show namespace selector when choosing pipelines
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, size/S

#4539 Add metadata field to PodDefaults
  components/admission-webhook/main.go
  components/admission-webhook/main_test.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#4533 Add kubeflow labels into namespace by profile-controller
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/profile_controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#4548 Use v1alpha1 for poddefaults instead of v1beta1
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
Labels: approved, cla: yes, lgtm, size/XS

#4577 delete kubeflow/kubeflow/py
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
  py/kubeflow/kubeflow/ci/kfctl_go_build_test.py
  py/kubeflow/kubeflow/ci/kfctl_go_deploy_test.py
  py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Labels: approved, cla: yes, lgtm, size/XXL

#4556 jupyter-web-app: Use SubjectAccessReviews instead of KFAM
  components/jupyter-web-app/backend/Makefile
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
Labels: approved, cla: yes, lgtm, size/L

#4568 Make the Tekton CD pipeline for profile controller run on KF release cluster
  components/base/README.md
  components/base/kustomization.yaml
  components/base/namespace.yaml
  components/base/params.env
  components/base/persistent-volume-claim.yaml
  components/base/pipeline.yaml
  components/base/secrets.yaml
  components/base/service-account.yaml
  components/base/task.yaml
  components/profile-controller/ci/params.env
  components/profile-controller/ci/pipeline-run.yaml
  py/kubeflow/kubeflow/ci/rebuild-manifests.sh
Labels: approved, cla: yes, lgtm, size/L

#4593 Move the CD scripts and Tekton pipelines into kubeflow/testing
  components/admission-webhook/ci/kustomization.yaml
  components/admission-webhook/ci/params.env
  components/admission-webhook/ci/params.yaml
  components/admission-webhook/ci/pipeline-run.yaml
  components/base/README.md
  components/base/kustomization.yaml
  components/base/params.env
  components/base/params.env.save
  components/base/params.yaml
  components/base/pipeline-resource.yaml
  components/base/pipeline.yaml
  components/base/role-binding.yaml
  components/base/service-account.yaml
  components/base/task.yaml
  components/centraldashboard/ci/kustomization.yaml
  components/centraldashboard/ci/params.env
  components/centraldashboard/ci/params.yaml
  components/centraldashboard/ci/pipeline-run.yaml
  components/notebook-controller/ci/kustomization.yaml
  components/notebook-controller/ci/params.env
  components/notebook-controller/ci/params.yaml
  components/notebook-controller/ci/pipeline-run.yaml
  components/profile-controller/ci/kustomization.yaml
  components/profile-controller/ci/params.env
  components/profile-controller/ci/params.yaml
  components/profile-controller/ci/pipeline-run.yaml
  py/kubeflow/kubeflow/ci/rebuild-manifests.sh
Labels: approved, cla: yes, lgtm, size/XL
