Repository kubeflow/kubeflow, pull requests merged in 2019-01, with the labels that each got.

#2179 Add instructions for enabling the periodic tests on the new release branch
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/S

#2167 Add log timestamps, and do not wait for IAP if skipped IAP
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#2200 Add CUJs for multiuser kubeflow to the ROADMAP.
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/XS

#2199 Add retry to loading the sample job
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2198 Add log timestamps, and do not wait for IAP if skipped IAP
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, area/0.4.0, cla: yes, lgtm, size/S

#2202 Fix OWNERs file for gcp package.
  kubeflow/gcp/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2203 Cherrypick - Add retry to loading the sample job (#2199)
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2180 Add the TF 1.11 & TF 1.12 Jupyter images to the spawner drop down box.
  kubeflow/jupyter/ui/default/config.yaml
  kubeflow/jupyter/ui/rok/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2204 Tag and update katib for v0.4.0 release
  kubeflow/katib/prototypes/all.jsonnet
  releasing/add_image_shas.py
  releasing/add_katib_image_shas.sh
  releasing/image_tags.yaml
Labels: approved, cla: yes, lgtm, size/L

#2039 Remove Seldon Cluster Roles by default
  kubeflow/seldon/prototypes/core.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2113 Update tf-serving.libsonnet for replicas
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2191 Check the name of the deployment is < 25 characters on GCP
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2210 kfctl: add default zone if not specified
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2214 Cherrypick v0.4-branch: kfctl: add default zone if not specified (#2210)
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2215 add status tag to deployments_failure; exclude failure caused by quota or permission issue
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/M

#2217 publish v0.4.0 on web app
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#2216 Update kubebench tags for 0.4.0 release
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
  kubeflow/kubebench/prototypes/kubebench-operator.jsonnet
  releasing/image_tags.yaml
  releasing/update_components.sh
Labels: approved, cla: yes, lgtm, size/L

#2219 Add kubebench-dashboard package
  kubeflow/kubebench/kubebench-dashboard.libsonnet
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2218 simplify cloud shell; add instruction message
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#2220 Kubebench component update cherrypick
  kubeflow/kubebench/kubebench-dashboard.libsonnet
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
  kubeflow/kubebench/prototypes/kubebench-job.jsonnet
  kubeflow/kubebench/prototypes/kubebench-operator.jsonnet
  releasing/image_tags.yaml
  releasing/update_components.sh
Labels: approved, cla: yes, lgtm, size/L

#2228 Undefined name: from six.moves import xrange for line 50
  testing/test_tf_serving.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2221 Consistent formatting of prototype docs
  kubeflow/README.md
  kubeflow/application/prototypes/README.md
  kubeflow/argo/README.md
  kubeflow/chainer-job/README.md
  kubeflow/common/README.md
  kubeflow/credentials-pod-preset/README.md
  kubeflow/gcp/README.md
  kubeflow/jupyter/prototypes/README.md
  kubeflow/katib/README.md
  kubeflow/mpi-job/README.md
  kubeflow/mxnet-job/README.md
  kubeflow/new-package-stub/README.md
  kubeflow/nvidia-inference-server/README.md
  kubeflow/openmpi/README.md
  kubeflow/pachyderm/README.md
  kubeflow/profiles/prototypes/README.md
  kubeflow/pytorch-job/README.md
  kubeflow/tf-serving/README.md
  kubeflow/weaveflux/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2225 Adding pytorch operator to non gcp platforms
  scripts/gke/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/XS

#2231 Add HorizontalPodAutoscaler to TF-Serving component
  kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2224 Make ambassador number of replicas configurable #1112
  kubeflow/common/ambassador.libsonnet
  kubeflow/common/prototypes/ambassador.jsonnet
  kubeflow/common/tests/ambassador_test.jsonnet
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2235 set jupyterHubAuthenticator explicitly even for default values
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#2230 Sync up Kubeflow official docker images to user's registry
  releasing/sync_images.py
Labels: approved, cla: yes, lgtm, size/L

#2227 Undefined name: 'false' --> 'False'
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2237 Fix katib repo for the docker registry which doesn't support sub namespace
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/XS

#2238 argo s3 artifact repository configuration added
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/prototypes/argo.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2242 split debug case into separate docker file so we don't expose port unnecessary
  bootstrap/Dockerfile
  bootstrap/DockerfileDebug
Labels: approved, cla: yes, lgtm, size/S

#2245 update params following ksonnet v0.13.1; update image build file path
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/XS

#2246 Minor readability modifications in test_jsonnet.py
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2243 update jupyter hub with customized docker registry
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/XS

#2258 use golang:1.11.2 as base image; more ksonnet 0.13.1 API change
  bootstrap/Dockerfile
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/M

#2252 Update Pipeline version to v0.1.7
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2253 bump pipeline sdk version to 0.1.7
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2254 remove load sample job from pipeline config
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2154 fixes Change the application component to agree with kubernetes-sigs application CRD
  kubeflow/application/OWNERS
  kubeflow/application/README.md
  kubeflow/application/application.libsonnet
  kubeflow/application/application.schema
  kubeflow/application/docs/kubeflow_application.png
  kubeflow/application/prototypes/README.md
  kubeflow/application/prototypes/application.jsonnet
  kubeflow/application/sync-application.template
  kubeflow/application/tests/application_test.jsonnet
  kubeflow/common/util.libsonnet
  kubeflow/examples/prototypes/tensorboard.jsonnet
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/notebooks.libsonnet
  kubeflow/jupyter/tests/jupyter_test.jsonnet
  kubeflow/jupyter/tests/notebooks_test.jsonnet
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/pipeline-persistenceagent.libsonnet
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/util.sh
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#2265 remove ghost registries; make kf version env var on deploy app
  components/gcp-click-to-deploy/src/DeployForm.tsx
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/S

#2266 remove ghost registries from 0.4 branch
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2255 Branch v0.4.0 fix
  releasing/sync_images.py
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/L

#2251 Update image pull policy for pipeline
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/pipeline-persistenceagent.libsonnet
  kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
  kubeflow/pipeline/pipeline-ui.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2259 use istio 1.1
  dependencies/istio/README.md
  dependencies/istio/README.yaml
  dependencies/istio/install/README.md
  dependencies/istio/install/crds.yaml
  dependencies/istio/install/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2276 add missing pkg to registry
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2277 add missing pkg to registry
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2281 add gcp to registry
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2274 cherrypick changes to V0.4 branch
  components/tensorflow-notebook-image/Dockerfile
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/mysql.libsonnet
  kubeflow/pipeline/pipeline-apiserver.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2280 add gcp to registry
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2285 adjust param name for v0.3 compatibility
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#2278 Update kfctl to export PLATFORM and GKE_API_VERSION
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/XS

#2297 add neuromage to owner of pipeline registry
  kubeflow/pipeline/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2298 Bump ScheduledWorkflow CRD version to v1beta1
  kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2279 Update README for newer TRTIS releases
  kubeflow/nvidia-inference-server/README.md
  kubeflow/nvidia-inference-server/nvidia-inference-server.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2264 fixes "add jsonnet tests for all libsonnet files"
  kubeflow/application/tests/application_test.jsonnet
  kubeflow/argo/tests/argo_test.jsonnet
  kubeflow/common/tests/ambassador_test.jsonnet
  kubeflow/common/tests/centraldashboard_test.jsonnet
  kubeflow/common/tests/echo-server_test.jsonnet
  kubeflow/common/tests/spartakus_test.jsonnet
  kubeflow/common/testsuite.libsonnet
  kubeflow/examples/tests/tensorboard_test.jsonnet
  kubeflow/gcp/tests/cert-manager_test.jsonnet
  kubeflow/gcp/tests/cloud-endpoints_test.jsonnet
  kubeflow/gcp/tests/google-cloud-filestore-pv_test.jsonnet
  kubeflow/gcp/tests/iap_test.jsonnet
  kubeflow/gcp/tests/metric-collector_test.jsonnet
  kubeflow/gcp/tests/prometheus_test.jsonnet
  kubeflow/jupyter/tests/jupyter_test.jsonnet
  kubeflow/jupyter/tests/notebooks_test.jsonnet
  kubeflow/jupyter/tests/sync-notebook_test.jsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
  kubeflow/tensorboard/tests/tensorboard-aws_test.jsonnet
  kubeflow/tensorboard/tests/tensorboard-gcp_test.jsonnet
  kubeflow/tf-batch-predict/tests/tf-batch-predict_test.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#2301 update katib studyjob controller manifest
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2241 Added 'google-api-python-client' to JH images
  components/tensorflow-notebook-image/requirements.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2286 Add xgboost to image, fix credential-helper
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2305 Added context check before issuing delete
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2283 Define signer_email in main to remove flake8 F821 #2229
  docs/gke/iap_request.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2303 Do best practices for kfctl_test Argo workflow
  testing/workflows/app.yaml
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/util.libsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
  testing/workflows/lib/ksonnet-lib/v1.7.0/k.libsonnet
  testing/workflows/lib/ksonnet-lib/v1.7.0/k8s.libsonnet
  testing/workflows/lib/ksonnet-lib/v1.7.0/swagger.json
Labels: approved, cla: yes, lgtm, size/XXL

#2322 Clean up - Remove the load sample job
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2313 create secrets before checking for oauth env vars
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2324 GCP secrets cherrypick
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2328 add in-cluster nfs
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/nfs.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2335 add condition to create pv and pvc for kubeflow pipeline
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/mysql.libsonnet
  kubeflow/pipeline/nfs.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/storage.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2299 add pipeline team to the owner file
  OWNERS
Labels: approved, cla: yes, lgtm, size/S

#2262 basic auth service
  components/gatekeeper/Dockerfile
  components/gatekeeper/Makefile
  components/gatekeeper/README.md
  components/gatekeeper/auth/AuthServer.go
  components/gatekeeper/cmd/gatekeeper/main.go
  components/gatekeeper/cmd/gatekeeper/options/options.go
  components/gatekeeper/go.mod
  components/gatekeeper/go.sum
  kubeflow/common/basic-auth.libsonnet
  kubeflow/common/prototypes/basic-auth.jsonnet
Labels: approved, cla: yes, lgtm, size/XL

#2323 Create an E2E test for the Jupyter custom resource.
  kubeflow/jupyter/tests/conftest.py
  kubeflow/jupyter/tests/jupyter_test.py
  kubeflow/jupyter/tests/test_app/.gitignore
  kubeflow/jupyter/tests/test_app/README.md
  kubeflow/jupyter/tests/test_app/app.lock
  kubeflow/jupyter/tests/test_app/app.yaml
  kubeflow/jupyter/tests/test_app/components/jupyter.jsonnet
  kubeflow/jupyter/tests/test_app/components/params.libsonnet
  kubeflow/jupyter/tests/test_app/environments/base.libsonnet
  kubeflow/jupyter/tests/test_app/environments/default/globals.libsonnet
  kubeflow/jupyter/tests/test_app/environments/default/main.jsonnet
  kubeflow/jupyter/tests/test_app/environments/default/params.libsonnet
  kubeflow/jupyter/tests/test_app/environments/jlewi/globals.libsonnet
  kubeflow/jupyter/tests/test_app/environments/jlewi/main.jsonnet
  kubeflow/jupyter/tests/test_app/environments/jlewi/params.libsonnet
  testing/test_jsonnet.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2315 bootstrapper install istio
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/k8sUtil.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/bootstrap/app/util.go
  dependencies/istio/install/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2352 Add annotation to istio ingressgateway to enable IAP
  dependencies/istio/install/README.md
  dependencies/istio/install/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2346 update config and README for local test
  components/gcp-click-to-deploy/README.md
  components/gcp-click-to-deploy/app-config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2344 Improve the delete_deployment script.
  scripts/gke/delete_deployment.sh
  scripts/gke/delete_role_bindings.py
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/L
