Repository kubeflow/kubeflow, pull requests merged in 2019-05, with the labels that each got.

#3160 revert param true
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/common/prototypes/centraldashboard.jsonnet
  kubeflow/common/prototypes/echo-server.jsonnet
  kubeflow/examples/prototypes/tensorboard.jsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
  kubeflow/openvino/prototypes/openvino.jsonnet
  kubeflow/pipeline/pipeline.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
  kubeflow/tf-serving/prototypes/tf-serving-service.jsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3123 fix permission leak; give default admin permission for namespace owner
  components/profile-controller/pkg/apis/apis.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/profile_types.go
  components/profile-controller/pkg/controller/profile/profile_controller.go
Labels: approved, cla: yes, lgtm, size/L

#3121 Update Pipelines to version 0.1.18
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2993 docs: minor spelling tweaks
  ROADMAP.md
  components/centraldashboard/README.md
  components/jupyter-web-app/README.md
  components/jupyterhub/README.md
  docs_dev/kubeflow_deployment.md
  docs_dev/releasing.md
  kfctl/README.md
  kubeflow/profiles/prototypes/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, priority/p1, size/S

#3097 Add additional APIs to Central Dashboard roles
  kubeflow/common/centraldashboard.libsonnet
  kubeflow/common/tests/centraldashboard_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3170 default v0.5 version to v0.5-branch
  bootstrap/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/XS

#3142 change max interval for gcp Retry to 30 seconds
  bootstrap/go.sum
  bootstrap/pkg/kfapp/gcp/gcp.go
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2926 Enable iframed pages to communicate with Central Dashboard.
  components/centraldashboard/README.md
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/index_test.js
  components/centraldashboard/public/library.js
  components/centraldashboard/public/library_test.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3177 Set jupyter-web-app image to a stable image
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3187 Jupyter UI - Handle no Annotations
  components/jupyter-web-app/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
Labels: approved, cla: yes, lgtm, size/S

#3146 Update the job specs for the auto-updater.
  releasing/auto-update/update_job.yaml
  releasing/auto-update/update_job_cron.yaml
Labels: approved, cla: yes, lgtm, size/M

#3190 Centralize iframe link building and replace quick shortcuts links
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/iframe-link.js
  components/centraldashboard/public/components/iframe-link_test.js
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/utilities-mixin.js
  components/centraldashboard/public/components/utilities-mixin_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3195 Change to enforce CRLF -> LF changes
  components/centraldashboard/.gitattributes
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p2, size/XS

#3201 Update packages and fix TS tests to avoid compiler issues
  components/centraldashboard/app/k8s_service_test.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XXL

#3191 Restyles dashboard namespace selector to match UX specifications
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/namespace-selector_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3193 upgrade pipeline to 0.1.19
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3205 kfctl use 0.5.1
  bootstrap/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/XS

#3192 Fix pipeline viewer ISTIO rule
  kubeflow/pipeline/istio-service.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3161 Grant user-created notebook namespaced default edit permission
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
  kubeflow/jupyter/jupyter-web-app.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#3209 Delete the NFS directory.
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3183 quick fix for make build-kfctl on Macbook
  bootstrap/Makefile
Labels: approved, cla: yes, lgtm, size/S

#3215 Add kkasravi and gabrielwen to bootstrap OWNERS
  bootstrap/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3185 Extend the grace period for ksonnet.go to delete namespace
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/S

#3083 Basic auth login istio routing rule
  kubeflow/common/basic-auth.libsonnet
  kubeflow/common/prototypes/basic-auth.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3200 remove unused katib rbac
  kubeflow/katib/OWNERS
  kubeflow/katib/vizier.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3189 kfctl - Makefile and Dockerfile enhancements
  bootstrap/Dockerfile
  bootstrap/Makefile
Labels: approved, cla: yes, lgtm, size/S

#3224 fix invalid access to request body.
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
Labels: approved, cla: yes, lgtm, size/XS

#3067 kfctl (golang) add bash/zsh completion
  bootstrap/cmd/kfctl/cmd/apply.go
  bootstrap/cmd/kfctl/cmd/completion.go
  bootstrap/cmd/kfctl/cmd/delete.go
  bootstrap/cmd/kfctl/cmd/generate.go
Labels: approved, cla: yes, lgtm, size/M

#3229 Fix webhook to read updated secret
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/webhook.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3233 Update Kflogin page title
  components/kflogin/public/index.html
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3238 Automated cherry pick of #3229: fix for #3227 Cherry pick of #3229 on v0.5-branch. #3229: fix for #3227
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/webhook.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3235 enable Istio Injection in user-created namespace; notebook and Istio integration
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  dependencies/istio/install/README.md
  dependencies/istio/install/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/S

#3231 Prune root OWNERs file to better assign reviews.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3196 Sidebar updated to spec (Active bar on left)
  components/centraldashboard/public/components/iframe-link.js
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/M

#3202 Adds generalized webhook
  bootstrap/config/gcp_prototype.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  components/admission-webhook/.gitignore
  components/admission-webhook/Dockerfile
  components/admission-webhook/Makefile
  components/admission-webhook/README.md
  components/admission-webhook/config.go
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
  components/admission-webhook/pkg/apis/addtoscheme_settings_v1alpha1.go
  components/admission-webhook/pkg/apis/apis.go
  components/admission-webhook/pkg/apis/settings/group.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/doc.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/podpreset_types.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/podpreset_types_test.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/register.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/v1alpha1_suite_test.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/zz_generated.deepcopy.go
  components/admission-webhook/scheme.go
  components/gcp-admission-webhook/README.md
  components/gcp-admission-webhook/go.mod
  components/gcp-admission-webhook/go.sum
  components/gcp-admission-webhook/main.go
  components/gcp-click-to-deploy/app-config.yaml
  components/gcp-click-to-deploy/src/DeployForm.tsx
  kubeflow/admission-webhook/OWNERS
  kubeflow/admission-webhook/README.md
  kubeflow/admission-webhook/create_ca.sh
  kubeflow/admission-webhook/parts.yaml
  kubeflow/admission-webhook/podpreset-crd.libsonnet
  kubeflow/admission-webhook/prototypes/podpreset-crd.jsonnet
  kubeflow/admission-webhook/prototypes/webhook.jsonnet
  kubeflow/admission-webhook/webhook.libsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#3217 upgrade pipeline to 0.1.19
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3241 Moves view tabs from header to content pane
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3258 Fix PRs created by auto-updater so that CLA checks pass.
  releasing/auto-update/update_job.yaml
  releasing/auto-update/update_job_cron.yaml
Labels: approved, cla: yes, lgtm, size/S

#3176 Add a README with the redoc link for the kfctl API.
  bootstrap/api/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3253 Deploy JWT policy with ingress
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/prototypes/iap-ingress.jsonnet
  kubeflow/gcp/tests/iap_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3262 update istio to the latest 1.1.6
  dependencies/istio/install/README.md
  dependencies/istio/install/crds.yaml
  dependencies/istio/install/istio-noauth.yaml
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#3260 Turn on the stale probot.
  .github/stale.yml
Labels: approved, cla: yes, lgtm, size/S

#3270 Handle imageType error when readOnly is true.
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
Labels: approved, cla: yes, lgtm, size/XS

#3211 Add MiniKF to the central dashboard
  ROADMAP.md
  components/centraldashboard/public/components/dashboard-view.js
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3134 3032 statefulset service name
  kubeflow/admission-webhook/webhook.libsonnet
  kubeflow/gcp/iap.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3263 update kfp version
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3279 disable tests for pipelines branch
  prow_config.yaml
Labels: approved, cla: yes, size/L

#3269 Don't create the PR or push changes if the PR already exists.
  py/kubeflow/kubeflow/ci/update_jupyter_web_app.py
Labels: approved, cla: yes, lgtm, size/M

#3281 cherrypick Pipelines v0.1.20
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3255 Add permssion for ml-pipeline-ui account to access pod resources
  kubeflow/pipeline/pipeline-ui.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3283 Fix overlay for app.yaml
  bootstrap/config/base/kfctl_default.yaml
  bootstrap/config/overlays/basic_auth/kfctl_default-patch.yaml
  bootstrap/config/overlays/basic_auth/kfctl_default.yaml
  bootstrap/config/overlays/gcp/kfctl_default-patch.yaml
  bootstrap/config/overlays/gcp/kfctl_default.yaml
  bootstrap/config/overlays/ksonnet/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#3169 Fix no response when click Spawn button on creating notebook servers.
  components/jupyter-web-app/releaser/components/params.libsonnet
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3272 Add AWS ALB OIDC support
  kubeflow/aws/istio-ingress.libsonnet
  kubeflow/aws/prototypes/istio-ingress.jsonnet
  kubeflow/aws/tests/istio-ingress_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3293 Cherry-pick pipeline-runner ClusterRole changes (#2556) to pipelines branch
  kubeflow/pipeline/pipeline-apiserver.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3291 Allow defining kubeflow repo in download script
  scripts/download.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3268 Need to set storageClassName of the persistent volume used with cloud filestore
  kubeflow/gcp/google-cloud-filestore-pv.libsonnet
  kubeflow/gcp/tests/google-cloud-filestore-pv_test.jsonnet
  testing/kfctl/kf_is_ready_test.py
Labels: approved, cla: yes, lgtm, size/S

#3289 #3259 AWS: Disable istio-injection by default in kubeflow ns
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3298 Patch JWT audiences and fix ingressgateway
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/jwt-policy-template.yaml
  kubeflow/gcp/setup_backend.sh
  kubeflow/gcp/update_backend.sh
Labels: approved, cla: yes, lgtm, size/M

#3171 define kubeflow Access Management API
  components/access-management/README.md
  components/access-management/api/swagger.yaml
Labels: approved, cla: yes, lgtm, size/L

#3302 Use empty list when OIDC not being used
  kubeflow/aws/istio-ingress.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3280 Upgrade eksctl api version to v1alpha5
  deployment/aws/infra_configs/cluster_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3292 Allow defining VPC id and region for AWS alb-ingress-controller
  kubeflow/aws/aws-alb-ingress-controller.libsonnet
  kubeflow/aws/prototypes/aws-alb-ingress-controller.jsonnet
  kubeflow/aws/tests/aws-alb-ingress-controller_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3304 iap-ingress is missing parameters used in ksonnet
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/XS

#3314 Add command field for defaultMetricsColloctor deployment
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3245 Integrates notebook-controller and jupyter-web-app with admission-webhook
  components/jupyter-web-app/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/output.yaml
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/admission-webhook/podpreset-crd.libsonnet
  kubeflow/admission-webhook/prototypes/podpreset-crd.jsonnet
  kubeflow/admission-webhook/webhook.libsonnet
  kubeflow/jupyter/jupyter-web-app.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  testing/kfctl/kf_is_ready_test.py
Labels: approved, cla: yes, lgtm, size/L

#3321 Fix manifest rewritten in error during apply
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/XS

#3322 Adding support for Pytorch v1 api
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#3197 [CentralDashboard] Column View for Dashboard, Platform links card, user image added to spec
  components/centraldashboard/app/api.ts
  components/centraldashboard/make-win.ps1
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/assets/gcp-logo.png
  components/centraldashboard/public/assets/icons/ic_bolt.svg
  components/centraldashboard/public/components/activity-view.js
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/dashboard-view_test.js
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/resources/cloud-platform-data.js
  components/centraldashboard/public/components/resources/kubeflow-icons.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/L

#3320 Renamed PodPreset CRD to PodDefault
  components/admission-webhook/README.md
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types_test.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/zz_generated.deepcopy.go
  components/jupyter-web-app/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/output.yaml
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/admission-webhook/prototypes/webhook.jsonnet
  kubeflow/admission-webhook/webhook.libsonnet
  kubeflow/jupyter/jupyter-web-app.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#3307 Remove kfctl-go-iap workflow test
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#3325 allow commonlabels, commonannotations to be copied to parent kustomization.yaml
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/S

#3327 Update tf-training and tests for TFJob v1
  kubeflow/examples/prototypes/tf-job-simple-v1.jsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
  testing/tf_job_simple_test.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#3328 Add admission-webhook to kfctl default components
  bootstrap/config/base/kfctl_default.yaml
  bootstrap/config/default.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
Labels: approved, cla: yes, lgtm, size/S

#3069 mini fix for kfctl show
  bootstrap/cmd/kfctl/README.md
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/cmd/kfctl/cmd/root.go
  bootstrap/cmd/kfctl/cmd/show.go
  bootstrap/cmd/kfctl/cmd/version.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/M

#3335 Upgraded Argo to v2.3.0
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/argo/tests/argo_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#3297 User Info badge and API Added
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/public/assets/anon-user.png
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3338 Merge deprecated kfctl-test with kfctl-go-test
  prow_config.yaml
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#3350 Fix pvc overlays
  bootstrap/config/overlays/kustomize/kfctl_default.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/M

#3349 Cherry-picking - Upgraded Argo to v2.3.0 (#3335)
  kubeflow/argo/prototypes/argo.jsonnet
  kubeflow/argo/tests/argo_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#3251 Dashboard metrics backend with Stackdriver.
  components/centraldashboard/Dockerfile
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/k8s_service_test.ts
  components/centraldashboard/app/metrics_service.ts
  components/centraldashboard/app/metrics_service_factory.ts
  components/centraldashboard/app/metrics_service_factory_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/app/stackdriver_metrics_service.ts
  components/centraldashboard/app/stackdriver_metrics_service_test.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/tsconfig.json
  components/centraldashboard/types/@google-cloud/monitoring/index.d.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XXL

#3244 Jupyter Web App Integration with Central-Dashboard SDK
  components/jupyter-web-app/Makefile
  components/jupyter-web-app/kubeflow_jupyter/default/templates/add_notebook.html
  components/jupyter-web-app/kubeflow_jupyter/default/templates/layout.html
  components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
  components/jupyter-web-app/kubeflow_jupyter/rok/templates/add_notebook.html
  components/jupyter-web-app/kubeflow_jupyter/rok/templates/notebooks.html
  components/jupyter-web-app/output.yaml
Labels: approved, area/centraldashboard, area/front-end, area/jupyter, cla: yes, lgtm, size/XXL

#3345 SVG Iconset Dynamic Generation from Icons Assets
  components/centraldashboard/public/assets/icons/bolt.svg
  components/centraldashboard/public/assets/logo.svg
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/resources/kubeflow-icons.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/M

#3352 Update notebooks-contriller image
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3360 MINIO PVC names
  bootstrap/config/overlays/kustomize/kfctl_default.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3356 Address UX feedback tweaks.
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/iframe-link.js
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/resources/cloud-platform-data.js
  components/centraldashboard/public/styles.css
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XXL

#3369 Update pipeline image version to v0.1.21
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3326 Resource charts for CPU Utilization
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/dashboard-view_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/resource-chart.js
  components/centraldashboard/public/components/resource-chart_test.js
  components/centraldashboard/public/components/resources/cloud-platform-data.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XL

#3372 Collapse sidebar threshold updated from 900px to 1270px
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XS

#3377 Adds recent Jupyter Notebooks card to Central Dashboard
  components/centraldashboard/public/components/card-styles.js
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/iframe-link.js
  components/centraldashboard/public/components/iframe-link_test.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/notebooks-card.js
  components/centraldashboard/public/components/notebooks-card_test.js
  components/centraldashboard/public/components/resource-chart.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XL

#3374 Cherrypick: update pipeline image version to v0.1.21 (#3369)
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S
