Repository kubeflow/kubeflow, pull requests merged in 2019-11, with the labels that each got.

#4444 Store secrets using EnvSource for basic auth
  bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
  bootstrap/pkg/apis/apps/configconverters/testdata/v1beta1.yaml
  bootstrap/pkg/apis/apps/configconverters/v1beta1.go
  bootstrap/pkg/apis/apps/configconverters/v1beta1_test.go
  bootstrap/pkg/apis/apps/kfconfig/types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/M

#4445 Automated cherry pick of #4443: Add a message after kfctl apply succeeds
  bootstrap/cmd/kfctl/cmd/apply.go
Labels: approved, cla: yes, lgtm, size/XS

#4438 Add arm64 support for controllers
  components/notebook-controller/Dockerfile
  components/profile-controller/Dockerfile
  components/tensorboard-controller/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4452 Automated cherry pick of #4417: Fix: error isn't logged before retry Cherry pick of #4417 on v0.7-branch. #4417: Fix: error isn't logged before retry
  bootstrap/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/XS

#4448 Automated cherry pick of #4444: Store secrets using EnvSource for basic auth
  bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
  bootstrap/pkg/apis/apps/configconverters/testdata/v1beta1.yaml
  bootstrap/pkg/apis/apps/configconverters/v1beta1.go
  bootstrap/pkg/apis/apps/configconverters/v1beta1_test.go
  bootstrap/pkg/apis/apps/kfconfig/types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/M

#4447 Endpoint basic auth test
  prow_config.yaml
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
  py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
  testing/gcp_util.py
  testing/kfctl/endpoint_ready_test.py
Labels: approved, cla: yes, lgtm, size/L

#4422 Add arm64 support for centraldashboard and Fix chromium@edge version cannot start bug
  components/centraldashboard/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4456 pass app_path as args
  py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Labels: approved, cla: yes, lgtm, size/XS

#4458 remove xfail for endpoint_is_ready test
  testing/kfctl/endpoint_ready_test.py
Labels: approved, cla: yes, lgtm, size/XS

#4405 Kfctl e2e workflow should check out main repo by default
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
Labels: approved, cla: yes, lgtm, size/M

#4454 Use replaceState instead of pushState to track iframe navigation
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, size/XS

#4459 Refactor kfctl_go_test_utils codes
  prow_config.yaml
  py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Labels: approved, cla: yes, lgtm, size/M

#4470 fix json field names
  testing/kfctl/endpoint_ready_test.py
Labels: approved, cla: yes, lgtm, size/XS

#4387 run 2nd apply test for perdiodic
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
  testing/kfctl/kfctl_second_apply.py
Labels: approved, cla: yes, lgtm, size/M

#4475 catch http connection error when endpoint is not ready
  testing/gcp_util.py
Labels: approved, cla: yes, lgtm, size/M

#4478 Fix a minor bug in the jupyter GPU image name
  components/tensorflow-notebook-image/versions/1.14.0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/XS

#4479 Fix var name error
  testing/gcp_util.py
Labels: approved, cla: yes, lgtm, size/XS

#4476 update test config to rm kfctl tests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/L

#4493 Fix KFCTL e2e test build path
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
  py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Labels: approved, cla: yes, lgtm, size/M

#4489 Added website versioning steps to the release procedures
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/M

#4494 Update router/kfctlClient/kfctlServer API
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/cmd/bootstrap/app/kfctlServer_test.go
  bootstrap/cmd/bootstrap/app/kfctlUtil.go
  bootstrap/cmd/bootstrap/app/kfctl_test.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/kfctlClient/main.go
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/XXL

#4139 [3772][notebook-controller] Reissue pod and sts events as notebook events
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4522 update dockerfile & makefile
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/kfctlServer.go
Labels: approved, cla: yes, lgtm, size/M

#4487 C2D UI: add option for v0.7 and deprecate v0.5
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
Labels: approved, cla: yes, lgtm, size/L

#4526 Add a github action to add/remove issues from the needs triage Kanban board
  .github/workflows/triage_issues.yaml
Labels: approved, cla: yes, lgtm, size/S

#4531 Fix the GitHub action workflow to add issue triage issues
  .github/workflows/triage_issues.yaml
Labels: approved, cla: yes, lgtm, size/XS
