Repository kubeflow/kubeflow, pull requests merged in 2019-07, with the labels that each got.

#3587 Update pipeline SDK version
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#3582 Fix SyncCache and define errors to indicate Secret not found.
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#3581 Add a list of Applications to KfDef.
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
Labels: approved, cla: yes, lgtm, size/S

#3569 Add Metadata UI links to Central Dashboard
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/main-page.js
Labels: approved, area/centraldashboard, cla: yes, lgtm, size/S

#3538 kfctl: add platform existing
  bootstrap/.dockerignore
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/config/kfctl_existing_arrikto.0.6.yaml
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go
  bootstrap/v2/pkg/utils/k8utils.go
  deployment/existing/auth_oidc/authservice.tmpl
  deployment/existing/auth_oidc/dex.tmpl
  deployment/existing/auth_oidc/envoy-filter.yaml
  deployment/existing/auth_oidc/gateway.yaml
  deployment/existing/istio/crds.yaml
  deployment/existing/istio/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#3595 Some error and logging utilities.
  bootstrap/pkg/utils/logging.go
  bootstrap/v2/pkg/apis/kferrors.go
  bootstrap/v2/pkg/utils/logging.go
Labels: approved, cla: yes, lgtm, size/M

#3577 Refactor gcp KfApp to be more of a plugin and support click to deploy.
  bootstrap/cmd/bootstrap/app/kfctlUtil.go
  bootstrap/go.mod
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_plugin.go
  bootstrap/pkg/kfapp/gcp/gcp_plugin_test.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
  bootstrap/pkg/kfapp/gcp/testdata/doc.go
  bootstrap/pkg/kfapp/gcp/testdata/kfctl_gcp.yaml
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XXL

#3598 kfctl: existing_arrikto: add self-signed https certificates
  bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go
  bootstrap/v2/pkg/kfapp/existing_arrikto/existing_test.go
  deployment/existing/auth_oidc/authservice.tmpl
  deployment/existing/auth_oidc/dex.tmpl
  deployment/existing/auth_oidc/envoy-filter.yaml
  deployment/existing/auth_oidc/gateway.yaml
  deployment/existing/istio/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/L

#3506 kfctl: OWNERS: add yanniszark
  bootstrap/OWNERS
  bootstrap/cmd/kfctl/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3588 kustomize should support injecting the K8s restconfig.
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3533 Add monitoring.viewer role to enable dashboard utilzation graphs
  deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3600 Use manifest master for tests.
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/XS

#3590 Add metadata service as a component of Kubeflow
  bootstrap/config/base/kfctl_default.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/config/overlays/istio/kfctl_default.yaml
  testing/kfctl/kf_is_ready_test.py
Labels: approved, cla: yes, lgtm, size/M

#3537 jupyter-web-app: Integrate with PodDefaults
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml
  components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/rok/rok.py
  components/jupyter-web-app/backend/main.py
  components/jupyter-web-app/frontend/src/app/app.module.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-configurations/form-configurations.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/form-configurations/form-configurations.component.scss
  components/jupyter-web-app/frontend/src/app/resource-form/form-configurations/form-configurations.component.spec.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-configurations/form-configurations.component.ts
  components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.ts
  components/jupyter-web-app/frontend/src/app/services/kubernetes.service.ts
  components/jupyter-web-app/frontend/src/app/services/namespace.service.ts
  components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-resource-form.component.html
  components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-resource-form.component.ts
  components/jupyter-web-app/frontend/src/app/utils/common.ts
  components/jupyter-web-app/frontend/src/app/utils/types.ts
  components/jupyter-web-app/frontend/src/styles.scss
Labels: approved, cla: yes, lgtm, size/XL

#3601 keep manifest in kfctl directory as kustomize pkg
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize_test.go
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/cluster-role-binding.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/cluster-role.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/config-map.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/deployment.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/kustomization.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/params.env
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/service-account.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/service.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/expected/kustomization.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/application.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#3631 make basic auth work with kustomize
  bootstrap/config/overlays/basic_auth/kfctl_default.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#3630 jupyter-web-app: Use kfam to check if user is authorized
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
Labels: approved, cla: yes, lgtm, size/L

#3634 Sync06
  bootstrap/config/overlays/basic_auth/kfctl_default.yaml
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize_test.go
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/cluster-role-binding.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/cluster-role.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/config-map.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/deployment.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/kustomization.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/params.env
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/service-account.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/service.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/expected/kustomization.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/application.yaml
  bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#3647 jupyter-web-app: backend: fix default storage class detection
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
Labels: approved, cla: yes, lgtm, size/S

#3594 Add helper methods to set application parameters and define conditions.
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#2354 Fix minikube setup script's df inference
  scripts/setup-minikube.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3608 Add Seldon to kfctl config
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
Labels: approved, cla: yes, lgtm, priority/p0, size/XS

#3651 coordinator should load packagemanagers and platform KfApps once at construction time
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/coordinator/coordinator_test.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/L

#3664 Use the new istio pkg in manifest
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/overlays/istio/kfctl_default.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3564 Removing unnecessary rbac authorization for pytorch operator
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3565 Removing unnecessary rbac authorization for tf operator
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3622 Correct View All Pipelines link
  components/centraldashboard/public/components/dashboard-view.js
Labels: approved, cla: yes, lgtm, size/XS

#3668 kustomize.go should use KfDef.Applications
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize_test.go
Labels: approved, cla: yes, lgtm, size/L

#3669 gcp should support KfDef.Application
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
  bootstrap/pkg/kfapp/gcp/util.go
Labels: approved, cla: yes, lgtm, size/L

#3680 update dashboard test API
  releasing/releaser/app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3682 fix auto release for central dashboard
  releasing/releaser/app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3663 Add kfctl config for k8s only
  bootstrap/config/kfctl_k8s_istio.yaml
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3675 turn off Istio isolation for basic auth
  bootstrap/config/overlays/istio/kfctl_default.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#3692 set kfctl default version to v0.6
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/coordinator/coordinator_test.go
  bootstrap/v2/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/S

#3621 Create a module for managing google cloud source repos.
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/sourceRepos.go
  bootstrap/cmd/bootstrap/app/sourceRepos_test.go
  bootstrap/cmd/bootstrap/app/util.go
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/L

#3652 KfctlServer should take KfDef as the request payload.
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/cmd/bootstrap/app/kfctlServer_test.go
  bootstrap/cmd/bootstrap/app/kfctlUtil.go
  bootstrap/cmd/bootstrap/app/kfctl_test.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/bootstrap/app/sourceRepos_test.go
  bootstrap/cmd/bootstrap/app/tokenSource.go
  bootstrap/cmd/bootstrap/app/util.go
Labels: approved, cla: yes, lgtm, size/XXL

#3714 Add metadata istio overlay into bootstrap configs
  bootstrap/config/kfctl_existing_arrikto.0.6.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#3717 Automated cherry pick of #3714 upstream v0.6 branch
  bootstrap/config/kfctl_existing_arrikto.0.6.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#3693 Create PodDefault if platform is GCP
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
  bootstrap/v2/pkg/apis/apps/group.go
  bootstrap/v2/pkg/apis/apps/group_test.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3732 Fix metadata component name
  bootstrap/config/overlays/istio/kfctl_default.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3729 Backend changes for Central Dashboard to support multi-user isolation.
  components/centraldashboard/app/.jasmine.json
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/attach_user_middleware.ts
  components/centraldashboard/app/attach_user_middleware_test.ts
  components/centraldashboard/app/clients/profile_controller.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/namespace-selector_test.js
  components/centraldashboard/tsconfig.json
  components/centraldashboard/tslint.json
  components/centraldashboard/types/index.d.ts
Labels: approved, cla: yes, lgtm, size/XXL

#3734 Automated cherry pick of #3732 upstream v0.6 branch
  bootstrap/config/overlays/istio/kfctl_default.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3741 Automated cherry pick of #3693: Create PodDefault if platform is GCP
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
  bootstrap/v2/pkg/apis/apps/group.go
  bootstrap/v2/pkg/apis/apps/group_test.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3742 Paper-menu-dropdown is aligned left
  components/centraldashboard/public/components/namespace-selector.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/XS

#3385 Don't mutate the go installation during build.
  bootstrap/Makefile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3743 Paper-menu-dropdown is aligned left
  components/centraldashboard/public/components/namespace-selector.js
Labels: approved, cla: yes, lgtm, size/XS

#3384 Clarify the dependency build step
  bootstrap/developer_guide.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3745 Change default version for v0.6.1-rc.1 release
  bootstrap/pkg/apis/apps/group.go
  bootstrap/v2/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/XS

#3695 Add AWS kfctl(golang) support and 0.6 support
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/config/kfctl_aws.yaml
  bootstrap/config/kfctl_aws_cognito.yaml
  bootstrap/config/overlays/aws/kfctl_default.yaml
  bootstrap/config/overlays/aws/kustomization.yaml
  bootstrap/go.mod
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/aws/aws.go
  bootstrap/pkg/kfapp/aws/aws_plugin.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/v2/pkg/apis/apps/group.go
  bootstrap/v2/pkg/utils/awsutil.go
  deployment/aws/infra_configs/cluster_config.yaml
  deployment/aws/infra_configs/cluster_features.sh
  deployment/aws/infra_configs/cluster_features.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#3763 Automated cherry pick of #3695 upstream v0.6 branch
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/config/kfctl_aws.yaml
  bootstrap/config/kfctl_aws_cognito.yaml
  bootstrap/config/overlays/aws/kfctl_default.yaml
  bootstrap/config/overlays/aws/kustomization.yaml
  bootstrap/go.mod
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/aws/aws.go
  bootstrap/pkg/kfapp/aws/aws_plugin.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/v2/pkg/apis/apps/group.go
  bootstrap/v2/pkg/utils/awsutil.go
  deployment/aws/infra_configs/cluster_config.yaml
  deployment/aws/infra_configs/cluster_features.sh
  deployment/aws/infra_configs/cluster_features.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#3769 Update v0.6.1 rc2 kfctl default version
  bootstrap/pkg/apis/apps/group.go
  bootstrap/v2/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/XS

#3697 Support gcp workload identity
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_plugin.go
  bootstrap/pkg/kfapp/gcp/gcp_test.go
  bootstrap/v2/pkg/utils/iamutils.go
  bootstrap/v2/pkg/utils/iamutils_test.go
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/L

#3751 add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/questions.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3718 use --config for testing kfctl
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  prow_config.yaml
  testing/kfctl/conftest.py
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/XL

#3782 Update default v0.6.1 versions
  bootstrap/pkg/apis/apps/group.go
  bootstrap/v2/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/XS

#3779 Add gcp-credential and cert overlay
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/S

#3503 [Central Dashboard v2] Multi-User Isolation PR
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/.eslintrc.json
  components/centraldashboard/public/assets/icons/namespace.svg
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/registration-page.css
  components/centraldashboard/public/components/registration-page.js
  components/centraldashboard/public/components/registration-page.pug
  components/centraldashboard/public/components/resources/animated-checkmark.js
  components/centraldashboard/public/components/resources/carousel-indicator.js
  components/centraldashboard/public/components/resources/paper-chip.js
  components/centraldashboard/public/components/utilities-mixin.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XL
