Repository kubeflow/kubeflow, pull requests merged in 2019-06, with the labels that each got.

#3378 Adds prometheus annotation and port configurations for tf-operator
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3319 Add details to "conditions" in notebook status
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
  kubeflow/jupyter/tests/jupyter_test.py
  kubeflow/jupyter/tests/test_app/components/jupyter.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3301 added aws link to dashboard, fixed typo, corrected link
  components/centraldashboard/public/components/dashboard-view.js
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3393 Fix notebook controller for virtual service
  bootstrap/config/base/kfctl_default.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/overlays/basic_auth/kfctl_default.yaml
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#3351 Improve admission-webhook to use Job (instead of Statefulset) to exchange TLS certificate
  kubeflow/admission-webhook/create_ca.sh
  kubeflow/admission-webhook/webhook.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3379 Adds recent Pipelines cards for Definitions and Runs.
  components/centraldashboard/public/assets/icons/pipeline.svg
  components/centraldashboard/public/components/activities-list.js
  components/centraldashboard/public/components/card-styles.js
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/notebooks-card.js
  components/centraldashboard/public/components/pipelines-card.js
  components/centraldashboard/public/components/pipelines-card_test.js
  components/centraldashboard/public/components/resource-chart.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/XL

#3390 fix log level
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#3402 Fix multiple iframe-link behaviors.
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/public/components/iframe-link.js
  components/centraldashboard/public/components/iframe-link_test.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3341 Upgraded scripts to Argo v2.3.0
  scripts/gke/gcb_copy_images.jsonnet
  scripts/gke/use_gcr_for_all_images.sh
Labels: approved, cla: yes, lgtm, size/S

#3342 Minor update for kfctl.
  bootstrap/cmd/kfctl/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3308 Fix notebook example
  kubeflow/jupyter/prototypes/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3008 iam_patch.py should detect errors
  scripts/gke/iam_patch.py
Labels: approved, cla: yes, lgtm, size/XS

#3412 Miscellaneous improvements from team feedback
  components/centraldashboard/public/components/card-styles.js
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/resource-chart.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#3408 Adds new service config for tf-operator
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3423 Contrib notebook refresh
  components/contrib/kaggle-notebook-image/Dockerfile
  components/contrib/kaggle-notebook-image/README.md
  components/contrib/rapidsai-notebook-image/Dockerfile
  components/contrib/rapidsai-notebook-image/README.md
Labels: approved, cla: yes, lgtm, size/M

#3424 Removed TF-Job link from Central-Dashoard
  components/centraldashboard/public/components/main-page.js
Labels: approved, area/front-end, cla: yes, lgtm, priority/p2, size/XS

#3404 Make basic auth works with ISTIO - JSONNET
  bootstrap/config/overlays/basic_auth/kfctl_default.yaml
  kubeflow/common/ambassador.libsonnet
  kubeflow/common/prototypes/ambassador.jsonnet
  kubeflow/common/tests/ambassador_test.jsonnet
  kubeflow/gcp/basic-auth-ingress.libsonnet
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/prototypes/basic-auth-ingress.jsonnet
  kubeflow/gcp/setup_backend.sh
  kubeflow/gcp/update_backend.sh
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/L

#3420 Consolidate initial state retrieval and retrieve user email from IAP headers
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/namespace-selector_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#3427 Fixes Jupyter Web App SDK namespace change doesn't trigger view update
  components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
  components/jupyter-web-app/kubeflow_jupyter/rok/templates/notebooks.html
Labels: approved, area/centraldashboard, area/front-end, area/jupyter, cla: yes, lgtm, priority/p0, size/XS

#3089 Add emacs package to the Jupyter Image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3340 templatize istio k8s version for aws
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3435 fix typo in testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, area/kfctl, cla: yes, lgtm, size/XS

#3438 Add OWNERS file under aws components
  deployment/aws/OWNERS
  scripts/aws/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3432 Adds service to pytorch deployment
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3443 fix aws provider istio version
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3444 cherry-pick aws istio fix
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3445 Adding gang scheduling to params
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#3447 Fix a small bug in gcp.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#3365 kfctl: fix minor bug in Sprintf
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/XS

#3457 Automated cherry pick of #3438: Add OWNERS file under aws components
  deployment/aws/OWNERS
  scripts/aws/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3461 Automated cherry pick of #3280: Upgrade eksctl api to v1alpha5
  deployment/aws/infra_configs/cluster_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3455 kfctl: fix Makefile fmt,vet targets and refactor Dockerfile to use make
  bootstrap/.dockerignore
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/k8sUtil.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/server_test.go
  bootstrap/config/zz_generated.deepcopy.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/v2/pkg/apis/apps/group.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3415 Cherry-picking - iam_patch.py should detect errors (#3008)
  scripts/gke/iam_patch.py
Labels: approved, cla: yes, lgtm, size/XS

#3386 kfam backend
  components/access-management/Dockerfile
  components/access-management/Makefile
  components/access-management/api/swagger.yaml
  components/access-management/example/binding.json
  components/access-management/example/profile.json
  components/access-management/go.mod
  components/access-management/go.sum
  components/access-management/kfam/README.md
  components/access-management/kfam/api_default.go
  components/access-management/kfam/bindings.go
  components/access-management/kfam/logger.go
  components/access-management/kfam/model_binding.go
  components/access-management/kfam/model_binding_list.go
  components/access-management/kfam/profiles.go
  components/access-management/kfam/routers.go
  components/access-management/kfam/utils.go
  components/access-management/main.go
  components/access-management/pkg/apis/istiorbac/v1alpha1/register.go
  components/access-management/pkg/apis/kubeflow/v1alpha1/register.go
  components/profile-controller/pkg/controller/profile/profile_controller.go
  kubeflow/profiles/profiles.libsonnet
  kubeflow/profiles/prototypes/profiles.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#3460 Automated cherry pick of #3084: Update OWNERS file and make ingress configurable
  kubeflow/aws/OWNERS
  scripts/aws/util.sh
Labels: approved, cla: yes, lgtm, size/XS

#3474 fix pre-submit
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/XS

#3473 add profile and kfam API to kfctl default component
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3463 Add katib v1alpha2
  bootstrap/config/base/kfctl_default.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/config/overlays/istio/kfctl_default.yaml
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_go_test.py
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, size/M

#3480 Removing util dependency in operator package
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#3483 make kustomize the default
  bootstrap/cmd/kfctl/cmd/init.go
Labels: approved, cla: yes, lgtm, size/XS

#3311 add kkasravi to OWNERS
  components/notebook-controller/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3486 Fix error if gang scheduling not enabled
  kubeflow/pytorch-job/pytorch-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3493 pin manifests to a known good version
  testing/kfctl/kfctl_go_test.py
Labels: approved, area/kfctl, cla: yes, lgtm, priority/p0, size/XS

#3470 Add admission-webhook components to kustomize default components
  bootstrap/config/base/kfctl_default.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3429 Enable applications
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/overlays/application/kfctl_default.yaml
  bootstrap/config/overlays/application/kustomization.yaml
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/L

#3468 kfctl: add --config flag for specifying a static config file
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/M

#3495 add profiles / kfam to kustomize path
  bootstrap/config/overlays/gcp/kfctl_default.yaml
  bootstrap/config/overlays/istio/kfctl_default.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/S

#3045 add kfctl to deploy app backend
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/kfctlUtil.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/saKey.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/config/types.go
  bootstrap/go.mod
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/kfapp/minikube/minikube.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
  bootstrap/v2/pkg/utils/k8sAuth.go
  components/gcp-click-to-deploy/app-config.yaml
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XXL

#3492 adds pull sha for kustomize e2e
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/M

#3488 kfctl: kustomize: fail when a component is missing
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/M

#3507 jupyter-web-app: Fix 400 error
  components/jupyter-web-app/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/kubeflow_jupyter/rok/app.py
Labels: approved, cla: yes, lgtm, size/S

#3500 update API spec
  components/access-management/api/swagger.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3508 Kfctl kustomize e2e in manifests
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/XS

#3499 Create a token refresher and IAM checker.
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/tokenSource.go
  bootstrap/cmd/bootstrap/app/tokenSource_test.go
  bootstrap/cmd/bootstrap/main.go
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/L

#3482 E2e test to verify iap endpoint
  prow_config.yaml
  testing/gcp_util.py
  testing/kfctl/conftest.py
  testing/kfctl/endpoint_ready_test.py
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#3522 Account for optional pipelines/runs property in Pipelines card responses
  components/centraldashboard/public/components/pipelines-card.js
Labels: approved, cla: yes, lgtm, size/XS

#3466 Updated master with the latest image for central-dashboard for v0.6
  components/centraldashboard/Makefile
  components/centraldashboard/make-win.ps1
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/XS

#3479 Click to deploy; Launch a statefulset for each deployment
  bootstrap/.dockerignore
  bootstrap/.gcloudignore
  bootstrap/Dockerfile.bootstrap.dev
  bootstrap/Dockerfile.builder
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/cmd/bootstrap/app/kfctl_test.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/cmd/bootstrap/app/router_test.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/bootstrap/app/server_test.go
  bootstrap/cmd/bootstrap/app/tokenSource_test.go
  bootstrap/cmd/bootstrap/app/util.go
  bootstrap/developer_guide.md
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/kustomize/deployment.yaml
  bootstrap/kustomize/kustomization.yaml
  bootstrap/kustomize/role.yaml
  bootstrap/kustomize/role_binding.yaml
  bootstrap/kustomize/service.yaml
  bootstrap/kustomize/service_account.yaml
  bootstrap/skaffold.yaml
  bootstrap/test_deploy.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#3525 update pipeline version to v0.1.22
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#3440 upgrade gke version to 1.12
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  prow_config.yaml
  testing/test_deploy.py
  testing/tf_job_simple_test.py
Labels: approved, cla: yes, lgtm, size/M

#3557 add centraldashboard application CR
  bootstrap/config/overlays/application/kfctl_default.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3548 Update KfDef.Spec & Status to support storing information needed by kfctl
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/testdata/kfctl_plugin_test.yaml
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XL

#3541 [CentralDashboard] Update Dockerfile to run all tests apart from built image
  components/centraldashboard/Dockerfile
  components/centraldashboard/Makefile
  components/centraldashboard/karma.conf.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#3515 Refactor kfctl to begin address a number of issues related to repo management
  bootstrap/config/gcp_prototype.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_gcp_iap.0.6.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/config/zz_generated.deepcopy.go
  bootstrap/developer_guide.md
  bootstrap/go.mod
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/coordinator/coordinator_test.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/testdata/doc.go
  bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/XXL

#3570 Create a fake coordinator to support unittesting.
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/coordinator/fake/fake.go
  bootstrap/pkg/kfapp/gcp/fake/fake.go
Labels: approved, cla: yes, lgtm, size/L
