Repository kubeflow/kubeflow, pull requests merged in 2019-03, with the labels that each got.

#2404 Profiles e2e test
  kubeflow/profiles/tests/profiles_test.py
  kubeflow/profiles/tests/sample_profile.yaml
  scripts/kfctl.sh
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2589 Update the jupyter-web-app Image
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2533 Golang profile controller
  components/profile-controller/.gitignore
  components/profile-controller/Dockerfile
  components/profile-controller/Makefile
  components/profile-controller/PROJECT
  components/profile-controller/cmd/manager/main.go
  components/profile-controller/config/crds/kubeflow_v1alpha1_profile.yaml
  components/profile-controller/config/default/kustomization.yaml
  components/profile-controller/config/default/manager_auth_proxy_patch.yaml
  components/profile-controller/config/default/manager_image_patch.yaml
  components/profile-controller/config/default/manager_prometheus_metrics_patch.yaml
  components/profile-controller/config/manager/manager.yaml
  components/profile-controller/config/rbac/auth_proxy_role.yaml
  components/profile-controller/config/rbac/auth_proxy_role_binding.yaml
  components/profile-controller/config/rbac/auth_proxy_service.yaml
  components/profile-controller/config/rbac/rbac_role.yaml
  components/profile-controller/config/rbac/rbac_role_binding.yaml
  components/profile-controller/config/samples/kubeflow_v1alpha1_profile.yaml
  components/profile-controller/go.mod
  components/profile-controller/go.sum
  components/profile-controller/hack/boilerplate.go.txt
  components/profile-controller/pkg/apis/addtoscheme_kubeflow_v1alpha1.go
  components/profile-controller/pkg/apis/apis.go
  components/profile-controller/pkg/apis/kubeflow/group.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/doc.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/profile_types.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/profile_types_test.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/register.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/v1alpha1_suite_test.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  components/profile-controller/pkg/controller/add_profile.go
  components/profile-controller/pkg/controller/controller.go
  components/profile-controller/pkg/controller/profile/profile_controller.go
  components/profile-controller/pkg/controller/profile/profile_controller_suite_test.go
  components/profile-controller/pkg/controller/profile/profile_controller_test.go
  components/profile-controller/pkg/webhook/webhook.go
  kubeflow/profiles/profiles.libsonnet
  kubeflow/profiles/prototypes/profiles.jsonnet
  kubeflow/profiles/tests/profiles_test.jsonnet
  kubeflow/profiles/tests/sample_profile.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2591 Turnning off jupyter images authentication
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2552 Updated Jupyter image paths for using in notebook controller
  kubeflow/jupyter/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2606 Updated jupyter images to allow any origin
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2598 Removing prune for Subresource field in CRD
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2597 Adding backOffLimit to metric collector spec
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2576 Fixed Dashboard v0.0.1 w/ Polymer3 + Webpack
  components/centraldashboard/Dockerfile
  components/centraldashboard/Gopkg.lock
  components/centraldashboard/Gopkg.toml
  components/centraldashboard/README.md
  components/centraldashboard/app/server.ts
  components/centraldashboard/make-win.ps1
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/webpack.config.js
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#2611 Updated jupyter spawning options to the latest images.
  kubeflow/jupyter/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2609 Adding additional printer columns to display status
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2587 Semi-working kfctl go binary
  bootstrap/Makefile
  bootstrap/cmd/kfctl/cmd/apply.go
  bootstrap/cmd/kfctl/cmd/generate.go
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/config/types.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/gcp/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/client/gcp/gcp.go
  bootstrap/pkg/client/ksonnet/ksonnet.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/k8utils.go
Labels: approved, cla: yes, lgtm, size/XXL

#2558 Add status to notebook
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  components/notebook-controller/pkg/util/util.go
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
  kubeflow/jupyter/tests/jupyter_test.py
Labels: approved, cla: yes, lgtm, size/L

#2613 Add prodonjs to OWNERS
  components/centraldashboard/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2619 [Dashboard v1] Changed sidebar tab from JupyterHub to Notebooks
  components/centraldashboard/public/components/main-page.js
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#2620 Fix ambassador route and base_url in notebook controller
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2603 Add build using GCB support to profile controller
  components/notebook-controller/OWNERS
  components/profile-controller/.gitignore
  components/profile-controller/Makefile
  components/profile-controller/OWNERS
  components/profile-controller/gcb_build.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2627 Setting the base_url flag of Jupyter images
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2631 Fix typo in kfctl
  bootstrap/cmd/kfctl/cmd/apply.go
Labels: approved, cla: yes, lgtm, size/XS

#2625 store non exist parameter differently
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go
Labels: approved, cla: yes, lgtm, size/S

#2632 Fix kfctl: didn't pass flag client_id/secret
  bootstrap/cmd/kfctl/cmd/apply.go
Labels: approved, cla: yes, lgtm, size/XS

#2637 update pipeline system images to 0.1.12 release
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2638 Updated jupyter image paths to point to the latest ones
  kubeflow/jupyter/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2640 update pipeline system images to 0.1.12 release (#2637)
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2643 add retry around ks init
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#2651 Getting started card completed
  components/centraldashboard/.eslintignore
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashbosard, area/front-end, cla: yes, lgtm, priority/p0, size/L

#2557 Add Azure support for kfctl.sh
  scripts/azure/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2626 Separate front-end components and add mock activities service.
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/app/server.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/components/activity-view.js
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/webpack.config.js
Labels: approved, cla: yes, lgtm, size/XL

#2564 new deploy API following Open API format
  bootstrap/api/swagger.yaml
Labels: approved, cla: yes, lgtm, size/L

#2656 Add GCB scripts for Jupyter UI
  components/jupyter-web-app/releaser/.gitignore
  components/jupyter-web-app/releaser/app.yaml
  components/jupyter-web-app/releaser/components/params.libsonnet
  components/jupyter-web-app/releaser/components/workflows.jsonnet
  components/jupyter-web-app/releaser/environments/base.libsonnet
  components/jupyter-web-app/releaser/environments/default/globals.libsonnet
  components/jupyter-web-app/releaser/environments/default/main.jsonnet
  components/jupyter-web-app/releaser/environments/default/params.libsonnet
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/parts.yaml
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/prototypes/release.jsonnet
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/release.libsonnet
  scripts/build_image.sh
Labels: approved, cla: yes, lgtm, size/L

#2569 Enabling EFS on AWS for Tensorboard
  kubeflow/tensorboard/aws.libsonnet
  kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
  kubeflow/tensorboard/tests/tensorboard-aws_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2666 Updated TFMA and TFDV versions of Jupyter images
  components/tensorflow-notebook-image/versions/1.11.0/version-config.json
  components/tensorflow-notebook-image/versions/1.11.0gpu/version-config.json
  components/tensorflow-notebook-image/versions/1.12.0/version-config.json
  components/tensorflow-notebook-image/versions/1.12.0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#2677 Serve Pytorch v1beta2 and v1beta1 crd
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2671 Add pre/post submit jobs for Jupyter UI
  components/jupyter-web-app/releaser/.gitignore
  components/jupyter-web-app/releaser/components/params.libsonnet
  components/jupyter-web-app/releaser/lib/ksonnet-lib/v1.8.0/k.libsonnet
  components/jupyter-web-app/releaser/lib/ksonnet-lib/v1.8.0/k8s.libsonnet
  components/jupyter-web-app/releaser/lib/ksonnet-lib/v1.8.0/swagger.json
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/prototypes/release.jsonnet
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/release.libsonnet
  prow_config.yaml
  scripts/build_image.sh
Labels: approved, cla: yes, lgtm, size/XXL

#2689 fixes 'Install profiles CR by default'
  bootstrap/config/gcp_prototype.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2687 Skip check to oauth_id/oauth_secret if using basic auth
  bootstrap/pkg/client/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#2684 Add ClusterRole and ClusterRole
  kubeflow/common/centraldashboard.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2681 fix IAM policy set
  bootstrap/pkg/client/gcp/gcp.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/iamutils_test.go
Labels: approved, cla: yes, lgtm, size/L

#2676 store azure secrets to cluster during setup
  scripts/azure/util.sh
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2669 Update the ROADMAP with more details about how we are approaching 1.0
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/S

#2683 fix pipeline-viewer-controller access kube-apiserver 403
  kubeflow/pipeline/pipeline-viewercrd.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2403 Integrated test_flake8.py into CI system
  testing/test_flake8.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2702 Fix param set on ipName and hostname
  bootstrap/pkg/client/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/XS

#2690 Create secret for basic login
  bootstrap/cmd/kfctl/cmd/apply.go
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/pkg/apis/apps/gcp/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/client/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/L

#2694 Attempt to fix spark-operator and argo-deploy test flakiness.
  prow_config.yaml
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2710 Added PVC volumeName
  kubeflow/gcp/google-cloud-filestore-pv.libsonnet
  kubeflow/gcp/tests/google-cloud-filestore-pv_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2704 Fix error in setup_backend
  kubeflow/gcp/setup_backend.sh
Labels: approved, cla: yes, lgtm, size/XS

#2692 moved the Profiles golang controller kustomize manifests around
  components/profile-controller/config/crds/kustomization.yaml
  components/profile-controller/config/default/kustomization.yaml
  components/profile-controller/config/manager/kustomization.yaml
  components/profile-controller/config/rbac/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/S

#2695 [Dashboard v1] Sidebar dynamic hide support added, stylistic refactor
  components/centraldashboard/dashboard.go
  components/centraldashboard/package.json
  components/centraldashboard/public/components/activity-view.js
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/front-end, cla: yes, lgtm, priority/p0, size/L

#2711 Update centraldashboard.jsonnet
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2654 Fix iap libsonnet: avoid empty object
  kubeflow/gcp/iap.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2648 Use multiple projects in the load test for 1-click-deployment
  bootstrap/config/gcp_prototype.yaml
  testing/run_deploy_app.sh
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/L

#2674 fixes 'kfctl generated yaml fails validation #2653'
  kubeflow/argo/argo.libsonnet
  kubeflow/argo/tests/argo_test.jsonnet
  kubeflow/common/ambassador.libsonnet
  kubeflow/common/tests/ambassador_test.jsonnet
  kubeflow/pipeline/pipeline-viewercrd.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2705 Kfctl go E2E test should deploy kubeflow
  bootstrap/cmd/kfctl/main.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/client/coordinator/coordinator.go
  bootstrap/pkg/client/gcp/gcp.go
  bootstrap/pkg/client/ksonnet/ksonnet.go
  bootstrap/pkg/utils/iamutils_test.go
  testing/kfctl/conftest.py
  testing/kfctl/kfctl_delete_test.py
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2720 Admission webhook for inserting credential to pod
  components/gcp-admission-webhook/.gitignore
  components/gcp-admission-webhook/Dockerfile
  components/gcp-admission-webhook/Makefile
  components/gcp-admission-webhook/README.md
  components/gcp-admission-webhook/go.mod
  components/gcp-admission-webhook/go.sum
  components/gcp-admission-webhook/main.go
Labels: approved, cla: yes, lgtm, size/L

#2667 Add Namespaces and Activities from API server.
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/components/activities-list.js
  components/centraldashboard/public/components/activity-view.js
  components/centraldashboard/public/components/dashboard-view.css
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/tslint.json
Labels: approved, area/front-end, cla: yes, lgtm, size/XXL

#2728 update fairing@7f7a66687ceab3ed2838ad29e3ff4b04afe351ab
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2730 Added tf 1.13 to the list of jupyter images
  components/tensorflow-notebook-image/versions/1.13.1/version-config.json
  components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#2729 Fix presubmit kfctl_go_test
  bootstrap/pkg/client/gcp/gcp.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/k8utils.go
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2733 Polish changes:
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/activity-view.js
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/namespace-selector.js
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, area/front-end, cla: yes, lgtm, priority/p0, size/M

#2713 Move basic auth username/password to ENV
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/pkg/apis/apps/gcp/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/client/gcp/gcp.go
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/M

#2726 Launch trtserver so that CUDA driver compatibility is enabled
  kubeflow/nvidia-inference-server/nvidia-inference-server.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2679 Don't create PVCs if no default StorageClass is set
  components/jupyter-web-app/Dockerfile
  components/jupyter-web-app/Makefile
  components/jupyter-web-app/OWNERS
  components/jupyter-web-app/baseui/.gitignore
  components/jupyter-web-app/baseui/README.md
  components/jupyter-web-app/baseui/__init__.py
  components/jupyter-web-app/baseui/api.py
  components/jupyter-web-app/baseui/utils.py
  components/jupyter-web-app/default/kubeflow/jupyter/server.py
  components/jupyter-web-app/default/kubeflow/jupyterui/.gitignore
  components/jupyter-web-app/default/kubeflow/jupyterui/__init__.py
  components/jupyter-web-app/default/kubeflow/jupyterui/routes.py
  components/jupyter-web-app/default/kubeflow/jupyterui/static/css/main.css
  components/jupyter-web-app/default/kubeflow/jupyterui/static/css/notebooks.css
  components/jupyter-web-app/default/kubeflow/jupyterui/static/js/add_notebook.js
  components/jupyter-web-app/default/kubeflow/jupyterui/static/js/notebooks.js
  components/jupyter-web-app/default/kubeflow/jupyterui/static/kubeflow.png
  components/jupyter-web-app/default/kubeflow/jupyterui/templates/add_notebook.html
  components/jupyter-web-app/default/kubeflow/jupyterui/templates/layout.html
  components/jupyter-web-app/default/kubeflow/jupyterui/templates/notebooks.html
  components/jupyter-web-app/default/run.py
  components/jupyter-web-app/rok/kubeflow/rokui/.gitignore
  components/jupyter-web-app/rok/kubeflow/rokui/api.py
  components/jupyter-web-app/rok/kubeflow/rokui/routes.py
  components/jupyter-web-app/rok/kubeflow/rokui/server.py
  components/jupyter-web-app/rok/kubeflow/rokui/templates/notebooks.html
  components/jupyter-web-app/rok/kubeflow/rokui/utils.py
  kubeflow/jupyter/jupyter-web-app.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/XL

#2751 fix make build; set IAM policy following read/modify/write
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/gcpUtils_test.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/iamutils_test.go
Labels: approved, cla: yes, lgtm, size/L

#2718 fixes 'kfctl creates invalid IAM policy binding file if email not set'
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/S

#2719 fixes 'kfctl needs to support passing swagger spec to ks init from file'
  bootstrap/cmd/kfctl/cmd/root.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/M

#2756 Fix error in iap component
  kubeflow/gcp/iap.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2755 kfctl install istio
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/L

#2744 admission webhook manifest
  kubeflow/credentials-admission-webhook/README.md
  kubeflow/credentials-admission-webhook/create_ca.sh
  kubeflow/credentials-admission-webhook/parts.yaml
  kubeflow/credentials-admission-webhook/prototypes/webhook.jsonnet
  kubeflow/credentials-admission-webhook/webhook.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2757 ModelDB V2 support in KubeFlow
  kubeflow/modeldb/modeldb.libsonnet
  kubeflow/modeldb/parts.yaml
  kubeflow/modeldb/prototypes/modeldb.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#2763 fixes 'kfctl Incorrect ksonnet OptionServer is specified when no platform is provided'
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/S

#2774 fixes 'ipName and zone are being written to app.yaml even when no platform is specified'
  bootstrap/cmd/kfctl/cmd/generate.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/XS

#2743 added ReadyReplicas status to notebook-controller
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2762 kfctl delete for GCP
  bootstrap/cmd/kfctl/cmd/delete.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/utils/gcputils.go
  testing/kfctl/kfctl_delete_test.py
Labels: approved, cla: yes, lgtm, size/L

#2771 remove openmpi package
  kubeflow/openmpi/OWNERS
  kubeflow/openmpi/README.md
  kubeflow/openmpi/all.libsonnet
  kubeflow/openmpi/assets.libsonnet
  kubeflow/openmpi/assets/init.sh
  kubeflow/openmpi/assets/mca-params.conf
  kubeflow/openmpi/assets/ssh_config
  kubeflow/openmpi/assets/sshd_config
  kubeflow/openmpi/parts.yaml
  kubeflow/openmpi/prototypes/openmpi.jsonnet
  kubeflow/openmpi/service.libsonnet
  kubeflow/openmpi/serviceaccount.libsonnet
  kubeflow/openmpi/util.libsonnet
  kubeflow/openmpi/workloads.libsonnet
Labels: approved, cla: yes, lgtm, size/XL

#2765 cache k8s spec in kubeflow so it can be used by ksonnet lib
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/k8sSpec/README.md
  bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  bootstrap/pkg/apis/apps/group.go
Labels: approved, cla: yes, lgtm, size/XXL

#2772 replace download k8s manifest with ksonnet entry
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/kfapp/gcp/gcp.go
  kubeflow/gcp/gpu-driver.libsonnet
  kubeflow/gcp/prototypes/gpu-driver.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2783 update pipeline version to v0.1.13
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2768 update katib image for 0.5
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2769 Adds Kferror interface
  bootstrap/pkg/apis/kferrors.go
Labels: approved, cla: yes, lgtm, size/M

#2779 Obtain build version from ENV
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/Dockerfile
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/S

#2655 update DM config file
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/S

#2782 add jupyter image with tf 2.0
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/versions/2.0.0a0/version-config.json
  components/tensorflow-notebook-image/versions/2.0.0a0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/S

#2732 Add pdb to mpi-operator clusterrole
  kubeflow/mpi-job/mpi-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2737 [KUBEFLOW-2735] Fix regex for distribution detection.
  scripts/setup-minikube.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2784 add spartakus as component
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/M

#2788 Namespace selector now only shows up when on activity page
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/S

#2786 Privacy link implemented with CSS changes
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.pug
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/M

#2764 added notebook-controller and jupyter-web-app as part of kf deployment
  bootstrap/config/default.yaml
  bootstrap/config/gcp_prototype.yaml
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
Labels: approved, cla: yes, lgtm, size/S

#2793 Add missing alsologtostderr flag to mpi-operator args
  kubeflow/mpi-job/mpi-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2798 Stop setting JupyterHub parameters and pull config from PR branch.
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/M

#2780 update dashboard image
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2805 Retag jupyter images with tag v0.5.0
  kubeflow/jupyter/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2803 check CLIENT_ID/CLIENT_SECRET before acutal Apply
  bootstrap/cmd/kfctl/cmd/apply.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/M

#2794 Update the developer guide for kfctl.
  bootstrap/developer_guide.md
Labels: approved, cla: yes, lgtm, size/S

#2787 notebook CR shows container status
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2822 Cherrypick #2787 into 0.5 branch
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2795 E2E kfctl go test should verify that Kubeflow is deployed.
  testing/kfctl/conftest.py
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_delete_test.py
  testing/kfctl/kfctl_go_test.py
  testing/wait_for_kubeflow.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2816 update ks for 0.5
  kubeflow/application/prototypes/application.jsonnet
  kubeflow/common/prototypes/basic-auth.jsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2827 fixes 'kfctl attribute deleteStorage is appearing in app.yaml when platform is not gcp'
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/XS

#2792 Add "update" verb to pdb resource of mpi-job
  kubeflow/mpi-job/mpi-operator.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2802 Add named context to KUBECONFIG
  bootstrap/pkg/kfapp/gcp/gcp.go
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/L

#2781 move admission webhook to gcp
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  components/gcp-admission-webhook/README.md
  kubeflow/credentials-admission-webhook/README.md
  kubeflow/credentials-admission-webhook/parts.yaml
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/prototypes/webhook.jsonnet
  kubeflow/gcp/webhook.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2837 update pytorch image
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2813 fixes 'kfctl apply fails to create k8s resources; tries to deploy to 127.0.0.1'
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/S

#2840 remove openmpi from registry file
  kubeflow/registry.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2814 Add kfctl E2E test on GCP with IAP
  prow_config.yaml
  testing/kfctl/conftest.py
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/util.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2815 Use YAML modifications instead of regex replacement
  bootstrap/pkg/kfapp/gcp/gcp.go
Labels: approved, cla: yes, lgtm, size/L

#2810 fixes 'kfctl delete fails when no platform or minikube is specified'
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/M

#2839 make createResourceFromFile check first, then create
  bootstrap/cmd/bootstrap/app/k8sUtil.go
Labels: approved, cla: yes, lgtm, size/S

#2801 kfctl interface in gcp.go/ksonnet.go for deploy app
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/utils/gcputils.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/k8utils.go
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2849 Cherrypick to 0.5
  bootstrap/cmd/bootstrap/app/k8sUtil.go
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  components/gcp-admission-webhook/README.md
  kubeflow/application/prototypes/application.jsonnet
  kubeflow/common/prototypes/basic-auth.jsonnet
  kubeflow/credentials-admission-webhook/README.md
  kubeflow/credentials-admission-webhook/parts.yaml
  kubeflow/gcp/create_ca.sh
  kubeflow/gcp/prototypes/webhook.jsonnet
  kubeflow/gcp/webhook.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  kubeflow/mpi-job/mpi-operator.libsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/registry.yaml
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  prow_config.yaml
  testing/kfctl/conftest.py
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_delete_test.py
  testing/kfctl/kfctl_go_test.py
  testing/wait_for_kubeflow.py
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/util.libsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: cla: yes, size/XL

#2851 check if spec is already set
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/XS

#2778 Add NotFoundView to catch invalid paths
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/not-found-view.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/L

#2855 Update the changelog for 0.5.
  CHANGELOG.md
  docs_dev/releasing.md
  scripts/update-changelog.sh
Labels: approved, cla: yes, lgtm, size/XL

#2859 Added a height change for Firefox support
  components/centraldashboard/public/styles.css
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/XS

#2865 Update README with additional information on release/testing
  components/centraldashboard/README.md
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, size/M

#2856 use whitelist for iam policy clean
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/iamutils_test.go
Labels: approved, cla: yes, lgtm, size/M

#2758 Add unit tests to Central Dashboard component
  components/centraldashboard/.gitignore
  components/centraldashboard/.nycrc
  components/centraldashboard/Dockerfile
  components/centraldashboard/Makefile
  components/centraldashboard/app/.jasmine.json
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/k8s_service_test.ts
  components/centraldashboard/karma.conf.js
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/.eslintrc.json
  components/centraldashboard/public/ajax_test_helper.js
  components/centraldashboard/public/components/activities-list_test.js
  components/centraldashboard/public/components/activity-view.js
  components/centraldashboard/public/components/activity-view_test.js
  components/centraldashboard/public/components/dashboard-view_test.js
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/namespace-selector_test.js
  components/centraldashboard/public/index.js
  components/centraldashboard/public/index_test.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/XXL

#2868 Cherrypick to 0.5
  CHANGELOG.md
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_default.yaml
  bootstrap/config/kfctl_iap.yaml
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/ksonnet/ksonnet.go
  bootstrap/pkg/utils/gcputils.go
  bootstrap/pkg/utils/iamutils.go
  bootstrap/pkg/utils/iamutils_test.go
  bootstrap/pkg/utils/k8utils.go
  components/centraldashboard/.eslintrc.json
  components/centraldashboard/README.md
  components/centraldashboard/package-lock.json
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/not-found-view.js
  components/centraldashboard/public/styles.css
  components/centraldashboard/webpack.config.js
  docs_dev/releasing.md
  kubeflow/pipeline/pipeline.libsonnet
  scripts/update-changelog.sh
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, size/XXL

#2833 adding kfctl to a container, Makefile related changes, developer_guide updated
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/cmd/kfctl/README.md
  bootstrap/developer_guide.md
Labels: approved, cla: yes, lgtm, size/L

#2853 add labels for notebook so that gcp credentials will be injected by webhook
  bootstrap/pkg/kfapp/gcp/gcp.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, priority/p0, size/S

#2875 Update image tags for katib
  kubeflow/katib/prototypes/all.jsonnet
Labels: approved, cla: yes, lgtm, size/S
