Repository kubeflow/kubeflow, pull requests merged in 2019-09, with the labels that each got.

#4053 Fix presubmit build; typo fix
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/S

#3957 Apply refactor
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/kfapp/kustomize/kustomize.go
  bootstrap/pkg/utils/k8utils.go
Labels: approved, cla: yes, lgtm, size/XL

#4013 Migrate notebook CR to kubebuilder V2
  components/notebook-controller/Dockerfile
  components/notebook-controller/Makefile
  components/notebook-controller/OWNERS
  components/notebook-controller/PROJECT
  components/notebook-controller/README.md
  components/notebook-controller/api/v1alpha1/groupversion_info.go
  components/notebook-controller/api/v1alpha1/notebook_types.go
  components/notebook-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/cmd/manager/main.go
  components/notebook-controller/config/certmanager/certificate.yaml
  components/notebook-controller/config/certmanager/kustomization.yaml
  components/notebook-controller/config/certmanager/kustomizeconfig.yaml
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/config/crd/kustomization.yaml
  components/notebook-controller/config/crd/kustomizeconfig.yaml
  components/notebook-controller/config/crd/patches/cainjection_in_notebooks.yaml
  components/notebook-controller/config/crd/patches/webhook_in_notebooks.yaml
  components/notebook-controller/config/crds/notebook_v1alpha1_notebook.yaml
  components/notebook-controller/config/crds/v1alpha1_notebook.yaml
  components/notebook-controller/config/default/kustomization.yaml
  components/notebook-controller/config/default/manager_auth_proxy_patch.yaml
  components/notebook-controller/config/default/manager_image_patch.yaml
  components/notebook-controller/config/default/manager_prometheus_metrics_patch.yaml
  components/notebook-controller/config/default/manager_webhook_patch.yaml
  components/notebook-controller/config/default/webhookcainjection_patch.yaml
  components/notebook-controller/config/manager/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/notebook-controller/config/rbac/auth_proxy_service.yaml
  components/notebook-controller/config/rbac/kustomization.yaml
  components/notebook-controller/config/rbac/leader_election_role.yaml
  components/notebook-controller/config/rbac/leader_election_role_binding.yaml
  components/notebook-controller/config/rbac/rbac_role.yaml
  components/notebook-controller/config/rbac/role.yaml
  components/notebook-controller/config/rbac/role_binding.yaml
  components/notebook-controller/config/samples/v1alpha1_notebook.yaml
  components/notebook-controller/config/webhook/kustomization.yaml
  components/notebook-controller/config/webhook/kustomizeconfig.yaml
  components/notebook-controller/config/webhook/manifests.yaml
  components/notebook-controller/config/webhook/service.yaml
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/gcb_build.jsonnet
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/notebook-controller/hack/boilerplate.go.txt
  components/notebook-controller/main.go
  components/notebook-controller/pkg/apis/addtoscheme_gg_v1alpha1.go
  components/notebook-controller/pkg/apis/apis.go
  components/notebook-controller/pkg/apis/notebook/group.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/doc.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/register.go
  components/notebook-controller/pkg/controller/add_notebook.go
  components/notebook-controller/pkg/controller/controller.go
  components/notebook-controller/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#4054 kfctl server integrate new kustomize apply
  bootstrap/Dockerfile
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/pkg/kfapp/kustomize/kustomize.go
  bootstrap/pkg/utils/k8utils.go
Labels: approved, cla: yes, lgtm, size/M

#3996 Set userid prefix and header for IAP.
  bootstrap/config/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/M

#4082 update auto redirect; add name regex check
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#4083 Make config version consistent with kubeflow.org doc
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#4029 * Update jupyter web-app CD scripts to run in the kf-releasing namespace
  py/kubeflow/kubeflow/ci/application_util.py
  releasing/auto-update/README.md
  releasing/auto-update/base/params.env
  releasing/auto-update/base/params.yaml
  releasing/auto-update/overlays/cron/kustomization.yaml
  releasing/auto-update/overlays/cron/update_job_cron.yaml
  releasing/auto-update/overlays/job/kustomization.yaml
  releasing/auto-update/overlays/job/update_job.yaml
Labels: approved, cla: yes, lgtm, size/M

#4089 set email explicitly for v0.5
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#4097 Fix broken kfctl build on v0.6-branch
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/XS

#4052 provide a way to generate a name that doesn't require kubectl create
  bootstrap/pkg/kfapp/kustomize/kustomize.go
Labels: approved, cla: yes, lgtm, size/S

#4084 Remove kfctl.sh
  ack_guide.md
  scripts/aws/OWNERS
  scripts/aws/util.sh
  scripts/azure/util.sh
  scripts/download.sh
  scripts/download_test.py
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/kfctl_generate_test.sh
  scripts/setup-minikube.sh
  scripts/util-minikube.sh
Labels: approved, cla: yes, lgtm, size/XXL

#3700 Update Makefile to not build with `-i`
  bootstrap/Makefile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4106 Apply with strawman reconcile
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/M

#4127 Updated the guide to releasing the website
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/L

#4122 pick up manifest config fix on v0.6 branch
  bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4128 pick up v0.6 head config
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#4130 pick up manifest config fix on v0.6 branch
  bootstrap/config/kfctl_gcp_iap.0.6.2.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4132 kfctlClient createDeployment should respect the deadline set in the context
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctl_test.go
Labels: approved, cla: yes, lgtm, size/S

#4134 use latest config version; remove unused logic
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#4143 copy Kfdef beta to kubeflow/kubeflow
  bootstrap/Makefile
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types_test.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/doc.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/register.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/testdata/doc.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/testdata/kfctl_plugin_test.yaml
  bootstrap/pkg/apis/apps/kfdef/v1beta1/zz_generated.deepcopy.go
  bootstrap/pkg/apis/kferrors.go
Labels: approved, cla: yes, lgtm, size/XL

#3880 [Central-Dashboard v2] MUI Tests - Backend:
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/api_workgroup_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/app/test_resources.ts
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/tsconfig.json
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/XXL

#4120 [CentralDashboard v2] MUI Front-end tests
  components/centraldashboard/public/ajax_test_helper.js
  components/centraldashboard/public/components/manage-users-view.pug
  components/centraldashboard/public/components/manage-users-view_test.js
  components/centraldashboard/public/components/registration-page_test.js
  components/centraldashboard/public/components/utilities-mixin.js
  components/centraldashboard/public/components/utilities-mixin_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/L

#4129 Update E2E tests to pull GCP KFDef from kubeflow/manifests
  bootstrap/Makefile
  bootstrap/README.md
  bootstrap/config/gcp_prototype.yaml
  bootstrap/config/kfctl_gcp_basic_auth.yaml
  bootstrap/config/kfctl_gcp_iap.yaml
  deployment/gke/cloud_shell_templates/conn.md
  deployment/gke/cloud_shell_templates/conn.sh
  deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
  deployment/gke/deployment_manager_configs/cluster.jinja
  deployment/gke/deployment_manager_configs/cluster.jinja.schema
  deployment/gke/deployment_manager_configs/gcfs.yaml
  deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
  deployment/gke/deployment_manager_configs/network.jinja
  deployment/gke/deployment_manager_configs/network.yaml
  deployment/gke/deployment_manager_configs/storage-kubeflow.yaml
  deployment/gke/deployment_manager_configs/storage.jinja
  deployment/gke/deployment_manager_configs/storage.jinja.schema
  prow_config.yaml
  testing/kfctl/kfctl_go_test.py
  testing/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#4161 Disable test_jsonnet.py because it is failing blocking presubmits.
  testing/test_jsonnet.py
Labels: approved, cla: yes, lgtm, size/S

#4165 Fix v1beta1 deepcopy rule
  bootstrap/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#4055 Migrate kustomize.go to Kustomize3
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/kustomize/kustomize.go
  bootstrap/pkg/kfapp/kustomize/kustomize_test.go
  components/notebook-controller/config/crd/kustomization.yaml
  components/notebook-controller/config/default/kustomization.yaml
  components/profile-controller/config/default/kustomization.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4121 Arrikto and AWS plugins should pull additional configuration files from kubeflow/manifests
  bootstrap/pkg/kfapp/aws/aws.go
  bootstrap/pkg/kfapp/existing_arrikto/existing.go
Labels: approved, cla: yes, lgtm, size/S

#4170 First refactor in prep to kubeflow/kfctl/issues/36
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4176 Update C2D UI to improve operation status reporting.
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, area/front-end, cla: yes, lgtm, size/L

#4177 C2D: Fix bugs in _enableGcpServices.
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, area/front-end, cla: yes, lgtm, size/S

#4178 add time estimate for basic auth as well
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#4174 Delete the aws & existing config files; they are now in kubeflow/manifests
  deployment/existing/OWNERS
  deployment/existing/auth_oidc/authservice.tmpl
  deployment/existing/auth_oidc/dex.tmpl
  deployment/existing/auth_oidc/envoy-filter.yaml
  deployment/existing/auth_oidc/gateway.yaml
  deployment/existing/istio/crds.yaml
  deployment/existing/istio/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#4179 unify auto redirect logic
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/M

#4149 Kfdef converter
  bootstrap/cmd/bootstrap/app/kfctl_test.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/expected.txt
  bootstrap/pkg/apis/apps/kfdef/kfloader.go
  bootstrap/pkg/apis/apps/kfdef/kfloader_test.go
  bootstrap/pkg/apis/apps/kfdef/read.txt
  bootstrap/pkg/apis/apps/kfdef/testdata/kfdef_v1alpha1.yaml
  bootstrap/pkg/apis/apps/kfdef/testdata/kfdef_v1beta1.yaml
  bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/zz_generated.deepcopy.go
  bootstrap/pkg/apis/kferrors.go
  bootstrap/pkg/kfapp/aws/aws.go
  bootstrap/pkg/kfapp/coordinator/coordinator.go
  bootstrap/pkg/kfapp/gcp/gcp.go
  bootstrap/pkg/kfapp/gcp/gcp_plugin.go
  bootstrap/pkg/kfapp/kustomize/kustomize.go
  bootstrap/pkg/kfapp/kustomize/kustomize_test.go
Labels: approved, cla: yes, lgtm, size/XL

#4182 Move aws deployment files to kubeflow/manifests
  deployment/aws/OWNERS
  deployment/aws/infra_configs/cluster_config.yaml
  deployment/aws/infra_configs/cluster_features.yaml
  deployment/aws/infra_configs/iam_alb_ingress_policy.json
  deployment/aws/infra_configs/iam_cloudwatch_policy.json
  deployment/aws/infra_configs/iam_csi_fsx_policy.json
Labels: approved, cla: yes, lgtm, size/L

#3968 update release doc
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/L

#4166 Add condition operations to KfDef for reconcile semantics
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/kfdef/kfloader.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types_test.go
Labels: approved, cla: yes, lgtm, size/L

#4193 jupyter webapp uses notebook v1beta1
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml
Labels: approved, cla: yes, lgtm, size/S

#4148 Use python to define the E2E test workflow for kfctl.
  bootstrap/pkg/kfapp/gcp/gcp.go
  go.mod
  prow_config.yaml
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
  testing/kfctl/conftest.py
  testing/kfctl/kfctl_go_test.py
Labels: approved, cla: yes, lgtm, size/XL

#4197 Kfctl breakage
  bootstrap/Dockerfile
  bootstrap/Makefile
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/kfdef/testdata/doc.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types_test.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/doc.go
  bootstrap/pkg/apis/apps/kfdef/v1beta1/register.go
  bootstrap/pkg/kfapp/kustomize/kustomize.go
  components/profile-controller/Dockerfile
  components/profile-controller/cmd/manager/main.go
  components/profile-controller/go.mod
  components/profile-controller/pkg/apis/addtoscheme_kubeflow_v1alpha1.go
  components/profile-controller/pkg/apis/istiorbac/v1alpha1/doc.go
  components/profile-controller/pkg/apis/istiorbac/v1alpha1/register.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/doc.go
  components/profile-controller/pkg/apis/kubeflow/v1alpha1/register.go
  components/profile-controller/pkg/controller/add_profile.go
  components/profile-controller/pkg/controller/profile/profile_controller.go
  components/profile-controller/pkg/controller/profile/profile_controller_suite_test.go
  components/profile-controller/pkg/controller/profile/profile_controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#4206 Fixed the deprecated proxy URL
  testing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#4204 Revert "Apply with strawman reconcile (#4106)"
  bootstrap/pkg/kfapp/coordinator/coordinator.go
Labels: approved, cla: yes, lgtm, size/M

#4207 Add AWS CLI
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4201 Fix test_endpoint.
  prow_config.yaml
  py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
  testing/kfctl/endpoint_ready_test.py
Labels: approved, cla: yes, lgtm, size/M
