Repository kubeflow/kubeflow, pull requests merged in 2019-02, with the labels that each got.

#2348 use Istio for JWT validation
  kubeflow/gcp/cert-manager.libsonnet
  kubeflow/gcp/healthcheck_route.yaml
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/jwt-policy-template.yaml
  kubeflow/gcp/prototypes/iap-ingress.jsonnet
  kubeflow/gcp/setup_backend.sh
  kubeflow/gcp/tests/cert-manager_test.jsonnet
  kubeflow/gcp/tests/iap_test.jsonnet
  kubeflow/gcp/update_backend.sh
Labels: approved, cla: yes, lgtm, size/L

#2362 one-click-deploy fix - break if deploy successfully
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/S

#2363 Propagate Disk name to ks application
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  deployment/gke/deployment_manager_configs/storage-kubeflow.yaml
  deployment/gke/deployment_manager_configs/storage.jinja
  deployment/gke/deployment_manager_configs/storage.jinja.schema
Labels: approved, cla: yes, lgtm, size/M

#2333 Integrate Jupyter e2e test into CI
  kubeflow/jupyter/tests/conftest.py
  kubeflow/jupyter/tests/jupyter_test.py
  scripts/kfctl.sh
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2240 Fix TabError in sync_images.py
  releasing/sync_images.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2361 Dashboard v1 UI rewrite done
  ROADMAP.md
  components/centraldashboard/frontend/index/assets/kf-logo_64px.svg
  components/centraldashboard/frontend/index/components.html
  components/centraldashboard/frontend/index/index.html
  components/centraldashboard/frontend/index/main-page.html
  components/centraldashboard/frontend/index/styles.css
Labels: approved, cla: yes, lgtm, size/XL

#2295 Update pipelines version to 0.1.8
  components/tensorflow-notebook-image/Dockerfile
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2369 Combine check for kf client dependencies into one utility function check_installed_deps
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/M

#2260 Extend Katib documentation to use not in GKE
  kubeflow/katib/README.md
Labels: approved, cla: yes, lgtm, size/M

#2336 Golang notebook controller
  components/notebook-controller/.gitignore
  components/notebook-controller/Dockerfile
  components/notebook-controller/Makefile
  components/notebook-controller/PROJECT
  components/notebook-controller/README.md
  components/notebook-controller/cmd/manager/main.go
  components/notebook-controller/config/crds/notebook_v1alpha1_notebook.yaml
  components/notebook-controller/config/crds/v1alpha1_notebook.yaml
  components/notebook-controller/config/default/kustomization.yaml
  components/notebook-controller/config/default/manager_auth_proxy_patch.yaml
  components/notebook-controller/config/default/manager_image_patch.yaml
  components/notebook-controller/config/default/manager_prometheus_metrics_patch.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/notebook-controller/config/rbac/auth_proxy_role.yaml
  components/notebook-controller/config/rbac/auth_proxy_role_binding.yaml
  components/notebook-controller/config/rbac/auth_proxy_service.yaml
  components/notebook-controller/config/rbac/rbac_role.yaml
  components/notebook-controller/config/rbac/rbac_role_binding.yaml
  components/notebook-controller/config/samples/v1alpha1_notebook.yaml
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/notebook-controller/hack/boilerplate.go.txt
  components/notebook-controller/pkg/apis/addtoscheme_gg_v1alpha1.go
  components/notebook-controller/pkg/apis/apis.go
  components/notebook-controller/pkg/apis/notebook/group.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/doc.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/register.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/pkg/controller/add_notebook.go
  components/notebook-controller/pkg/controller/controller.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  components/notebook-controller/pkg/webhook/webhook.go
  kubeflow/jupyter/notebook_controller.libsonnet
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#2407 Create kfctl command
  bootstrap/.dockerignore
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/gcpUtils.go
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/options/options.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/bootstrap/main.go
  bootstrap/cmd/kfctl/.gitignore
  bootstrap/cmd/kfctl/OWNERS
  bootstrap/cmd/kfctl/README.md
  bootstrap/cmd/kfctl/cmd/apply.go
  bootstrap/cmd/kfctl/cmd/delete.go
  bootstrap/cmd/kfctl/cmd/generate.go
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/cmd/kfctl/cmd/root.go
  bootstrap/cmd/kfctl/cmd/version.go
  bootstrap/cmd/kfctl/config/app.yaml
  bootstrap/cmd/kfctl/main.go
  bootstrap/cmd/plugins/fooapp.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/hack/boilerplate.go.txt
  bootstrap/pkg/apis/addtoscheme_apps_v1alpha1.go
  bootstrap/pkg/apis/apis.go
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/apis/apps/ksapp/app.go
  bootstrap/pkg/apis/apps/ksapp/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/ksapp/v1alpha1/application_types_test.go
  bootstrap/pkg/apis/apps/ksapp/v1alpha1/doc.go
  bootstrap/pkg/apis/apps/ksapp/v1alpha1/register.go
  bootstrap/pkg/apis/apps/ksapp/v1alpha1/v1alpha1_suite_test.go
  bootstrap/pkg/apis/apps/ksapp/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/client/ksapp/ksapp.go
  bootstrap/pkg/client/minikube/minikube.go
  bootstrap/pkg/utils/k8utils.go
  kubeflow/jupyter/jupyter.libsonnet
  kubeflow/jupyter/localstorage.libsonnet
  kubeflow/jupyter/prototypes/jupyter.jsonnet
  kubeflow/jupyter/tests/jupyter_test.jsonnet
  kubeflow/jupyter/tests/notebooks_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#2400 fix click_deploy_test
  bootstrap/build_image.sh
  testing/test_deploy_app.py
  testing/workflows/components/click_deploy_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2384 add query string to click-to-deploy app to support arbitrary version
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#2425 provision minio using pv or pd directly. only create nfs conditionally
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/storage.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2424 Specify CRD version using v1beta1 schema
  kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2427 Bump pipeline version to 0.1.9
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2373 deploy storage through kfctl.sh
  deployment/gke/deployment_manager_configs/storage-kubeflow.yaml
  scripts/gke/util.sh
  testing/workflows/components/kfctl_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2409 Wait for at most 100s on namespace deletion
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/S

#2431 fix click_to_deploy test
  bootstrap/Dockerfile
  bootstrap/build_image.sh
  bootstrap/cmd/bootstrap/app/ksServer.go
  testing/workflows/components/click_deploy_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2419 fixes kfctl (golang) rename 'ks' directory and app to ksonnet and ksonnet.go respectively
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/bootstrap/app/server.go
  bootstrap/cmd/kfctl/README.md
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/cmd/kfctl/cmd/root.go
  bootstrap/cmd/kfctl/config/app.yaml
  bootstrap/cmd/plugins/foo.go
  bootstrap/cmd/plugins/fooapp.go
  bootstrap/pkg/apis/addtoscheme_apps_v1alpha1.go
  bootstrap/pkg/apis/apps/ksonnet/app.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types_test.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/doc.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/register.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/v1alpha1_suite_test.go
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/zz_generated.deepcopy.go
  bootstrap/pkg/client/ksonnet/ksonnet.go
  bootstrap/pkg/client/minikube/minikube.go
Labels: approved, cla: yes, lgtm, size/XL

#2429 Cherry pick storage changes to pipelines branch
  deployment/gke/deployment_manager_configs/storage-kubeflow.yaml
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/storage.libsonnet
  scripts/gke/util.sh
  scripts/kfctl.sh
  testing/workflows/components/kfctl_test.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2426 fixes 'kfctl - Fetch registry automatically'
  bootstrap/Makefile
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/go.mod
  bootstrap/go.sum
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/client/ksonnet/ksonnet.go
Labels: approved, cla: yes, lgtm, size/M

#2437 make click-deploy-test upload junit artifacts
  bootstrap/test_delete.sh
  testing/test_deploy_app.py
  testing/workflows/components/click_deploy_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2410 port leftover diff from kfapp-ksapp branch after kfctl merge
  .gitignore
  bootstrap/.dockerignore
  bootstrap/Dockerfile
  bootstrap/DockerfileDebug
  bootstrap/Makefile
  bootstrap/cmd/bootstrap/app/ksServer.go
  bootstrap/cmd/kfctl/README.md
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/go.sum
  bootstrap/pkg/apis/apis.go
  components/centraldashboard/frontend/index/components.html
  components/centraldashboard/frontend/index/main-page.html
  components/notebook-controller/hack/boilerplate.go.txt
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2439 NB controller fix
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  kubeflow/jupyter/notebook_controller.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2247 Create test_flake8.py
  testing/test_flake8.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2446 Deploy NFS only when explicitly set the nfs parameter
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/storage.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2416 Deploy viewer CRD controller for Kubeflow Pipelines.
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/pipeline-viewercrd.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2438 ingress entry for basic auth
  kubeflow/gcp/basic-auth-ingress.libsonnet
  kubeflow/gcp/prototypes/basic-auth-ingress.jsonnet
  kubeflow/gcp/update_backend.sh
Labels: approved, cla: yes, lgtm, size/L

#2453 Skipped context check on OSX
  scripts/kfctl.sh
Labels: approved, cla: yes, lgtm, size/M

#2450 Fix testgrid test name
  testing/test_deploy.py
  testing/test_deploy_app.py
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2449 fix artifact dir
  testing/workflows/components/click_deploy_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2428 fixes 'make it easy to configure the foo sample plugin as a plugin or statically linked'
  bootstrap/Makefile
  bootstrap/app.yaml
  bootstrap/cmd/kfctl/README.md
  bootstrap/cmd/kfctl/cmd/init.go
  bootstrap/cmd/kfctl/cmd/root.go
  bootstrap/cmd/plugins/foo/foo.go
  bootstrap/developer_guide.md
  bootstrap/go.sum
  bootstrap/hack/plugins
  bootstrap/hack/static
  bootstrap/pkg/apis/apps/group.go
  bootstrap/pkg/client/foo/foo.go
  bootstrap/pkg/client/minikube/minikube.go
Labels: approved, cla: yes, lgtm, size/L

#2464 Reduce NFS disk size from 200 -> 20 GB
  kubeflow/pipeline/storage.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2462 fix test name on testgrid
  prow_config.yaml
  testing/test_tf_serving.py
  testing/workflows/components/click_deploy_test.jsonnet
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/tfserving.libsonnet
  testing/workflows/components/workflows.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2434 Use command array in mpi job prototype
  kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet
  kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2338 upgrade ks app for E2E test to 0.3.0
  components/image-releaser/components/tf-notebook-workflow.libsonnet
  components/image-releaser/components/tf-serving-workflow.libsonnet
  components/k8s-model-server/images/releaser/components/workflows.libsonnet
  components/k8s-model-server/images/test-worker/Dockerfile
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  prow_config.yaml
  releasing/releaser/components/params.libsonnet
  testing/Dockerfile
  testing/workflows/app.yaml
  testing/workflows/components/click_deploy_test.jsonnet
  testing/workflows/components/tfserving.libsonnet
  testing/workflows/components/unit_tests.jsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/debug_pod.yaml
Labels: approved, cla: yes, lgtm, size/M

#2466 add selector for minio deploy
  kubeflow/pipeline/minio.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2455 add basic auth as alternative of iap access to deploy app;
  bootstrap/Makefile
  bootstrap/go.mod
  bootstrap/go.sum
  components/gatekeeper/auth/AuthServer.go
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Utils.ts
  kubeflow/common/prototypes/basic-auth.jsonnet
  kubeflow/gcp/basic-auth-ingress.libsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#2442 Add mpijobs and pods/log in kubebench rbac
  kubeflow/kubebench/kubebench-rbac.libsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2470 cherrypick pipeline deployment changes to pipelines branch
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/minio.libsonnet
  kubeflow/pipeline/pipeline-viewercrd.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/storage.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2477 fix test image
  testing/Dockerfile
  testing/workflows/components/click_deploy_test.jsonnet
  testing/workflows/components/tfserving.libsonnet
  testing/workflows/components/unit_tests.jsonnet
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#1467 Add Spark Job
  kubeflow/spark/README.md
  kubeflow/spark/all.libsonnet
  kubeflow/spark/parts.yaml
  kubeflow/spark/prototypes/spark-job.jsonnet
  kubeflow/spark/prototypes/spark-operator.jsonnet
  testing/workflows/components/kfctl_test.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2357 Jupyter UI that manages Notebook CRs
  components/jupyter-web-app/Dockerfile
  components/jupyter-web-app/Makefile
  components/jupyter-web-app/README.md
  components/jupyter-web-app/default/kubeflow/jupyter/__init__.py
  components/jupyter-web-app/default/kubeflow/jupyter/routes.py
  components/jupyter-web-app/default/kubeflow/jupyter/server.py
  components/jupyter-web-app/default/kubeflow/jupyter/static/css/main.css
  components/jupyter-web-app/default/kubeflow/jupyter/static/css/notebooks.css
  components/jupyter-web-app/default/kubeflow/jupyter/static/js/add_notebook.js
  components/jupyter-web-app/default/kubeflow/jupyter/static/js/notebooks.js
  components/jupyter-web-app/default/kubeflow/jupyter/static/kubeflow.png
  components/jupyter-web-app/default/kubeflow/jupyter/templates/add_notebook.html
  components/jupyter-web-app/default/kubeflow/jupyter/templates/layout.html
  components/jupyter-web-app/default/kubeflow/jupyter/templates/notebooks.html
  components/jupyter-web-app/default/kubeflow/jupyter/utils.py
  components/jupyter-web-app/default/run.py
  components/jupyter-web-app/requirements.txt
  components/jupyter-web-app/rok/kubeflow/rokui/__init__.py
  components/jupyter-web-app/rok/kubeflow/rokui/routes.py
  components/jupyter-web-app/rok/kubeflow/rokui/server.py
  components/jupyter-web-app/rok/kubeflow/rokui/static/css/main.css
  components/jupyter-web-app/rok/kubeflow/rokui/static/css/notebooks.css
  components/jupyter-web-app/rok/kubeflow/rokui/static/js/add_notebook.js
  components/jupyter-web-app/rok/kubeflow/rokui/static/js/notebooks.js
  components/jupyter-web-app/rok/kubeflow/rokui/static/kubeflow.png
  components/jupyter-web-app/rok/kubeflow/rokui/templates/add_notebook.html
  components/jupyter-web-app/rok/kubeflow/rokui/templates/layout.html
  components/jupyter-web-app/rok/kubeflow/rokui/templates/notebooks.html
  components/jupyter-web-app/rok/kubeflow/rokui/utils.py
  components/jupyter-web-app/rok/run.py
  kubeflow/jupyter/config.yaml
  kubeflow/jupyter/jupyter-web-app.libsonnet
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: no, cla: yes, lgtm, ok-to-test, size/XXL

#2473 Fix typo in profile CR
  kubeflow/profiles/profiles.libsonnet
  kubeflow/profiles/tests/profiles_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2451 bootstrapper e2e test with istio
  bootstrap/test_deploy_istio.yaml
  prow_config.yaml
  testing/workflows/components/click_deploy_test.jsonnet
  testing/workflows/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2482 add config file entries for deployment on GCP
  bootstrap/config/kfctl_basic_auth.yaml
  bootstrap/config/kfctl_iap.yaml
Labels: approved, cla: yes, lgtm, size/M

#2485 pass username & password hash as k8s secret instead of ks parameters
  bootstrap/cmd/bootstrap/app/saKey.go
  components/gcp-click-to-deploy/src/DeployForm.tsx
  kubeflow/common/basic-auth.libsonnet
  kubeflow/common/prototypes/basic-auth.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2463 Notebook controller fixes
  components/notebook-controller/config/crds/notebook_v1alpha1_notebook.yaml
  components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
  components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
  components/notebook-controller/pkg/util/util.go
  kubeflow/jupyter/prototypes/notebook_controller.jsonnet
  kubeflow/jupyter/tests/jupyter_test.py
  kubeflow/jupyter/tests/test_app/components/jupyter.jsonnet
  kubeflow/jupyter/tests/test_app/environments/test2/globals.libsonnet
  kubeflow/jupyter/tests/test_app/environments/test2/main.jsonnet
  kubeflow/jupyter/tests/test_app/environments/test2/params.libsonnet
  scripts/kfctl.sh
  scripts/util.sh
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2474 Support multiple CRD versions for TFJob
  kubeflow/examples/prototypes/tf-job-simple-v1beta2.jsonnet
  kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
  kubeflow/tf-training/tests/tf-job_test.jsonnet
  kubeflow/tf-training/tf-job-operator.libsonnet
  testing/deploy_kubeflow.py
  testing/tf_job_simple_test.py
  testing/wait_for_kubeflow.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/XL

#2486 Add build with GCB support to notebook controller
  components/notebook-controller/.gitignore
  components/notebook-controller/Makefile
  components/notebook-controller/gcb_build.jsonnet
  tools/gcb/template.libsonnet
Labels: approved, cla: yes, lgtm, size/L

#2493 update jupyter-web-app image path
  kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2492 fix workflow name
  bootstrap/test_delete.sh
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2494 add missing fields
  bootstrap/cmd/bootstrap/app/ksServer.go
Labels: approved, cla: yes, lgtm, size/XS

#2490 Update Jupyter WebApp redirect URL and libsonnet
  components/jupyter-web-app/default/kubeflow/jupyter/static/js/notebooks.js
  components/jupyter-web-app/rok/kubeflow/rokui/static/js/notebooks.js
  kubeflow/jupyter/jupyter-web-app.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2432 Dashboard immediate changes complete
  components/centraldashboard/.gitignore
  components/centraldashboard/dashboard.go
  components/centraldashboard/frontend/assets/kf-logo_64px.svg
  components/centraldashboard/frontend/bower.json
  components/centraldashboard/frontend/components.html
  components/centraldashboard/frontend/index.html
  components/centraldashboard/frontend/layout/index.html
  components/centraldashboard/frontend/layout/styles.css
  components/centraldashboard/frontend/main-page.html
  components/centraldashboard/frontend/styles.css
Labels: approved, cla: yes, lgtm, size/L

#2496 Bump up pipeline version to 0.1.10
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2483 Wrap os.makedir calls inside try,catch block
  components/tensorflow-notebook-image/jupyter_notebook_config.py
  testing/test_deploy.py
  testing/test_deploy_app.py
Labels: approved, cla: yes, lgtm, size/M

#2501 Bump up pipeline version to 0.1.10 (#2496)
  kubeflow/pipeline/prototypes/pipeline.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#2500 Add jupyter-web-app to kfctl
  bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go
  components/jupyter-web-app/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2502 Add myself to Central Dashboard owners
  components/centraldashboard/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2495 Add kubebench-operator jsonnet unit test
  kubeflow/kubebench/tests/kubebench-operator_test.jsonnet
  testing/test_jsonnet.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#2511 Add optional parameter ambassadorNodePort
  kubeflow/common/ambassador.libsonnet
  kubeflow/common/prototypes/ambassador.jsonnet
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2499 Readme added for Kubeflow Central-Dashboard Component
  components/centraldashboard/README.md
Labels: approved, cla: yes, lgtm, size/S

#2478 Refactor the Kubeflow Pipeline ksonnet to better support upgrade
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/pipeline.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/storage.libsonnet
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/L

#2504 create permanent storage from click-to-deploy app
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS

#2519 Fix periodic test
  testing/workflows/components/click_deploy_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2503 name the PD generically and assign to minio
  bootstrap/cmd/bootstrap/app/ksServer.go
  deployment/gke/deployment_manager_configs/storage-kubeflow.yaml
  deployment/gke/deployment_manager_configs/storage.jinja.schema
  scripts/gke/util.sh
Labels: approved, cla: yes, lgtm, size/S

#2523 Fix typo
  components/centraldashboard/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2527 Update dev guide for bootstrapper
  bootstrap/README.md
  bootstrap/developer_guide.md
  components/gcp-click-to-deploy/README.md
Labels: approved, cla: yes, lgtm, size/M

#2479 Add script to upgrade kubeflow pipeline
  scripts/upgrade_kfp.sh
Labels: approved, cla: yes, lgtm, size/M

#2517 Change jupyter images to work with the new jupyter CR, issue# 2458
  components/tensorflow-notebook-image/Dockerfile
  components/tensorflow-notebook-image/start-notebook.sh
Labels: approved, cla: yes, lgtm, size/XS

#2534 update pipeline image version to v0.1.10
  kubeflow/pipeline/pipeline.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#2532 Pytorch v1beta2 support
  kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
  kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
  kubeflow/pytorch-job/pytorch-operator.libsonnet
  kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2538 fix command in bootstrap dev guide
  bootstrap/developer_guide.md
Labels: approved, cla: yes, lgtm, size/XS

#2540 Update dashboard image to point to newest build
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2544 Fixed Version bump
  components/centraldashboard/make-win.ps1
  kubeflow/common/prototypes/centraldashboard.jsonnet
Labels: approved, cla: yes, lgtm, size/M

#2541 port ksonnet changes to pipeline branchs
  bootstrap/cmd/bootstrap/app/ksServer.go
  deployment/gke/deployment_manager_configs/storage-kubeflow.yaml
  deployment/gke/deployment_manager_configs/storage.jinja.schema
  kubeflow/pipeline/all.libsonnet
  kubeflow/pipeline/pipeline.libsonnet
  kubeflow/pipeline/prototypes/pipeline.jsonnet
  kubeflow/pipeline/storage.libsonnet
  scripts/gke/util.sh
  scripts/kfctl.sh
  scripts/upgrade_kfp.sh
  scripts/util.sh
Labels: approved, cla: yes, lgtm, size/L

#2542 fix backendconfig name
  kubeflow/gcp/iap.libsonnet
  kubeflow/gcp/tests/iap_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2506 Small fix for notebook controller
  components/notebook-controller/pkg/controller/notebook/notebook_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#2516 Added unit tests for GetUpdatedPolicy at gcpUtils.go - bootstrap/app
  bootstrap/cmd/bootstrap/app/gcpUtils_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2553 update katib component
  kubeflow/katib/prototypes/all.jsonnet
  kubeflow/katib/studyjobcontroller.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#2555 Temporary change to pin kubeflow to the latest verified tf-operator commit
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#2572 Refactor for Express + Webpack build stack.
  components/centraldashboard/.gitignore
  components/centraldashboard/Dockerfile
  components/centraldashboard/README.md
  components/centraldashboard/app/server.ts
  components/centraldashboard/frontend/bower.json
  components/centraldashboard/frontend/components.html
  components/centraldashboard/frontend/index.html
  components/centraldashboard/frontend/main-page.html
  components/centraldashboard/frontend/styles.css
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/assets/kf-logo_64px.svg
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/index.html
  components/centraldashboard/public/index.js
  components/centraldashboard/public/styles.css
  components/centraldashboard/tsconfig.json
  components/centraldashboard/tslint.json
  components/centraldashboard/webpack.config.js
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#2579 Add ESLint to enforce Google JS style in public/
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/.eslintrc.json
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/index.js
  components/centraldashboard/webpack.config.js
Labels: approved, area/front-end, cla: yes, lgtm, ok-to-test, size/XL

#2581 Updating python package imports related to tf-operator
  testing/tf_job_simple_test.py
  testing/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S
