Repository kubeflow/kubeflow, pull requests merged in 2020-03, with the labels that each got.

#4791 Remove dead tests and notebook image release on postsubmit.
  prow_config.yaml
  testing/deploy_kubeflow.py
  testing/install_minikube.sh
  testing/workflows/components/workflows.jsonnet
Labels: approved, cla: yes, lgtm, size/L

#4810 Fix admission webhook build issue
  components/admission-webhook/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#4669 Fix dashboard wrong katib hyperlink name
  components/centraldashboard/public/components/dashboard-view.js
Labels: approved, cla: yes, lgtm, size/XS

#4816 Add the Azure CLI to Tensorflow Jupyter Image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4814 Fix the kubeflow git link for clone.
  bootstrap/developer_guide.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4796 Fix typo: Rename moniotring.go to monitoring.go
  components/profile-controller/controllers/monitoring.go
Labels: approved, cla: yes, lgtm, size/XS

#4853 static-config-server
  components/static-config-server/Dockerfile
  components/static-config-server/Makefile
  components/static-config-server/README.md
  components/static-config-server/go.mod
  components/static-config-server/go.sum
  components/static-config-server/main.go
Labels: approved, cla: yes, lgtm, size/L

#4869 [CentralDashboard] E2E Test fixes
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/attach_user_middleware.ts
  components/centraldashboard/test/e2e.test.ts
Labels: approved, area/front-end, area/metadata, cla: yes, lgtm, priority/p1, size/S

#4880 Add dash (a shell) the profile-controller docker image.
  components/profile-controller/Dockerfile
  components/profile-controller/skaffold.yaml
Labels: approved, cla: yes, lgtm, size/M

#4879 Add $HOME/.local/bin into PATH
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4662 [CentralDashboard] Registration flow onError delay removed
  components/centraldashboard/public/components/registration-page.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#4867 Fix Jupyter Notebook $HOME Permission
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4698 update releasing guide.
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/S
