Repository kubeflow/kubeflow, pull requests merged in 2020-04, with the labels that each got.

#4773 [Jupyter-Web-App]:Add basic E2E Tests
  .gitignore
  testing/auth.py
  testing/test_jwa.py
Labels: approved, cla: yes, lgtm, size/L

#4918 Fix typo
  .github/ISSUE_TEMPLATE/questions.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4920 Retains DWARF tables for golang build
  components/admission-webhook/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4967 add deprecation warning on kubeflow c2d
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/S

#4909 updated Kubeflow roadmap
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/M
