Repository kubeflow/kubeflow, pull requests merged in 2020-02, with the labels that each got.

#4722 [CentralDashboard] Added a root level `healthz` api call for liveness checks.
  components/centraldashboard/app/server.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/XS

#4723 Automated cherry pick of #4722: Added a root level `healthz` api call for liveness checks. Cherry pick of #4722 on v1.0-branch. #4722: Added a root level `healthz` api call for liveness checks.
  components/centraldashboard/app/server.ts
Labels: approved, cla: yes, lgtm, size/XS

#4734 Add license for jupyter web app frontend
  components/jupyter-web-app/Dockerfile
  components/jupyter-web-app/frontend/third_party/license.txt
  components/jupyter-web-app/frontend/third_party/license_info.csv
Labels: approved, cla: yes, lgtm, size/XXL

#4729 Jupyter displays Warn event message when hover over the spinner
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4741 Automated cherry pick of #4729: Jupyter displays Warn event message when hover over the Cherry pick of #4729 on v1.0-branch. #4729: Jupyter displays Warn event message when hover over the
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
Labels: approved, cla: yes, lgtm, size/S

#4740 Add new jupyter images; kubeflow/kubeflow#4738
  components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
  components/tensorflow-notebook-image/versions/1.15.2/version-config.json
  components/tensorflow-notebook-image/versions/1.15.2gpu/version-config.json
  components/tensorflow-notebook-image/versions/2.1.0/version-config.json
  components/tensorflow-notebook-image/versions/2.1.0gpu/version-config.json
Labels: approved, cla: yes, lgtm, size/M

#4703 [CentralDashboard][Licenses] Pushed license_info.csv file
  components/centraldashboard/third_party/license.txt
  components/centraldashboard/third_party/license_info.csv
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/XXL

#4717 Update the documentation for how to publish/release the website.
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/L

#4687 Delete dead code for releasing and updating images.
  components/jupyter-web-app/releaser/.gitignore
  components/jupyter-web-app/releaser/app.yaml
  components/jupyter-web-app/releaser/components/params.libsonnet
  components/jupyter-web-app/releaser/components/workflows.jsonnet
  components/jupyter-web-app/releaser/environments/base.libsonnet
  components/jupyter-web-app/releaser/environments/default/globals.libsonnet
  components/jupyter-web-app/releaser/environments/default/main.jsonnet
  components/jupyter-web-app/releaser/environments/default/params.libsonnet
  components/jupyter-web-app/releaser/lib/ksonnet-lib/v1.8.0/k.libsonnet
  components/jupyter-web-app/releaser/lib/ksonnet-lib/v1.8.0/k8s.libsonnet
  components/jupyter-web-app/releaser/lib/ksonnet-lib/v1.8.0/swagger.json
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/parts.yaml
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/prototypes/release.jsonnet
  components/jupyter-web-app/releaser/vendor/kubeflow/automation@51b410ade94fdd42556ac2f2fc3d21bf5b649042/release.libsonnet
  prow_config.yaml
  releasing/add_image_shas.py
  releasing/add_image_tag.py
  releasing/add_katib_image_shas.sh
  releasing/apply_image_tags.py
  releasing/image_tags.yaml
  releasing/run_apply_image_tags.sh
  releasing/update_components.sh
  releasing/update_image_tags.sh
Labels: approved, cla: yes, lgtm, size/XXL

#4756 dockerfile for image replicate
  components/private-utils/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4754 Use project id from the default credentials for identity namesapce
  components/profile-controller/controllers/plugin_workload_identity.go
  components/profile-controller/controllers/profile_controller_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4760 Move info about IAP and TFServing to the docs website
  docs/gke/tf_serving_iap.md
Labels: approved, cla: yes, doc-sprint, lgtm, size/M

#4645 Updates to install Fairing from PyPI
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4713 Adding env var to suppress automatic additon of fsGroup in notebook pod
  components/notebook-controller/README.md
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4779 Add load test for notebook controller
  components/notebook-controller/loadtest/jupyter_pvc.yaml
  components/notebook-controller/loadtest/jupyter_test.yaml
  components/notebook-controller/loadtest/start_notebooks.py
Labels: approved, cla: yes, lgtm, size/L

#4777 Fix notebook controller event filtering
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/controllers/notebook_controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#4782 Adding env var to suppress automatic additon of fsGroup in notebook pod
  components/notebook-controller/README.md
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4784 Automated cherry pick of #4777: notebook-controller: Fix event filtering Cherry pick of #4777 on v1.0-branch. #4777: notebook-controller: Fix event filtering
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/controllers/notebook_controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#4785 README.md: Add Link to PR dashboard
  README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#4755 update c2d dependency to include latest kfctl
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/L

#4780 [CentralDashboard][Testing] End-to-end testing added
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/test/.jasmine.json
  components/centraldashboard/test/README.md
  components/centraldashboard/test/e2e.test.ts
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p0, size/XL

#4775 Distroless latest for admission-webhook Dockerfile
  components/admission-webhook/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4804 Automated cherry pick of #4751: Add AWS IAM Role for ServiceAccount support in profile Cherry pick of #4751 on v1.0-branch. #4751: Add AWS IAM Role for ServiceAccount support in profile
  components/profile-controller/README.md
  components/profile-controller/config/samples/profile_v1_aws_iam.yaml
  components/profile-controller/controllers/plugin_iam.go
  components/profile-controller/controllers/plugin_iam_test.go
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/profile_controller_test.go
  components/profile-controller/go.mod
  components/profile-controller/go.sum
Labels: approved, cla: yes, lgtm, size/XL
