Repository kubeflow/kubeflow, pull requests merged in 2020-08, with the labels that each got.

#5177 Deleted GCP Click To Deploy code.
  components/gcp-click-to-deploy/.gitignore
  components/gcp-click-to-deploy/Dockerfile
  components/gcp-click-to-deploy/Makefile
  components/gcp-click-to-deploy/OWNERS
  components/gcp-click-to-deploy/README.md
  components/gcp-click-to-deploy/app-config.yaml
  components/gcp-click-to-deploy/build_serve.sh
  components/gcp-click-to-deploy/ks-app/.gitignore
  components/gcp-click-to-deploy/ks-app/app.yaml
  components/gcp-click-to-deploy/ks-app/components/clusterrole-external-dns.yaml
  components/gcp-click-to-deploy/ks-app/components/clusterrolebinding-external-dns-viewer.yaml
  components/gcp-click-to-deploy/ks-app/components/deployment-external-dns.yaml
  components/gcp-click-to-deploy/ks-app/components/ingress.jsonnet
  components/gcp-click-to-deploy/ks-app/components/params.libsonnet
  components/gcp-click-to-deploy/ks-app/components/serviceaccount-external-dns.yaml
  components/gcp-click-to-deploy/ks-app/components/webapp.jsonnet
  components/gcp-click-to-deploy/ks-app/create_gcp_deploy_sa.sh
  components/gcp-click-to-deploy/ks-app/environments/base.libsonnet
  components/gcp-click-to-deploy/ks-app/environments/default/globals.libsonnet
  components/gcp-click-to-deploy/ks-app/environments/default/main.jsonnet
  components/gcp-click-to-deploy/ks-app/environments/default/params.libsonnet
  components/gcp-click-to-deploy/module_types.d.ts
  components/gcp-click-to-deploy/package-lock.json
  components/gcp-click-to-deploy/package.json
  components/gcp-click-to-deploy/public/favicon.ico
  components/gcp-click-to-deploy/public/index.html
  components/gcp-click-to-deploy/public/manifest.json
  components/gcp-click-to-deploy/src/App.tsx
  components/gcp-click-to-deploy/src/Css.ts
  components/gcp-click-to-deploy/src/DeployForm.tsx
  components/gcp-click-to-deploy/src/Gapi.ts
  components/gcp-click-to-deploy/src/Header.tsx
  components/gcp-click-to-deploy/src/Page404.tsx
  components/gcp-click-to-deploy/src/Splash.tsx
  components/gcp-click-to-deploy/src/Utils.ts
  components/gcp-click-to-deploy/src/hero.png
  components/gcp-click-to-deploy/src/index.tsx
  components/gcp-click-to-deploy/src/kubeflow-text.svg
  components/gcp-click-to-deploy/src/logo.svg
  components/gcp-click-to-deploy/tsconfig.json
  components/gcp-click-to-deploy/tsconfig.prod.json
  components/gcp-click-to-deploy/tsconfig.test.json
  components/gcp-click-to-deploy/tslint.json
Labels: approved, cla: yes, lgtm, size/XXL

#5174 logout on Central dashboard
  components/centraldashboard/public/assets/icons/logout.svg
  components/centraldashboard/public/components/main-page.css
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, size/S

#5118 Fix #4842 Pod resources limit
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5184 Create a new directory in components for web apps
  components/crud-web-apps/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5016 Bumping central dashboard node version to v12.18.3
  components/centraldashboard/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5088 Add OWNERs file to tensorboard controller
  components/tensorboard-controller/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5164 Common code between the different python backends
  components/crud-web-apps/common/README.md
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/custom_resource.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/namespace.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pod.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/poddefault.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/secret.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/storageclass.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/utils.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authn.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authz.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/config.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/decorators.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/handlers.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/utils.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/probes.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/requirements.txt
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/rok/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/rok/routes.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/routes/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/routes/get.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/serving.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/status.py
  components/crud-web-apps/common/backend/setup.py
Labels: approved, cla: yes, lgtm, size/XL

#5112 Fix #5111: Trim whitespace from custom images
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.ts
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5208 Add step for outdated banner to release guide
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5180 tensorboard web-app: Create Tensorboard web-app backend
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py
  components/crud-web-apps/tensorboards/backend/Makefile
  components/crud-web-apps/tensorboards/backend/app/__init__.py
  components/crud-web-apps/tensorboards/backend/app/routes/__init__.py
  components/crud-web-apps/tensorboards/backend/app/routes/delete.py
  components/crud-web-apps/tensorboards/backend/app/routes/get.py
  components/crud-web-apps/tensorboards/backend/app/routes/post.py
  components/crud-web-apps/tensorboards/backend/app/utils.py
  components/crud-web-apps/tensorboards/backend/entrypoint.py
Labels: approved, cla: yes, lgtm, size/L

#5229 poddefaults: Add OWNERS file
  components/admission-webhook/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5240 Add owners for the Notebooks Controller
  components/notebook-controller/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5222 Remove deadcode and add OWNERs files
  components/echo-server/OWNERS
  components/gatekeeper/Dockerfile
  components/gatekeeper/Makefile
  components/gatekeeper/README.md
  components/gatekeeper/auth/AuthServer.go
  components/gatekeeper/cmd/gatekeeper/main.go
  components/gatekeeper/cmd/gatekeeper/options/options.go
  components/gatekeeper/go.mod
  components/gatekeeper/go.sum
  components/https-redirect/Dockerfile
  components/https-redirect/Makefile
  components/https-redirect/main.py
  components/https-redirect/main_test.py
  components/https-redirect/requirements.txt
  components/image-releaser/.gitignore
  components/image-releaser/app.yaml
  components/image-releaser/components/params.libsonnet
  components/image-releaser/components/tf-notebook-workflow.jsonnet
  components/image-releaser/components/tf-notebook-workflow.libsonnet
  components/image-releaser/components/tf-serving-workflow.jsonnet
  components/image-releaser/components/tf-serving-workflow.libsonnet
  components/image-releaser/components/util.libsonnet
  components/image-releaser/environments/base.libsonnet
  components/image-releaser/environments/releasing/globals.libsonnet
  components/image-releaser/environments/releasing/main.jsonnet
  components/image-releaser/environments/releasing/params.libsonnet
  components/ingress-setup-image/OWNERS
  components/kflogin/.gitignore
  components/kflogin/Dockerfile
  components/kflogin/Makefile
  components/kflogin/README.md
  components/kflogin/package-lock.json
  components/kflogin/package.json
  components/kflogin/public/favicon.ico
  components/kflogin/public/index.html
  components/kflogin/public/manifest.json
  components/kflogin/src/App.css
  components/kflogin/src/App.js
  components/kflogin/src/App.test.js
  components/kflogin/src/index.js
  components/kflogin/src/login.js
  components/kflogin/src/logo.svg
  components/private-utils/OWNERS
  components/static-config-server/OWNERS
Labels: approved, cla: yes, lgtm, size/XXL

#5218 Tensorboard controller: Add scheduling functionality for Tensorboard servers that use RWO PVCs as log storages
  components/tensorboard-controller/controllers/tensorboard_controller.go
  components/tensorboard-controller/main.go
Labels: approved, cla: yes, lgtm, size/L

#5259 Tensorboard web-app: Add functionality to inform TWA frontend about the status of Tensorboard servers
  components/crud-web-apps/tensorboards/backend/app/routes/get.py
  components/crud-web-apps/tensorboards/backend/app/utils.py
  components/crud-web-apps/tensorboards/backend/requirements.txt
  components/tensorboard-controller/api/v1alpha1/tensorboard_types.go
  components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, size/L

#5262 Add roles for Tensorboard controller pod
  components/tensorboard-controller/Makefile
  components/tensorboard-controller/README.md
  components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
  components/tensorboard-controller/config/rbac/role.yaml
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, size/L

#5249 Upgrade jupyter-web-app to Angular 8
  components/jupyter-web-app/frontend/browserslist
  components/jupyter-web-app/frontend/package-lock.json
  components/jupyter-web-app/frontend/package.json
  components/jupyter-web-app/frontend/src/app/app.module.ts
  components/jupyter-web-app/frontend/src/app/main-table/resource-table/confirm-dialog/confirm-dialog.component.ts
  components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.ts
  components/jupyter-web-app/frontend/src/app/services/snack-bar.service.ts
  components/jupyter-web-app/frontend/src/app/services/snack-bar/snack-bar.component.ts
  components/jupyter-web-app/frontend/src/app/utils/imports.ts
  components/jupyter-web-app/frontend/tsconfig.json
  components/jupyter-web-app/frontend/tslint.json
Labels: approved, cla: yes, lgtm, size/XXL

#5237 Add support for Tolerations and Affinity in Notebooks
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml
  components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml
  components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
  components/jupyter-web-app/frontend/src/app/app.module.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.scss
  components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.spec.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.scss
  components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.spec.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.ts
  components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.html
  components/jupyter-web-app/frontend/src/app/utils/common.ts
  components/jupyter-web-app/frontend/src/app/utils/types.ts
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5266 Add RWO_PVC_SCHEDULING env var to the Tensorboard Controller deployment
  components/tensorboard-controller/README.md
  components/tensorboard-controller/config/manager/manager.yaml
Labels: approved, cla: yes, lgtm, size/S

#5267 Add TWA frontend
  components/crud-web-apps/tensorboards/Dockerfile
  components/crud-web-apps/tensorboards/Dockerfile.dockerignore
  components/crud-web-apps/tensorboards/Makefile
  components/crud-web-apps/tensorboards/README.md
  components/crud-web-apps/tensorboards/deploy/app-rbac.yaml
  components/crud-web-apps/tensorboards/deploy/app.yaml
  components/crud-web-apps/tensorboards/frontend/.editorconfig
  components/crud-web-apps/tensorboards/frontend/.gitignore
  components/crud-web-apps/tensorboards/frontend/.prettierrc
  components/crud-web-apps/tensorboards/frontend/README.md
  components/crud-web-apps/tensorboards/frontend/angular.json
  components/crud-web-apps/tensorboards/frontend/browserslist
  components/crud-web-apps/tensorboards/frontend/e2e/protractor.conf.js
  components/crud-web-apps/tensorboards/frontend/e2e/src/app.e2e-spec.ts
  components/crud-web-apps/tensorboards/frontend/e2e/src/app.po.ts
  components/crud-web-apps/tensorboards/frontend/e2e/tsconfig.json
  components/crud-web-apps/tensorboards/frontend/karma.conf.js
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/src/app/app-routing.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.scss
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/app.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.scss
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.scss
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/tensorboards/frontend/src/app/types.ts
  components/crud-web-apps/tensorboards/frontend/src/assets/.gitkeep
  components/crud-web-apps/tensorboards/frontend/src/environments/environment.prod.ts
  components/crud-web-apps/tensorboards/frontend/src/environments/environment.ts
  components/crud-web-apps/tensorboards/frontend/src/favicon.ico
  components/crud-web-apps/tensorboards/frontend/src/index.html
  components/crud-web-apps/tensorboards/frontend/src/kubeflow.css
  components/crud-web-apps/tensorboards/frontend/src/main.ts
  components/crud-web-apps/tensorboards/frontend/src/polyfills.ts
  components/crud-web-apps/tensorboards/frontend/src/styles.scss
  components/crud-web-apps/tensorboards/frontend/src/test.ts
  components/crud-web-apps/tensorboards/frontend/tsconfig.app.json
  components/crud-web-apps/tensorboards/frontend/tsconfig.json
  components/crud-web-apps/tensorboards/frontend/tsconfig.spec.json
  components/crud-web-apps/tensorboards/frontend/tslint.json
Labels: approved, cla: yes, lgtm, size/XXL
