Repository kubeflow/kubeflow, pull requests merged in 2020-01, with the labels that each got.

#4623 Add licensing info for Notebook Controller
  components/notebook-controller/Makefile
  components/notebook-controller/third_party/README.md
  components/notebook-controller/third_party/additional_license_info.csv
  components/notebook-controller/third_party/check-license.sh
  components/notebook-controller/third_party/concatenate_license.py
  components/notebook-controller/third_party/dep.txt
  components/notebook-controller/third_party/dep_repo.manual.csv
  components/notebook-controller/third_party/license.txt
  components/notebook-controller/third_party/license_info.csv
  components/notebook-controller/third_party/repo.txt
Labels: approved, cla: yes, lgtm, size/XXL

#4625 generate license for kfam image; switch to a distroless base image
  components/access-management/Dockerfile
  components/access-management/Makefile
  components/access-management/third_party/library/license.txt
  components/access-management/third_party_licenses/additional_license_info.csv
  components/access-management/third_party_licenses/dep.txt
  components/access-management/third_party_licenses/dep_repo.manual.csv
  components/access-management/third_party_licenses/license_info.csv
  components/access-management/third_party_licenses/repo.txt
Labels: approved, cla: yes, lgtm, size/XXL

#4622 generate license for profile controller image
  components/profile-controller/Dockerfile
  components/profile-controller/third_party/library/license.txt
  components/profile-controller/third_party_licenses/additional_license_info.csv
  components/profile-controller/third_party_licenses/dep.txt
  components/profile-controller/third_party_licenses/dep_repo.manual.csv
  components/profile-controller/third_party_licenses/license_info.csv
  components/profile-controller/third_party_licenses/repo.txt
Labels: approved, cla: yes, lgtm, size/XXL

#4628 change profile image base to gcr.io/distroless/base
  components/profile-controller/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4631 Fix notebook controller and tensorboard controller docker image build.
  components/common/go.mod
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/tensorboard-controller/go.mod
  components/tensorboard-controller/go.sum
Labels: approved, cla: yes, lgtm, size/M

#4626 JWA: Add readiness/liveness probes
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
Labels: approved, cla: yes, lgtm, size/M

#4633 move profile e2e test to py/kubeflow/kubeflow/ci
  kubeflow/profiles/tests/sample_profile.yaml
  py/kubeflow/kubeflow/ci/profiles_test.py
  py/kubeflow/kubeflow/ci/test_data/profile_v1beta1_profile.yaml
Labels: approved, cla: yes, lgtm, size/S

#4214 [3772][jupyter-web-app] Surface notebook events as extra information
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4641 Update notebook Controller Dockerfile
  components/notebook-controller/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4640 add hashicorp/golang-lru source code to kfam image
  components/access-management/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4643 Add source code for MPL licensed library
  components/notebook-controller/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4632 Add third party licenses for Jupyter web app backend
  components/jupyter-web-app/Dockerfile
  components/jupyter-web-app/backend/Pipfile
  components/jupyter-web-app/backend/Pipfile.lock
  components/jupyter-web-app/backend/third_party/license.txt
  components/jupyter-web-app/backend/third_party/license_info.csv
Labels: approved, cla: yes, lgtm, size/XXL

#4649 Add Notebook Controller v1 spec
  components/notebook-controller/PROJECT
  components/notebook-controller/api/v1/groupversion_info.go
  components/notebook-controller/api/v1/notebook_conversion.go
  components/notebook-controller/api/v1/notebook_types.go
  components/notebook-controller/api/v1/zz_generated.deepcopy.go
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/main.go
Labels: approved, cla: yes, lgtm, size/L

#4655 remove lluunn from owners
  OWNERS
  components/profile-controller/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4657 add hashicorp/golang-lru source code to profile controller image
  components/profile-controller/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4658 update kfctl server
  bootstrap/cmd/bootstrap/app/kfctlClient.go
  bootstrap/cmd/bootstrap/app/kfctlServer.go
  bootstrap/cmd/bootstrap/app/kfctlServer_test.go
  bootstrap/cmd/bootstrap/app/router.go
  bootstrap/go.mod
  bootstrap/go.sum
Labels: approved, cla: yes, lgtm, size/XL

#4614 Jupyter-Web-App: Support for selecting GPUs
  components/jupyter-web-app/backend/Makefile
  components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/settings.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml
  components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
  components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
  components/jupyter-web-app/backend/main.py
  components/jupyter-web-app/frontend/.prettierrc
  components/jupyter-web-app/frontend/package.json
  components/jupyter-web-app/frontend/src/app/app.module.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-advanced-options/form-advanced-options.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.scss
  components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.spec.ts
  components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.ts
  components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.html
  components/jupyter-web-app/frontend/src/app/utils/common.ts
  components/jupyter-web-app/frontend/src/app/utils/types.ts
Labels: approved, cla: yes, lgtm, size/XL

#4659 [CentralDashboard] Namespace defaulting and validation
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/components/namespace-selector_test.js
Labels: approved, area/centraldashboard, area/front-end, cla: yes, lgtm, priority/p1, size/M

#4663 update profile api version to v1
  components/profile-controller/PROJECT
  components/profile-controller/api/v1/groupversion_info.go
  components/profile-controller/api/v1/profile_types.go
  components/profile-controller/api/v1/zz_generated.deepcopy.go
  components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
  components/profile-controller/config/crd/kustomization.yaml
  components/profile-controller/config/crd/patches/trivial_conversion_patch.yaml
  components/profile-controller/config/samples/profile_v1_profile.yaml
  components/profile-controller/controllers/plugin_workload_identity.go
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/suite_test.go
  components/profile-controller/main.go
Labels: approved, cla: yes, lgtm, size/L

#4544 Fix annotation/label injection in admission hook
  components/admission-webhook/main.go
  components/admission-webhook/main_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4664 Fix docker builds of notebook and tensorboard controller
  components/notebook-controller/Dockerfile
  components/notebook-controller/Makefile
  components/notebook-controller/developer_guide.md
  components/notebook-controller/gcb_build.jsonnet
  components/notebook-controller/skaffold.yaml
  components/tensorboard-controller/Dockerfile
  components/tensorboard-controller/skaffold.yaml
Labels: approved, cla: yes, lgtm, size/L

#4675 Add license for cffi in Jupyter Web App
  components/jupyter-web-app/backend/third_party/license.txt
  components/jupyter-web-app/backend/third_party/license_info.csv
Labels: approved, cla: yes, lgtm, size/M

#4676 add prometheus metrics for profile controller
  components/profile-controller/Dockerfile
  components/profile-controller/controllers/moniotring.go
  components/profile-controller/controllers/profile_controller.go
Labels: approved, cla: yes, lgtm, size/L

#4674 kfam: prometheus monitoring integration
  components/access-management/go.mod
  components/access-management/go.sum
  components/access-management/kfam/api_default.go
  components/access-management/kfam/monitoring.go
  components/access-management/kfam/routers.go
Labels: approved, cla: yes, lgtm, size/L

#4682 profile controller: remove unused tag
  components/profile-controller/controllers/moniotring.go
Labels: approved, cla: yes, lgtm, size/XS

#4683 use controller runtime metrics registry
  components/profile-controller/controllers/moniotring.go
  components/profile-controller/go.mod
Labels: approved, cla: yes, lgtm, size/S

#4688 Add release instructions for using the new CD infrastructure.
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/S

#4684 [centraldashboard] Sync iframe href on hashchange too
  components/centraldashboard/public/components/iframe-container.js
  components/centraldashboard/public/components/iframe-container_test.js
Labels: approved, cla: yes, lgtm, size/S

#4665 Updated website versioning procedure for new banner on archived doc branches
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/M

#4686 Delete the old jupyter release infrastructure
  py/kubeflow/kubeflow/ci/update_jupyter_web_app.py
  releasing/auto-update/README.md
  releasing/auto-update/base/kustomization.yaml
  releasing/auto-update/base/params.yaml
  releasing/auto-update/base/scripts.yaml
  releasing/auto-update/overlays/cron/kustomization.yaml
  releasing/auto-update/overlays/cron/update_job_cron.yaml
  releasing/auto-update/overlays/job/kustomization.yaml
  releasing/auto-update/overlays/job/update_job.yaml
Labels: approved, cla: yes, lgtm, size/XL

#4710 Remove authorization check for events (kubeflow/kubeflow#4699)
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
Labels: approved, cla: yes, lgtm, size/XS

#4715 Automated cherry pick of #4710: Remove authorization check for events Cherry pick of #4710 on v1.0-branch. #4710: Remove authorization check for events
  components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
Labels: approved, cla: yes, lgtm, size/XS
