Repository kubeflow/kubeflow, pull requests merged in 2020-12, with the labels that each got.

#5309 Use valid commit for kubeflow/components/common module.
  components/notebook-controller/go.mod
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5464 Centraldashboard: Clean up OWNERS file
  components/centraldashboard/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5469 centraldashboard: redirect non-iframed apps
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/config/centraldashboard-config.yaml
  components/centraldashboard/public/library.js
Labels: approved, cla: yes, lgtm, size/M

#5481 web-apps(front): Update the README
  components/crud-web-apps/common/frontend/kubeflow-common-lib/README.md
Labels: approved, cla: yes, lgtm, size/M

#5472 web-apps(back): Add CSRF protection mechanisms to the backends
  components/crud-web-apps/common/README.md
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/csrf.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/serving.py
Labels: approved, cla: yes, lgtm, size/L
