Repository kubeflow/kubeflow, pull requests merged in 2020-05, with the labels that each got.

#5015 Enable kfam, admission_webhook on arm64
  components/access-management/Dockerfile
  components/admission-webhook/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#5027 Consistent components names and fixed indentation
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/S

#5033 Add missing `login` command for gcloud authentication
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/XS

#4979 Pr/email escape (issue 4970)
  components/access-management/kfam/bindings.go
  components/access-management/kfam/bindings_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4933 print orignial error when failed enabling GCP APIs
  components/gcp-click-to-deploy/src/DeployForm.tsx
Labels: approved, cla: yes, lgtm, size/XS
