Repository kubeflow/kubeflow, pull requests merged in 2020-11, with the labels that each got.

#5374 Fixes the default leader election ID
  components/notebook-controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5353 Allow intra namespace traffic by default
  components/profile-controller/controllers/profile_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5382 wg-notebooks: Update OWNERS files
  components/access-management/OWNERS
  components/admission-webhook/OWNERS
  components/centraldashboard/OWNERS
  components/jupyter-web-app/OWNERS
  components/profile-controller/OWNERS
  components/tensorflow-notebook-image/OWNERS
Labels: cla: yes, size/S

#5385 Fixes the leader election ID
  components/profile-controller/main.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#5383 Included the instructions to contribute notebook-controller.
  components/notebook-controller/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#5378 Implemented functional tests using ginkgo for notebook controller
  components/notebook-controller/.gitignore
  components/notebook-controller/Makefile
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/config/rbac/role.yaml
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/controllers/notebook_controller_bdd_test.go
  components/notebook-controller/controllers/suite_test.go
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5351 Fix development README for central dashboard
  components/centraldashboard/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5408 update OWNERS
  components/access-management/OWNERS
  components/admission-webhook/OWNERS
  components/centraldashboard/OWNERS
  components/profile-controller/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#5404 Remove metadata link from centraldashboard
  components/centraldashboard/config/centraldashboard-links-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5412 Automated cherry pick of #5404: Remove metadata link from centraldashboard
  components/centraldashboard/config/centraldashboard-links-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5425 Remove components no longer being maintained
  components/build_image.py
  components/echo-server/Dockerfile
  components/echo-server/Makefile
  components/echo-server/OWNERS
  components/echo-server/main.py
  components/echo-server/main_test.py
  components/echo-server/requirements.txt
  components/ingress-setup-image/Dockerfile
  components/ingress-setup-image/OWNERS
  components/ingress-setup-image/README.md
  components/openmpi-controller/.gitignore
  components/openmpi-controller/Dockerfile
  components/openmpi-controller/Makefile
  components/openmpi-controller/OWNERS
  components/openmpi-controller/controller/__init__.py
  components/openmpi-controller/controller/controller.py
  components/openmpi-controller/controller/main.py
  components/openmpi-controller/controller/util.py
  components/openmpi-controller/requirements.txt
  components/private-utils/Dockerfile
  components/private-utils/OWNERS
  components/static-config-server/Dockerfile
  components/static-config-server/Makefile
  components/static-config-server/OWNERS
  components/static-config-server/README.md
  components/static-config-server/go.mod
  components/static-config-server/go.sum
  components/static-config-server/main.go
  components/tensorflow-notebook-image/README.md
  components/tensorflow-notebook-image/contrib/kaggle-notebook-image/Dockerfile
  components/tensorflow-notebook-image/contrib/kaggle-notebook-image/README.md
  components/tensorflow-notebook-image/contrib/rapidsai-notebook-image/Dockerfile
  components/tensorflow-notebook-image/contrib/rapidsai-notebook-image/README.md
Labels: approved, cla: yes, lgtm, size/XL
