Repository kubeflow/kubeflow, pull requests merged in 2020-06, with the labels that each got.

#4907 JWA: Fix UI handling of default StorageClass
  components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.ts
  components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.ts
  components/jupyter-web-app/frontend/src/app/uis/rok/utils/common.ts
  components/jupyter-web-app/frontend/src/app/utils/common.ts
  components/jupyter-web-app/frontend/src/app/utils/types.ts
Labels: approved, cla: yes, lgtm, size/L

#5058 Remove duplicate import
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#5069 tensorboard-controller: Mount GCP secret only when accessing Google storage
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5084 Update docs for releasing the website and prune root OWNERs file
  OWNERS
  docs_dev/releasing.md
Labels: approved, cla: yes, lgtm, size/XS

#5083 Fix notebook controller rbac gen
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5080 env variable driven registrationFlow
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/api_workgroup_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#5090 Update kubeflow-fairing version in notebook image
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS
