Repository kubeflow/kubeflow, pull requests merged in 2020-07, with the labels that each got.

#4468 notebook_controller.go: make clusterDomain an option
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5108 Remove sync_images.py
  releasing/sync_images.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5113 Refactoring: Deduplication
  metric-collector/service-readiness/kubeflow-readiness.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5114 Refactoring: Early Return Pattenr (if else -> if return)
  testing/kfctl/conftest.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5109 Remove test_deploy.py
  testing/test_deploy.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5120 Automated cherry pick of #5080: env driven registration flow via REGISTRATION_FLOW Cherry pick of #5080 on v1.1-branch. #5080: env driven registration flow via REGISTRATION_FLOW
  components/centraldashboard/app/api_workgroup.ts
  components/centraldashboard/app/api_workgroup_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, size/S

#5139 Update kubeflow-fairing to avoid mismatching with kfserving
  components/tensorflow-notebook-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5142 Deduplicate contributing docs
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5074 Added gpu details to the notebook server table
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.html
  components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.ts
  components/jupyter-web-app/frontend/src/app/utils/types.ts
  prow_config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5153 Adding reviewer to centraldashboard OWNERS file
  components/centraldashboard/OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5147 Rendering centraldashboard links from a configmap
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/config/centraldashboard-links-config.yaml
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5160 Add StefanoFioravanzo to Centraldashboard OWNERS
  components/centraldashboard/OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5162 Automated cherry pick of #5074: added gpu details to the notebook server table #5086: show all existing PVCs as dropdown under volumes while Cherry pick of #5074 #5086 on v1.1-branch. #5074: added gpu details to the notebook server table #5086: show all existing PVCs as dropdown under volumes while
  components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
  components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.html
  components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.ts
  components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.html
  components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.ts
  components/jupyter-web-app/frontend/src/app/utils/types.ts
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/L
