Repository kubeflow/kubeflow, pull requests merged in 2021-04, with the labels that each got.

#5804 Update notebook server base images
  components/example-notebook-servers/codeserver/Dockerfile
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/rstudio/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5809 Update second layer docker images to new tags and some python deps
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
  components/example-notebook-servers/jupyter-scipy/Dockerfile
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
  components/example-notebook-servers/rstudio-tidyverse/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#5817 Update image tags and python packages in pytorch and tensorflow full dockerfiles
  components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
Labels: approved, cla: yes, lgtm, size/S

#5811 Add CI format checks for the Jupyter web app
  components/crud-web-apps/.dockerignore
  components/crud-web-apps/jupyter/Dockerfile
  components/crud-web-apps/jupyter/Dockerfile.dockerignore
  components/crud-web-apps/jupyter/Makefile
  components/crud-web-apps/jupyter/backend/apps/common/form.py
  components/crud-web-apps/jupyter/backend/apps/common/routes/__init__.py
  components/crud-web-apps/jupyter/backend/apps/default/routes/__init__.py
  components/crud-web-apps/jupyter/backend/apps/default/routes/post.py
  components/crud-web-apps/jupyter/backend/apps/rok/routes/post.py
  components/crud-web-apps/jupyter/backend/entrypoint.py
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/jupyter/frontend/scripts/check-format-error.js
  components/crud-web-apps/jupyter/frontend/src/app/app-routing.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/app.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/app.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-affinity-tolerations/form-affinity-tolerations.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-affinity-tolerations/form-affinity-tolerations.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-configurations/form-configurations.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-data-volumes/form-data-volumes.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-gpus/form-gpus.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-name/form-name.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/volume.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-form-configurations/rok-form-configurations.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-form-configurations/rok-form-configurations.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-form-data-volumes/rok-form-data-volumes.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-form-data-volumes/rok-form-data-volumes.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-form-workspace-volume/rok-form-workspace-volume.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/rok-volume/rok-volume.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/utils.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.module.ts
  components/crud-web-apps/jupyter/frontend/src/main.ts
  components/crud-web-apps/jupyter/frontend/src/polyfills.ts
  components/crud-web-apps/jupyter/frontend/src/test.ts
  py/kubeflow/kubeflow/ci/jwa_tests.py
  py/kubeflow/kubeflow/ci/workflow_utils.py
Labels: approved, cla: yes, lgtm, size/XL

#5818 initial notebook server images README.md
  components/example-notebook-servers/README.md
  components/example-notebook-servers/image-flow-chart.png
Labels: approved, cla: yes, lgtm, size/M

#5819 tensorboard-controller: Fix scheduling unbound PVCs
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#5822 Fix profile-controller CRD pruning issue
  components/profile-controller/api/v1/profile_types.go
  components/profile-controller/api/v1beta1/profile_types.go
  components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
  components/profile-controller/go.mod
  components/profile-controller/go.sum
Labels: approved, cla: yes, lgtm, size/M

#5823 Remove Logo Trademarks from the Jupyter Web App and make logos configurable
  components/crud-web-apps/jupyter/README.md
  components/crud-web-apps/jupyter/backend/apps/common/form.py
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/types.ts
  components/crud-web-apps/jupyter/frontend/src/assets/jupyter-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/jupyterlab-logo.svg
  components/crud-web-apps/jupyter/frontend/src/assets/rstudio-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/rstudio-logo.svg
  components/crud-web-apps/jupyter/frontend/src/assets/visual-studio-code-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/visual-studio-code-logo.svg
  components/crud-web-apps/jupyter/frontend/src/environments/environment.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.ts
  components/crud-web-apps/jupyter/manifests/base/configs/logos-configmap.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  releasing/update-manifests-images
Labels: approved, cla: yes, lgtm, size/XL

#5815 Make notebook limits configurable with a multiplication factor
  components/crud-web-apps/jupyter/backend/apps/common/form.py
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
  components/crud-web-apps/jupyter/frontend/src/app/types.ts
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
Labels: approved, cla: yes, lgtm, size/L

#5834 Automated cherry pick of #5819: tensorboard-controller: Fix scheduling unbound PVCs
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#5838 Release v1.3.0-rc.1 for kubeflow/kubeflow
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: approved, cla: yes, lgtm, size/M

#5846 notebook-servers: Update JupyterLab and add Git Extension
  components/example-notebook-servers/jupyter/requirements.txt
Labels: approved, cla: yes, lgtm, size/XS
