Repository kubeflow/kubeflow, pull requests merged in 2021-03, with the labels that each got.

#5653 CI: Correct the name of the workflow
  prow_config.yaml
  py/kubeflow/kubeflow/ci/Makefile
  py/kubeflow/kubeflow/ci/common_ui_tests.py
  py/kubeflow/kubeflow/ci/common_ui_tests_runner.py
Labels: approved, cla: yes, lgtm, size/M

#5606 Fix entrypoint of crud-jwa
  components/crud-web-apps/jupyter/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5609 Central Dashboard: Move manifests development upstream
  components/centraldashboard/manifests/base/clusterrole-binding.yaml
  components/centraldashboard/manifests/base/clusterrole.yaml
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/manifests/base/deployment_patch.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/links-configmap.yaml
  components/centraldashboard/manifests/base/params.env
  components/centraldashboard/manifests/base/params.yaml
  components/centraldashboard/manifests/base/role-binding.yaml
  components/centraldashboard/manifests/base/role.yaml
  components/centraldashboard/manifests/base/service-account.yaml
  components/centraldashboard/manifests/base/service.yaml
  components/centraldashboard/manifests/base_v3/deployment_patch.yaml
  components/centraldashboard/manifests/base_v3/kustomization.yaml
  components/centraldashboard/manifests/overlays/application/application.yaml
  components/centraldashboard/manifests/overlays/application/kustomization.yaml
  components/centraldashboard/manifests/overlays/istio/kustomization.yaml
  components/centraldashboard/manifests/overlays/istio/params.yaml
  components/centraldashboard/manifests/overlays/istio/virtual-service.yaml
  components/centraldashboard/manifests/overlays/stacks/deployment_kf_config.yaml
  components/centraldashboard/manifests/overlays/stacks/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#5612 PodDefaults Webhook: Move manifests development upstream
  components/admission-webhook/manifests/bootstrap/base/cluster-role-binding.yaml
  components/admission-webhook/manifests/bootstrap/base/cluster-role.yaml
  components/admission-webhook/manifests/bootstrap/base/config-map.yaml
  components/admission-webhook/manifests/bootstrap/base/kustomization.yaml
  components/admission-webhook/manifests/bootstrap/base/params.env
  components/admission-webhook/manifests/bootstrap/base/params.yaml
  components/admission-webhook/manifests/bootstrap/base/service-account.yaml
  components/admission-webhook/manifests/bootstrap/base/stateful-set.yaml
  components/admission-webhook/manifests/bootstrap/overlays/application/application.yaml
  components/admission-webhook/manifests/bootstrap/overlays/application/kustomization.yaml
  components/admission-webhook/manifests/webhook/base/cluster-role-binding.yaml
  components/admission-webhook/manifests/webhook/base/cluster-role.yaml
  components/admission-webhook/manifests/webhook/base/crd.yaml
  components/admission-webhook/manifests/webhook/base/deployment.yaml
  components/admission-webhook/manifests/webhook/base/kustomization.yaml
  components/admission-webhook/manifests/webhook/base/mutating-webhook-configuration.yaml
  components/admission-webhook/manifests/webhook/base/params.env
  components/admission-webhook/manifests/webhook/base/params.yaml
  components/admission-webhook/manifests/webhook/base/service-account.yaml
  components/admission-webhook/manifests/webhook/base/service.yaml
  components/admission-webhook/manifests/webhook/overlays/application/application.yaml
  components/admission-webhook/manifests/webhook/overlays/application/kustomization.yaml
  components/admission-webhook/manifests/webhook/overlays/cert-manager/certificate.yaml
  components/admission-webhook/manifests/webhook/overlays/cert-manager/deployment.yaml
  components/admission-webhook/manifests/webhook/overlays/cert-manager/kustomization.yaml
  components/admission-webhook/manifests/webhook/overlays/cert-manager/mutating-webhook-configuration.yaml
  components/admission-webhook/manifests/webhook/overlays/cert-manager/params.env
  components/admission-webhook/manifests/webhook/overlays/cert-manager/params.yaml
  components/admission-webhook/manifests/webhook/v3/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XL

#5611 Profiles KFAM: Move manifests development upstream
  components/profile-controller/config/base/README.md
  components/profile-controller/config/base/cluster-role-binding.yaml
  components/profile-controller/config/base/crd.yaml
  components/profile-controller/config/base/deployment.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/params.env
  components/profile-controller/config/base/params.yaml
  components/profile-controller/config/base/service-account.yaml
  components/profile-controller/config/base/service.yaml
  components/profile-controller/config/base_v3/deployment_patch.yaml
  components/profile-controller/config/base_v3/kustomization.yaml
  components/profile-controller/config/overlays/application/application.yaml
  components/profile-controller/config/overlays/application/kustomization.yaml
  components/profile-controller/config/overlays/debug/deployment.yaml
  components/profile-controller/config/overlays/debug/kustomization.yaml
  components/profile-controller/config/overlays/debug/params.env
  components/profile-controller/config/overlays/debug/params.yaml
  components/profile-controller/config/overlays/devices/deployment.yaml
  components/profile-controller/config/overlays/devices/kustomization.yaml
  components/profile-controller/config/overlays/istio/kustomization.yaml
  components/profile-controller/config/overlays/istio/params.yaml
  components/profile-controller/config/overlays/istio/virtual-service.yaml
  components/profile-controller/config/overlays/test/app_test.yaml
  components/profile-controller/config/overlays/test/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XL

#5603 Update ROADMAP.md
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/M

#5617 profile-controller: Migrate to Istio AuthorizationPolicy
  components/profile-controller/Dockerfile
  components/profile-controller/Makefile
  components/profile-controller/README.md
  components/profile-controller/api/istiorbac/v1alpha1/groupversion_info.go
  components/profile-controller/api/istiorbac/v1alpha1/servicerole_types.go
  components/profile-controller/api/istiorbac/v1alpha1/servicerole_types_test.go
  components/profile-controller/api/istiorbac/v1alpha1/servicerolebinding_types.go
  components/profile-controller/api/istiorbac/v1alpha1/servicerolebinding_types_test.go
  components/profile-controller/api/istiorbac/v1alpha1/v1alpha1_suite_test.go
  components/profile-controller/api/istiorbac/v1alpha1/zz_generated.deepcopy.go
  components/profile-controller/api/v1/zz_generated.deepcopy.go
  components/profile-controller/api/v1beta1/zz_generated.deepcopy.go
  components/profile-controller/controllers/monitoring.go
  components/profile-controller/controllers/plugin_iam.go
  components/profile-controller/controllers/plugin_iam_test.go
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/suite_test.go
  components/profile-controller/go.mod
  components/profile-controller/go.sum
  components/profile-controller/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#5613 Jupyter Web App: Move manifests development upstream
  components/crud-web-apps/jupyter/manifests/base/cluster-role-binding.yaml
  components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment_patch.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/params.env
  components/crud-web-apps/jupyter/manifests/base/params.yaml
  components/crud-web-apps/jupyter/manifests/base/role-binding.yaml
  components/crud-web-apps/jupyter/manifests/base/role.yaml
  components/crud-web-apps/jupyter/manifests/base/service-account.yaml
  components/crud-web-apps/jupyter/manifests/base/service.yaml
  components/crud-web-apps/jupyter/manifests/base_v3/deployment_patch.yaml
  components/crud-web-apps/jupyter/manifests/base_v3/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/application/application.yaml
  components/crud-web-apps/jupyter/manifests/overlays/application/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/aws/config-map.yaml
  components/crud-web-apps/jupyter/manifests/overlays/aws/deployment-aws-patch.yaml
  components/crud-web-apps/jupyter/manifests/overlays/aws/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/params.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/XL

#5663 First iteration and common utils for Jupyter web app CD
  prow_config.yaml
  py/kubeflow/kubeflow/cd/Makefile
  py/kubeflow/kubeflow/cd/__init__.py
  py/kubeflow/kubeflow/cd/config.py
  py/kubeflow/kubeflow/cd/jwa.py
  py/kubeflow/kubeflow/cd/jwa_runner.py
  py/kubeflow/kubeflow/ci/__init__.py
  py/kubeflow/kubeflow/ci/workflow_utils.py
Labels: approved, cla: yes, lgtm, size/L

#5661 Fix build failure on admission webhook component
  components/admission-webhook/main.go
  components/admission-webhook/main_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5644 Tesorboard-Controller: use updateStatus instead of update
  components/tensorboard-controller/api/v1alpha1/tensorboard_types.go
  components/tensorboard-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5660 (Notebook-controller): Add `http-rewrite-uri` and `http-headers-request-set` annotations
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, size/M

#5690 Fix ECR registry to add /notebooks prefix
  py/kubeflow/kubeflow/cd/config.py
Labels: approved, cla: yes, lgtm, size/XS

#5685 Centraldashboard: Fix active menu item for path-based URLs
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/pipelines-card.js
Labels: approved, cla: yes, lgtm, size/L

#5709 update testing OWNERS with Notebook WG leads
  py/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5668 Rebase Fix wrong port in admission-webhook-controller #5637
  components/admission-webhook/main.go
  components/admission-webhook/manifests/webhook/base/service.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5697 Fix access-management OOMKilled during container build
  py/kubeflow/kubeflow/cd/access_management.py
  py/kubeflow/kubeflow/cd/kaniko_builder.py
  py/kubeflow/kubeflow/ci/access_management_tests.py
  py/kubeflow/kubeflow/ci/workflow_utils.py
Labels: approved, cla: yes, lgtm, size/S

#5673 Use informer / indexer to cache rolebindings
  components/access-management/kfam/api_default.go
  components/access-management/kfam/bindings.go
Labels: approved, cla: yes, lgtm, size/M

#5693 Fixes in Tensorboard web app
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py
  components/crud-web-apps/tensorboards/Dockerfile
  components/crud-web-apps/tensorboards/Makefile
  components/crud-web-apps/tensorboards/backend/app/routes/get.py
  components/crud-web-apps/tensorboards/backend/app/utils.py
  components/crud-web-apps/tensorboards/backend/entrypoint.py
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
Labels: approved, cla: yes, lgtm, size/M

#5710 web-apps: Extend common code for the apps to work in standalone mode
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authn.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authz.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/settings.py
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/enums/dashboard.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/namespace.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
Labels: approved, cla: yes, lgtm, size/M

#5706 Centraldashboard: update menu items in manifests
  components/centraldashboard/manifests/base/configmap.yaml
  components/centraldashboard/manifests/base/links-configmap.yaml
Labels: approved, cla: yes, lgtm, size/L

#5707 Add prow config for new notebook servers
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/L

#5721 jupyter-web-app: Consolidate manifests
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment_patch.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/params.env
  components/crud-web-apps/jupyter/manifests/base/service.yaml
  components/crud-web-apps/jupyter/manifests/base_v3/deployment_patch.yaml
  components/crud-web-apps/jupyter/manifests/base_v3/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/application/application.yaml
  components/crud-web-apps/jupyter/manifests/overlays/application/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/aws/config-map.yaml
  components/crud-web-apps/jupyter/manifests/overlays/aws/deployment-aws-patch.yaml
  components/crud-web-apps/jupyter/manifests/overlays/aws/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/L

#5723 Notebook Controller: Consolidate manifests
  components/notebook-controller/Makefile
  components/notebook-controller/api/v1/notebook_types.go
  components/notebook-controller/api/v1beta1/notebook_types.go
  components/notebook-controller/config/README.md
  components/notebook-controller/config/base/cluster-role-binding.yaml
  components/notebook-controller/config/base/crd.yaml
  components/notebook-controller/config/base/deployment.yaml
  components/notebook-controller/config/base/deployment_patch.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/notebook-controller/config/base/params.env
  components/notebook-controller/config/base/service-account.yaml
  components/notebook-controller/config/base/service.yaml
  components/notebook-controller/config/base_v3/deployment_patch.yaml
  components/notebook-controller/config/base_v3/kustomization.yaml
  components/notebook-controller/config/certmanager/certificate.yaml
  components/notebook-controller/config/certmanager/kustomization.yaml
  components/notebook-controller/config/certmanager/kustomizeconfig.yaml
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/config/crd/kustomization.yaml
  components/notebook-controller/config/crd/patches/old_crd.yaml
  components/notebook-controller/config/default/kustomization.yaml
  components/notebook-controller/config/manager/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/notebook-controller/config/overlays/application/application.yaml
  components/notebook-controller/config/overlays/application/kustomization.yaml
  components/notebook-controller/config/overlays/istio/deployment.yaml
  components/notebook-controller/config/overlays/istio/kustomization.yaml
  components/notebook-controller/config/overlays/istio/params.env
  components/notebook-controller/config/overlays/kubeflow/kustomization.yaml
  components/notebook-controller/config/overlays/kubeflow/patches/remove-namespace.yaml
  components/notebook-controller/config/overlays/standalone/kustomization.yaml
  components/notebook-controller/config/rbac/auth_proxy_role_binding.yaml
  components/notebook-controller/config/rbac/kustomization.yaml
  components/notebook-controller/config/rbac/leader_election_role_binding.yaml
  components/notebook-controller/config/rbac/role.yaml
  components/notebook-controller/config/rbac/role_binding.yaml
  components/notebook-controller/config/rbac/user_cluster_roles.yaml
  components/notebook-controller/config/samples/v1alpha1_notebook.yaml
  components/notebook-controller/config/samples/v1beta1_notebook.yaml
  components/notebook-controller/config/webhook/kustomization.yaml
  components/notebook-controller/config/webhook/kustomizeconfig.yaml
  components/notebook-controller/config/webhook/manifests.yaml
  components/notebook-controller/config/webhook/service.yaml
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, cla: yes, lgtm, size/XXL

#5720 centraldashboard: Consolidate manifests
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/manifests/base/deployment_patch.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/params.env
  components/centraldashboard/manifests/base/params.yaml
  components/centraldashboard/manifests/base/service.yaml
  components/centraldashboard/manifests/base_v3/deployment_patch.yaml
  components/centraldashboard/manifests/base_v3/kustomization.yaml
  components/centraldashboard/manifests/overlays/application/application.yaml
  components/centraldashboard/manifests/overlays/application/kustomization.yaml
  components/centraldashboard/manifests/overlays/istio/kustomization.yaml
  components/centraldashboard/manifests/overlays/istio/virtual-service.yaml
  components/centraldashboard/manifests/overlays/stacks/deployment_kf_config.yaml
  components/centraldashboard/manifests/overlays/stacks/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#5719 admission-webhook: Consolidate manifests
  components/admission-webhook/manifests/base/cluster-role-binding.yaml
  components/admission-webhook/manifests/base/cluster-role.yaml
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/manifests/base/deployment.yaml
  components/admission-webhook/manifests/base/kustomization.yaml
  components/admission-webhook/manifests/base/mutating-webhook-configuration.yaml
  components/admission-webhook/manifests/base/params.yaml
  components/admission-webhook/manifests/base/service-account.yaml
  components/admission-webhook/manifests/base/service.yaml
  components/admission-webhook/manifests/bootstrap/base/cluster-role-binding.yaml
  components/admission-webhook/manifests/bootstrap/base/cluster-role.yaml
  components/admission-webhook/manifests/bootstrap/base/config-map.yaml
  components/admission-webhook/manifests/bootstrap/base/kustomization.yaml
  components/admission-webhook/manifests/bootstrap/base/params.env
  components/admission-webhook/manifests/bootstrap/base/params.yaml
  components/admission-webhook/manifests/bootstrap/base/stateful-set.yaml
  components/admission-webhook/manifests/bootstrap/overlays/application/application.yaml
  components/admission-webhook/manifests/bootstrap/overlays/application/kustomization.yaml
  components/admission-webhook/manifests/overlays/cert-manager/certificate.yaml
  components/admission-webhook/manifests/overlays/cert-manager/deployment.yaml
  components/admission-webhook/manifests/overlays/cert-manager/kustomization.yaml
  components/admission-webhook/manifests/overlays/cert-manager/mutating-webhook-configuration.yaml
  components/admission-webhook/manifests/overlays/cert-manager/params.yaml
  components/admission-webhook/manifests/webhook/base/params.env
  components/admission-webhook/manifests/webhook/base/params.yaml
  components/admission-webhook/manifests/webhook/base/service-account.yaml
  components/admission-webhook/manifests/webhook/overlays/application/application.yaml
  components/admission-webhook/manifests/webhook/overlays/application/kustomization.yaml
  components/admission-webhook/manifests/webhook/overlays/cert-manager/params.env
  components/admission-webhook/manifests/webhook/v3/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#5725 Recreation: [istio-authz-kfam] Support Istio Authorization Policy in KFAM
  components/access-management/go.mod
  components/access-management/go.sum
  components/access-management/kfam/api_default.go
  components/access-management/kfam/bindings.go
  components/access-management/kfam/logger.go
  components/access-management/kfam/model_binding.go
  components/access-management/kfam/model_binding_list.go
  components/access-management/kfam/monitoring.go
  components/access-management/kfam/routers.go
  components/access-management/main.go
  components/access-management/pkg/apis/istiorbac/v1alpha1/register.go
  components/access-management/pkg/apis/kubeflow/v1beta1/register.go
Labels: approved, cla: yes, lgtm, size/L

#5729 fix notebook controller manifests
  components/notebook-controller/.gitignore
  components/notebook-controller/config/manager/params.env
  components/notebook-controller/config/manager/service-account.yaml
  components/notebook-controller/config/manager/service.yaml
Labels: approved, cla: yes, lgtm, size/S

#5727 Manifests for Tensorboards web app
  components/crud-web-apps/tensorboards/manifests/base/cluster-role-binding.yaml
  components/crud-web-apps/tensorboards/manifests/base/cluster-role.yaml
  components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/params.env
  components/crud-web-apps/tensorboards/manifests/base/params.yaml
  components/crud-web-apps/tensorboards/manifests/base/service-account.yaml
  components/crud-web-apps/tensorboards/manifests/base/service.yaml
  components/crud-web-apps/tensorboards/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/overlays/istio/params.yaml
  components/crud-web-apps/tensorboards/manifests/overlays/istio/virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/L

#5728 Manifests for the Volumes web app
  components/crud-web-apps/volumes/manifests/base/cluster-role-binding.yaml
  components/crud-web-apps/volumes/manifests/base/cluster-role.yaml
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/params.env
  components/crud-web-apps/volumes/manifests/base/params.yaml
  components/crud-web-apps/volumes/manifests/base/service-account.yaml
  components/crud-web-apps/volumes/manifests/base/service.yaml
  components/crud-web-apps/volumes/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/volumes/manifests/overlays/istio/params.yaml
  components/crud-web-apps/volumes/manifests/overlays/istio/virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/L

#5738 fix broken link
  docs/gke/README.md
Labels: approved, cla: yes, lgtm, size/XS

#5733 Prepare CI/CD configs for Notebook Server images
  py/kubeflow/kubeflow/cd/Makefile
  py/kubeflow/kubeflow/cd/config.py
  py/kubeflow/kubeflow/ci/Makefile
Labels: approved, cla: yes, lgtm, size/L

#5622 Add notebook-server-base dockerfile and CI/CD
  components/example-notebook-servers/OWNERS
  components/example-notebook-servers/base/Dockerfile
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_base.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_base_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_base_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_base_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5623 Add notebook-server-jupyter dockerfile and CI/CD
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/jupyter/requirements.txt
  components/example-notebook-servers/jupyter/s6/cont-init.d/01-copy-tmp-home
  components/example-notebook-servers/jupyter/s6/cont-init.d/02-conda-init
  components/example-notebook-servers/jupyter/s6/services.d/jupyterlab/run
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5626 Add notebook-server-jupyter-pytorch dockerfiles and CI/CD
  components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
  components/example-notebook-servers/jupyter-pytorch/requirements-cpu.txt
  components/example-notebook-servers/jupyter-pytorch/requirements-cuda.txt
  py/kubeflow/kubeflow/cd/kaniko_builder.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_tests_runner.py
  py/kubeflow/kubeflow/ci/workflow_utils.py
Labels: approved, cla: yes, lgtm, size/L

#5631 Add notebook-server-jupyter-pytorch-full dockerfiles and CI/CD
  components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  py/kubeflow/kubeflow/cd/kaniko_builder.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_full.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_full_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_full_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_full_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5739 centraldashboard: Add missing links ConfigMap
  components/centraldashboard/manifests/base/configmap.yaml
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/S

#5627 Add notebook-server-tensorflow dockerfiles and CI/CD
  components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow/requirements-cpu.txt
  components/example-notebook-servers/jupyter-tensorflow/requirements-cuda.txt
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_tensorflow.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_tensorflow_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tensorflow_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tensorflow_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5625 Add notebook-server-codeserver dockerfile and CI/CD
  components/example-notebook-servers/codeserver/Dockerfile
  components/example-notebook-servers/codeserver/s6/cont-init.d/01-copy-tmp-home
  components/example-notebook-servers/codeserver/s6/services.d/code-server/run
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_codeserver.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_codeserver_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_codeserver_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_codeserver_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5732 Add listing nodes to JWA ClusterRole for GPU vendor detection
  components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5730 Manifests for Tensorboard controller
  components/tensorboard-controller/.gitignore
  components/tensorboard-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/patches/add_controller_config.yaml
  components/tensorboard-controller/config/base/patches/add_service_account.yaml
  components/tensorboard-controller/config/base/service_account.yaml
  components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
  components/tensorboard-controller/config/manager/manager.yaml
  components/tensorboard-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/overlays/kubeflow/patches/remove-namespace.yaml
  components/tensorboard-controller/config/overlays/standalone/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#5632 Add notebook-server-jupyter-tensorflow-full dockerfiles and CI/CD
  components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_tensorflow_full.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_tensorflow_full_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tensorflow_full_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tensorflow_full_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5699 Add notebook-server-jupyter-scipy dockerfile and CI/CD
  components/example-notebook-servers/jupyter-scipy/Dockerfile
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_scipy.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_scipy_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_scipy_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_scipy_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5700 Add notebook-server-codeserver-python dockerfile and CI/CD
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/codeserver-python/requirements.txt
  components/example-notebook-servers/codeserver-python/s6/cont-init.d/02-conda-init
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_codeserver_python.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_codeserver_python_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_codeserver_python_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_codeserver_python_tests_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5646 (JWA): Add server type selector for jupterlab, vs-code and r-studio
  components/crud-web-apps/jupyter/backend/apps/common/form.py
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
  components/crud-web-apps/jupyter/backend/apps/common/yaml/notebook_template.yaml
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/backend/apps/default/routes/post.py
  components/crud-web-apps/jupyter/backend/apps/rok/routes/post.py
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/types.ts
  components/crud-web-apps/jupyter/frontend/src/assets/jupyter-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/jupyterlab-logo.svg
  components/crud-web-apps/jupyter/frontend/src/assets/rstudio-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/rstudio-logo.svg
  components/crud-web-apps/jupyter/frontend/src/assets/visual-studio-code-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/visual-studio-code-logo.svg
  components/crud-web-apps/jupyter/frontend/src/environments/environment.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.ts
Labels: approved, cla: yes, lgtm, size/XXL

#5742 Fix conda activation in notebook-server-base for JupyterLab
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/jupyter/s6/cont-init.d/02-conda-init
Labels: approved, cla: yes, lgtm, size/S

#5744 Update notebook dependency + cleanup
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/jupyter/requirements.txt
Labels: approved, cla: yes, lgtm, size/XS

#5743 Fix conda activation for JupyterLab + cleanup
  components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
  components/example-notebook-servers/jupyter-scipy/Dockerfile
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#5748 Fix conda activation for JupyterLab in full images + cleanup
  components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
Labels: approved, cla: yes, lgtm, size/M

#5753 Tensorboards web app manifests: Don't use specific namespace in base
  components/tensorboard-controller/config/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5741 Update the manifests for the Jupyter web app
  components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/params.env
Labels: approved, cla: yes, lgtm, size/M

#5754 centraldashboard: Add ConfigMap flag to force iframe redirection
  components/centraldashboard/manifests/base/configmap.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5756 set TZ in rstudio notebook image
  components/example-notebook-servers/rstudio/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5711 Add notebook-server-rstudio-tidyverse dockerfile and CI/CD
  components/example-notebook-servers/rstudio-tidyverse/Dockerfile
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_rstudio_tidyverse.py
  py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_rstudio_tidyverse_runner.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_rstudio_tidyverse_tests.py
  py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_rstudio_tidyverse_tests_runner.py
Labels: approved, cla: yes, lgtm, size/M

#5757 (JWA): update manifests with latest notebook image tags
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#5758 (JWA): Add RStudio trademark statement in Notebook Spawner UI
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.module.ts
  components/crud-web-apps/jupyter/frontend/src/assets/jupyter-icon.svg
Labels: approved, cla: yes, lgtm, size/S

#5764 web-apps: Introduce an APP_SECURE_COOKIES env var
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/csrf.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/settings.py
  components/crud-web-apps/jupyter/backend/Makefile
  components/crud-web-apps/tensorboards/backend/Makefile
  components/crud-web-apps/volumes/backend/Makefile
Labels: approved, cla: yes, lgtm, size/S

#5765 Update manifests to use ECR and fix fieldPath in kustomization files
  components/admission-webhook/manifests/base/deployment.yaml
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/manager/manager.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#5768 (manifests): Remove unused params that break newer kustomize for web apps
  components/centraldashboard/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/params.yaml
  components/centraldashboard/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/params.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/params.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/params.yaml
Labels: approved, cla: yes, lgtm, size/M

#5762 feat(profile-controller): add pipelines.kubeflow.org/enabled label to namespaces
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/profile_controller_test.go
Labels: approved, cla: yes, lgtm, size/XS

#5766 Add Tensorboards and Volumes to central-dashboard
  components/centraldashboard/config/centraldashboard-config.yaml
  components/centraldashboard/manifests/base/configmap.yaml
Labels: approved, cla: yes, lgtm, size/M

#5770 Amend the AutoML entry in the Central Dashboard
  components/centraldashboard/manifests/base/configmap.yaml
  components/centraldashboard/public/assets/icons/katib.svg
Labels: approved, cla: yes, lgtm, size/M

#5746 Establish release process
  prow_config.yaml
  py/kubeflow/kubeflow/ci/workflow_utils.py
  releasing/README.md
  releasing/update-manifests-images
  releasing/version/VERSION
Labels: approved, cla: yes, lgtm, size/L

#5777 releasing: Add WG-Notebooks leads to release owners
  releasing/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5776 Release v1.3.0-rc.0 for kubeflow/kubeflow
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: approved, cla: yes, lgtm, size/M

#5780 Specify commonLabels for tensorboard-controller
  components/tensorboard-controller/config/default/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5786 Remove jlewi as an approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5781 Automated cherry pick of #5777: releasing: Add WG-Notebooks leads to release owners Cherry pick of #5777 on v1.3-branch. #5777: releasing: Add WG-Notebooks leads to release owners
  releasing/OWNERS
Labels: approved, cla: yes, lgtm, size/XS
