Repository kubeflow/kubeflow, pull requests merged in 2021-02, with the labels that each got.

#5573 Add Notebooks WG leads as owners of components
  components/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5564 web-apps(front): Make the library tests run in CI
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/karma.conf.js
Labels: approved, cla: yes, lgtm, size/XS

#5574 Add initial owners for testing dir
  py/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5577 Add initial python files for CI
  py/kubeflow/kubeflow/ci/Makefile
  py/kubeflow/kubeflow/ci/shared_ui_tests.py
  py/kubeflow/kubeflow/ci/shared_ui_tests_runner.py
  py/kubeflow/kubeflow/ci/workflow_utils.py
Labels: approved, cla: yes, lgtm, size/L

#5585 Add redirection links to kubeflow app repo
  .github/ISSUE_TEMPLATE/config.yml
Labels: approved, cla: yes, lgtm, size/M

#5599 chore: fix issue config typo
  .github/ISSUE_TEMPLATE/config.yml
Labels: approved, cla: yes, lgtm, size/XS

#5608 Notebook Controller: Move manifests development upstream
  components/notebook-controller/config/base/cluster-role-binding.yaml
  components/notebook-controller/config/base/cluster-role.yaml
  components/notebook-controller/config/base/crd.yaml
  components/notebook-controller/config/base/deployment.yaml
  components/notebook-controller/config/base/deployment_patch.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/notebook-controller/config/base/params.env
  components/notebook-controller/config/base/service-account.yaml
  components/notebook-controller/config/base/service.yaml
  components/notebook-controller/config/base_v3/deployment_patch.yaml
  components/notebook-controller/config/base_v3/kustomization.yaml
  components/notebook-controller/config/overlays/application/application.yaml
  components/notebook-controller/config/overlays/application/kustomization.yaml
  components/notebook-controller/config/overlays/istio/deployment.yaml
  components/notebook-controller/config/overlays/istio/kustomization.yaml
  components/notebook-controller/config/overlays/istio/params.env
Labels: approved, cla: yes, lgtm, size/L

#5600 Include workflow for ui lib unittests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S
