Repository kubeflow/kubeflow, pull requests merged in 2021-05, with the labels that each got.

#5884 chore: Add comment to reference RStudio license.
  components/example-notebook-servers/rstudio/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5919 CI/CD: add kustomize build tests
  py/kubeflow/kubeflow/ci/admission_webhook_tests.py
  py/kubeflow/kubeflow/ci/central_dashboard_tests.py
  py/kubeflow/kubeflow/ci/jwa_tests.py
  py/kubeflow/kubeflow/ci/notebook_controller_tests.py
  py/kubeflow/kubeflow/ci/profile_controller_tests.py
  py/kubeflow/kubeflow/ci/tensorboard_controller_tests.py
  py/kubeflow/kubeflow/ci/twa_tests.py
  py/kubeflow/kubeflow/ci/vwa_tests.py
Labels: approved, cla: yes, lgtm, size/L

#5820 Add CI format checks for the Volumes web app
  components/crud-web-apps/jupyter/Dockerfile
  components/crud-web-apps/volumes/Dockerfile
  components/crud-web-apps/volumes/Dockerfile.dockerignore
  components/crud-web-apps/volumes/Makefile
  components/crud-web-apps/volumes/backend/apps/common/status.py
  components/crud-web-apps/volumes/backend/entrypoint.py
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/scripts/check-format-error.js
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-default/form-default.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
  components/crud-web-apps/volumes/frontend/src/app/services/backend.service.spec.ts
  components/crud-web-apps/volumes/frontend/src/main.ts
  components/crud-web-apps/volumes/frontend/src/polyfills.ts
  components/crud-web-apps/volumes/frontend/src/test.ts
  py/kubeflow/kubeflow/ci/vwa_tests.py
Labels: approved, cla: yes, lgtm, size/XL

#5925 tensorboard-controller: fix binding issue
  components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#5942 JWA: Don't override assets with logos ConfigMap
  components/crud-web-apps/jupyter/frontend/src/assets/logos/group-one-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/logos/group-one-logo.svg
  components/crud-web-apps/jupyter/frontend/src/assets/logos/group-two-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/logos/group-two-logo.svg
  components/crud-web-apps/jupyter/frontend/src/assets/logos/jupyter-icon.svg
  components/crud-web-apps/jupyter/frontend/src/assets/logos/jupyterlab-logo.svg
  components/crud-web-apps/jupyter/frontend/src/environments/environment.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.ts
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/L

#5871 Make it possible to add Namespaced menu items
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
