Repository kubeflow/kubeflow, pull requests merged in 2021-09, with the labels that each got.

#6126 Remove virtualservice timeout to prevent websocket disconnect
  components/notebook-controller/controllers/notebook_controller.go
Labels: needs-ok-to-test, size/XS, lgtm, approved, cla: yes

#6052 fix(admission-webhook): attach namespace to pod request if pod does not have it
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
Labels: size/S, needs-ok-to-test, lgtm, approved, cla: yes

#6135 Cherry picks for RC 1
  ROADMAP.md
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
  components/crud-web-apps/jupyter/backend/apps/common/form.py
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/M, lgtm, cla: yes

#6138 Fix notebook base image gpg keys
  components/example-notebook-servers/base/Dockerfile
Labels: size/XS, lgtm, approved, cla: yes

#6139 Cherry-pick: Notebooks base gpg fix
  components/example-notebook-servers/base/Dockerfile
Labels: size/XS, lgtm, approved, cla: yes

#6137 Update images for RC 1
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved, cla: yes

#6144 update links for new testing infra
  README.md
Labels: size/XS, lgtm, approved, cla: yes

#6146 Add more root OWNERS
  OWNERS
Labels: size/XS, lgtm, approved, cla: yes
