Repository kubeflow/kubeflow, pull requests merged in 2021-07, with the labels that each got.

#5939 Add support for ServiceAccountName and AutomountServiceAccountName to admission-webhook
  components/admission-webhook/main.go
  components/admission-webhook/main_test.go
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#6034 WA: Use relative paths for fetching translation files
  components/crud-web-apps/jupyter/frontend/src/app/app.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/app.module.ts
  components/crud-web-apps/volumes/frontend/src/app/app.module.ts
Labels: approved, cla: yes, lgtm, size/XS

#6055 lists roadmap in reverse chronological order
  ROADMAP.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L
