Repository kubeflow/kubeflow, pull requests merged in 2021-08, with the labels that each got.

#5873 Correct missing predicates in controller watches. Fixes #5326
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/M, needs-ok-to-test, lgtm, approved, cla: yes

#6085 [CentralDashboard] Add entry for Models web app
  components/centraldashboard/manifests/base/configmap.yaml
  components/centraldashboard/public/assets/icons/models.svg
Labels: size/XS, lgtm, approved, cla: yes

#5995 Interact with the namespace selector
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page_test.js
Labels: size/M, lgtm, approved, cla: yes, ok-to-test

#6058 fix(jwa): Fix limits calculation when limitFactor is none
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
Labels: size/M, lgtm, approved, cla: yes

#6092 Fix NaN in Kubeflow Notebooks
  components/crud-web-apps/jupyter/backend/apps/common/form.py
Labels: size/S, lgtm, approved, cla: yes, ok-to-test

#6096 Update image tags in 1.4 release branch
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved, cla: yes
