Repository kubeflow/kubeflow, pull requests merged in 2022-03, with the labels that each got.

#6383 centraldashboard: Add KServe overlay
  components/centraldashboard/manifests/overlays/kserve/kustomization.yaml
  components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml
Labels: size/L, lgtm, approved

#6391 notebooks: Don't reconcile on Events deletion
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/XS, lgtm, approved

#6394 releasing: Create v1.5.0-rc.2 images
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#6398 release: Images for the 1.5.0 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#6395 added env for app secure cookies
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/params.env
  components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
  components/crud-web-apps/tensorboards/manifests/base/params.env
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
  components/crud-web-apps/volumes/manifests/base/params.env
Labels: size/XS, lgtm, approved, ok-to-test
