Repository kubeflow/kubeflow, pull requests merged in 2022-05, with the labels that each got.

#6422 Fix kubernetes python client to v22.6.0
  components/crud-web-apps/common/backend/setup.py
Labels: size/XS, lgtm, approved, ok-to-test

#6374 Support K8s 1.22 in notebook controller
  components/notebook-controller/.dockerignore
  components/notebook-controller/Dockerfile
  components/notebook-controller/Makefile
  components/notebook-controller/PROJECT
  components/notebook-controller/README.md
  components/notebook-controller/api/v1/notebook_types.go
  components/notebook-controller/api/v1/zz_generated.deepcopy.go
  components/notebook-controller/api/v1alpha1/notebook_types.go
  components/notebook-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/api/v1beta1/notebook_types.go
  components/notebook-controller/api/v1beta1/notebook_webhook.go
  components/notebook-controller/api/v1beta1/zz_generated.deepcopy.go
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/config/crd/kustomization.yaml
  components/notebook-controller/config/crd/patches/cainjection_in_notebooks.yaml
  components/notebook-controller/config/crd/patches/old_crd.yaml
  components/notebook-controller/config/crd/patches/trivial_conversion_patch.yaml
  components/notebook-controller/config/crd/patches/webhook_in_notebooks.yaml
  components/notebook-controller/config/default/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/notebook-controller/config/rbac/role.yaml
  components/notebook-controller/config/samples/_v1_notebook.yaml
  components/notebook-controller/config/samples/_v1alpha1_notebook.yaml
  components/notebook-controller/config/samples/_v1beta1_notebook.yaml
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/controllers/suite_test.go
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/notebook-controller/main.go
  components/notebook-controller/pkg/culler/culler.go
  components/notebook-controller/skaffold.yaml
  components/notebook-controller/third_party/dep.txt
  components/notebook-controller/third_party/license.txt
Labels: size/XXL, lgtm, approved, ok-to-test

#6426 Fix vendortooltip typo
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-gpus/form-gpus.component.ts
Labels: size/XS, lgtm, approved, ok-to-test

#6453 notebooks: notebook controller config RESTClient QPS and Burst in com…
  components/notebook-controller/main.go
Labels: size/S, lgtm, approved, ok-to-test

#6459 AIP-5879 Admission Webhook 1.22 Compatibility
  components/admission-webhook/Makefile
  components/admission-webhook/README.md
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/manifests/base/mutating-webhook-configuration.yaml
  components/admission-webhook/manifests/overlays/cert-manager/mutating-webhook-configuration.yaml
  components/admission-webhook/pkg/apis/settings/v1alpha1/register.go
  components/admission-webhook/scheme.go
Labels: size/XXL, lgtm, approved, ok-to-test
