Repository kubeflow/kubeflow, pull requests merged in 2022-02, with the labels that each got.

#6295 proposal: Extend Notebook Controller to expose idleness for Jupyter
  components/proposals/20220121-jupyter-notebook-idleness.md
Labels: size/L, lgtm, approved, ok-to-test

#6266 Kubeflow Roadmap update - with 1.5 details
  ROADMAP.md
Labels: size/M, lgtm, approved

#6338 notebooks: Graceful handling of events
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/S, lgtm, approved

#6341 notebooks: Fix endless restarts
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/pkg/culler/culler.go
Labels: size/M, lgtm, approved

#6343 releasing: Update tags for v1.5.0-rc.1
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#6195 fix error comparison between pointer and pointer in "CopyStatefulSetFields"
  components/common/reconcilehelper/util.go
Labels: size/XS, lgtm, approved, cla: yes, ok-to-test
