Repository kubeflow/kubeflow, pull requests merged in 2022-07, with the labels that each got.

#6555 Introduce a mechanism to build all Kubeflow images
  .github/workflows/all_components_docker_publish.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
  components/Makefile
  components/access-management/Makefile
  components/admission-webhook/Makefile
  components/centraldashboard/Makefile
  components/crud-web-apps/jupyter/Makefile
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebook.ts
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/tensorboards/Makefile
  components/crud-web-apps/volumes/Makefile
  components/example-notebook-servers/Makefile
  components/example-notebook-servers/README.md
  components/example-notebook-servers/base/Dockerfile
  components/example-notebook-servers/base/Makefile
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/codeserver-python/Makefile
  components/example-notebook-servers/codeserver/Dockerfile
  components/example-notebook-servers/codeserver/Makefile
  components/example-notebook-servers/jupyter-pytorch-full/Makefile
  components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-pytorch/Makefile
  components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
  components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
  components/example-notebook-servers/jupyter-scipy/Dockerfile
  components/example-notebook-servers/jupyter-scipy/Makefile
  components/example-notebook-servers/jupyter-tensorflow-full/Makefile
  components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow/Makefile
  components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
  components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/jupyter/Makefile
  components/example-notebook-servers/rstudio-tidyverse/Dockerfile
  components/example-notebook-servers/rstudio-tidyverse/Makefile
  components/example-notebook-servers/rstudio/Dockerfile
  components/example-notebook-servers/rstudio/Makefile
  components/notebook-controller/Makefile
  components/notebook-controller/README.md
  components/notebook-controller/config/samples/_v1_notebook.yaml
  components/notebook-controller/config/samples/_v1alpha1_notebook.yaml
  components/notebook-controller/config/samples/_v1beta1_notebook.yaml
  components/profile-controller/Makefile
  components/tensorboard-controller/Makefile
Labels: size/XL, lgtm, approved

#6531 proposals: Show objects from all namespaces
  components/proposals/20220621-all-namespaces.md
Labels: size/M, lgtm, approved

#6542 Add support for `command` and `args` in `PodDefault`
  components/admission-webhook/main.go
  components/admission-webhook/main_test.go
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
Labels: size/L, lgtm, approved

#6577 Fix typo in notebook_controller.go
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/XS, lgtm, approved

#6578 Use controller-gen for PodDefaults
  components/admission-webhook/Makefile
  components/admission-webhook/hack/boilerplate.go.txt
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/pkg/apis/settings/v1alpha1/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved

#6464 crud-web-apps: Migrate from tslint to eslint
  components/crud-web-apps/common/frontend/kubeflow-common-lib/.eslintrc.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/angular.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/.eslintrc.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/tslint.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/tslint.json
  components/crud-web-apps/jupyter/frontend/.eslintrc.json
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/jupyter/frontend/tslint.json
  components/crud-web-apps/tensorboards/frontend/.eslintrc.json
  components/crud-web-apps/tensorboards/frontend/angular.json
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/tslint.json
  components/crud-web-apps/volumes/frontend/.eslintrc.json
  components/crud-web-apps/volumes/frontend/angular.json
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/tslint.json
Labels: size/XXL, lgtm, approved, ok-to-test

#6586 Fix ng lint
  .github/workflows/frontend_lint.yaml
  components/crud-web-apps/common/frontend/kubeflow-common-lib/.eslintrc.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/types.ts
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/src/app/types/affinity.ts
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package-lock.json
Labels: size/XL, lgtm, approved

#6583 Profile Controller, Admission webhook cherry-picks + v1.6.0-rc.1 tag
  components/admission-webhook/config.go
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/.dockerignore
  components/profile-controller/.gitignore
  components/profile-controller/Dockerfile
  components/profile-controller/Makefile
  components/profile-controller/PROJECT
  components/profile-controller/README.md
  components/profile-controller/api/v1/groupversion_info.go
  components/profile-controller/api/v1/profile_types.go
  components/profile-controller/api/v1/zz_generated.deepcopy.go
  components/profile-controller/api/v1beta1/groupversion_info.go
  components/profile-controller/api/v1beta1/profile_types.go
  components/profile-controller/api/v1beta1/zz_generated.deepcopy.go
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
  components/profile-controller/config/crd/kustomization.yaml
  components/profile-controller/config/crd/kustomizeconfig.yaml
  components/profile-controller/config/crd/patches/cainjection_in_profiles.yaml
  components/profile-controller/config/crd/patches/trivial_conversion_patch.yaml
  components/profile-controller/config/crd/patches/webhook_in_profiles.yaml
  components/profile-controller/config/default/kustomization.yaml
  components/profile-controller/config/default/manager_auth_proxy_patch.yaml
  components/profile-controller/config/manager/kustomization.yaml
  components/profile-controller/config/manager/manager.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/profile-controller/config/prometheus/kustomization.yaml
  components/profile-controller/config/prometheus/monitor.yaml
  components/profile-controller/config/rbac/auth_proxy_client_clusterrole.yaml
  components/profile-controller/config/rbac/auth_proxy_role.yaml
  components/profile-controller/config/rbac/auth_proxy_service.yaml
  components/profile-controller/config/rbac/kustomization.yaml
  components/profile-controller/config/rbac/leader_election_role_binding.yaml
  components/profile-controller/config/rbac/profile_editor_role.yaml
  components/profile-controller/config/rbac/profile_viewer_role.yaml
  components/profile-controller/config/rbac/role.yaml
  components/profile-controller/config/rbac/role_binding.yaml
  components/profile-controller/config/rbac/service_account.yaml
  components/profile-controller/config/samples/_v1_profile.yaml
  components/profile-controller/config/samples/_v1beta1_profile.yaml
  components/profile-controller/config/samples/profile_v1_aws_iam.yaml
  components/profile-controller/config/samples/profile_v1_profile.yaml
  components/profile-controller/config/samples/profile_v1beta1_profile.yaml
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/suite_test.go
  components/profile-controller/go.mod
  components/profile-controller/go.sum
  components/profile-controller/hack/boilerplate.go.txt
  components/profile-controller/main.go
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/XXL, lgtm, approved

#6561 Fix legacy of Python version information in README files.
  components/crud-web-apps/tensorboards/README.md
  components/crud-web-apps/volumes/README.md
Labels: size/S, lgtm, approved

#6559 Update few packages and images to fix critical CVEs in centraldashboard component
  components/centraldashboard/Dockerfile
  components/centraldashboard/package-lock.json
  components/centraldashboard/third_party/license.txt
  components/centraldashboard/third_party/license_info.csv
Labels: size/S, lgtm, approved

#6562 Bump Jupyter web app to Python 3.8.
  components/crud-web-apps/jupyter/Dockerfile
  components/crud-web-apps/jupyter/README.md
Labels: size/S, lgtm, approved

#6591 Extend Docker Publish workflows to be triggered on Version change
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
  releasing/version/VERSION
Labels: size/XL, lgtm, approved

#6596 Fix(Jupyter): Fix the ImageGroup object path
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
Labels: size/XS, lgtm, approved

#6597 Fix workflows for building all images when Version file changes
  .github/workflows/all_components_docker_publish.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
  components/centraldashboard/Makefile
Labels: size/L, lgtm, approved

#6598 Update Version file to tag 'v1.6.0-rc.1'
  releasing/version/VERSION
Labels: size/XS, lgtm, approved

#6603 notebooks: Fix notebook endless restarts (#6337)
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/XS, lgtm, approved

#6051 Cast nvidia.com/gpu value as string respective of K8s Resource Spec
  components/crud-web-apps/jupyter/backend/apps/common/form.py
Labels: size/XS, lgtm, approved, cla: yes, ok-to-test
