Repository kubeflow/kubeflow, pull requests merged in 2022-08, with the labels that each got.

#6620 Fix #6616: Typo on New Notebook page
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.html
Labels: size/XS, lgtm, approved

#6625 JWA(front): Fix image group one and two not showing
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
Labels: size/S, lgtm, approved

#6624 fix Profile Plugins functionality
  .github/workflows/prof_controller_unit_test.yaml
  components/profile-controller/README.md
  components/profile-controller/config/samples/_v1_profile.yaml
  components/profile-controller/config/samples/_v1_profile_aws_iam.yaml
  components/profile-controller/controllers/plugin_iam.go
  components/profile-controller/controllers/profile_controller.go
  components/profile-controller/controllers/profile_controller_test.go
Labels: size/L, lgtm, approved

#6619 Fix #6528: Mirroring Pod conditions to Notebook
  components/notebook-controller/api/v1/notebook_types.go
  components/notebook-controller/api/v1/zz_generated.deepcopy.go
  components/notebook-controller/api/v1alpha1/notebook_types.go
  components/notebook-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/api/v1beta1/notebook_types.go
  components/notebook-controller/api/v1beta1/zz_generated.deepcopy.go
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/L, lgtm, approved

#6628 Fix #6056: Update Notebook status properly
  .github/workflows/notebook_controller_unit_test.yaml
  components/notebook-controller/Makefile
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/controllers/notebook_controller_test.go
Labels: size/L, lgtm, approved

#6632 Ensure we build images for a new Version only on push events
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: size/S, lgtm, approved

#6631 release: Images for the v1.6.0-rc.2 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved
