Repository kubeflow/kubeflow, pull requests merged in 2022-11, with the labels that each got.

#6694 [wa-age-column-improvements] Improvements in the web app's age column
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
Labels: size/XS, lgtm, approved

#6696 [wa-upgrade-k8s-client] Upgrade @kubernetes/client-node in wa frontends
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/jupyter/frontend/tsconfig.json
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/tsconfig.json
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/tsconfig.json
Labels: size/XXL, lgtm, approved

#6703 Adding web apps to istio service mesh
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/authorization-policy.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/destination-rule.yaml
  components/crud-web-apps/jupyter/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
  components/crud-web-apps/tensorboards/manifests/overlays/istio/authorization-policy.yaml
  components/crud-web-apps/tensorboards/manifests/overlays/istio/destination-rule.yaml
  components/crud-web-apps/tensorboards/manifests/overlays/istio/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
  components/crud-web-apps/volumes/manifests/overlays/istio/authorization-policy.yaml
  components/crud-web-apps/volumes/manifests/overlays/istio/destination-rule.yaml
  components/crud-web-apps/volumes/manifests/overlays/istio/kustomization.yaml
Labels: size/M, lgtm, approved

#6689 add manifest parameters for notebook culling
  components/notebook-controller/config/manager/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/notebook-controller/config/manager/params.env
Labels: size/S, lgtm, approved

#6688 fix APP_SECURE_COOKIES manifest parameters
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
Labels: size/S, lgtm, approved

#6711 JWA: Fix backend unittests and add GH Action
  .github/workflows/jwa_backend_unittests.yaml
  components/crud-web-apps/jupyter/backend/apps/common/volumes_test.py
Labels: size/M, lgtm, approved

#6719 jwa: Use common date component for age
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
Labels: size/XS, lgtm, approved

#6722 tensorboard-controller: Fix tensorboard endless restarts
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: size/XS, lgtm, approved

#6718 web-apps: Ensure in-flight requests are cancelled
  components/crud-web-apps/common/frontend/kubeflow-common-lib/angular.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/poller.service.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/poller.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.ts
  components/crud-web-apps/tensorboards/frontend/angular.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
  components/crud-web-apps/tensorboards/frontend/src/proxy.conf.json
  components/crud-web-apps/volumes/backend/Makefile
  components/crud-web-apps/volumes/frontend/angular.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.ts
  components/crud-web-apps/volumes/frontend/src/proxy.conf.json
  components/crud-web-apps/volumes/frontend/src/proxy.conf.rok.json
Labels: size/L, lgtm, approved

#6732 web-apps(front): Introduce Logs Viewer component
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
Labels: size/L, lgtm, approved

#6733 web-apps(front): Introduce new Editor component
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/.eslintrc.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/karma.conf.js
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/README.md
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/interfaces/monaco.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/frontend/editor-loader.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.component.html
Labels: size/XXL, lgtm, approved

#6730 web-apps: Common code for all-namespaces
  .github/workflows/frontend_lint.yaml
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/utils.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/backend/backend.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/types.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/tsconfig.lib.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/tsconfig.json
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
Labels: size/XL, lgtm, approved

#6742 Sorting support for JWA
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
Labels: size/M, lgtm, approved

#6744 web-apps(front): Create unit tests for sorting
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/conditions-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
Labels: size/L, lgtm, approved

#6663 Remember the most recently selected namespace
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
Labels: size/S, lgtm, approved

#6743 Sorting support for VWA and TWA
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
Labels: size/S, priority/p1, lgtm, area/jupyter, approved

#6750 centraldashboard: Add support for apps in new windows
  components/centraldashboard/public/components/iframe-container.js
  components/centraldashboard/public/components/iframe-container_test.js
  components/centraldashboard/public/library.js
  components/centraldashboard/public/library_test.js
Labels: size/L, lgtm, approved

#6752 centraldashboard: Fix eslint errors
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/namespace-selector.js
Labels: size/S, lgtm, approved

#6705 Public roadmap update for v1.7
  ROADMAP.md
Labels: size/S, lgtm, approved

#6650 updated compatible base images & removed arch dependencies in different components for multiple arch support
  components/access-management/Dockerfile
  components/admission-webhook/Dockerfile
  components/crud-web-apps/jupyter/Dockerfile
  components/crud-web-apps/tensorboards/Dockerfile
  components/crud-web-apps/volumes/Dockerfile
  components/notebook-controller/Dockerfile
  components/profile-controller/Dockerfile
  components/tensorboard-controller/Dockerfile
Labels: size/M, lgtm, approved

#6754 Filtering support for the web apps
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
Labels: size/XL, lgtm, approved

#6762 web-apps(front): Enable sorting in namespace column
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/utils.ts
Labels: size/XS, lgtm, approved

#6763 Upgrade @angular/material in WAs
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
Labels: size/L, lgtm, approved

#6753 centraldashboard: Fix how the app is ran locally
  components/centraldashboard/README.md
  components/centraldashboard/webpack.config.js
Labels: size/S, lgtm, approved

#6751 Use K8s 1.25 for the tests
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/jwa_backend_unittests.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/prof_controller_kind_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/vwa_kind_test.yaml
  components/admission-webhook/manifests/test-file
  components/centraldashboard/manifests/test-file
  components/crud-web-apps/jupyter/manifests/test-file
  components/crud-web-apps/volumes/manifests/test-file
  components/notebook-controller/Makefile
  components/notebook-controller/config/testing-file
  components/profile-controller/config/testing-file
  components/tensorboard-controller/config/testing-file
  components/testing/gh-actions/install_istio.sh
  components/testing/gh-actions/install_kind.sh
  components/testing/gh-actions/kind-1-25.yaml
Labels: size/M, lgtm, approved

#6735 fix setting readOnly on gpus
  components/crud-web-apps/jupyter/README.md
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/notebook.ts
Labels: size/S, lgtm, approved

#6765 centraldashboard: Decouple backend and frontend
  components/centraldashboard-angular/OWNERS
  components/centraldashboard-angular/README.md
  components/centraldashboard-angular/backend/.eslintignore
  components/centraldashboard-angular/backend/.eslintrc.json
  components/centraldashboard-angular/backend/.gitignore
  components/centraldashboard-angular/backend/.nycrc
  components/centraldashboard-angular/backend/app/.jasmine.json
  components/centraldashboard-angular/backend/app/api.ts
  components/centraldashboard-angular/backend/app/api_test.ts
  components/centraldashboard-angular/backend/app/api_workgroup.ts
  components/centraldashboard-angular/backend/app/api_workgroup_test.ts
  components/centraldashboard-angular/backend/app/attach_user_middleware.ts
  components/centraldashboard-angular/backend/app/attach_user_middleware_test.ts
  components/centraldashboard-angular/backend/app/clients/profile_controller.ts
  components/centraldashboard-angular/backend/app/k8s_service.ts
  components/centraldashboard-angular/backend/app/k8s_service_test.ts
  components/centraldashboard-angular/backend/app/metrics_service.ts
  components/centraldashboard-angular/backend/app/metrics_service_factory.ts
  components/centraldashboard-angular/backend/app/metrics_service_factory_test.ts
  components/centraldashboard-angular/backend/app/server.ts
  components/centraldashboard-angular/backend/app/stackdriver_metrics_service.ts
  components/centraldashboard-angular/backend/app/stackdriver_metrics_service_test.ts
  components/centraldashboard-angular/backend/app/test_resources.ts
  components/centraldashboard-angular/backend/config/centraldashboard-config.yaml
  components/centraldashboard-angular/backend/package-lock.json
  components/centraldashboard-angular/backend/package.json
  components/centraldashboard-angular/backend/tsconfig.json
  components/centraldashboard-angular/backend/tslint.json
  components/centraldashboard-angular/backend/types/@google-cloud/monitoring/index.d.ts
  components/centraldashboard-angular/backend/types/index.d.ts
Labels: size/XXL, lgtm, approved

#6768 web-apps(front): Changes needed for trials table
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
Labels: size/L, lgtm, approved

#6775 jwa(front): Use new Editor component
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/existing/existing-volume.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/existing/existing-volume.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/existing/existing-volume.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.module.ts
Labels: size/M, lgtm, approved

#6776 centraldashboard: Introduce new frontend project in Angular
  components/centraldashboard-angular/README.md
  components/centraldashboard-angular/frontend/.browserslistrc
  components/centraldashboard-angular/frontend/.editorconfig
  components/centraldashboard-angular/frontend/.gitignore
  components/centraldashboard-angular/frontend/README.md
  components/centraldashboard-angular/frontend/angular.json
  components/centraldashboard-angular/frontend/karma.conf.js
  components/centraldashboard-angular/frontend/package-lock.json
  components/centraldashboard-angular/frontend/package.json
  components/centraldashboard-angular/frontend/proxy.conf.json
  components/centraldashboard-angular/frontend/src/app/app-routing.module.ts
  components/centraldashboard-angular/frontend/src/app/app.component.html
  components/centraldashboard-angular/frontend/src/app/app.component.scss
  components/centraldashboard-angular/frontend/src/app/app.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/app.component.ts
  components/centraldashboard-angular/frontend/src/app/app.module.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.module.ts
  components/centraldashboard-angular/frontend/src/assets/.gitkeep
  components/centraldashboard-angular/frontend/src/environments/environment.prod.ts
  components/centraldashboard-angular/frontend/src/environments/environment.ts
  components/centraldashboard-angular/frontend/src/favicon.ico
  components/centraldashboard-angular/frontend/src/index.html
  components/centraldashboard-angular/frontend/src/main.ts
  components/centraldashboard-angular/frontend/src/polyfills.ts
  components/centraldashboard-angular/frontend/src/styles.scss
  components/centraldashboard-angular/frontend/src/test.ts
  components/centraldashboard-angular/frontend/tsconfig.app.json
  components/centraldashboard-angular/frontend/tsconfig.json
  components/centraldashboard-angular/frontend/tsconfig.spec.json
Labels: size/XXL, lgtm, approved

#6769 jwa(front): Create distinct notebook details page
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pod.py
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/details-list/details-list-item/details-list-item.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/types.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/variables-groups-table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/variables-groups-table.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/variables-groups-table.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/variables-groups-table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/variables-groups-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles.scss
  components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/jupyter/frontend/src/app/app-routing.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/app.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configuration-info-dialog/configuration-info-dialog.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configuration-info-dialog/configuration-info-dialog.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configuration-info-dialog/configuration-info-dialog.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configuration-info-dialog/configuration-info-dialog.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/jupyter/frontend/src/app/shared/utils/error.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/condition.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/configuration.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/environmentVariablesGroup.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/notebook.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/poddefault.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/responses.ts
Labels: size/XXL, lgtm, approved

#6778 web-apps: Add support for all-namespaces in the Volumes and TensorBoards web apps
  components/centraldashboard/public/components/namespace-selector.js
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/namespace-select/namespace-select.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebook.ts
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/settings.ts
  components/crud-web-apps/jupyter/frontend/cypress/integration/main-page.spec.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/commands.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/index.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
  components/crud-web-apps/volumes/frontend/src/app/services/backend.service.ts
Labels: size/L, lgtm, approved

#6780 jwa: Update manifests to access Pods and Pods/log
  components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
Labels: size/XS, lgtm, approved

#6779 jwa(front): Add LOGS tab to the notebook details page
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pod.py
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/responses.ts
Labels: size/L, lgtm, approved
