Repository kubeflow/kubeflow, pull requests merged in 2022-10, with the labels that each got.

#6667 release: Images for the v1.6.1 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#6673 Docker -> OCI Update form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
Labels: size/XS, lgtm, approved

#6656 chore(icons): the model icon is grey instead of black
  components/centraldashboard/public/assets/icons/models.svg
Labels: size/XS, lgtm, approved

#6676 kwa(front): Fixes needed for Katib unit tests
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/conditions-table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/tsconfig.json
Labels: size/XXL, lgtm, approved

#6674 centraldashboard: Show objects from all namespaces
  components/centraldashboard/public/components/iframe-container.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/main-page_test.js
  components/centraldashboard/public/components/namespace-selector.js
  components/centraldashboard/public/library.js
Labels: size/L, lgtm, approved

#6655 Add quotes to notebook_template.yaml namespace field.
  components/crud-web-apps/jupyter/backend/apps/common/yaml/notebook_template.yaml
Labels: size/XS, lgtm, approved

#6681 fix(volume name): update formCtrl.get()
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
Labels: size/XS, lgtm, approved

#6692 Make admission-webhook port number configurable
  components/admission-webhook/main.go
Labels: size/XS, lgtm, approved
