Repository kubeflow/kubeflow, pull requests merged in 2022-06, with the labels that each got.

#6456 1st update of Kubeflow Roadmap for Kubeflow 1.6
  ROADMAP.md
Labels: size/M, lgtm, approved

#6510 Add GH actions to push images to a DockerHub registry after a merge
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: size/L, lgtm, approved

#6494 Pin alpine repository version
  components/centraldashboard/Dockerfile
Labels: size/XS, lgtm, approved

#6482 feat(Jupyter): Show group one or two only if images exists
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
Labels: size/XS, lgtm, approved, ok-to-test

#6406 Upgrade API version of `Tensorboard` CRD to `v1`
  components/tensorboard-controller/.dockerignore
  components/tensorboard-controller/.gitignore
  components/tensorboard-controller/Dockerfile
  components/tensorboard-controller/Makefile
  components/tensorboard-controller/PROJECT
  components/tensorboard-controller/api/v1alpha1/groupversion_info.go
  components/tensorboard-controller/api/v1alpha1/tensorboard_types.go
  components/tensorboard-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/tensorboard-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/patches/add_controller_config.yaml
  components/tensorboard-controller/config/base/patches/add_service_account.yaml
  components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
  components/tensorboard-controller/config/crd/kustomization.yaml
  components/tensorboard-controller/config/crd/kustomizeconfig.yaml
  components/tensorboard-controller/config/crd/patches/cainjection_in_tensorboards.yaml
  components/tensorboard-controller/config/crd/patches/webhook_in_tensorboards.yaml
  components/tensorboard-controller/config/default/kustomization.yaml
  components/tensorboard-controller/config/default/manager_auth_proxy_patch.yaml
  components/tensorboard-controller/config/default/manager_prometheus_metrics_patch.yaml
  components/tensorboard-controller/config/default/manager_webhook_patch.yaml
  components/tensorboard-controller/config/manager/controller_manager_config.yaml
  components/tensorboard-controller/config/manager/manager.yaml
  components/tensorboard-controller/config/prometheus/kustomization.yaml
  components/tensorboard-controller/config/prometheus/monitor.yaml
  components/tensorboard-controller/config/rbac/auth_proxy_client_clusterrole.yaml
  components/tensorboard-controller/config/rbac/auth_proxy_role.yaml
  components/tensorboard-controller/config/rbac/auth_proxy_role_binding.yaml
  components/tensorboard-controller/config/rbac/auth_proxy_service.yaml
  components/tensorboard-controller/config/rbac/kustomization.yaml
  components/tensorboard-controller/config/rbac/leader_election_role.yaml
  components/tensorboard-controller/config/rbac/leader_election_role_binding.yaml
  components/tensorboard-controller/config/rbac/role.yaml
  components/tensorboard-controller/config/rbac/role_binding.yaml
  components/tensorboard-controller/config/rbac/service_account.yaml
  components/tensorboard-controller/config/samples/tensorboard_v1alpha1_tensorboard.yaml
  components/tensorboard-controller/controllers/suite_test.go
  components/tensorboard-controller/controllers/tensorboard_controller.go
  components/tensorboard-controller/go.mod
  components/tensorboard-controller/go.sum
  components/tensorboard-controller/hack/boilerplate.go.txt
  components/tensorboard-controller/main.go
Labels: size/XXL, lgtm, approved, ok-to-test

#6524 Add GH actions for building manifests at any pull request
  .github/workflows/centraldb_manifests_test.yaml
  .github/workflows/jwa_manifests_test.yaml
  .github/workflows/nb_controller_manifests_test.yaml
  .github/workflows/poddefaults_manifests_test.yaml
  .github/workflows/prof_controller_manifests_test.yaml
  .github/workflows/tb_controller_manifests_test.yaml
  .github/workflows/twa_manifests_test.yaml
  .github/workflows/vwa_manifests_test.yaml
Labels: size/L, lgtm, approved

#6541 Fix typos in GH actions that build and push Docker images
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: size/XS, lgtm, approved

#6530 Add GH actions for applying manifests at any pull request
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/prof_controller_kind_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/vwa_kind_test.yaml
  components/testing/gh-actions/install_istio.sh
  components/testing/gh-actions/install_kind.sh
  components/testing/gh-actions/install_kustomize.sh
  components/testing/gh-actions/kind-1-22.yaml
Labels: size/L, lgtm, approved

#6544 jwa: Expose a last-activity column
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
Labels: size/S, lgtm, approved

#6548 release: Use DockerHub for all images
  components/admission-webhook/manifests/base/deployment.yaml
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/Makefile
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebook.ts
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/Makefile
  components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/Makefile
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/Makefile
  components/notebook-controller/README.md
  components/notebook-controller/config/base/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/notebook-controller/config/samples/_v1_notebook.yaml
  components/notebook-controller/config/samples/_v1alpha1_notebook.yaml
  components/notebook-controller/config/samples/_v1beta1_notebook.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/manager/manager.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/manager/manager.yaml
  releasing/update-manifests-images
  releasing/version/VERSION
Labels: size/L, lgtm, approved

#6554 Update install command for code server extension
  components/example-notebook-servers/codeserver-python/Dockerfile
Labels: size/XS, lgtm, approved
