Repository kubeflow/kubeflow, pull requests merged in 2022-12, with the labels that each got.

#6781 centraldashboard-angular: Create Docker and Make files
  .github/workflows/centraldb_angular_docker_build.yaml
  components/centraldashboard-angular/Dockerfile
  components/centraldashboard-angular/Makefile
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
Labels: size/M, lgtm, approved

#6782 jwa: Add EVENTS tab to Notebook details page
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py
  components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/event.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/responses.ts
Labels: size/L, lgtm, approved

#6771 Adding multi-arch support for linux-ppc64le in CI for notebook-controller
  .github/workflows/nb_controller_docker_publish.yaml
  components/notebook-controller/DUMMY_FILE
  components/notebook-controller/Makefile
Labels: size/M, lgtm, approved

#6789 web-apps: Create .gitignore file to ignore web-apps-dev files
  components/crud-web-apps/.gitignore
Labels: size/XS, lgtm, approved

#6788 VWA: Create Volume details page
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py
  components/crud-web-apps/volumes/backend/apps/default/routes/get.py
  components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
  components/crud-web-apps/volumes/frontend/src/app/app-routing.module.ts
  components/crud-web-apps/volumes/frontend/src/app/app.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/types.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.module.ts
  components/crud-web-apps/volumes/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/volumes/frontend/src/app/types/backend.ts
Labels: size/XL, lgtm, approved

#6790 jwa(front): Add YAML tab to Notebook details page
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.module.ts
  components/crud-web-apps/jupyter/frontend/src/styles.scss
Labels: size/L, lgtm, approved

#6785 Adding support for linux-ppc64le in CI for kfam multi-arch docker image
  .github/workflows/kfam_docker_publish.yaml
  components/access-management/Makefile
Labels: size/M, lgtm, approved

#6786 gh-actions: Add GH actions for centraldashboard-angular
  .github/workflows/centraldb_angular_backend_test.yaml
  .github/workflows/centraldb_angular_frontend_test.yaml
  .github/workflows/frontend_lint.yaml
  components/centraldashboard-angular/backend/package.json
  components/centraldashboard-angular/frontend/.eslintignore
  components/centraldashboard-angular/frontend/.eslintrc.json
  components/centraldashboard-angular/frontend/.prettierrc
  components/centraldashboard-angular/frontend/angular.json
  components/centraldashboard-angular/frontend/karma.conf.js
  components/centraldashboard-angular/frontend/package-lock.json
  components/centraldashboard-angular/frontend/package.json
  components/centraldashboard-angular/frontend/src/app/app.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.ts
  components/centraldashboard-angular/frontend/src/environments/environment.prod.ts
  components/centraldashboard-angular/frontend/src/environments/environment.ts
  components/centraldashboard-angular/frontend/src/main.ts
  components/centraldashboard-angular/frontend/src/polyfills.ts
  components/centraldashboard-angular/frontend/src/styles.scss
  components/centraldashboard-angular/frontend/src/test.ts
Labels: size/XXL, lgtm, approved

#6808 vwa: Update cluster role to list notebooks
  components/crud-web-apps/volumes/manifests/base/cluster-role.yaml
Labels: size/XS, lgtm, approved

#6809 Adding support for linux-ppc64le in CI for profile-controller
  .github/workflows/prof_controller_docker_publish.yaml
  components/profile-controller/Makefile
Labels: size/M, lgtm, approved

#6800 Adding support for linux/ppc64le in CI for jupyter-web-app multi-arch…
  .github/workflows/jwa_docker_publish.yaml
  components/crud-web-apps/jupyter/Makefile
Labels: size/M, lgtm, approved

#6825 Cherry-pick commits for using DockerHub for all images
  components/admission-webhook/manifests/base/deployment.yaml
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/deployment.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/notebook-controller/config/manager/manager.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/manager/manager.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/manager/manager.yaml
  releasing/update-manifests-images
Labels: size/L, lgtm, approved

#6803 Adding support for linux-ppc64le in CI for admission-webhook multi-arch docker image
  .github/workflows/poddefaults_docker_publish.yaml
  components/admission-webhook/Makefile
Labels: size/M, lgtm, approved

#6805 Adding support for linux/ppc64le in CI for tensorboard-controller multi-arch docker images.
  .github/workflows/tb_controller_docker_publish.yaml
  components/tensorboard-controller/Makefile
Labels: size/M, lgtm, approved

#6810 Adding support for linux/ppc64le in CI for tensorboard-web-app multi-arch docker images.
  .github/workflows/twa_docker_publish.yaml
  components/crud-web-apps/tensorboards/Makefile
Labels: size/M, lgtm, approved

#6823 vwa(front): Add YAML tab to Volume details page
  components/crud-web-apps/volumes/frontend/angular.json
  components/crud-web-apps/volumes/frontend/karma.conf.js
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.module.ts
Labels: size/L, lgtm, approved

#6824 twa(front): Fix unit tests
  .github/workflows/twa_frontend_tests.yaml
  components/crud-web-apps/tensorboards/frontend/angular.json
  components/crud-web-apps/tensorboards/frontend/karma.conf.js
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.spec.ts
Labels: size/L, lgtm, approved

#6787 web-apps(front): Enable source maps in WAs
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/tensorboards/frontend/angular.json
  components/crud-web-apps/volumes/frontend/angular.json
Labels: size/M, lgtm, approved

#6820 profile-controller: Extend tests for using images of each PR
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/prof_controller_kind_test.yaml
  .github/workflows/prof_controller_manifests_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
Labels: size/L, lgtm, approved

#6832 crud-web-apps: Extend tests for using images of each PR
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/jwa_manifests_test.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/twa_manifests_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_intergration_test.yaml
  .github/workflows/vwa_kind_test.yaml
  .github/workflows/vwa_manifests_test.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
Labels: size/L, lgtm, approved

#6831 tensorboard-controller: Extend tests for using images of each PR
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/tb_controller_manifests_test.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
Labels: size/L, lgtm, approved

#6830 notebook-controller: Extend tests for using images of each PR
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/nb_controller_manifests_test.yaml
  components/notebook-controller/config/base/kustomization.yaml
Labels: size/L, lgtm, approved

#6841 centraldashboard: Extend tests for using images of each PR
  .github/workflows/centraldb_angular_docker_build.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/centraldb_manifests_test.yaml
  components/centraldashboard-angular/Makefile
  components/centraldashboard/Makefile
  components/centraldashboard/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/test-file
Labels: size/L, lgtm, approved

#6836 poddefaults: Extend tests for using images of each PR
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/poddefaults_manifests_test.yaml
  components/admission-webhook/Makefile
  components/admission-webhook/manifests/base/kustomization.yaml
  components/admission-webhook/manifests/test-file
  components/testing/gh-actions/install_cert_manager.sh
Labels: size/L, lgtm, approved

#6826 jwa(front): Rework the create page
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/form.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-name/form-name.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-name/form-name.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-workspace-volume/form-workspace-volume.component.html
  components/crud-web-apps/jupyter/frontend/src/app/shared/utils/volumes/panel.ts
Labels: size/L, lgtm, approved

#6842 Fix workflows for publishing images only when PR is merged
  .github/workflows/all_components_docker_publish.yaml
  .github/workflows/centraldb_angular_docker_build.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
  components/crud-web-apps/jupyter/manifests/test-file
  components/crud-web-apps/volumes/manifests/test-file
  components/notebook-controller/config/testing-file
  components/profile-controller/config/testing-file
  components/tensorboard-controller/config/testing-file
Labels: size/XL, lgtm, approved

#6835 vwa(front): Handle query parameters and add unit tests
  .github/workflows/vwa_frontend_tests.yaml
  components/crud-web-apps/volumes/frontend/.eslintrc.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pod-groups-mock.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pods-mock.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/pvc-mock.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.ts
Labels: size/XXL, lgtm, approved

#6822 jwa(front): Add details page functionalities & unit tests
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/conditions-table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/config.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/backend/backend.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.scss
  components/crud-web-apps/jupyter/frontend/.eslintrc.json
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-mock.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/pod-mock.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/actions.service.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/actions.service.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/jupyter/frontend/src/app/services/config.ts
Labels: size/XXL, lgtm, approved

#6851 jwa(front): Add formatting/linting to JWA's frontend workflow
  .github/workflows/jwa_frontend_tests.yaml
Labels: size/S, lgtm, approved

#6848 centraldashboard-angular: Extend tests for using images of each PR
  .github/workflows/centraldb_angular_docker_build.yaml
  .github/workflows/centraldb_angular_docker_publish.yaml
  .github/workflows/centraldb_angular_intergration_test.yaml
  components/centraldashboard-angular/manifests/base/clusterrole-binding.yaml
  components/centraldashboard-angular/manifests/base/clusterrole.yaml
  components/centraldashboard-angular/manifests/base/configmap.yaml
  components/centraldashboard-angular/manifests/base/deployment.yaml
  components/centraldashboard-angular/manifests/base/kustomization.yaml
  components/centraldashboard-angular/manifests/base/params.env
  components/centraldashboard-angular/manifests/base/role-binding.yaml
  components/centraldashboard-angular/manifests/base/role.yaml
  components/centraldashboard-angular/manifests/base/service-account.yaml
  components/centraldashboard-angular/manifests/base/service.yaml
  components/centraldashboard-angular/manifests/overlays/istio/authorizationpolicy.yaml
  components/centraldashboard-angular/manifests/overlays/istio/kustomization.yaml
  components/centraldashboard-angular/manifests/overlays/istio/params.yaml
  components/centraldashboard-angular/manifests/overlays/istio/virtual-service.yaml
  components/centraldashboard-angular/manifests/overlays/kserve/kustomization.yaml
  components/centraldashboard-angular/manifests/overlays/kserve/patches/configmap.yaml
Labels: size/XL, lgtm, approved

#6849 Extend Docker Publish workflows to be triggered on Version change
  .github/workflows/centraldb_angular_docker_publish.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
  releasing/version/VERSION
Labels: size/L, lgtm, approved

#6854 Update KF manifests and gh-action workflows to use the tag=`latest`
  .github/workflows/centraldb_angular_docker_publish.yaml
  .github/workflows/centraldb_angular_intergration_test.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_intergration_test.yaml
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard-angular/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/notebook-controller/config/samples/_v1_notebook.yaml
  components/notebook-controller/config/samples/_v1alpha1_notebook.yaml
  components/notebook-controller/config/samples/_v1beta1_notebook.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
Labels: size/L, lgtm, approved

#6845 web-apps(front): Fix namespace selector bug
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
Labels: size/S, lgtm, approved

#6857 jwa(front): Link to VWA details page
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/types.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/urls.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/urls.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/urls.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/urls.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/urls.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/configurations/configurations.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/volumes.constants.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/volumes/types.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/volumes/volumes.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/volumes/volumes.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/volumes/volumes.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/volumes/volumes.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/types.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.ts
Labels: size/L, lgtm, approved

#6858 web-apps(front): Sort events & conditions tables by date
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/config.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/config.ts
  components/crud-web-apps/volumes/frontend/src/app/app.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/events/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pod-groups-mock.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pods-mock.ts
Labels: size/L, lgtm, approved

#6860 Fix Makefiles/Workflows/Manifests for the example-notebook-server images
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/example-notebook-servers/Makefile
  components/example-notebook-servers/base/Makefile
  components/example-notebook-servers/codeserver-python/Makefile
  components/example-notebook-servers/codeserver/Makefile
  components/example-notebook-servers/jupyter-pytorch-full/Makefile
  components/example-notebook-servers/jupyter-pytorch/Makefile
  components/example-notebook-servers/jupyter-scipy/Makefile
  components/example-notebook-servers/jupyter-tensorflow-full/Makefile
  components/example-notebook-servers/jupyter-tensorflow/Makefile
  components/example-notebook-servers/jupyter/Makefile
  components/example-notebook-servers/rstudio-tidyverse/Makefile
  components/example-notebook-servers/rstudio/Makefile
Labels: size/L, lgtm, approved

#6863 gh-actions: Revert changes for fetching full git history in the workflows
  .github/workflows/centraldb_angular_docker_publish.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: size/M, lgtm, approved

#6846 centraldashboard-angular(front): Add library.js, source-maps & ESLint
  components/centraldashboard-angular/Dockerfile
  components/centraldashboard-angular/frontend/.eslintrc.json
  components/centraldashboard-angular/frontend/angular.json
  components/centraldashboard-angular/frontend/package-lock.json
  components/centraldashboard-angular/frontend/package.json
  components/centraldashboard-angular/frontend/proxy.conf.json
  components/centraldashboard-angular/frontend/public/library.js
  components/centraldashboard-angular/frontend/tsconfig.json
  components/centraldashboard-angular/frontend/webpack.config.js
Labels: size/XXL, lgtm, approved

#6853 web-apps(front): Install prettier and create a frontend workflow
  .github/workflows/common_frontend_tests.yaml
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/conditions-table.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/confirm-dialog/dialog/dialog.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/date-time/date-time.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/details-list/details-list-item/details-list-item.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/details-list/details-list.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/fonts.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/advanced-options/advanced-options.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/name-namespace-inputs/name-input/name-input.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/name-namespace-inputs/name-namespace-inputs.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/positive-number-input/positive-number-input.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/positive-number-input/positive-number-input.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/rok-url-input/rok-url-input.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/step-info/step-info.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/submit-bar/submit-bar.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/validators.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/heading-subheading-row/heading-subheading-row.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/heading-subheading-row/heading-subheading-row.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/icon/icon.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/loading-spinner/loading-spinner.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/namespace-select/namespace-select.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/panel/panel.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/popover/popover.directive.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/action-button/action-button.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/action/action.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/chips-list/chips-list.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/component-value/component-value.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/status/status.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/namespace.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/poller.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/snack-bar/component/snack-bar.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/snack-bar/component/snack-bar.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/utils/kubernetes.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables-groups-table/variables-groups-table.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/scripts/check-format-error.js
Labels: size/XL, lgtm, approved
