Repository kubeflow/kubeflow, pull requests merged in 2022-09, with the labels that each got.

#6604 Fix invalid kustomization patch introduced for profile-controller manager
  components/profile-controller/config/manager/manager.yaml
Labels: size/S, lgtm, approved

#6634 update stablebot configs
  .github/stale.yml
Labels: size/M, lgtm, approved

#6600 Extend PodDefaults for support for imagePullSecrets
  components/admission-webhook/main.go
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
  components/admission-webhook/pkg/apis/settings/v1alpha1/zz_generated.deepcopy.go
Labels: size/M, lgtm, approved

#6636 release: Images for the v1.6.0 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#6637 update Kubeflow roadmap to show delivery of v1.6
  ROADMAP.md
Labels: size/XS, lgtm, approved

#6659 Fix notebook culling
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/XS, lgtm, approved

#6660 release: Images for the v1.6.1-rc.0 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved
