Repository kubeflow/kubeflow, pull requests merged in 2023-06, with the labels that each got.

#7122 ARM docker images for kubeflow components
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: kind/feature, size/S, lgtm, approved

#7116 feat(centraldashboard): Displaying metrics from Prometheus
  components/centraldashboard/app/api.ts
  components/centraldashboard/app/api_test.ts
  components/centraldashboard/app/metrics_service.ts
  components/centraldashboard/app/prometheus_metrics_service.ts
  components/centraldashboard/app/prometheus_metrics_service_test.ts
  components/centraldashboard/app/server.ts
  components/centraldashboard/app/stackdriver_metrics_service.ts
  components/centraldashboard/package-lock.json
  components/centraldashboard/package.json
  components/centraldashboard/public/components/dashboard-view.js
  components/centraldashboard/public/components/dashboard-view.pug
  components/centraldashboard/public/components/dashboard-view_test.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/resource-chart.js
  components/centraldashboard/public/components/resources/cloud-platform-data.js
Labels: size/L, lgtm, approved

#6876 Re-Introducing the Volumes Viewer
  components/pvcviewer-controller/.dockerignore
  components/pvcviewer-controller/.gitignore
  components/pvcviewer-controller/Dockerfile
  components/pvcviewer-controller/Makefile
  components/pvcviewer-controller/OWNERS
  components/pvcviewer-controller/PROJECT
  components/pvcviewer-controller/README.md
  components/pvcviewer-controller/api/v1alpha1/groupversion_info.go
  components/pvcviewer-controller/api/v1alpha1/pvcviewer_types.go
  components/pvcviewer-controller/api/v1alpha1/pvcviewer_webhook.go
  components/pvcviewer-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/pvcviewer-controller/config/certmanager/certificate.yaml
  components/pvcviewer-controller/config/certmanager/kustomization.yaml
  components/pvcviewer-controller/config/certmanager/kustomizeconfig.yaml
  components/pvcviewer-controller/config/crd/bases/kubeflow.org_pvcviewers.yaml
  components/pvcviewer-controller/config/crd/kustomization.yaml
  components/pvcviewer-controller/config/crd/kustomizeconfig.yaml
  components/pvcviewer-controller/config/crd/patches/cainjection_in_pvcviewers.yaml
  components/pvcviewer-controller/config/crd/patches/webhook_in_pvcviewers.yaml
  components/pvcviewer-controller/config/default/kustomization.yaml
  components/pvcviewer-controller/config/default/manager_auth_proxy_patch.yaml
  components/pvcviewer-controller/config/default/manager_webhook_patch.yaml
  components/pvcviewer-controller/config/default/remove_namespace.yaml
  components/pvcviewer-controller/config/default/webhookcainjection_patch.yaml
  components/pvcviewer-controller/config/manager/kustomization.yaml
  components/pvcviewer-controller/config/manager/manager.yaml
  components/pvcviewer-controller/config/prometheus/kustomization.yaml
  components/pvcviewer-controller/config/prometheus/monitor.yaml
  components/pvcviewer-controller/config/rbac/auth_proxy_client_clusterrole.yaml
  components/pvcviewer-controller/config/rbac/auth_proxy_role.yaml
  components/pvcviewer-controller/config/rbac/auth_proxy_role_binding.yaml
  components/pvcviewer-controller/config/rbac/auth_proxy_service.yaml
  components/pvcviewer-controller/config/rbac/kustomization.yaml
  components/pvcviewer-controller/config/rbac/leader_election_role.yaml
  components/pvcviewer-controller/config/rbac/leader_election_role_binding.yaml
  components/pvcviewer-controller/config/rbac/role.yaml
  components/pvcviewer-controller/config/rbac/role_binding.yaml
  components/pvcviewer-controller/config/rbac/service_account.yaml
  components/pvcviewer-controller/config/rbac/volumesviewer_editor_role.yaml
  components/pvcviewer-controller/config/rbac/volumesviewer_viewer_role.yaml
  components/pvcviewer-controller/config/samples/_v1alpha1_pvcviewer.yaml
  components/pvcviewer-controller/config/samples/kustomization.yaml
  components/pvcviewer-controller/config/webhook/kustomization.yaml
  components/pvcviewer-controller/config/webhook/kustomizeconfig.yaml
  components/pvcviewer-controller/config/webhook/manifests.yaml
  components/pvcviewer-controller/config/webhook/service.yaml
  components/pvcviewer-controller/controllers/pvcviewer_controller.go
  components/pvcviewer-controller/controllers/pvcviewer_controller_test.go
  components/pvcviewer-controller/controllers/suite_test.go
  components/pvcviewer-controller/controllers/test_setup_utils.go
  components/pvcviewer-controller/controllers/test_utils.go
  components/pvcviewer-controller/controllers/testdata/podspec_default.yaml
  components/pvcviewer-controller/go.mod
  components/pvcviewer-controller/go.sum
  components/pvcviewer-controller/hack/boilerplate.go.txt
  components/pvcviewer-controller/main.go
Labels: size/XXL, lgtm, approved
