Repository kubeflow/kubeflow, pull requests merged in 2023-10, with the labels that each got.

#7260 Only load spawner_ui_config.yaml once every 10 minutes. closes #7259
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
Labels: size/S, lgtm, approved

#7220 ci: Build ARM images for core components
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/centraldb_multi_arch_test.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/jwa_multi_arch_test.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/kfam_multi_arch_test.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/nb_controller_multi_arch_test.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/poddefaults_multi_arch_test.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/prof_controller_multi_arch_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/pvcviewer_controller_docker_publish.yaml
  .github/workflows/pvcviewer_controller_intergration_test.yaml
  .github/workflows/pvcviewer_controller_multi_arch_test.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_multi_arch_test.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/twa_multi_arch_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_intergration_test.yaml
  .github/workflows/vwa_multi_arch_test.yaml
  components/crud-web-apps/jupyter/Dockerfile
  components/crud-web-apps/tensorboards/Dockerfile
  components/crud-web-apps/volumes/Dockerfile
  releasing/update-manifests-images
Labels: size/XL, lgtm, approved

#7321 fix: set default GPU vendors list
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
Labels: size/S, lgtm, approved

#7320 fix: set default GPU vendors list
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
Labels: size/S, lgtm, approved

#7322 Bump the controller-runtime version to 0.16.2
  components/admission-webhook/Dockerfile
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
Labels: size/L, lgtm, approved

#7310 Make principals dynamic in Profiles Controller
  .github/workflows/prof_controller_unit_test.yaml
  components/access-management/kfam/bindings.go
  components/access-management/kfam/utils.go
  components/profile-controller/config/manager/kustomization.yaml
  components/profile-controller/controllers/profile_controller.go
Labels: size/M, lgtm, approved

#7335 fix: KeyError on KF 1.8
  components/crud-web-apps/jupyter/backend/apps/common/status.py
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
Labels: size/S, lgtm, approved

#7339 fix: KeyError and line length
  components/crud-web-apps/jupyter/backend/apps/common/status.py
Labels: size/XS, lgtm, approved

#7338 poddefaults: Bump golang to 1.20
  .github/workflows/poddefaults_unit_test.yaml
  components/admission-webhook/go.mod
Labels: size/XS, lgtm, approved

#7340 Cherry-pick: Only load spawner_ui_config.yaml once every 10 minutes. closes #7259
  components/crud-web-apps/jupyter/backend/apps/common/utils.py
Labels: size/S, lgtm, approved

#7341 wa(front): Make the background white of all webapps
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/styles.scss
Labels: size/XS, lgtm, approved

#7337 Cherry-pick: PodDefaults versions bump #7322 and #7338
  .github/workflows/poddefaults_unit_test.yaml
  components/admission-webhook/Dockerfile
  components/admission-webhook/go.mod
  components/admission-webhook/go.sum
  components/admission-webhook/main.go
Labels: size/L, lgtm, approved

#7345 ci: Push the multi-arch image for specific tag
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/pvcviewer_controller_docker_publish.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: size/S, lgtm, approved

#7346 Cherry-pick: Make the background white of all webapps (#7341)
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/styles.scss
Labels: size/XS, lgtm, approved

#7348 ci: bump golang version 1.17->1.20
  .github/workflows/notebook_controller_unit_test.yaml
Labels: size/XS, lgtm, approved

#7347 Release v1.8.0-rc.2
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#7352 fix: point to ~kubeflow/styles/fonts.scss
  components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
  components/centraldashboard-angular/frontend/src/styles/styles.scss
Labels: size/XS, lgtm, approved

#7353 fix: point to ~kubeflow/styles/fonts.scss
  components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
  components/centraldashboard-angular/frontend/src/styles/styles.scss
Labels: size/XS, lgtm, approved

#7351 feat: make pvcviewer istio gateway configurable
  components/pvcviewer-controller/controllers/pvcviewer_controller.go
Labels: size/S, lgtm, approved

#7375 fix: local var shadowing import
  components/crud-web-apps/jupyter/backend/apps/common/status.py
Labels: size/XS, lgtm, approved

#7376 fix: local var shadowing import
  components/crud-web-apps/jupyter/backend/apps/common/status.py
Labels: size/XS, lgtm, approved

#7378 fix: remove extra ) from env variables
  components/profile-controller/config/manager/kustomization.yaml
Labels: size/XS, lgtm, approved

#7379 fix: remove extra ) from env variables
  components/profile-controller/config/manager/kustomization.yaml
Labels: size/XS, lgtm, approved

#7381 feat: make pvcviewer istio gateway configurable (#7351)
  components/pvcviewer-controller/controllers/pvcviewer_controller.go
Labels: size/S, lgtm, approved

#7380 Release v1.8.0-rc.3
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved, do-not-merge/hold

#7383 Release v1.8.0-rc.4
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#7386 ci: fix version tagging of notebook server images
  .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
Labels: size/XS, lgtm, approved

#7387 ci: fix version tagging of notebook server images (#7386)
  .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
Labels: size/XS, lgtm, approved

#7388 Release v1.8.0-rc.5
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#7390 chore: update default filebrowser version
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
Labels: size/XS, lgtm, approved

#7398 fix: downgrade jupyterlab to 3.6.6
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/codeserver-python/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/rstudio/Dockerfile
Labels: size/M, lgtm, approved

#7400 fix: downgrade jupyterlab to 3.6.6 (#7398)
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/codeserver-python/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/rstudio/Dockerfile
Labels: size/M, lgtm, approved

#7399 Release v1.8.0-rc.6
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved
