Repository kubeflow/kubeflow, pull requests merged in 2023-07, with the labels that each got.

#7068 Adding changes to build profile-controller and admission-webhook images on pull_request.
  .github/workflows/profiles_kfam_intergration_test.yaml
  components/access-management/Makefile
  components/profile-controller/Makefile
Labels: size/S, lgtm, approved

#7175 Add GH action integration testing pvcviewer controller
  .github/workflows/pvcviewer_controller_intergration_test.yaml
Labels: size/M, lgtm, approved

#7177 fix: deprecation of 'go get' for installing modules
  components/admission-webhook/Makefile
  components/notebook-controller/Makefile
  components/pvcviewer-controller/Makefile
  components/tensorboard-controller/Makefile
Labels: size/S, lgtm, approved

#7211 (frontend): Adding style for main drawer scrollbar
  components/centraldashboard/public/components/main-page.css
Labels: size/S, lgtm, approved

#7032 Profile controller and KFAM allow unauthenticated in-cluster traffic
  components/access-management/kfam/bindings.go
  components/profile-controller/controllers/profile_controller.go
Labels: size/S, lgtm, approved

#7183 Disabling multi-arch builds for PRs and enable them on Merge for Profile Controller, Profile+KFAM, VWA &TWA
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/vwa_docker_publish.yaml
Labels: size/S, lgtm, approved

#7174 Add GH action unit testing pvcviewer controller
  .github/workflows/pvcviewer_controller_unit_test.yaml
Labels: size/S, lgtm, approved

#7173 Add GH action building pvcviewer controller
  .github/workflows/pvcviewer_controller_docker_publish.yaml
Labels: size/M, lgtm, approved

#7200 fix(api_default.go): resolve write response call order
  components/access-management/kfam/api_default.go
Labels: size/XS, lgtm, approved

#7076 feat(notebooks): propagate annotations from notebook cr to pods
  components/notebook-controller/controllers/notebook_controller.go
Labels: size/S, lgtm, approved

#7062 [wa-theme-typography]: Define theme and typography
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/popover/popover.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/snack-bar/component/snack-bar.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/fonts.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/kubeflow.css
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/styles.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/variables.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-advanced-options/form-advanced-options.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/access-modes/access-modes.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/storage-class/storage-class.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
  components/crud-web-apps/jupyter/frontend/src/index.html
  components/crud-web-apps/jupyter/frontend/src/styles.scss
  components/crud-web-apps/tensorboards/frontend/cypress/e2e/index-page.cy.ts
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.html
  components/crud-web-apps/tensorboards/frontend/src/index.html
  components/crud-web-apps/tensorboards/frontend/src/styles.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
  components/crud-web-apps/volumes/frontend/src/index.html
  components/crud-web-apps/volumes/frontend/src/styles.scss
Labels: size/L, lgtm, approved

#7178 Update PVCViewer manifests
  components/pvcviewer-controller/config/crd/bases/kubeflow.org_pvcviewers.yaml
  components/pvcviewer-controller/config/default/cainjection_patch.yaml
  components/pvcviewer-controller/config/default/dnsnames_patch.yaml
  components/pvcviewer-controller/config/default/kustomization.yaml
  components/pvcviewer-controller/config/default/kustomizeconfig.yaml
  components/pvcviewer-controller/config/rbac/role.yaml
  components/pvcviewer-controller/config/rbac/role_binding.yaml
  components/pvcviewer-controller/config/webhook/manifests.yaml
Labels: size/L, lgtm, approved
