Repository kubeflow/kubeflow, pull requests merged in 2023-01, with the labels that each got.

#6862 vwa(front): Add UI tests with Cypress
  .github/workflows/vwa_frontend_tests.yaml
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/name-namespace-inputs/name-namespace-inputs.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/urls/urls.component.ts
  components/crud-web-apps/volumes/frontend/.gitignore
  components/crud-web-apps/volumes/frontend/README.md
  components/crud-web-apps/volumes/frontend/angular.json
  components/crud-web-apps/volumes/frontend/cypress.config.ts
  components/crud-web-apps/volumes/frontend/cypress/e2e/form-dialog.cy.ts
  components/crud-web-apps/volumes/frontend/cypress/e2e/index-page.cy.ts
  components/crud-web-apps/volumes/frontend/cypress/fixtures/namespaces.json
  components/crud-web-apps/volumes/frontend/cypress/fixtures/pvcs.json
  components/crud-web-apps/volumes/frontend/cypress/fixtures/settings.json
  components/crud-web-apps/volumes/frontend/cypress/support/commands.ts
  components/crud-web-apps/volumes/frontend/cypress/support/e2e.ts
  components/crud-web-apps/volumes/frontend/e2e/protractor.conf.js
  components/crud-web-apps/volumes/frontend/e2e/src/app.e2e-spec.ts
  components/crud-web-apps/volumes/frontend/e2e/src/app.po.ts
  components/crud-web-apps/volumes/frontend/e2e/tsconfig.json
  components/crud-web-apps/volumes/frontend/package-lock.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-default/form-default.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.ts
Labels: size/XXL, lgtm, approved

#6850 twa(front): Install prettier and add gh action
  .github/workflows/twa_frontend_tests.yaml
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/scripts/check-format-error.js
  components/crud-web-apps/tensorboards/frontend/src/app/app.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.spec.ts
Labels: size/L, lgtm, approved

#6855 centraldashboard(front): Move code linting to app's frontend workflow
  .github/workflows/centraldb_angular_frontend_test.yaml
  .github/workflows/frontend_lint.yaml
  components/centraldashboard-angular/frontend/scripts/check-format-error.js
Labels: size/L, lgtm, approved

#6882 gh-actions: Create testing setup for CDB tests
  .github/workflows/centraldb_angular_frontend_test.yaml
  components/testing/gh-actions/resources/test-notebook.yaml
  components/testing/gh-actions/resources/user-profile.yaml
Labels: size/L, lgtm, approved

#6875 jwa(front): Auto update mount path
  components/crud-web-apps/jupyter/frontend/cypress/integration/form-page.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/mount/mount.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/mount/mount.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/name/name.component.html
  components/crud-web-apps/jupyter/frontend/src/app/shared/utils/volumes/forms.ts
Labels: size/L, lgtm, approved

#6856 centraldashboard-angular(front): Sync Browser and Iframe URLs
  components/centraldashboard-angular/README.md
  components/centraldashboard-angular/frontend/proxy.conf.json
  components/centraldashboard-angular/frontend/src/app/app-routing.module.ts
  components/centraldashboard-angular/frontend/src/app/app.module.ts
  components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.html
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/pipes/safe.pipe.spec.ts
  components/centraldashboard-angular/frontend/src/app/pipes/safe.pipe.ts
Labels: size/L, lgtm, approved

#6749 add support of initContainers and sideCars in poddefault
  components/admission-webhook/examples/poddefault-inject-containers.yaml
  components/admission-webhook/main.go
  components/admission-webhook/main_test.go
  components/admission-webhook/manifests/base/crd.yaml
  components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
Labels: size/XXL, lgtm, approved

#6892 cdb-angular(front): Fix Iframe's sizing to fit to screen
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.html
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.scss
Labels: size/S, lgtm, approved

#6887 [Profile controller IAM plugin] Support annotation only
  components/profile-controller/controllers/plugin_iam.go
  components/profile-controller/controllers/plugin_iam_test.go
Labels: size/M, lgtm, approved

#6891 jwa(front): Add UI tests with Cypress
  .github/workflows/jwa_frontend_tests.yaml
  components/crud-web-apps/jupyter/frontend/README.md
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/jupyter/frontend/cypress.config.ts
  components/crud-web-apps/jupyter/frontend/cypress.json
  components/crud-web-apps/jupyter/frontend/cypress/e2e/form-page.cy.ts
  components/crud-web-apps/jupyter/frontend/cypress/e2e/main-page.cy.ts
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/config.json
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/namespaces.json
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebook.ts
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebooks.json
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/poddefaults.json
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/settings.json
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/settings.ts
  components/crud-web-apps/jupyter/frontend/cypress/integration/main-page.spec.ts
  components/crud-web-apps/jupyter/frontend/cypress/plugins/index.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/commands.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/e2e.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/handlers.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/index.ts
  components/crud-web-apps/jupyter/frontend/package-lock.json
  components/crud-web-apps/jupyter/frontend/package.json
Labels: size/XXL, lgtm, approved

#6890 rstudio: Update version to properly handle X-Forwarded headers
  components/example-notebook-servers/rstudio/Dockerfile
Labels: size/S, lgtm, approved

#6874 Support Pod Defaults in Tensorboard controller
  components/tensorboard-controller/config/base/kustomization.yaml
  components/tensorboard-controller/controllers/tensorboard_controller.go
Labels: kind/feature, size/S, lgtm, priority/p2, area/jupyter, approved

#6873 make: Build KF images in parallel
  components/Makefile
  components/example-notebook-servers/Makefile
  components/example-notebook-servers/codeserver-python/Makefile
  components/example-notebook-servers/codeserver/Makefile
  components/example-notebook-servers/jupyter-pytorch-full/Makefile
  components/example-notebook-servers/jupyter-pytorch/Makefile
  components/example-notebook-servers/jupyter-scipy/Makefile
  components/example-notebook-servers/jupyter-tensorflow-full/Makefile
  components/example-notebook-servers/jupyter-tensorflow/Makefile
  components/example-notebook-servers/jupyter/Makefile
  components/example-notebook-servers/rstudio-tidyverse/Makefile
  components/example-notebook-servers/rstudio/Makefile
Labels: size/L, lgtm, approved

#6903 jwa(front): Fix ENV vars bug in details page
  components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
  components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.ts
Labels: size/L, lgtm, approved

#6861 Updating central-board Dockerfile for multi-arch support
  components/centraldashboard/Dockerfile
Labels: size/M, lgtm, approved

#6896 twa(front): Add UI tests with Cypress
  .github/workflows/twa_frontend_tests.yaml
  components/crud-web-apps/tensorboards/frontend/README.md
  components/crud-web-apps/tensorboards/frontend/angular.json
  components/crud-web-apps/tensorboards/frontend/cypress.config.ts
  components/crud-web-apps/tensorboards/frontend/cypress/e2e/form-dialog.cy.ts
  components/crud-web-apps/tensorboards/frontend/cypress/e2e/index-page.cy.ts
  components/crud-web-apps/tensorboards/frontend/cypress/fixtures/namespaces.json
  components/crud-web-apps/tensorboards/frontend/cypress/fixtures/settings.json
  components/crud-web-apps/tensorboards/frontend/cypress/fixtures/tensorboards.json
  components/crud-web-apps/tensorboards/frontend/cypress/support/commands.ts
  components/crud-web-apps/tensorboards/frontend/cypress/support/e2e.ts
  components/crud-web-apps/tensorboards/frontend/e2e/protractor.conf.js
  components/crud-web-apps/tensorboards/frontend/e2e/src/app.e2e-spec.ts
  components/crud-web-apps/tensorboards/frontend/e2e/src/app.po.ts
  components/crud-web-apps/tensorboards/frontend/package-lock.json
  components/crud-web-apps/tensorboards/frontend/package.json
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.html
Labels: size/XXL, lgtm, approved

#6807 Implement a culling controller for Notebooks
  components/notebook-controller/Makefile
  components/notebook-controller/README.md
  components/notebook-controller/controllers/culling_controller.go
  components/notebook-controller/controllers/culling_controller_test.go
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/hack/dev_culling_authorization_policy.yaml
  components/notebook-controller/main.go
  components/notebook-controller/pkg/culler/culler.go
Labels: size/XXL, lgtm, approved

#6911 centraldashboard: Rename Models to Endpoints
  components/centraldashboard/manifests/base/configmap.yaml
  components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml
Labels: size/XS, lgtm, approved

#6899 vwa(front): Prevent PVCs from being deleted when there is a corresponding notebook
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/component-value/component-value.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/volumes/backend/apps/common/utils.py
  components/crud-web-apps/volumes/backend/apps/default/routes/get.py
  components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
  components/crud-web-apps/volumes/backend/apps/rok/utils.py
  components/crud-web-apps/volumes/frontend/cypress/fixtures/pvcs.json
  components/crud-web-apps/volumes/frontend/src/app/app.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/columns.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
  components/crud-web-apps/volumes/frontend/src/app/types/backend.ts
Labels: size/L, lgtm, approved

#6922 Update GH Action script for installing Cert Manager
  components/testing/gh-actions/install_cert_manager.sh
Labels: size/S, lgtm, approved

#6917 gh-actions: Fix KF intergration tests for release branches
  .github/workflows/centraldb_angular_intergration_test.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/vwa_intergration_test.yaml
Labels: size/M, lgtm, approved

#6916 release: Images for the v1.7.0-rc.0 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved
