Repository kubeflow/kubeflow, pull requests merged in 2023-03, with the labels that each got.

#6985 jwa: Remove all the Rok references
  components/crud-web-apps/jupyter/backend/Makefile
  components/crud-web-apps/jupyter/backend/apps/rok/__init__.py
  components/crud-web-apps/jupyter/backend/apps/rok/routes/__init__.py
  components/crud-web-apps/jupyter/backend/apps/rok/routes/post.py
  components/crud-web-apps/jupyter/backend/apps/rok/utils/common.py
  components/crud-web-apps/jupyter/backend/entrypoint.py
  components/crud-web-apps/jupyter/frontend/.gitignore
  components/crud-web-apps/jupyter/frontend/angular.json
  components/crud-web-apps/jupyter/frontend/cypress/e2e/form-page.cy.ts
  components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebooks.json
  components/crud-web-apps/jupyter/frontend/cypress/support/commands.ts
  components/crud-web-apps/jupyter/frontend/cypress/support/e2e.ts
  components/crud-web-apps/jupyter/frontend/package.json
  components/crud-web-apps/jupyter/frontend/src/app/app-routing.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/app.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/new.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/new.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/new.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/new.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/rok-url/rok-url.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/rok-url/rok-url.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/rok-url/rok-url.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/rok-url/rok-url.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/rok-url/rok-url.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.component.html
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.component.scss
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.component.spec.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.component.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.module.ts
  components/crud-web-apps/jupyter/frontend/src/app/shared/utils/volumes/panel.ts
  components/crud-web-apps/jupyter/frontend/src/app/types/volume/enums.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.prod.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.rok.ts
  components/crud-web-apps/jupyter/frontend/src/environments/environment.ts
  components/crud-web-apps/jupyter/frontend/src/proxy.conf.rok.json
Labels: size/XL, lgtm, approved

#6984 vwa: Remove all the Rok references
  components/crud-web-apps/volumes/Dockerfile
  components/crud-web-apps/volumes/backend/Makefile
  components/crud-web-apps/volumes/backend/apps/rok/__init__.py
  components/crud-web-apps/volumes/backend/apps/rok/pvcviewer.yaml
  components/crud-web-apps/volumes/backend/apps/rok/routes/__init__.py
  components/crud-web-apps/volumes/backend/apps/rok/routes/delete.py
  components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
  components/crud-web-apps/volumes/backend/apps/rok/routes/post.py
  components/crud-web-apps/volumes/backend/apps/rok/utils.py
  components/crud-web-apps/volumes/backend/entrypoint.py
  components/crud-web-apps/volumes/frontend/.gitignore
  components/crud-web-apps/volumes/frontend/angular.json
  components/crud-web-apps/volumes/frontend/cypress/fixtures/namespaces.json
  components/crud-web-apps/volumes/frontend/cypress/fixtures/pvcs.json
  components/crud-web-apps/volumes/frontend/package.json
  components/crud-web-apps/volumes/frontend/src/app/app-routing.module.ts
  components/crud-web-apps/volumes/frontend/src/app/app.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-default/form-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/utils.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/pvc-mock.ts
  components/crud-web-apps/volumes/frontend/src/app/types/index.ts
  components/crud-web-apps/volumes/frontend/src/app/types/rok.ts
  components/crud-web-apps/volumes/frontend/src/environments/environment.rok.prod.ts
  components/crud-web-apps/volumes/frontend/src/environments/environment.rok.ts
  components/crud-web-apps/volumes/frontend/src/proxy.conf.rok.json
Labels: size/XXL, lgtm, approved

#7017 web-apps(front): Fix typos
  components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.html
  components/crud-web-apps/tensorboards/frontend/i18n/fr/messages.fr.xlf
  components/crud-web-apps/tensorboards/frontend/i18n/messages.xlf
  components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
Labels: size/XS, lgtm, approved

#6736 clean up default `spawner_ui_config.yaml`
  components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
Labels: size/XL, lgtm, approved

#7016 profile-controller: Support custom cluster domain other than cluster.local
  components/profile-controller/controllers/profile_controller.go
Labels: size/XS, lgtm, approved

#7026 Fix: Strip unwanted space in custom image name
  components/crud-web-apps/jupyter/backend/apps/common/form.py
Labels: size/XS, lgtm, approved

#7031 gh-actions(cdb): Fix Build and Publish action
  .github/workflows/centraldb_angular_docker_publish.yaml
Labels: size/XS, lgtm, approved

#7020 web-apps: Remove all the Rok references
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/rok/__init__.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/rok/routes.py
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/assets/browse-in-rok-blue.svg
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/assets/browse-in-rok-gray.svg
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/assets/browse-in-rok-grey.svg
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/form.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/rok-url-input/rok-url-input.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/rok-url-input/rok-url-input.component.scss
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/rok-url-input/rok-url-input.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/rok-url-input/rok-url-input.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/validators.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/rok/injector.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/rok/rok.service.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/rok/types.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
Labels: size/L, lgtm, approved

#6535 testing: Cleanup the testing dir and add gh actions placeholder folder
  testing/Dockerfile
  testing/Makefile
  testing/README.md
  testing/__init__.py
  testing/auth.py
  testing/deploy_utils.py
  testing/gcp_util.py
  testing/get_gke_credentials.py
  testing/gh-actions/OWNERS
  testing/katib_studyjob_test.py
  testing/kfctl/conftest.py
  testing/kfctl/endpoint_ready_test.py
  testing/kfctl/kf_is_ready_test.py
  testing/kfctl/kfctl_delete_test.py
  testing/kfctl/kfctl_go_test.py
  testing/kfctl/kfctl_second_apply.py
  testing/kfctl/scripts/create_existing_cluster.sh
  testing/kfctl/scripts/delete_existing_cluster.py
  testing/run.sh
  testing/run_deploy_app.sh
  testing/run_with_retry.py
  testing/test_deploy_app.py
  testing/test_deploy_test.py
  testing/test_flake8.py
  testing/test_jsonnet.py
  testing/test_jwa.py
  testing/test_tf_serving.py
  testing/vm_util.py
  testing/wait_for_deployment.py
  testing/wait_for_kubeflow.py
  testing/workflows/.ksonnet/registries/incubator/ea3408d44c2d8ea4d321364e5533d5c60e74bce0.yaml
  testing/workflows/.ksonnet/registries/kubeflow/5c35580d76092788b089cb447be3f3097cffe60b.yaml
  testing/workflows/app.yaml
  testing/workflows/components/click_deploy_test.jsonnet
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/kfctl_test.jsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/unit_tests.jsonnet
  testing/workflows/components/util.libsonnet
  testing/workflows/components/workflows.libsonnet
  testing/workflows/debug_pod.yaml
  testing/workflows/environments/base.libsonnet
  testing/workflows/environments/kubeflow-testing/main.jsonnet
  testing/workflows/environments/kubeflow-testing/params.libsonnet
  testing/workflows/environments/prow/.metadata/k.libsonnet
  testing/workflows/environments/prow/.metadata/k8s.libsonnet
  testing/workflows/environments/prow/.metadata/swagger.json
  testing/workflows/environments/prow/main.jsonnet
  testing/workflows/environments/prow/params.libsonnet
  testing/workflows/lib/ksonnet-lib/v1.7.0/k.libsonnet
  testing/workflows/lib/ksonnet-lib/v1.7.0/k8s.libsonnet
  testing/workflows/lib/ksonnet-lib/v1.7.0/swagger.json
  testing/workflows/lib/v1.7.0/k.libsonnet
  testing/workflows/lib/v1.7.0/k8s.libsonnet
  testing/workflows/lib/v1.7.0/swagger.json
  testing/workflows/run.sh
  testing/workflows/vendor/kubeflow/core/tf-job-operator.libsonnet
Labels: size/XXL, lgtm, approved

#6992 Adding changes to build JWA on pull_request
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_intergration_test.yaml
  components/crud-web-apps/jupyter/Makefile
Labels: size/S, lgtm, approved

#6995 centraldashboard: Allow all-namespaces option for mwa
  components/centraldashboard/public/components/namespace-selector.js
Labels: size/XS, lgtm, approved

#7019 web-apps(back): Fetch resources events
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/events.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py
Labels: size/M, lgtm, approved

#7055 Adding changes to build admission-webhook on pull_request
  .github/workflows/poddefaults_intergration_test.yaml
  components/admission-webhook/Makefile
Labels: size/S, lgtm, approved

#7052 Adding changes to build multi arch images on pull_request for VWA.
  .github/workflows/vwa_intergration_test.yaml
  components/crud-web-apps/volumes/Makefile
Labels: size/S, lgtm, approved

#7054 Adding changes to build nb-controller on pull_request
  .github/workflows/nb_controller_intergration_test.yaml
  components/notebook-controller/Makefile
Labels: size/S, lgtm, approved

#7050 Update requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
Labels: size/XS, lgtm, approved

#7030 cdb(front): Add namespace selector
  components/centraldashboard-angular/frontend/angular.json
  components/centraldashboard-angular/frontend/cypress/e2e/namespace-selector.cy.ts
  components/centraldashboard-angular/frontend/cypress/fixtures/envinfo.json
  components/centraldashboard-angular/frontend/cypress/support/commands.ts
  components/centraldashboard-angular/frontend/cypress/support/e2e.ts
  components/centraldashboard-angular/frontend/public/library.d.ts
  components/centraldashboard-angular/frontend/src/app/app.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/app.module.ts
  components/centraldashboard-angular/frontend/src/app/interceptors/error.interceptor.ts
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.html
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.module.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/namespace-selector/namespace-selector.component.html
  components/centraldashboard-angular/frontend/src/app/pages/main-page/namespace-selector/namespace-selector.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/main-page/namespace-selector/namespace-selector.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/namespace-selector/namespace-selector.component.ts
  components/centraldashboard-angular/frontend/src/app/services/backend.service.ts
  components/centraldashboard-angular/frontend/src/app/services/environment.service.spec.ts
  components/centraldashboard-angular/frontend/src/app/services/environment.service.ts
  components/centraldashboard-angular/frontend/src/app/services/local-storage.service.spec.ts
  components/centraldashboard-angular/frontend/src/app/services/local-storage.service.ts
  components/centraldashboard-angular/frontend/src/app/services/namespace.service.spec.ts
  components/centraldashboard-angular/frontend/src/app/services/namespace.service.ts
  components/centraldashboard-angular/frontend/src/app/services/svg-icons.service.spec.ts
  components/centraldashboard-angular/frontend/src/app/services/svg-icons.service.ts
  components/centraldashboard-angular/frontend/src/app/shared/utils.ts
  components/centraldashboard-angular/frontend/src/app/types/env-info.ts
  components/centraldashboard-angular/frontend/src/app/types/namespace.ts
  components/centraldashboard-angular/frontend/src/app/types/platform-info.ts
  components/centraldashboard-angular/frontend/src/assets/icons/namespace.svg
  components/centraldashboard-angular/frontend/src/styles/styles.scss
  components/centraldashboard-angular/frontend/src/styles/utils.scss
  components/centraldashboard-angular/frontend/tsconfig.json
  components/centraldashboard-angular/frontend/tsconfig.spec.json
Labels: size/XXL, lgtm, approved

#7073 Update requirements.txt (#7050)
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
Labels: size/XS, lgtm, approved

#7074 release: images for the v1.7.0 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#7071 cdb(front): Introduce 404 not found page
  components/centraldashboard-angular/frontend/cypress/e2e/namespace-selector.cy.ts
  components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
  components/centraldashboard-angular/frontend/package-lock.json
  components/centraldashboard-angular/frontend/src/app/app-routing.module.ts
  components/centraldashboard-angular/frontend/src/app/app.module.ts
  components/centraldashboard-angular/frontend/src/app/guards/iframe.guard.spec.ts
  components/centraldashboard-angular/frontend/src/app/guards/iframe.guard.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/namespace-needed-page/namespace-needed-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/namespace-needed-page/namespace-needed-page.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/namespace-needed-page/namespace-needed-page.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/namespace-needed-page/namespace-needed-page.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/not-found-page/not-found-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/not-found-page/not-found-page.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/not-found-page/not-found-page.component.spec.ts
  components/centraldashboard-angular/frontend/src/app/pages/not-found-page/not-found-page.component.ts
  components/centraldashboard-angular/frontend/src/styles/styles.scss
Labels: size/XL, lgtm, approved
