Repository kubeflow/kubeflow, pull requests merged in 2023-02, with the labels that each got.

#6895 cdb-angular(front): Add UI tests
  .github/workflows/centraldb_angular_frontend_test.yaml
  components/centraldashboard-angular/backend/package.json
  components/centraldashboard-angular/frontend/.gitignore
  components/centraldashboard-angular/frontend/README.md
  components/centraldashboard-angular/frontend/cypress.config.ts
  components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
  components/centraldashboard-angular/frontend/cypress/fixtures/example.json
  components/centraldashboard-angular/frontend/cypress/support/commands.ts
  components/centraldashboard-angular/frontend/cypress/support/e2e.ts
  components/centraldashboard-angular/frontend/package-lock.json
  components/centraldashboard-angular/frontend/package.json
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/shared/utils.ts
Labels: size/XXL, lgtm, approved

#6923 Adding support for linux/ppc64le in CI for centraldashboard multi-arc…
  .github/workflows/centraldb_docker_publish.yaml
  components/centraldashboard/Makefile
Labels: size/M, lgtm, approved

#6609 Fix the logout button to work with the recent version of `oidc-authservice`
  components/centraldashboard/Dockerfile
  components/centraldashboard/public/components/logout-button.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
Labels: size/M, lgtm, approved

#6188 Fix the bug of ResourceQuota removal
  components/profile-controller/controllers/profile_controller.go
Labels: size/S, needs-ok-to-test, lgtm, approved, lifecycle/stale, cla: yes

#6924 Support Pod Defaults in Tensorboard Web App
  components/crud-web-apps/tensorboards/backend/app/routes/get.py
  components/crud-web-apps/tensorboards/backend/app/routes/post.py
  components/crud-web-apps/tensorboards/backend/app/utils.py
  components/crud-web-apps/tensorboards/deploy/app-rbac.yaml
  components/crud-web-apps/tensorboards/frontend/src/app/app.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.scss
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/tensorboards/frontend/src/app/types.ts
  components/crud-web-apps/tensorboards/manifests/base/cluster-role.yaml
Labels: size/L, lgtm, approved

#6929 Add approvers to the frontends
  components/crud-web-apps/common/frontend/OWNERS
  components/crud-web-apps/jupyter/frontend/OWNERS
  components/crud-web-apps/tensorboards/frontend/OWNERS
  components/crud-web-apps/volumes/frontend/OWNERS
Labels: size/S, lgtm, approved

#6921 Update GH Action script for installing Cert Manager
  components/testing/gh-actions/install_cert_manager.sh
Labels: size/S, lgtm, approved

#6959 centraldashboard: Fix failing test
  components/centraldashboard/public/components/activities-list_test.js
Labels: size/S, lgtm, approved

#6960 centraldashboard(make): Use correct dir
  components/centraldashboard/Makefile
Labels: size/XS, lgtm, approved

#6965 Fix the bug of ResourceQuota removal (#6188)
  components/profile-controller/controllers/profile_controller.go
Labels: size/S, lgtm, approved

#6966 centraldashboard: Fix failing test (#6959)
  components/centraldashboard/public/components/activities-list_test.js
Labels: size/S, lgtm, approved

#6970 web-apps(front): Fix flaky filtering unit test
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
Labels: size/XS, lgtm, approved

#6962 vwa(front): Prevent PVCs from being deleted when there is a corresponding notebook
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/component-value/component-value.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
  components/crud-web-apps/volumes/backend/apps/common/utils.py
  components/crud-web-apps/volumes/backend/apps/default/routes/get.py
  components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
  components/crud-web-apps/volumes/backend/apps/rok/utils.py
  components/crud-web-apps/volumes/frontend/cypress/fixtures/pvcs.json
  components/crud-web-apps/volumes/frontend/src/app/app.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/columns.module.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.html
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.scss
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.spec.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
  components/crud-web-apps/volumes/frontend/src/app/types/backend.ts
Labels: size/L, lgtm, approved

#6963 Adding support for linux/ppc64le in CI for centraldashboard multi-arc…
  .github/workflows/centraldb_docker_publish.yaml
  components/centraldashboard/Makefile
Labels: size/M, lgtm, approved

#6964 Fix the logout button to work with the recent version of `oidc-authservice`
  components/centraldashboard/Dockerfile
  components/centraldashboard/public/components/logout-button.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
Labels: size/M, lgtm, approved

#6945 centraldashboard: Support dynamic logout URL
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/k8s_service_test.ts
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/public/components/logout-button.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
Labels: size/M, lgtm, approved

#6971 Support Pod Defaults in Tensorboard Web App (#6924)
  components/crud-web-apps/tensorboards/backend/app/routes/get.py
  components/crud-web-apps/tensorboards/backend/app/routes/post.py
  components/crud-web-apps/tensorboards/backend/app/utils.py
  components/crud-web-apps/tensorboards/deploy/app-rbac.yaml
  components/crud-web-apps/tensorboards/frontend/src/app/app.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.scss
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.module.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.html
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
  components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.ts
  components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
  components/crud-web-apps/tensorboards/frontend/src/app/types.ts
  components/crud-web-apps/tensorboards/manifests/base/cluster-role.yaml
Labels: size/L, lgtm, approved

#6972 centraldashboard(make): Use correct dir (#6960)
  components/centraldashboard/Makefile
Labels: size/XS, lgtm, approved

#6974 centraldashboard: Support dynamic logout URL (#6945)
  components/centraldashboard/app/k8s_service.ts
  components/centraldashboard/app/k8s_service_test.ts
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/public/components/logout-button.js
  components/centraldashboard/public/components/main-page.js
  components/centraldashboard/public/components/main-page.pug
  components/centraldashboard/public/components/namespace-selector.js
Labels: size/M, lgtm, approved

#6975 release: Images for the v1.7.0-rc.1 tag
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#6967 web-apps(front): Fix the action component
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/action/action.component.css
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/action/action.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/action-icon-value.ts
Labels: size/S, lgtm, approved

#6976 Document the release process for Notebooks
  releasing/README.md
Labels: size/XS, lgtm, approved

#6897 jwa(front): JWA shows a weird long value for memory when restoring notebook from snapshot
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/utils.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/index.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/memory-value.ts
  components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
  components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
  components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
Labels: size/L, lgtm, approved

#6958 centraldashboard: Allow all-namespaces option for kwa
  components/centraldashboard/public/components/namespace-selector.js
Labels: size/XS, lgtm, approved

#6953 cdb(front): Fetch left sidebar links
  components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
  components/centraldashboard-angular/frontend/cypress/fixtures/dashboardlinks.json
  components/centraldashboard-angular/frontend/cypress/fixtures/envinfo.json
  components/centraldashboard-angular/frontend/cypress/support/commands.ts
  components/centraldashboard-angular/frontend/cypress/support/e2e.ts
  components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.scss
  components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.ts
  components/centraldashboard-angular/frontend/src/app/services/backend.service.ts
  components/centraldashboard-angular/frontend/src/app/shared/utils.ts
  components/centraldashboard-angular/frontend/src/app/types/dashboard-links.ts
Labels: size/L, lgtm, approved
