Repository kubeflow/kubeflow, pull requests merged in 2023-09, with the labels that each got.

#7263 ci: fix test image replacement
  .github/workflows/centraldb_angular_intergration_test.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/pvcviewer_controller_intergration_test.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/vwa_intergration_test.yaml
Labels: size/L, lgtm, approved

#7237 Cherry-Pick #7230 into v1.8-branch
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
  components/crud-web-apps/volumes/manifests/base/viewer-spec.yaml
  components/pvcviewer-controller/README.md
Labels: size/S, lgtm, approved

#7247 fix: downgrade filebrowser to v2.23.0
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
Labels: size/XS, lgtm, approved

#7279 fix: remove creationTimestamp line
  components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
Labels: size/S, lgtm, approved

#7289 ci: wait for deployment instead of pods for test execution
  .github/workflows/centraldb_angular_integration_test.yaml
  .github/workflows/centraldb_integration_test.yaml
  .github/workflows/jwa_integration_test.yaml
  .github/workflows/nb_controller_integration_test.yaml
  .github/workflows/poddefaults_integration_test.yaml
  .github/workflows/profiles_kfam_integration_test.yaml
  .github/workflows/pvcviewer_controller_integration_test.yaml
  .github/workflows/tb_controller_integration_test.yaml
  .github/workflows/twa_integration_test.yaml
  .github/workflows/vwa_integration_test.yaml
Labels: size/M, lgtm, approved

#7292 fix: pvcviewer tests
  components/pvcviewer-controller/.gitignore
  components/pvcviewer-controller/config/crd/bases/kubeflow.org_pvcviewers.yaml
  components/pvcviewer-controller/controllers/crds/istio_crds.yaml
  components/pvcviewer-controller/controllers/suite_test.go
  components/pvcviewer-controller/controllers/test_setup_utils.go
Labels: size/XXL, lgtm, approved

#7286 Release v1.8.0-rc.1
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/.gitignore
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/pvcviewer-controller/config/crd/bases/kubeflow.org_pvcviewers.yaml
  components/pvcviewer-controller/controllers/crds/istio_crds.yaml
  components/pvcviewer-controller/controllers/suite_test.go
  components/pvcviewer-controller/controllers/test_setup_utils.go
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/XXL, lgtm, approved

#6556 Fix typo in centraldashboard/README.md
  components/centraldashboard/README.md
Labels: size/XS, lgtm, approved
