Repository kubeflow/kubeflow, pull requests merged in 2024-10, with the labels that each got.

#7647 feat: update notebook server images
  components/example-notebook-servers/base/Dockerfile
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/codeserver-python/requirements.txt
  components/example-notebook-servers/codeserver/Dockerfile
  components/example-notebook-servers/image-flow-chart.png
  components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-cuda/Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-gaudi-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch/Dockerfile
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow/Dockerfile
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/rstudio-tidyverse/Dockerfile
  components/example-notebook-servers/rstudio/Dockerfile
  components/example-notebook-servers/rstudio/rsession.sh
  components/example-notebook-servers/rstudio/s6/cont-init.d/02-rstudio-env-fix
  components/example-notebook-servers/rstudio/s6/services.d/rstudio/run
Labels: size/L, lgtm, approved

#7654 fix: logout button for oauth2-proxy
  components/centraldashboard/README.md
  components/centraldashboard/manifests/base/deployment.yaml
  components/centraldashboard/public/components/logout-button.css
  components/centraldashboard/public/components/logout-button.js
Labels: size/M, lgtm, approved

#7649 fix: return notebook events error message
  components/crud-web-apps/jupyter/backend/apps/common/status.py
Labels: size/XS, lgtm, approved
