Repository kubeflow/kubeflow, pull requests merged in 2025-03, with the labels that each got.

#7711 chore: Release v1.10.0-rc.2
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved, ok-to-test

#7697 fix: don't require authentication for crud-web-apps metrics endpoints
  components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/metrics.py
Labels: size/XS, lgtm, approved, ok-to-test

#7703 chore: update filebrowser image to v2.32.0
  components/crud-web-apps/volumes/manifests/base/deployment.yaml
Labels: size/XS, lgtm, approved, ok-to-test, area/security
