Repository kubeflow/kubeflow, pull requests merged in 2025-02, with the labels that each got.

#7675 Updating OWNERS for 2025 KSC members
  OWNERS
Labels: size/XS, approved

#7676 Updating to include emeritus_approvers
  OWNERS
Labels: size/XS, lgtm, approved

#7678 fix: stop using gcr.io registry for kube-rbac-proxy
  components/notebook-controller/config/default/manager_auth_proxy_patch.yaml
  components/profile-controller/config/default/manager_auth_proxy_patch.yaml
  components/pvcviewer-controller/config/default/manager_auth_proxy_patch.yaml
  components/tensorboard-controller/config/default/manager_auth_proxy_patch.yaml
Labels: size/XS, lgtm, approved

#7669 fix: add container securityContext to profile-controller and kfam
  components/access-management/Dockerfile
  components/profile-controller/Dockerfile
  components/profile-controller/config/base/patches/manager.yaml
  components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
Labels: size/S, lgtm, approved, ok-to-test

#7679 Release v1.10.0-rc.0
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_multi_arch_test.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_multi_arch_test.yaml
  .github/workflows/kfam_multi_arch_test.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_multi_arch_test.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_multi_arch_test.yaml
  .github/workflows/prof_controller_multi_arch_test.yaml
  .github/workflows/pvcviewer_controller_docker_publish.yaml
  .github/workflows/pvcviewer_controller_multi_arch_test.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_multi_arch_test.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_multi_arch_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_multi_arch_test.yaml
  components/admission-webhook/manifests/base/kustomization.yaml
  components/centraldashboard/manifests/base/kustomization.yaml
  components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
  components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
  components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
  components/crud-web-apps/volumes/manifests/base/kustomization.yaml
  components/notebook-controller/config/base/kustomization.yaml
  components/profile-controller/config/base/kustomization.yaml
  components/profile-controller/config/overlays/kubeflow/kustomization.yaml
  components/pvcviewer-controller/config/base/kustomization.yaml
  components/tensorboard-controller/config/base/kustomization.yaml
  releasing/version/VERSION
Labels: size/M, lgtm, approved

#7681 ci: update actions and revert to ubuntu-22.04
  .github/workflows/centraldb_angular_backend_test.yaml
  .github/workflows/centraldb_angular_docker_publish.yaml
  .github/workflows/centraldb_angular_frontend_test.yaml
  .github/workflows/centraldb_angular_intergration_test.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_frontend_tests.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/centraldb_multi_arch_test.yaml
  .github/workflows/common_frontend_tests.yaml
  .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
  .github/workflows/jwa_backend_unittests.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_frontend_tests.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/jwa_multi_arch_test.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/kfam_multi_arch_test.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/nb_controller_multi_arch_test.yaml
  .github/workflows/notebook_controller_unit_test.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/poddefaults_multi_arch_test.yaml
  .github/workflows/poddefaults_unit_test.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/prof_controller_multi_arch_test.yaml
  .github/workflows/prof_controller_unit_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/pvcviewer_controller_docker_publish.yaml
  .github/workflows/pvcviewer_controller_intergration_test.yaml
  .github/workflows/pvcviewer_controller_multi_arch_test.yaml
  .github/workflows/pvcviewer_controller_unit_test.yaml
  .github/workflows/python_lint.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/tb_controller_multi_arch_test.yaml
  .github/workflows/triage_issues.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_frontend_tests.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/twa_multi_arch_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_frontend_tests.yaml
  .github/workflows/vwa_intergration_test.yaml
  .github/workflows/vwa_multi_arch_test.yaml
Labels: size/L, lgtm, approved

#7684 ci: trigger tests on release + update release guide
  .github/workflows/approve_gh_workflows.yaml
  .github/workflows/centraldb_angular_backend_test.yaml
  .github/workflows/centraldb_angular_frontend_test.yaml
  .github/workflows/centraldb_angular_intergration_test.yaml
  .github/workflows/centraldb_frontend_tests.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/centraldb_multi_arch_test.yaml
  .github/workflows/common_frontend_tests.yaml
  .github/workflows/jwa_backend_unittests.yaml
  .github/workflows/jwa_frontend_tests.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/jwa_multi_arch_test.yaml
  .github/workflows/kfam_multi_arch_test.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/nb_controller_multi_arch_test.yaml
  .github/workflows/notebook_controller_unit_test.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/poddefaults_multi_arch_test.yaml
  .github/workflows/poddefaults_unit_test.yaml
  .github/workflows/prof_controller_multi_arch_test.yaml
  .github/workflows/prof_controller_unit_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/pvcviewer_controller_intergration_test.yaml
  .github/workflows/pvcviewer_controller_multi_arch_test.yaml
  .github/workflows/pvcviewer_controller_unit_test.yaml
  .github/workflows/python_lint.yaml
  .github/workflows/semantic_prs.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/tb_controller_multi_arch_test.yaml
  .github/workflows/twa_frontend_tests.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/twa_multi_arch_test.yaml
  .github/workflows/vwa_frontend_tests.yaml
  .github/workflows/vwa_intergration_test.yaml
  .github/workflows/vwa_multi_arch_test.yaml
  releasing/README.md
Labels: size/L, lgtm, approved

#7686 feat: use rootless base image for nb-controller and pod-default
  components/admission-webhook/Dockerfile
  components/notebook-controller/Dockerfile
Labels: size/S, lgtm, approved, ok-to-test

#7687 feat: update notebook server images
  components/example-notebook-servers/base/Dockerfile
  components/example-notebook-servers/codeserver-python/Dockerfile
  components/example-notebook-servers/codeserver-python/home/README__CODESERVER_PYTHON.md
  components/example-notebook-servers/codeserver-python/requirements.txt
  components/example-notebook-servers/codeserver/Dockerfile
  components/example-notebook-servers/codeserver/s6/services.d/code-server/run
  components/example-notebook-servers/jupyter-pytorch-cuda-full/Dockerfile
  components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-cuda/Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/Dockerfile
  components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-gaudi-full/Dockerfile
  components/example-notebook-servers/jupyter-pytorch-gaudi-full/requirements.txt
  components/example-notebook-servers/jupyter-pytorch-gaudi/Dockerfile
  components/example-notebook-servers/jupyter-pytorch-gaudi/README.md
  components/example-notebook-servers/jupyter-pytorch-gaudi/home/README__PYTORCH_GAUDI.md
  components/example-notebook-servers/jupyter-pytorch/Dockerfile
  components/example-notebook-servers/jupyter-scipy/Dockerfile
  components/example-notebook-servers/jupyter-scipy/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-cuda-full/Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow-cuda/Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/Dockerfile
  components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
  components/example-notebook-servers/jupyter-tensorflow/Dockerfile
  components/example-notebook-servers/jupyter/Dockerfile
  components/example-notebook-servers/jupyter/s6/services.d/jupyterlab/run
  components/example-notebook-servers/rstudio/Dockerfile
  components/example-notebook-servers/rstudio/s6/services.d/rstudio/run
Labels: size/L, lgtm, approved, ok-to-test

#7688 ci: downgrade qemu, fix arm64 build segfaults
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_multi_arch_test.yaml
  .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_multi_arch_test.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/kfam_multi_arch_test.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_multi_arch_test.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_multi_arch_test.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/prof_controller_multi_arch_test.yaml
  .github/workflows/pvcviewer_controller_multi_arch_test.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_multi_arch_test.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_multi_arch_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_multi_arch_test.yaml
  components/example-notebook-servers/README.md
Labels: size/M, lgtm, approved, ok-to-test

#7680 feat: update gaudi notebooks to version 1.19.2
  components/example-notebook-servers/jupyter-pytorch-gaudi/Dockerfile
Labels: size/S, lgtm, approved, ok-to-test
